Fix preloading of st models on has_many through associations
rails/rails pull request #14312
Opened 2014-03-07 10:00 UTC by moktin

This patch fixes #11078 by removing the type conditions from `through_scope`.
It is really inspired by #11082 and the comment from @neerajdotname.

2016-11-16 07:58 UTC, AlfonsoUceda commented
@moktin I know this is an old PR, but it could be rebased?

2016-11-20 19:03 UTC, moktin commented
@AlfonsoUceda done, but I can't promise it will be merge.

2017-01-18 04:34 UTC, rafaelfranca requested changes

2017-01-18 04:34 UTC, rafaelfranca commented on activerecord/lib/active_record/core.rb
> +        def relation_with_type_condition #:nodoc:
Could you make this method public and keep the `# :nodoc:` so we don't have to use `send`?

2017-01-18 04:34 UTC, rafaelfranca commented on activerecord/lib/active_record/core.rb
> +        def relation_with_type_condition #:nodoc:
Also we should move those methods to `inheritance.rb` file with `finder_needs_type_condition`

2017-01-18 04:34 UTC, rafaelfranca commented on activerecord/lib/active_record/core.rb
> +          relation = Relation.create(self, arel_table, predicate_builder)
this variable is not needed.

2017-01-18 04:34 UTC, rafaelfranca commented on activerecord/lib/active_record/core.rb
>            relation = Relation.create(self, arel_table, predicate_builder)
This line is not needed anymore.

2017-01-18 13:49 UTC, kamipo commented on activerecord/lib/active_record/associations/preloader/through_association.rb
> +                scope.where_clause = reflection_scope.where_clause - base_wheres
How about it?

```diff
--- a/activerecord/lib/active_record/associations/preloader/through_association.rb
+++ b/activerecord/lib/active_record/associations/preloader/through_association.rb
@@ -87,6 +87,9 @@ def through_scope
             else
               unless reflection_scope.where_clause.empty?
                 scope.includes_values = Array(reflection_scope.values[:includes] || options[:source])
+                if reflection.klass.finder_needs_type_condition?
+                  reflection_scope = reflection_scope.unscope(where: reflection_scope.klass.inheritance_column)
+                end
                 scope.where_clause = reflection_scope.where_clause
               end
```

`WhereClause#-` not always works properly unlike `WhereClause#except`.

2017-01-18 16:34 UTC, kamipo commented on activerecord/lib/active_record/core.rb
> +            relation_with_type_condition
It is unneccesary changes anymore.

2017-01-18 16:34 UTC, kamipo commented on activerecord/lib/active_record/inheritance.rb
> +        relation.where(type_condition).create_with(inheritance_column.to_s => sti_name)
ditto.

2017-01-18 16:34 UTC, kamipo commented on activerecord/lib/active_record/relation/where_clause.rb
> +          binds - other.binds
ditto.

2017-01-24 09:38 UTC, kamipo commented on activerecord/lib/active_record/core.rb
> +            relation_without_type_condition
The changes to this file is unnecessary.

2017-01-24 09:38 UTC, kamipo commented on activerecord/lib/active_record/inheritance.rb
> +
ditto.

2017-07-18 13:40 UTC, mjansing commented
Any updates on this issue?

2017-09-01 22:40 UTC, closed without merging