add forward_validation_context flag to AssociatedValidator
rails/rails pull request #24135
Opened 2016-03-10 10:04 UTC by rafal-brize

### Summary

This PR comes as a result of a research done to solve issue https://github.com/rails/rails/issues/23261.
This allows to pass a forward_validation_context flag to `AssociatedValidator` so that writing `parent.valid?(:custom_context)` will pass that `:custom_context` down to child validation.
This is consistent with what `:autosave` does as a default behavior https://github.com/rails/rails/blob/master/activerecord/lib/active_record/autosave_association.rb#L328. Doing that a default behavior for `AssociatedValidator` would be a breaking change.

2017-06-12 23:23 UTC, brunzino commented
Bump. (I'd love to see this implemented) Thanks, guys, for your work!

2018-07-31 15:02 UTC, wenderjean commented
any update about this?

2018-07-31 21:42 UTC, rafaelfranca reviewed
This looks good. Can you rebase?

2018-07-31 21:42 UTC, rafaelfranca commented on activerecord/lib/active_record/validations/associated.rb
> +        @forward_validation_context ||= options[:forward_validation_context]
Do we need this memoization here?

2018-08-02 09:29 UTC, rafal-brize commented
@rafaelfranca Updated.

2018-08-02 10:23 UTC, sikachu approved these changes

2018-09-18 17:39 UTC, itsNikolay commented
@rafal-brize could you rebase the PR again? 
I met this issue too. And I made 100% the same PR :) 
But you're already done it 👍

2018-09-19 12:59 UTC, itsNikolay commented
@rafaelfranca could you review it? 
this bug hangs almost 2 years

2018-10-24 18:31 UTC, wenderjean commented
@rafal-brize Do you mind to rebase this one more time? @rafaelfranca Don't you think this is a really important fix?

2019-03-20 20:20 UTC, pedrofurtado commented
@rafaelfranca Any news about this PR? That is a simple, but SO IMPORTANT fix :+1:

2019-04-08 20:54 UTC, franciscomxs commented
Same issue here.
Good job @rafal-brize

2019-10-18 22:52 UTC, Tashows commented
@rafaelfranca @itsNikolay bump!

2020-01-14 15:58 UTC, Ancez commented
Hello, any news regarding this issue?
@rafal-brize could you please rebase?

@rafaelfranca @itsNikolay bumppp

2020-03-04 13:31 UTC, obfuscoder commented
One more rebase(TM). Hope this gets merged soon ;-)

2020-04-21 09:27 UTC, jesseclark commented
👍 This would be nice to have. 

It was a bit surprising to find out that this wasn't the default behavior since it is the default for `autosave`.

2020-07-20 11:14 UTC, pedrofurtado commented
Anyone can reopen this PR?

2020-08-19 13:30 UTC, ryantk commented
I just set out using validation contexts for a feature I am working on today and was bitten by this issue.
Would love it if some superhero fixed the conflicts and merged for me :D

2020-08-19 14:41 UTC, sikachu requested changes
I just came back to look at this ... and just noticed a few things.

- This PR needs rebase again (sorry).
- I think it would be nice if CHANGELOG contains a bit more detail about this feature.
- Now, I'm starting to question the naming of this flag a bit. It took me a while to realize what `forward` means in this context. Would `inherited_validation_context` be a better name since it's _inherited_ from the parent?

Thank you for your work on this. I'll try to get someone's attention to get this merge in once you take care of those issues.

2020-08-19 14:41 UTC, sikachu commented on activerecord/CHANGELOG.md
> +*   AssociatedValidator accepts `forward_validation_context` flag
Would you mind updating the CHANGELOG to include some more information?
I think what you have [here](https://github.com/rails/rails/pull/24135/files#diff-505967108be6686c7d9744aa378f0575R65-R66) is very clear on what this feature does.

2020-08-20 11:09 UTC, pedrofurtado commented
Happy to see it merged asap! 🎉 🏆 🥇

2020-08-20 14:14 UTC, sikachu approved these changes

2020-08-21 19:34 UTC, jeremy requested changes
Are there cases where *don't* want to inherit the parent record's validation context? Should this default to true—or not a config option at all?

2020-11-26 21:15 UTC, pedrofurtado commented
Rails bot, please reopen this 😄

2021-03-22 14:14 UTC, searls commented
I just got bitten by this and would love to see some kind of solution merged (I'm currently stuck trying to think through ways to pull a bunch of validation logic out of AR models as a result, which seems suboptimal)

I agree with @jeremy's point above that this sure seems like it should be the default behavior, even if it's ultimately a breaking change I highly doubt anybody is relying on the current behavior intentionally and I'd sooner classify this as a bug.

2021-05-06 15:03 UTC, emolayi commented
I also wanted this functionality on my `has_one` associations and have managed to get it working by using a combination of the `required` option in combination with `validates_associated`:
```
class Request < ApplicationRecord
  ...

  has_one :participant, required: true, dependent: :destroy
  accepts_nested_attributes_for :participant, allow_destroy: true
  validates_associated :participant

  with_options on: :summary do
    validates :location, :visit_type, presence: true
    ....
  end
...
end

class Participant < ApplicationRecord
...
  belongs_to :request

  with_options on: :summary do
    validates :first_name, :last_name, :dob, presence: true
...
  end
...
end

request.valid?(:summary)
# error on request.location as well as request.patient.first_name, request.patient.last_name, request.patient.dob
```

2021-08-04 15:06 UTC, pedrofurtado commented
Commenting on this PR for bot don't close it 👍

2021-08-04 15:15 UTC, intrip commented
@rafal-brize are you still interested in moving this forward?

2021-08-04 15:40 UTC, pedrofurtado commented
Happy to see this merged, if possible 🎉 🍻

2021-08-04 15:59 UTC, rafal-brize commented
Hey @intrip the PR is from 2016, since then it was reviewed by number of maintainers, with different point of view on this.
Shall it become a new default (breaking change) or an opt-in behaviour. 

I am happy to work on this again, provided there is a maintainer that would guide me through this process.

My take on it is to make it a opt-in first (like i did) and maybe a default later.

2021-08-06 07:23 UTC, intrip commented
@rafal-brize I understand this is open for a lot of time and you took your time working into this, that's why I'd really like to un-stale this situation.

I'd start improving the changelog as @jeremy suggested https://github.com/rails/rails/pull/24135#discussion_r474895991 and fixing conflicts such that the PR can be reviewed as up-to-date.

As per opt-in or not my take on this is to make it opt-in but I'm not the decision maker so we need to wait for further feedback.

2021-11-11 11:42 UTC, pedrofurtado commented
Can someone reopen please?👍

2022-03-23 14:23 UTC, mjbellantoni commented
Could someone reopen this?

2023-02-14 20:23 UTC, erikdstock commented
I realize this is now 7 years old but it just bit me too.

2023-03-30 10:00 UTC, superdaminou commented
Hi, having an issue today and this would be really great. Do we have any news on this feature ?

2023-04-07 18:16 UTC, austenmadden commented
I ended up finding and doing something similar [here](https://github.com/rails/rails/pull/46238) as well if anyone is interested.

2024-01-02 16:24 UTC, austenmadden commented
@rafaelfranca @rafal-brize this PR should be ready to go per the comment here: https://github.com/rails/rails/pull/46238#issuecomment-1782110991

2024-01-03 19:44 UTC, closed without merging