Deprecate locking of dirty records
rails/rails pull request #25873
Opened 2016-07-18 10:41 UTC by schuetzm

`lock!` and `with_lock` reload the record before doing the actual locking. If there were any unsaved changes, they will be discarded without any warning. IMO this behaviour is dangerous and error prone.

See also https://github.com/rails/rails/issues/19743

2016-07-20 02:07 UTC, rafaelfranca commented
Thank you for the pull request. What is the next step after this deprecation? When we remove the deprecation how the code will prevent this to happen again?

2016-07-20 09:35 UTC, schuetzm commented
I'd suggest to raise an exception, because that's easy to implement.

But thinking about it, there is a way that would just prevent the record from being dirty in the first place:

```ruby
MyModel.where(attr: 42).first_with_lock! do |record|
    # change record
    record.save!
end
```

On the other hand, this is more complicated, not as handy to use (you can't load the object, pass it to some other method, and lock it there), and might require major refactoring for the end users. So I'd still go with the exception.

2016-07-20 15:54 UTC, rafaelfranca commented on activerecord/lib/active_record/locking/pessimistic.rb
> +              WARNING! Locking a record with unpersisted changes is deprecated. Use
No need to WARNING! here.

2016-07-20 15:55 UTC, rafaelfranca commented on activerecord/lib/active_record/locking/pessimistic.rb
> +              WARNING! Locking a record with unpersisted changes is deprecated. Use
`Locking a record with unpersisted changes is deprecated and will raise an exception in Rails 5.1. Use`

2016-07-20 15:55 UTC, rafaelfranca commented on activerecord/lib/active_record/locking/pessimistic.rb
> +          reload(:lock => lock)
Use Ruby 1.9 hash syntax here.

2016-07-21 15:00 UTC, schuetzm commented
@rafaelfranca I addressed your comments.

2017-01-18 20:12 UTC, schuetzm commented
@rafaelfranca Rebased.

2017-01-18 21:00 UTC, rafaelfranca requested changes
Could you add a CHANGELOG entry?

2017-01-18 21:25 UTC, kamipo commented on activerecord/lib/active_record/locking/pessimistic.rb
> +              exception in Rails 5.1. Use `save` to persist the changes, or `reload` to
5.2?

2017-01-19 09:40 UTC, schuetzm commented
Added a changelog entry and changed the version in the deprecation notice to 5.2.

2017-02-07 10:14 UTC, schuetzm commented
@rafaelfranca Rebased again.

2017-02-07 12:31 UTC, rafaelfranca requested changes

2017-02-07 12:31 UTC, rafaelfranca commented on activerecord/lib/active_record/locking/pessimistic.rb
> +          if changed?
Sorry I forgot to ask before but can you add a test for this deprecation?

2017-02-07 15:36 UTC, schuetzm commented on activerecord/lib/active_record/locking/pessimistic.rb
> +          if changed?
Done.

2017-02-07 17:41 UTC, merged