support `-` as an argument to `rails runner`
rails/rails pull request #26343
Opened 2016-08-31 15:34 UTC by ccutrer

### Summary

in Rails 4.0, you could use `/dev/stdin` on both Linux and Mac, but with
the switch to Kernel.load in Rails 4.1, this broke on Linux (you get
a LoadError). Instead, explicitly detect `-` as meaning stdin, then
read from stdin explicitly, instead of performing file gymnastics. This
should now work on any platform uniformly.

### Other Information

Passing a script via stdin is useful when you're sshing to a server,
and the script you want to run is stored locally. You could theoretically
pass the entire script on the command line, but in reality you'll run
into problems with the command being too long.

2016-08-31 15:39 UTC, sgrif commented
Would it make sense for us to just always read from stdin when stdin isn't a TTY? /cc @rafaelfranca

2016-08-31 15:42 UTC, ccutrer commented
@sgrif: I'd say no. I would assume it would be a normal use case to do something like:

`cat some_data.csv | rails runner my_processing_script.rb`

2016-08-31 17:20 UTC, sgrif commented
I'm actually wondering if this is just a bug in Ruby that should be handled upstream. It strikes me as odd that `Kernel.load("/dev/stdin")` would work on mac but not linux.

2016-08-31 19:18 UTC, ccutrer commented
Yeah, I thought it was odd. But with this, it's also portable to Windows

2016-08-31 21:21 UTC, sgrif commented
I think it's reasonable. Can you fix the code climate issues. Can you also give some example of another application that uses `-` to specify "read from stdin"?

2016-09-01 16:07 UTC, ccutrer commented
commit updated; it should pass code climate this time, and I _think_ that's what you meant by an improved example

2017-05-17 10:35 UTC, jbbarth commented
Another useful case is running rails scripts inside a docker container: copying the file inside the container is a gymnastic you probably want to avoid, VS `cat script.rb | docker exec -it <container_id> rails runner -`.

@sgrif @ccutrer it would be cool to have this included in a future version of rails. Can I (or others) help to make this happen?

2017-07-17 18:10 UTC, sgrif requested changes
Can you rebase this?

2017-07-17 18:10 UTC, sgrif commented on railties/lib/rails/commands/runner.rb
> +  opts.separator "    cat local_script.rb | ssh myserver '/var/www/myapp/bin/rails runner -'"
This buries the example quite a bit. How about just `rails runner -`?

2017-07-17 19:48 UTC, ccutrer commented
Rebased with conflicts resolved, and simplified the usage example.

2017-07-17 19:53 UTC, merged