Use applications db/migrate paths when available
rails/rails pull request #26372
Opened 2016-09-02 21:48 UTC by natesalisbury

`ActiveRecord::Migrator::migrations_paths` defaults to 'db/migrate' when no other `migrations_paths` have been set. If your application uses a folder other than db/migrate for migrations, `ActiveRecord::Migration.maintain_test_schema!` in rails/test_help will trigger `rake db:test:prepare` at the start of each test run. 

When running database rake tasks this usually isn't an issue because they are dependent on the db:load_config task which will set `migrations_paths` based on an application's config. This is an issue however when calling `ActiveRecord::Migration.maintain_test_schema!` from rails/test_help which doesn't load the app's config, which then triggers db:test:prepare since `any_migrations?` will return false.

I noticed this after upgrading my application to rails 4.2 and each time I ran my cucumber tests, `rake db:test:prepare` was getting triggered at the start. This application has a large db schema so it was adding about 30 seconds to the beginning of each run.  

Fixes #22261

2017-03-21 19:37 UTC, maclover7 commented
@natesalisbury Can you add a regression test, to confirm to new behavior?

2017-03-22 16:59 UTC, natesalisbury commented
@maclover7 done. Let me know if you need anything else.

2017-03-22 19:13 UTC, maclover7 requested changes
Small CHANGELOG.md edits, otherwise looks good to me.

2017-03-22 19:13 UTC, maclover7 commented on activerecord/CHANGELOG.md
> +*  `Migrator::migrations_paths` will now use the application's db/migrate paths
Can you add backticks around db/migrate (`db/migrate`)

2017-03-22 19:13 UTC, maclover7 commented on activerecord/CHANGELOG.md
> +    instead of assuming 'db/migrate'.
Same comment as above

2017-03-22 19:13 UTC, maclover7 commented on activerecord/CHANGELOG.md
> +    Fixes #22261
Can you add a period after the number

2017-03-22 19:27 UTC, natesalisbury commented
Updated CHANGELOG.md.

2017-03-22 19:31 UTC, maclover7 approved these changes
👍 Awesome work!

2017-05-17 12:48 UTC, einarj commented
Awesome @natesalisbury , I can't wait until this is merged.

2017-05-24 04:59 UTC, matthewd commented
This has to be set in the Railtie instead of pulling it directly here... it's a layering violation for AR-the-library to go find the application and ask it for a value.

Can we perhaps move it from the rake task into the railtie proper? It seems rather odd to me that `DatabaseTasks` is the authoritative source for this, and we then copy from there to Migrator. :confused:

2019-09-30 16:05 UTC, eileencodes commented
Closing due to inactivity and I believe the problem this is trying to fix is fixed by multiple database migration support in Rails 6.0.

2019-09-30 16:05 UTC, closed without merging