bug report template for migrations
rails/rails pull request #26488
Opened 2016-09-14 06:45 UTC by girishso

### Summary

I had to create this for testing migrations in isolation.  Thought it will be helpful in future, without having to dig through the migrations tests.

2016-09-14 11:59 UTC, eileencodes commented
Hey @girishso thanks for the PR! Our other bug report templates have a version for the gem and a version for the master branch. Do you mind updating your PR to include both of those?

2016-09-14 12:10 UTC, prathamesh-sonpatki commented
If we are going to add then we need to mention it [here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) as well.

2016-09-15 07:00 UTC, girishso commented
@eileencodes done!

@prathamesh-sonpatki hi there! Done as well!

2016-09-15 07:02 UTC, prathamesh-sonpatki commented
@girishso Can you also squash the commits?

2016-09-15 07:04 UTC, prathamesh-sonpatki commented on guides/bug_report_templates/active_record_migrations_master.rb
> +  gem "activerecord"
We should use `gem "rails", github: "rails/rails"` here similar to how it is used in other master bug report templates.

2016-09-15 07:05 UTC, prathamesh-sonpatki requested changes

2016-09-15 07:07 UTC, sevenseacat commented
squashing commits can be done automatically as part of the merge now :)

2016-09-15 07:17 UTC, girishso commented on guides/bug_report_templates/active_record_migrations_master.rb
> +  gem "activerecord"
Done.  Somehow I missed that!

2016-09-15 07:19 UTC, prathamesh-sonpatki approved these changes

2016-09-15 11:28 UTC, merged

2016-09-15 11:29 UTC, eileencodes commented
Thanks @girishso! 👍 

(I loveee these new github review features 😍 )