add check of argument
rails/rails pull request #26524
Opened 2016-09-17 01:28 UTC by y-yagi

### Summary

`#fetch_multi` in case did not cache hit, to write a cache using the block value.
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache.rb#L383..L384

Therefore, block is a need to pass always, I think should check first.

2016-09-17 02:08 UTC, maclover7 approved these changes
👍 makes sense. Should we add anything to this method's documentation to make it more explicit that you need to pass a block?

2016-09-17 06:01 UTC, y-yagi commented
Thank you for pointing out! I added the document. How about that?

2016-09-17 07:08 UTC, prathamesh-sonpatki commented on activesupport/lib/active_support/cache.rb
> +      # to the cache. If you do not want to write the cache when the cache is
Instead of `that returns a data to`, `that returns the data to`

2016-09-17 07:08 UTC, prathamesh-sonpatki requested changes

2016-09-17 07:35 UTC, y-yagi commented on activesupport/lib/active_support/cache.rb
> +      # to the cache. If you do not want to write the cache when the cache is
Thanks! I updated!

2016-09-22 14:29 UTC, merged

2016-09-22 14:29 UTC, schneems commented
Thanks! 🚀