ActionController::Parameters#deep_dup
rails/rails pull request #26567
Opened 2016-09-21 12:58 UTC by Paxa

Provide `params.deep_dup` which actually create copy

Fixes https://github.com/rails/rails/issues/26566

2016-09-27 07:57 UTC, Paxa commented
Should it have some tests?

2016-10-07 06:43 UTC, Paxa commented
Any thoughts?

2016-10-07 13:53 UTC, arthurnn commented
hi @Paxa , thanks for the PR.
Can you add some tests for it.
I think it looks good to have a deep_dup method in here.
Let me know once you added the tests, and I will take a final look.
Thanks

2016-10-10 06:30 UTC, Paxa commented
@arthurnn Tests ready, please take a look

2016-10-10 17:37 UTC, rafaelfranca requested changes

2016-10-10 17:37 UTC, rafaelfranca commented on actionpack/test/controller/parameters/dup_test.rb
> +    assert_not_equal @params[:person][:addresses], dupped_params[:person][:addresses]
We need to assert that the permitted flag is also kept when doing the deep dup.

2016-10-11 13:29 UTC, merged

2016-10-11 13:31 UTC, rafaelfranca commented
Backported in bb3c364