ActiveJob::Core#serialize stores provider_job_id (fixes #26581).
rails/rails pull request #26587
Opened 2016-09-22 15:21 UTC by utilum

### Summary

Fixes #26581, adds provider_job_id to the hash returned by ActiveJob::Core#serialize, and a test.

2016-09-23 08:02 UTC, jvanbaarsen commented on activejob/lib/active_job/core.rb
> +        "provider_job_id" => provider_job_id,
If the enqueue system does not provide a provider_job_id, will this still work? (I assume it will, but might be worth checking)

2016-09-23 08:59 UTC, utilum commented on activejob/lib/active_job/core.rb
> +        "provider_job_id" => provider_job_id,
@jvanbaarsen The first assertion tests this, but perhaps it can be made clearer. I'll patch.

2016-09-23 09:32 UTC, jvanbaarsen commented on activejob/lib/active_job/core.rb
> +        "provider_job_id" => provider_job_id,
:+1:

2016-09-23 22:12 UTC, cristianbica commented
The `provider_job_id` is not guaranteed to be present on every adapter and is even less present at execution time. The way `provider_job_id` works on most adapters is:

- we enqueue the job (at this point we call `serialize`)
- from the response we get from the adapter we try to extract the `provider_job_id` and assign it to the `ActiveJob::Base` instance
- at execution time, when initializing the `ActiveJob::Base` instance from the adapter job wrapper,  we try to fetch the `provider_job_id` and assign it (from quickly looking at the code it seems it only works for [sidekiq](https://github.com/rails/rails/blob/b326e82dc012d81e9698cb1f402502af1788c1e9/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb#L40))

So this PR won't do much good as the `serialize` is called before obtaining the `provider_job_id`. However there's room for improving support for `provider_job_id` as I think we might be able to extract the `provider_job_id` at execution time for other adapters.

2016-09-24 07:54 UTC, utilum commented
This PR does (in my understanding) resolve #26581.
I'm sure there's room for improving support for `provider_job_id` yet more, but if `serialize` does not include it, it won't be available to `deserialize`.

2016-09-27 19:47 UTC, utilum commented
I don't understand the CI error log. Help? @maclover7 ?

2016-09-27 20:36 UTC, maclover7 commented
@utilum Sorry for the trouble, restarted the randomly failing build, should be green now.

2016-09-27 20:53 UTC, utilum commented
Thank you @maclover7 . This is something only you members can launch, right?

2016-12-19 19:28 UTC, utilum commented
rebased.

2017-06-23 08:23 UTC, utilum commented
rebased. failures seem unrelated (to my innocent eyes).

2017-06-25 10:10 UTC, utilum commented
I assume this is still relevant... ?
cc @maclover7

2017-06-26 22:36 UTC, rafaelfranca requested changes

2017-06-26 22:36 UTC, rafaelfranca commented on activejob/test/cases/job_serialization_test.rb
> +    assert job.serialize["provider_job_id"].nil?
`assert_nil`

2017-06-27 05:10 UTC, utilum commented
But of course! Thank you, fixed.

2017-06-27 17:06 UTC, merged