Fix docs for allowed params to `get` in controller tests  [ci skip]
rails/rails pull request #26605
Opened 2016-09-23 18:30 UTC by mjhoy

### Summary

Fixes #26602

Relevant method documentation for `ActionDispatch::Integration::RequestHelpers#get`:

https://github.com/rails/rails/blob/abe3da9f12710ea85be69b17172bef41220037fc/actionpack/lib/action_dispatch/testing/integration.rb#L14-L43

### Other Information

I'm not entirely happy with the documentation here, which still appears to be written with the old method in mind. For instance, in describing a test:

> Let's take a look at one such test, test_should_get_index from the file articles_controller_test.rb.

```
# articles_controller_test.rb
class ArticlesControllerTest < ActionDispatch::IntegrationTest
  test "should get index" do
    get articles_url
    assert_response :success
  end
end
```

> In the test_should_get_index test, Rails simulates a request on the action called index, making sure   the request was successful and also ensuring that the right response body has been generated.

`Rails simulates a request on the action called index` doesn't seem to be a precise description here. 

Perhaps instead, `Rails simulates a request to articles_url, triggering the index action`? I'm not sure what the most clear way to write this is.

2016-09-23 18:32 UTC, prathamesh-sonpatki commented on guides/source/testing.md
> +get show_url, params: { id: 12 }, headers: { "HTTP_REFERER" => "http://example.com/home" }
This should be `article_url` right?

2016-09-23 18:32 UTC, prathamesh-sonpatki requested changes

2016-09-23 18:33 UTC, mjhoy commented on guides/source/testing.md
> +get show_url, params: { id: 12 }, headers: { "HTTP_REFERER" => "http://example.com/home" }
oops. yes!

2016-09-23 18:34 UTC, mjhoy commented on guides/source/testing.md
> +get show_url, params: { id: 12 }, headers: { "HTTP_REFERER" => "http://example.com/home" }
I should probably fix the `update_url` below it as well. That should also be `article_url` if I'm not mistaken.

2016-09-23 18:35 UTC, prathamesh-sonpatki commented
@mjhoy Yes, please fix `update_url` as well.

2016-09-23 18:36 UTC, prathamesh-sonpatki commented on guides/source/testing.md
> -  This can be in the form of a string or a route (i.e. `articles_url`).
BTW this comment was useful, we should add it back.

2016-09-23 18:38 UTC, mjhoy commented on guides/source/testing.md
> -  This can be in the form of a string or a route (i.e. `articles_url`).
OK. I wanted to remove reference to string vs route, because I thought it was a little confusing. Isn't articles_url a method that returns a string?

2016-09-23 18:40 UTC, prathamesh-sonpatki commented on guides/source/testing.md
> -  This can be in the form of a string or a route (i.e. `articles_url`).
`articles_url` returns a string but `/articles` works as well :)

2016-09-23 18:40 UTC, prathamesh-sonpatki commented on guides/source/testing.md
> -  This can be in the form of a string or a route (i.e. `articles_url`).
you can say `route helper` instead of just `route` to make it more clear.

2016-09-23 18:44 UTC, mjhoy commented on guides/source/testing.md
> -  This can be in the form of a string or a route (i.e. `articles_url`).
done.

2016-09-23 18:45 UTC, merged

2016-09-23 18:45 UTC, prathamesh-sonpatki commented
Thanks a lot :smile:

2016-09-24 09:58 UTC, prathamesh-sonpatki commented
@rafaelfranca or @kaspth Can you backport this ?

2016-09-25 17:06 UTC, kaspth commented
Backported to 5-0-stable in: 136a257