Moved database-specific ActiveModel types into ActiveRecord
rails/rails pull request #26696
Opened 2016-10-03 13:14 UTC by iainbeeston

### Summary

I've been trying to the new `ActiveModel::Type` API without rails. However, I've noticed that a large number of the types in ActiveModel have no meaning in Ruby as they represent SQL data types. For example, Ruby has no concept of a `Text` type (`String` yes, `Text` no). A more subtle example is the `Decimal` type, which is called `BigDecimal` in Ruby. Or `UnsignedInteger`. Or `Binary`.

To reduce confusion I've moved types from the `ActiveModel::Type` module to the `ActiveRecord::Type` module where there is no obvious class in Ruby to represent that type, and updated the two type registries accordingly.

I admit that there's no immediate benefit to this refactoring, but hopefully it will make the dividing line clearer between `ActiveRecord::Type`s and `ActiveModel::Type`s, and make it easier to use the `ActiveModel::Type` API without rails.

2016-10-03 17:41 UTC, maclover7 commented
cc @sgrif

2016-10-03 23:57 UTC, sgrif commented
Fine with the general idea. Binary shouldn't move. Just because Ruby doesn't have a meaningful type to represent binary data doesn't mean that people don't have binary data in Ruby. I don't think decimal should be renamed. Fine with introducing BigDecimal as an alias.

2016-10-04 00:04 UTC, matthewd commented
Moving BigInteger seems quite backwards. More generally, I guess I'd challenge the implication that anything without a specific analogue in stdlib is "database-specific". Isn't the whole point of AM Types to allow us to build richer interpretations atop the primitives?

I'd argue that this isn't clarifying the dividing line, but changing it... and I'm not convinced the change is for the better.

Can you elaborate on how the existence of UnsignedInteger (say) makes the API harder to use without Rails?

2016-10-04 14:23 UTC, iainbeeston commented
Thanks for the thoughtful feedback.

I think there are two points of discussion here:

1. What belongs in ActiveModel vs what belongs in ActiveRecord?
2. Which of the existing `Type` classes are reusable outside of ActiveRecord?

ActiveModel vs ActiveRecord
------

My understanding is that ActiveModel is for code that can be used to create plain old ruby objects that act like ActiveRecord models (eg. with validation, assignment helpers etc). ActiveRecord builds on that layer with database persistence, querying etc. Based on that assumption, my thinking is that any code (or types) related to databases should probably go in ActiveRecord. Any code that relates to concepts in Ruby (or ActiveSupport?) should go in ActiveModel.

On master, all of the `Type`'s are defined in ActiveModel, with a small number altered slightly (through subclassing) in ActiveRecord. I would argue that some of the types (in ActiveModel) are only useful for persisting Ruby data types to an SQL database, which leaves me confused where the dividing line is supposed to be, right now, between ActiveModel and ActiveRecord for Type classes.


Which types are reusable?
----

On master, these are the type classes available, each with a (simplified) description of how they work:


| Type                | Converts input to    | Conversion method                           | Notes                                              |  
|---------------------|----------------------|---------------------------------------------|----------------------------------------------------|
| BigInteger          | Integer              | to_i                                        | Subclasses Integer Type without a min/max value    | 
| Binary              | String               | to_s                                        |                                                    |                              | 
| Boolean             | TrueClass/FalseClass | Checks a whitelist of possible false values |                                                    |
| Date                | Date                 | Date.new                                    | ActiveRecord subclasses this to use AR timezones   |                              | 
| DateTime            | Time                 | Time.utc                                    | ActiveRecord subclasses this to use AR timezones   |                              | 
| Decimal             | BigDecimal           | to_d                                        |                                                    | 
| DecimalWithoutScale | Integer              | to_i                                        | Subclasses BigInteger Type but functionally identical | 
| Float               | Float                | to_f                                        |                                                    |
| ImmutableString     | String               | to_s                                        | Result of to_s is frozen                           | 
| Integer             | Integer              | to_i                                        | min/max value of +/- 2^31                          | 
| String              | String               | to_s                                        | Subclasses ImmutableString Type                         |
| Text                | String               | to_s                                        | Subclasses String Type but functionally identical | 
| Time                | Time                 | Time.utc                                    | ActiveRecord subclasses this to use AR timezones   |                              | 
| UnsignedInteger     | Integer              | to_i                                        | Subclasses Integer Type. Doesn't allow negative values. |                              | 

Of these I would argue that many are very specific to SQL databases. For example, `DecimalWithoutScale` and `Text` behave exactly the same as `Decimal` and `String`, leaving little reason to have both unless you're using ActiveRecord. `Integer` has min and max values which make no sense in Ruby because Ruby `Integer`'s are infinite (the `BigInteger` type has no minimum or maximum, and so that more accurately represents a Ruby `Integer`). The `Binary` type simply casts it's input to a `String`, which is not what I'd normally expect converting to binary to do.


---------


Now that I've looked at the implementation in more detail, I agree with @matthewd that the `BigInteger` `Type` should be in ActiveModel, not ActiveRecord, as it most closely represents a Ruby `Integer` (but conversely the `Integer` type should probably be in ActiveRecord, as it's min/max values make no sense without a database). I'm not sure that the current implementation of the `Binary` type would make sense without ActiveRecord though, as it's implementation simply casts the input to a `String` ( @sgrif am I missing something important here about the `Binary` `Type`?).

What I've tried to achieve in this PR is to make the dividing line clearer between the `Type`'s in ActiveModel and ActiveRecord. At the moment, I find the API confusing, because when I start to use it using ActiveModel alone, there are a lot of `Type` classes that don't make sense in that context (eg. `Text` or `DecimalWithoutScale`). What's more - the implementation of some `Type`'s do not match what I would expect (e.g. why does the `Integer` type limit it's values to 2^31?).

I'm happy to keep working on this if you agree that the idea behind it is correct.

2016-10-04 21:42 UTC, sgrif commented
> I'm happy to keep working on this if you agree that the idea behind it is correct.

I agree that `DecimalWithoutScale` and `Text` make no sense outside of the context of Active Record. I disagree more broadly with your other statements but need to spend some time writing down in more detail why. The TL;DR though is that even if something isn't backed by a SQL database specifically, the concept of a 32 bit integer is a useful abstraction to have. While it doesn't map to Ruby's semantics, it does map to basically everything else a model will want to communicate with. There is probably a case for having an unbound integer type, but that can be a separate PR/discussion as the naming of that type is non-obvious, and specifically the question of what the symbol `:integer` should resolve to is not immediately clear.

2016-10-05 08:14 UTC, iainbeeston commented
I'd love to hear your thoughts on what the dividing line should be, or what the criteria should be for inclusion in ActiveModel vs ActiveRecord.

I'll incorporate your feedback into the code here.

Regarding integer types, does it make sense to refer to the limited size Integer type as Fixnum and the unlimited size type as Bignum? Those are standard Ruby integer types with fixed an unlimited sizes. (Obviously in ActiveRecord the types would be kept as they are)

2016-10-14 08:30 UTC, iainbeeston commented
Ah Fixnum and Bignum are deprecated in ruby 2.4...

2016-10-14 15:59 UTC, iainbeeston commented
@sgrif I've cut down this PR to only move the types that you suggested. I might raise another pull request later to rename the types in ActiveModel to more closely match pure ruby types...

2016-10-14 18:20 UTC, sgrif requested changes

2016-10-14 18:20 UTC, sgrif commented on activerecord/CHANGELOG.md
> +    ie. DecimalWithoutScale, Text and UnsignedInteger
Can we condense this down to `Moved DecimalWithoutScale, Text, and UnsignedInteger from ActiveModel to ActiveRecord`

2016-10-14 18:40 UTC, iainbeeston commented on activerecord/CHANGELOG.md
> +    ie. DecimalWithoutScale, Text and UnsignedInteger
Done

2016-10-14 19:06 UTC, kaspth commented on activemodel/CHANGELOG.md
> +*   Moved DecimalWithoutScale, Text, and UnsignedInteger from ActiveModel to ActiveRecord
It should be Active Model and Active Record in both changelogs since we're referring to the library names and not the Ruby constants.

2016-10-14 19:21 UTC, iainbeeston commented on activemodel/CHANGELOG.md
> +*   Moved DecimalWithoutScale, Text, and UnsignedInteger from ActiveModel to ActiveRecord
Done

2016-10-14 19:22 UTC, iainbeeston commented on activemodel/CHANGELOG.md
> +*   Moved DecimalWithoutScale, Text, and UnsignedInteger from ActiveModel to ActiveRecord
Done

2016-12-08 18:48 UTC, merged