Removed ActiveRecord::Type::Value
rails/rails pull request #26789
Opened 2016-10-14 15:58 UTC by iainbeeston

### Summary

The base class in the ActiveModel type API is `ActiveModel::Type::Value`, from which other types are subclassed (eg. `ActiveModel::Type::ImmutableString < ActiveModel::Type::Value`). ActiveRecord subclasses `ActiveModel::Type::Value` with it's own `Value` class. However, most of the ActiveRecord type classes don't use this base class, but instead are subclassed from ActiveModel's `Value` class. Other ActiveRecord type classes do sublass the ActiveRecord `Value` class.

For example,

| Subclasses `ActiveModel::Type::Value` | Subclasses `ActiveRecord::Type::Value` |
---|----|----
| `Decimal`, `Integer`, `String`... | `Time`, `Date`, `Array`... |

I believe there's a risk here, which is that if`ActiveRecord::Type::Value` is modified, the changes would be reflected inconsistently and could cause subtle bugs, because only the types that subclass `ActiveRecord::Type::Value` would pick up the changes.

My suggestion is that `ActiveRecord::Type::Value` should be removed entirely, which would mean that there is only one `Value` class, and everything is subclassed from that, in a single class hierarchy.

2016-10-14 21:50 UTC, maclover7 commented
cc @sgrif

2016-10-15 02:48 UTC, rafaelfranca requested changes
I could not see where the class was removed. And we can't remove a public facing class without deprecating it.

2016-10-15 02:48 UTC, rafaelfranca commented on activerecord/test/cases/adapters/postgresql/composite_test.rb
> +# coding: utf-8
why?

2016-10-15 02:48 UTC, rafaelfranca commented on activerecord/test/cases/adapters/sqlite3/sqlite3_adapter_test.rb
> +# coding: utf-8
Why?

2016-10-15 02:48 UTC, rafaelfranca commented on activerecord/test/cases/base_test.rb
> +# coding: utf-8
Why?

2016-10-15 06:09 UTC, iainbeeston commented on activerecord/test/cases/base_test.rb
> +# coding: utf-8
Removed

2016-10-15 06:09 UTC, iainbeeston commented on activerecord/test/cases/adapters/sqlite3/sqlite3_adapter_test.rb
> +# coding: utf-8
Removed

2016-10-15 06:10 UTC, iainbeeston commented on activerecord/test/cases/adapters/postgresql/composite_test.rb
> +# coding: utf-8
Removed

2016-10-15 06:28 UTC, iainbeeston commented
Sorry, my mistake. I've deprecated the class now.

2016-10-22 04:27 UTC, rafaelfranca approved these changes
LGTM. r? @sgrif

2016-10-22 09:52 UTC, sgrif commented
I don't know why this class was added. We used to have `Value = ActiveModel::Type::Value`. I would prefer to just return to that line. We purposely expose all of the types in `ActiveModel::Type` under the Active Record namespace. I see no reason to stop doing that.

2016-10-22 13:07 UTC, matthewd commented
Indeed. https://github.com/rails/rails/commit/671eb742eec77b5c8281ac2a2e3976ef32a6e424#diff-6764032bd285660fa20a2849e8dc81efL62

> I believe there's a risk here

@iainbeeston please better distinguish between problems you realise you've introduced a week earlier, and potential dangers that were already present. Doing otherwise leaves your intent.. open to interpretation.

2016-10-22 23:30 UTC, rafaelfranca commented
urgh! Yeah. I'd revert that commit.

2016-10-23 06:20 UTC, closed without merging

2016-10-23 06:22 UTC, iainbeeston commented
@matthewd That wasn't my intent at all. I've spent a lot of time lately trying to understand the types api, and cleaning it up where it felt messy. I agree that it was dumb of me to change the definition of ActiveRecord::Type::Value. But as the code used to be, we set up an "alias" for the Value class, and then used it interchangeably with the original. This seems messy, or at best a temporary solution for backwards compatibility. I can understand why the individual ActiveModel types are aliased in ActiveRecord, but not why their "abstract" parent class is also aliased. I'd argue that deprecating the alias is a better solution than simply changing it back.