Allow any key in Renderer environment hash
rails/rails pull request #26786
Opened 2016-10-13 22:54 UTC by codeodor

When rendering arbitrary templates, it would be helpful to not overwrite `env` keys with nil if they don't match any found in the `RACK_KEY_TRANSLATION`

Is there any interest in this?

2016-10-13 23:02 UTC, rafaelfranca commented
Depends, could you show the use case for this? Right now I don't see why people would want this.

2016-10-13 23:33 UTC, codeodor commented
In my case, I want to pass a key for Warden so that my templates will not throw errors.

But more generally, I was rather surprised that it converted my keys to `nil` instead of just passing them through. I would imagine there are an infinite number of ways that view templates might rely on the environment outside of those predefined keys.

2016-10-13 23:36 UTC, codeodor commented
I think a better way to go about it might be how it handles the values though: 

https://github.com/codeodor/rails/blob/bfc6fbb0004694f94a3679176c4a3e58f3ca8a97/actionpack/lib/action_controller/renderer.rb#L108

2016-10-14 00:32 UTC, codeodor commented
More specifically, if I do something like this:

```
warden_manager = "set up warden"
SomeController.renderer.new(warden: warden_manager).render
```

Then in the template, if we check `request.env['warden']` it is currently nil. If instead we check `request.env[nil]` it will be "set up warden".

This pull request fixes it so that the renderer will not produce the extra `nil` key, and to where `request.env['warden']` will equal "set up warden"

2016-10-15 02:53 UTC, rafaelfranca requested changes
Thank you for the explanation. Could you add a test case and a CHANGELOG entry?

2016-10-15 12:07 UTC, codeodor commented
Thanks @rafaelfranca, and done!

2016-10-15 14:53 UTC, merged

2016-10-15 14:53 UTC, eileencodes commented
Thanks @codeodor! 😄