Add examples of queue_adapter and perform_enqueued jobs to API Docs.
rails/rails pull request #26819
Opened 2016-10-19 06:06 UTC by lastgabs

### Summary

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

If you are updating any of the CHANGELOG files or are asked to update the
CHANGELOG files by reviewers, please add the CHANGELOG entry at the top of the file.

Finally, if your pull request affects documentation or any non-code
changes, guidelines for those changes are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation)

Thanks for contributing to Rails!

2016-10-19 08:29 UTC, prathamesh-sonpatki requested changes

2016-10-19 08:29 UTC, prathamesh-sonpatki commented on activejob/lib/active_job/test_helper.rb
> +    #
we should also write about the `only` argument.

2016-10-19 16:24 UTC, rafaelfranca requested changes
Thank you for the pull request and for improving the documentation. I made some comments inline about improvements that can be made.

2016-10-19 16:24 UTC, rafaelfranca commented on activejob/lib/active_job/test_helper.rb
> +    #
:+1:. It would be good to explain how it can be used.

2016-10-19 16:24 UTC, rafaelfranca commented on activejob/lib/active_job/test_helper.rb
> +    #   def test_assert_job_has_custom_queue_adapter_set
Could you add an empty line above this example?

2016-10-21 16:56 UTC, rafaelfranca approved these changes

2016-10-21 16:56 UTC, merged