allow ActiveRecord::Core#slice to use array arg
rails/rails pull request #26838
Opened 2016-10-20 04:21 UTC by Cohen-Carlisle

### Summary

This allows `ActiveRecord::Core#slice` to take an array of attributes to retain in addition to a splat of arguments, making it behave like like `ActiveRecord::QueryMethods#select`.

### Other Information

Imagine you have some code as follows:

```ruby
class User < ApplicationRecord
  PUBLIC_FIELDS = %i(foo bar baz).freeze

  scope :public_fooed, -> { select(PUBLIC_FIELDS).where(foo: true) }

  def publicize
   slice(*PUBLIC_FIELDS)
  end
end
```

It annoys me that to filter attributes at the model class level (while doing a `::select`), you don't need to splat `PUBLIC_FIELDS`, but you do when doing it at the model object level (with `#slice`).

Since ActiveRecord::Core#slice will never have attributes (or methods) that are arrays, we can safely flatten its arguments to make it behave like `::select` with regard to array arguments.

2016-10-22 03:15 UTC, rafaelfranca commented
Could you add a test case?

2016-10-22 03:15 UTC, rafaelfranca requested changes
Could you add a test case?

2016-10-22 04:14 UTC, Cohen-Carlisle commented
@rafaelfranca sure thing, let me know if `9f9b999` will suffice

2016-10-22 04:17 UTC, rafaelfranca requested changes
Only a small comment. After you fix it could you add a CHANGELOG entry and squash your commits? Thanks.

2016-10-22 04:17 UTC, rafaelfranca commented on activerecord/test/cases/base_test.rb
> +    assert_equal topic.slice(attrs.keys), attrs
it is the other way around. `assert_equal attrs, topic.slice(attrs.keys)`

2016-10-22 04:47 UTC, Cohen-Carlisle commented
@rafaelfranca done and done

2016-10-26 23:35 UTC, Cohen-Carlisle commented
Checking in on this PR.

2016-10-31 14:36 UTC, prathamesh-sonpatki requested changes

2016-10-31 14:36 UTC, prathamesh-sonpatki commented on activerecord/CHANGELOG.md
> +*   Allow `slice` to take an array of methods (without need for splatting)
Can you add a fullstop at the end.

2016-10-31 15:16 UTC, Cohen-Carlisle commented
@prathamesh-sonpatki Done and rebased/squashed.

2016-10-31 15:29 UTC, prathamesh-sonpatki approved these changes

2016-10-31 15:30 UTC, prathamesh-sonpatki commented
Looks good, let's wait for the committer now :smile:

2016-10-31 15:31 UTC, merged

2016-10-31 15:31 UTC, guilleiguaran commented
thank you very much for this, I've missed in some occasions