deep symbolize keys on secrets.yml
rails/rails pull request #26929
Opened 2016-10-29 07:17 UTC by elorest

### Summary

Changed symbolize_keys to deep_symbolize_keys where secrets.yml is loaded in. This allows secret files to contain more complex information without all child keys being strings while parent strings are symbols.

````ruby
{:smtp_settings=>{"address"=>"smtp.mailgun.org", "port"=>587, "domain"=>"example.com", "authentication"=>"plain", "enable_starttls_auto"=>true, "user_name"=>"postmaster@mailgun.example.com", "password"=>"12d3f673e0a83c97045eb4e2d10ebc8a4"}}
````

becomes this

````ruby
{:smtp_settings=>{:address=>"smtp.mailgun.org", :port=>587, :domain=>"example.com", :authentication=>"plain", :enable_starttls_auto=>true, :user_name=>"postmaster@mailgun.example.com", :password=>"12d3f673e0a83c97045eb4e2d10ebc8a4"}}
````

Source yaml.

````yaml
development:
  smtp_settings:
    address: "smtp.mailgun.org"
    port: 587
    domain: "example.com"
    authentication: "plain"
    enable_starttls_auto: true
    user_name: "postmaster@mailgun.example.com"
    password: "12d3f673e0a83c97045eb4e2d10ebc8a4"
````

### Benchmarks

To do benchmarks I wrote a rake task which loaded the environment, printed the secrets and exited.

With `symbolize_keys`:
`2.36 real         1.94 user         0.55 sys`
`2.38 real         1.93 user         0.51 sys`

With `deep_symbolize_keys`
`2.37 real         1.91 user         0.51 sys`
`2.31 real         1.89 user         0.49 sys`

As you can see their doesn't seem to be a negative effect in load time for this change. I wasn't able to find where the secrets.yml loading was being tested, but if someone could point that out to me I'll add tests as well.

2016-11-01 18:10 UTC, sgrif commented
Can you add a test case for this?

2016-11-01 18:16 UTC, elorest commented
@sgrif I would love too. Could you point me to where tests for secret.yml loading are currently being done?

2016-11-01 18:26 UTC, sgrif commented
Yes, those tests which are creating `.secrets.yml` and asserting the result seems like a fine place.

2016-11-01 18:28 UTC, elorest commented
Thanks. I'll add those after after work today.

2016-11-02 04:48 UTC, elorest commented
Tests have been added. Other than just consistency I feel deep serializing works better because it allows you to setup configurations with many options by just passing the hash in. For instance
`config.action_mailer.smtp_settings = Rails.application.secrets.smtp_settings` in application.rb only works if keys are symbols.

2016-11-18 22:28 UTC, rafaelfranca requested changes
Could you add a CHANGELOG entry and squash your commits? Even that is small it is a breaking change.

2016-11-21 22:25 UTC, elorest commented
@maclover7 I did as you requested but got an conflict on CHANGELOG.md so I merged in master but can't seem to squash the merge. Also weirdly after I merged in master, travis checks aren't passing... Any suggestions?

2016-11-21 22:27 UTC, maclover7 commented
@elorest hmm, do you have the latest master locally? I believe you should be able to squash down to one commit via `git rebase -i master`

2016-11-21 23:19 UTC, elorest commented
@maclover7 I created this pull request from my branch is_deep_symbolize_keys. rebase -i isn't working like normal. It brings up thousands of commits. So I just switch back to master, cherry-picked my commit and then force pushed it back to my is_deep_symbolize_secrets on github. Should be good now.

2016-11-21 23:50 UTC, elorest commented
@maclover7 Any idea why travis doesn't pass since I merged in master?

2016-11-21 23:56 UTC, guilleiguaran commented
Failures in Travis aren't related to this PR

2016-11-21 23:56 UTC, merged

2016-11-21 23:56 UTC, guilleiguaran commented
Thank you very much for this 👏

2016-11-22 00:44 UTC, kirs commented
Does this preserve backward compatibility if I used`app.secrets.smtp_settings['password']`? Looks like it doesn't :grimacing:
Maybe it's worth using `HashWithIndifferentAccess` here?

2016-11-22 00:46 UTC, guilleiguaran commented
@kirs: yes, absolutely makes sense

2016-11-22 00:49 UTC, rafaelfranca commented
I don't think it is needed. Like I said in the comment above it is fine to have this small backwards incompatible change as it is in the CHANGELOG.

2016-11-22 01:30 UTC, elorest commented
I considered doing that, but using `HashWithIndifferentAccess` did slow down my benchmark of loading and printing by a small amount. @kirs Default smtp settings for rails expect symbols when you mass assign them so `config.smtp_settings = app.secrets.smtp_settings` is now possible.

2017-04-21 14:54 UTC, printercu commented
@elorest @rafaelfranca This change breaks some gems. There is much more access _with indifferent access_ on every request, when accessing `params`, don't think this would be a problem to make `secrets` work the same way.

2017-04-21 20:41 UTC, rafaelfranca commented
Added a note in the upgrade guide 0541a0d548