Fix NameError: undefined local variable or method `result`
rails/rails pull request #26928
Opened 2016-10-29 06:55 UTC by kamipo

Caused by 007e50d8e5a900547471b6c4ec79d9d217682c5d.

#26925 was closed in favor of dcb364e.
But dcb364e is only fixed sqlite3 adapter and still broken mysql2
adapter with `prepared_statements: true` (`exec_stmt_and_free`).

```diff
diff --git a/activerecord/test/config.example.yml b/activerecord/test/config.example.yml
index 58e2d45..7b3c1a6 100644
--- a/activerecord/test/config.example.yml
+++ b/activerecord/test/config.example.yml
@@ -56,9 +56,11 @@ connections:
       username: rails
       encoding: utf8
       collation: utf8_unicode_ci
+      prepared_statements: true
     arunit2:
       username: rails
       encoding: utf8
+      prepared_statements: true

   oracle:
      arunit:
```

```
% be rake test_mysql2 --verbose
...
Using mysql2
/Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb:90: warning: assigned but unused variable - result
/Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb:101:in `block in exec_stmt_and_free': NameError: undefined local variable or method `result' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x007fe2c50eb140>: SELECT  `ar_internal_metadata`.* FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = ? LIMIT ? (ActiveRecord::StatementInvalid)
        from /Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:586:in `block in log'
...
```

2016-10-29 07:00 UTC, matthewd commented
Oops... looks like we need to add a test for this, because yeah, that's clearly broken.

2016-10-29 07:16 UTC, kamipo commented
BTW, I still see `PG::TRDeadlockDetected` error after 007e50d8e5a900547471b6c4ec79d9d217682c5d.

```
log writing failed. PG::TRDeadlockDetected: ERROR:  deadlock detected
DETAIL:  Process 14245 waits for ShareLock on transaction 1914202; blocked by process 14244.
Process 14244 waits for ShareLock on transaction 1914203; blocked by process 14245.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (0,2) in relation "samples"
: UPDATE "samples" SET "value" = $1 WHERE "samples"."id" = $2
```

```
% git grep -n samples test
test/cases/adapters/mysql2/transaction_test.rb:9:      self.table_name = "samples"
test/cases/adapters/mysql2/transaction_test.rb:17:        @connection.drop_table "samples", if_exists: true
test/cases/adapters/mysql2/transaction_test.rb:18:        @connection.create_table("samples") do |t|
test/cases/adapters/mysql2/transaction_test.rb:27:      @connection.drop_table "samples", if_exists: true
test/cases/adapters/postgresql/transaction_test.rb:10:      self.table_name = "samples"
test/cases/adapters/postgresql/transaction_test.rb:17:        @connection.drop_table "samples", if_exists: true
test/cases/adapters/postgresql/transaction_test.rb:18:        @connection.create_table("samples") do |t|
test/cases/adapters/postgresql/transaction_test.rb:27:      @connection.drop_table "samples", if_exists: true
```

2016-11-14 00:51 UTC, rafaelfranca requested changes

2016-11-14 00:51 UTC, rafaelfranca commented on activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb
> +                result =
Can we keep it in the same line of the method call?

2016-11-14 00:59 UTC, kamipo commented on activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb
> +                result =
Is this what you mean?

```ruby
                result = nil
                ActiveSupport::Dependencies.interlock.permit_concurrent_loads do
                  result = stmt.execute(*type_casted_binds)
                end
```

or

```ruby
                result = ActiveSupport::Dependencies.interlock.permit_concurrent_loads do
                  stmt.execute(*type_casted_binds)
                end
```

2016-11-14 01:08 UTC, kamipo commented on activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb
> +                  stmt.execute(*type_casted_binds)
Fixed it in the same line.

2016-11-14 01:11 UTC, merged