Add ActiveRecord::ConnectionAdapters::ConnectionPool.stat
rails/rails pull request #26988
Opened 2016-11-07 10:27 UTC by Paxa

Example:
```ruby
p ActiveRecord::Base.connection_pool.stat
{
  max: 25,
  total: 1,
  busy: 1,
  dead: 0,
  idle: 0,
  num_waiting: 0,
  checkout_timeout: 5
}
```

Related to #26898

2016-11-07 10:28 UTC, Paxa commented
@matthewd is it how you think or it?

2016-11-08 06:55 UTC, matthewd commented
:+1:

Wrap the method body in a `synchronize do` block to ensure the numbers are consistent.

2016-11-08 14:10 UTC, Paxa commented
Done

2016-11-08 14:38 UTC, jrafanie commented on activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb
> +            total: @connections.size,
Great idea!  Personal preference but max and total are a bit confusing to me.  Naming is hard.  We instantiate a pool with a "size".  A pool contains "connections".  Therefore, my poor naming would be:

```
size: size
connections: @connections.size
```

Either way, this is helpful!

2016-11-08 15:51 UTC, rafaelfranca commented on activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb
> +            total: @connections.size,
Yeah. I like the naming suggested by @jrafanie

2016-11-08 16:45 UTC, Paxa commented
Changed to
```ruby
{ size: 15, connections: 1, busy: 1, dead: 0, idle: 0, waiting: 0, checkout_timeout: 5 }
```

Also `waiting:` feels odd to me, because all other values related to connections, but waiting are consumers. Will it be better to name it as `waiting_in_queue` or `queue`?

2016-11-08 16:48 UTC, rafaelfranca requested changes

2016-11-08 16:48 UTC, rafaelfranca commented on activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb
> +      # Example: <tt>{ size: 15, connections: 1, busy: 1, dead: 0, idle: 0, waiting: 0, checkout_timeout: 5 }</tt>
```
# Example:
#
#    ActiveRecord::Base.connection_pool.stat # => { size: 15, connections: 1, busy: 1, dead: 0, idle: 0, waiting: 0, checkout_timeout: 5 }
```

2016-11-08 16:48 UTC, rafaelfranca commented
Could you add a CHANGELOG entry and squash your commits?

2016-11-08 17:13 UTC, Paxa commented
Done

2016-11-08 21:13 UTC, merged

2018-12-19 10:50 UTC, webervin commented
Spec: 
- add an `GET /db_pool_stat` endpoint, that returns ActiveRecord::Base.connection_pool.stat as json. 

- make followup issue to create munin charts and plot sampled values over time