Refactor ActionCable streaming
rails/rails pull request #27044
Opened 2016-11-14 20:22 UTC by palkan

Implementation of #26999 proposals.

What have been done:
- streaming handlers logic have been moved from `streams.rb` into separate classes
- avoid JSON double-encoding

The [benchmark](https://gist.github.com/palkan/4fa301e0eecc5c881ede385afc59b391) show the following:

```
Calculating -------------------------------------
                     PR  268.290  (±23.9%) i/s -      1.200k in   5.036351s
             current     75.673  (±15.9%) i/s -    365.000  in   5.034415s
```

So, broadcasting is about 4x faster.

/cc @maclover7 @matthewd

2016-11-14 21:00 UTC, maclover7 requested changes
Looking very good so far 👍 

Two small side notes:
- Can you add a description of the changes (especially the performance improvements) to Action Cable's CHANGELOG.md?
- Can you take a look at the failing Code Climate build?

2016-11-14 21:00 UTC, maclover7 commented on actioncable/lib/action_cable/channel/streams_handlers/base.rb
> +      class Base # :nodoc:
Can we move `Base`'s `:nodoc:` declaration up to `StreamHandlers`? Same deal with `Custom`.

2016-11-14 21:00 UTC, maclover7 commented on actioncable/lib/action_cable/channel/streams_handlers/base.rb
> +        attr_reader :channel, :identifier
I might be missing something, but is there are any reason why `channel` and `identifier` need to be part of the public API? 😬

2016-11-14 21:42 UTC, jeremy requested changes

2016-11-14 21:42 UTC, jeremy commented on actioncable/lib/action_cable/channel/streams_handlers/base.rb
> +      class Base # :nodoc:
This is a specialized no-op stream transmitter for use when there's no user handler and pubsub & transmit coders match. Wouldn't call it a Base transmitter which suggests it's meant for public API and subclassing.

2016-11-14 21:42 UTC, jeremy commented on actioncable/lib/action_cable/channel/streams_handlers/custom.rb
> +      end
This is a no-op coder, hence the existing "identity" language. Introducing "null" language ambiguously suggests that it's coding as null/nil or doing null coding.

2016-11-14 21:42 UTC, jeremy commented on actioncable/lib/action_cable/channel/streams_handlers/custom.rb
> +      end
This isn't inheriting anything substantial from Base—the inheritance relationship is misleading.

2016-11-14 21:42 UTC, jeremy commented on actioncable/lib/action_cable/connection/base.rb
>        end
Boolean flags in method signature are a good red flag to investigate.

In this case, we really want a separate API to transmit already-encoded messages. The existing `#transmit` can invoke that API after encoding its message.

2016-11-14 21:42 UTC, jeremy commented on actioncable/test/channel/stream_test.rb
> +        nil
This boilerplate isn't particular to this test; wouldn't move it.

2016-11-14 21:42 UTC, jeremy commented on actioncable/lib/action_cable/channel/streams_handlers/base.rb
> +            "{\"identifier\":#{identifier.to_json},\"message\":#{message}}",
Should identifier be quoted here? It's an embedded JSON document.

2016-11-14 21:42 UTC, jeremy commented on actioncable/lib/action_cable/channel/streams.rb
> -        end
Could introduce coder-aware stream handling directly:
```ruby
def stream_handler(broadcasting, user_handler, coder: nil)
  if user_handler
    user_stream_handler broadcasting, user_handler, coder: coder
  else
    default_stream_handler broadcasting, coder: coder
  end
end

def user_stream_handler(user_handler, coder: nil)
  -> encoded_message { user_handler.(coder.decode(encoded_message)) }
end

def default_stream_handler(broadcasting, coder: nil)
  coder ||= ActiveSupport::JSON
  via = "streamed from #{broadcasting}"

  if coder == ActiveSupport::JSON
    -> encoded_message { transmit_encoded encoded_message, coder: coder, via: via }
  else
    -> encoded_message { transmit coder.decode(encoded_message), via: via }
  end
end
```

2016-11-14 23:35 UTC, matthewd commented
I haven't yet looked in detail, but even in the no-op case, I wonder if we should decode to ensure it's valid JSON before we throw it at clients

2016-11-15 08:13 UTC, palkan commented
> I haven't yet looked in detail, but even in the no-op case, I wonder if we should decode to ensure it's valid JSON before we throw it at clients

No-op case doesn't mean that the message is JSON-encoded. For example:

```ruby
ActionCable.server.broadcast "test", { x: 1 }, coder: MyYAMLCoder
```

No-op only requires that message is a string. Nothing more. Kind of _stupid_ re-transmission.

2016-11-15 09:07 UTC, palkan commented on actioncable/lib/action_cable/channel/streams_handlers/base.rb
> +            "{\"identifier\":#{identifier.to_json},\"message\":#{message}}",
No, we should call `to_json` (which adds surrounding quotes and escapes existing quotes), 'cause `identifier` is a JSON string itself.

2016-11-15 12:01 UTC, palkan commented
@jeremy 
Return steam handlers generation back to `streams.rb`. Looks more clear and concise, thanks!

Also, `#transmit_encoded` methods added to both Connection and Channel.
I intentionally skip logging and instrumentation. First, due to the overhead (adding logging decrease performance about twice!); secondly, I don't think that logging re-transmissions make any sense (we're logging broadcasting as a whole).

@maclover7 
Changelog entry added.
Code Climate is green.

2017-03-08 17:57 UTC, Preen commented
Is there any news on this?

2019-12-25 13:39 UTC, closed without merging