Raise on invalid :as param in integration tests
rails/rails pull request #27060
Opened 2016-11-15 22:14 UTC by courtenay

see Rails/rails#27059

2016-11-15 22:19 UTC, maclover7 commented
cc @kaspth, since you implemented this feature

2016-11-15 22:22 UTC, courtenay commented
oh yeah I'm an idiot, re-pushing

2016-11-15 22:24 UTC, courtenay commented
just burned an hour trying to figure out why `as: :xml` wouldn't work, grrrr, happy to chat about alternatives if you had a good reason for falling back to WWW encoding @kaspth

2016-11-15 22:52 UTC, rafaelfranca requested changes
Many tests are broken because of this.

2016-11-16 10:35 UTC, kaspth commented on actionpack/lib/action_dispatch/testing/request_encoder.rb
> +      @encoders[name] || raise(ArgumentError, "Can't respond with unregistered encoder: #{name}. Register encoders with ActionDispatch::IntegrationTest.register_encoder(:#{name})")
We need to handle nil names:

```ruby
if name
  @encoders[name] || raise(#...)
else
  WWWFormEncoder
end
```

2016-11-16 10:38 UTC, kaspth commented on actionpack/lib/action_dispatch/testing/request_encoder.rb
> +      @encoders[name] || raise(ArgumentError, "Can't respond with unregistered encoder: #{name}. Register encoders with ActionDispatch::IntegrationTest.register_encoder(:#{name})")
For the error message, I'd go with:

```
Unknown encoder: can't encode the request as: #{name.inspect}. Define the encoder with `ActionDispatch::IntegrationTest.register_encoder`
```

2016-11-16 10:39 UTC, kaspth commented on actionpack/test/controller/integration_test.rb
> +  end
Needs to test that `as: nil` doesn't raise.

2016-11-23 21:21 UTC, kaspth commented
Heads up! I opted to expand the documentation instead. Thanks for bringing this up :)

2016-11-23 21:23 UTC, closed without merging