Fix unscope with subquery
rails/rails pull request #27122
Opened 2016-11-20 20:45 UTC by kamipo

Currently cannot unscope subquery properly.
This commit fixes the issue.

Fixes #26323.

2016-11-25 10:45 UTC, rafaelfranca requested changes

2016-11-25 10:45 UTC, rafaelfranca commented on activerecord/lib/active_record/relation/where_clause.rb
> +          *predicates.each_with_object([[], []]) { |node, (prts, bvs)|
This method is too complicated. Can we refactor it so the code is more intention revealing?

Like what is `prts` and `bvs`?

What this loop is doing?

What that case is trying to find?

What that `unless` block is doing?

2016-11-27 03:22 UTC, kamipo commented
I refactored to keep the indentation of the original case statement to reduce the diff. I think it is easier to read than the previous implementation.

2017-02-13 03:36 UTC, rafaelfranca requested changes

2017-02-13 03:36 UTC, rafaelfranca commented on activerecord/lib/active_record/relation/where_clause.rb
> +            end.tap do |except|
This tap is confusing. Can you avoid it?

2017-02-13 03:47 UTC, kamipo commented on activerecord/lib/active_record/relation/where_clause.rb
> +            if except && binds_contains > 0
I avoided using `tap`.

2017-02-13 03:51 UTC, rafaelfranca approved these changes

2017-02-13 04:35 UTC, merged