Action Cable: JavaScript test updates
rails/rails pull request #27123
Opened 2016-11-20 22:14 UTC by javan

* Adds more JavaScript tests (cc: @maclover7)
* Ensures Sauce Labs tunnel closes properly and fixes CI errors like https://travis-ci.org/rails/rails/jobs/165766716#L506 (cc: @matthewd)

2016-11-20 22:44 UTC, maclover7 requested changes
Overall big 👍 👍 to adding more tests for Action Cable's JS! If possible, can you make each of the test's names more descriptive? While I was reading through, it was a little tough to determine what each of the tests was doing 😬

2016-11-20 22:44 UTC, maclover7 commented on actioncable/test/javascript/src/unit/subscription_test.coffee
> +
too many empty lines here? 😬

2016-11-20 22:44 UTC, maclover7 commented on actioncable/test/javascript/src/unit/subscription_test.coffee
> +broadcast = (data = {}, callback) ->
Might be a bit early, but should we extract the `broadcast` function out to where the rest of the "helper" functions are?

2016-11-21 14:41 UTC, javan commented
@maclover7 done and done

2016-11-21 15:24 UTC, merged

2016-11-21 15:24 UTC, kaspth commented
Nice!