Fix unsigned with zerofill
rails/rails pull request #27126
Opened 2016-11-21 08:44 UTC by kamipo

Fixes #27125.

2016-11-21 08:54 UTC, prathamesh-sonpatki commented on activerecord/lib/active_record/connection_adapters/mysql/column.rb
> +          /\bunsigned\b/.match?(sql_type)
@kamipo The enum unsigned test will fail due to this, I think we need special treatment for enum.

Something like this:

```ruby
        def unsigned?
          if (/^enum/).match?(sql_type)
            actual_sql_type = sql_type[/^enum\((.+)\)(.+)/i, 2]
          else
            actual_sql_type = sql_type
          end

          /\bunsigned\b/.match?(actual_sql_type)
        end
```

2016-11-21 08:58 UTC, utilum reviewed
Would it be nice to give this all tests that other types need to pass?

2016-11-21 09:22 UTC, prathamesh-sonpatki commented on activerecord/lib/active_record/connection_adapters/mysql/column.rb
> +          !/\A(?:enum|set)\b/.match?(sql_type) && /\bunsigned\b/.match?(sql_type)
Nice!

2016-11-24 02:03 UTC, rafaelfranca commented on activerecord/lib/active_record/connection_adapters/mysql/column.rb
> +          !/\A(?:enum|set)\b/.match?(sql_type) && /\bunsigned\b/.match?(sql_type)
I don't get why this is needed. Does `enum` and `set` types allow to be defined as `unsigned`?

2016-11-24 08:56 UTC, kamipo commented on activerecord/lib/active_record/connection_adapters/mysql/column.rb
> +          !/\A(?:enum|set)\b/.match?(sql_type) && /\bunsigned\b/.match?(sql_type)
`enum` and `set` types does not allow to be defined as `unsigned`. But if defined as `enum('foo','bar','unsigned')`, `column.unsigned?` returns `true`. It is incorrect.

https://github.com/rails/rails/blob/master/activerecord/test/cases/adapters/mysql2/enum_test.rb#L12-L15

```ruby
  def test_should_not_be_unsigned
    column = EnumTest.columns_hash["enum_column"]
    assert_not column.unsigned?
  end
```

2016-11-25 09:28 UTC, rafaelfranca requested changes
Could you add a CHANGELOG entry?

2016-11-27 01:57 UTC, kamipo commented
I added a CHANGELOG entry!

2016-11-29 16:10 UTC, merged

2016-11-29 21:56 UTC, rafaelfranca commented
Backported in f39779f