Fix a force ssl redirection bug that occur when session store disabled.
rails/rails pull request #27140
Opened 2016-11-22 05:51 UTC by supercaracal

### Summary

https://github.com/rails/rails/pull/19682#issuecomment-261835411

@spastorino @prathamesh-sonpatki @rafaelfranca 

### Sample applications to reploduce
* https://github.com/supercaracal/session_store_less_sample
* https://github.com/bronson/force-ssl-repro-app

### Issues
* https://github.com/rails/rails/issues/19679
* https://github.com/rails/rails/issues/27009

2016-11-22 06:19 UTC, supercaracal commented
> PG::TRDeadlockDetected: ERROR:  deadlock detected
> SQLite3::BusyException: database is locked: DELETE FROM "delayed_jobs"

They're not seem to be related. Can I rerun this CI?

2016-11-22 06:43 UTC, prathamesh-sonpatki commented
Restarted the build, we can ignore that failure if it happens again.

2016-11-24 00:08 UTC, rafaelfranca requested changes

2016-11-24 00:08 UTC, rafaelfranca commented on actionpack/test/controller/force_ssl_test.rb
> +class RedirectToSSLIfSessionStoreDisabled < ForceSSLController
This is testing an implementation detail. Can we test it at integration level so we don't need to mock the request object?

2016-11-24 05:21 UTC, supercaracal commented on actionpack/test/controller/force_ssl_test.rb
> +class RedirectToSSLIfSessionStoreDisabled < ForceSSLController
I changed at da1453e @rafaelfranca

2016-11-24 05:46 UTC, supercaracal commented on actionpack/test/controller/force_ssl_test.rb
> +class RedirectToSSLIfSessionStoreDisabled < ForceSSLController
Build [failed](https://travis-ci.org/rails/rails/jobs/178503726). But we can ignore that.

> PG::TRDeadlockDetected: ERROR:  deadlock detected

2016-11-25 09:55 UTC, merged

2016-11-25 09:56 UTC, rafaelfranca commented
Backported in c1f990c