make path helper work with `ActionController::Parameters`
rails/rails pull request #27176
Opened 2016-11-25 05:55 UTC by y-yagi

### Summary

The path helper calls `#to_param` inside. But `ActionController::Parameters`
does not have `#to_param`, so `NoMethodError` error will raise.
To avoid this, convert to hash if argument is `ActionController::Parameters`

Fixes #26958.

2016-11-25 06:03 UTC, rafaelfranca requested changes

2016-11-25 06:03 UTC, rafaelfranca commented on actionpack/lib/action_dispatch/http/url.rb
> +          params.transform_values! { |v| v.respond_to?(:permitted?) ? v.to_h : v }
We should be doing the same as https://github.com/rails/rails/blob/2b4a9735d816d3a05c7fca207d97bebcb09c95a0/actionview/lib/action_view/helpers/url_helper.rb#L619-L628 here

2016-11-25 09:09 UTC, rafaelfranca commented
Could you add a CHANGELOG entry?

2016-11-25 14:00 UTC, y-yagi commented
I added CHANGELOG entry!

2017-01-19 12:56 UTC, bquorning commented
The [documentation for ActionController::Parameters](https://github.com/rails/rails/blob/v5.0.0.1/actionpack/lib/action_controller/metal/strong_parameters.rb#L44-L50) says

> Allows you to choose which attributes should be whitelisted for mass updating and thus prevent accidentally exposing that which shouldn't be exposed. Provides two methods for this purpose: `#require` and `#permit`. The former is used to mark parameters as required. The latter is used to set the parameter as permitted and limit which attributes should be allowed for mass updating.

As I understand it, AC::Parameters is about protecting mass assignment, not about protecting URL generation.

Of course, you probably want to filter out `:protocol`, `:host`, `:subdomain`, `:domain`, and `:port` before e.g. redirecting to `url_for(params)`, but for this you need blacklisting – not the whitelisting provided by `ActionController::Parameters#permit`. Something like `url_for(params.to_unsafe_h.merge(only_path: true))` works in these cases.

2017-01-20 08:46 UTC, y-yagi commented
> As I understand it, AC::Parameters is about protecting mass assignment, not about protecting URL generation.

In my understanding it is already discussed and I think it is a missing document update.
Ref: #20797

2017-03-04 08:52 UTC, y-yagi commented
Rebase with master.

2017-04-20 09:07 UTC, y-yagi commented
fixed by #28734.

2017-04-20 09:07 UTC, closed without merging