Stop testing MRI implementation details
rails/rails pull request #27324
Opened 2016-12-10 18:41 UTC by kirs

Right now this test fails on JRuby:

```
--- expected
+++ actual
@@ -1 +1 @@
-#<BigDecimal:5f3c866c,'0.333333333333333333',18(20)>
+#<BigDecimal:16e0afab,'0.3333333333333333',16(20)>
```

We should not describe MRI implementation details in tests because it's
valid only for MRI. We can't guarantee that `Rational(1, 3)` will
always be '0.3333333333333333',16(20) on other platforms.

This is the same issue as in #27117

@guilleiguaran @maclover

2016-12-10 19:47 UTC, matthewd commented
The test name doesn't say "at least 16".

We should at least change the test, but also review whether we consider this to be an interpreter detail we're happy to expose, or something we need to explicitly unify.

2016-12-12 23:25 UTC, kirs commented
Thanks, I've updated the test.

This test covers the behavior of `cast_value` method of the type object (https://github.com/rails/rails/blob/master/activemodel/lib/active_model/type/decimal.rb#L18-L34). IMO this is enough reason to not hardcore the expected precision that comes from the MRI implementation.

2016-12-12 23:52 UTC, matthewd commented
We have to make some statement about the precision -- that's the whole point of the test. And it seems disingenuous to imply that "18" is a short-sighted hardcoding of MRI implementation details, but ">= 16" is a universal truth: we're just changing the hard-coding to something that accommodates JRuby's implementation details. That might be a reasonable thing to do, but let's not pretend we're doing something more Pure.

My question remains, however, whether we *want* `AM::T::Decimal#cast_value` to have implementation-dependent behaviour, or whether (having identified that the current implementation can vary between runtimes) we instead want to rewrite it to something that guarantees a consistent result.

2017-01-03 17:40 UTC, sgrif commented
I'd prefer to change the implementation to return something consistent across platforms. Since this case only affects casting floats, it won't affect existing DB values and should be safe to make.

2017-01-03 17:41 UTC, sgrif requested changes
See above comment

2017-01-03 22:17 UTC, kirs commented
Normally I would change the implementation, but with floating point it may be hard to change. I'm not surprised that JVM does floating differently from CRuby. I'll see what I can do with JRuby.

2017-01-03 22:31 UTC, sgrif commented
I don't think it's hard to change. I'm pretty sure the solution is to just specify a precision [here](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/type/decimal.rb#L40)

2017-01-04 00:16 UTC, kirs commented
Oh, did you mean changing `ActiveModel::Type::Decimal`? I thought you were talking about float implementation in JRuby.

2017-01-04 00:40 UTC, sgrif commented
I am not asking you to change the implementation of JRuby

2017-01-22 15:34 UTC, kirs commented
Closing this in favor of https://github.com/rails/rails/pull/27768

2017-01-22 15:34 UTC, closed without merging