`primary_key` and `references` columns should be identical type
rails/rails pull request #27334
Opened 2016-12-11 23:10 UTC by kamipo

Follow up to #26266.

The default type of `primary_key` and `references` were changed to
`bigint` since #26266. But legacy migration and sqlite3 adapter should
keep its previous behavior.

2017-01-03 17:37 UTC, sgrif requested changes

2017-01-03 17:37 UTC, sgrif commented on activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb
> +        args.each do |ref_name|
The changes to this file don't seem necessary.

2017-01-03 17:37 UTC, sgrif commented on activerecord/lib/active_record/migration/compatibility.rb
> +                prepend TableDefinition
This looks identical to the body of the superclass definition. Am I missing something?

2017-01-04 02:22 UTC, kamipo commented on activerecord/lib/active_record/migration/compatibility.rb
> +                prepend TableDefinition
`class << t` is the eigenclass of the `t` instance, this `prepend` is to the the eigenclass, not the superclass.

2017-01-04 03:01 UTC, kamipo commented on activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb
> +        args.each do |ref_name|
Actually `args` is an array of `ref_name`, not `col`. And `**options` create new hash.

```ruby
irb(main):001:0> def foo(o)
irb(main):002:1>   o.object_id
irb(main):003:1> end
=> :foo
irb(main):004:0> a = {}
=> {}
irb(main):005:0> a.object_id
=> 70096840684060
irb(main):006:0> foo(a)
=> 70096840684060
irb(main):007:0> foo(**a)
=> 70096844445860
```

`TableDefinition` and `Table` classes exists in the doc. I think it is better to define consistent method signature.
Should I separate a PR as fixing the doc?

http://edgeapi.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/Table.html#method-i-references
http://edgeapi.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/TableDefinition.html#method-i-references

2017-02-07 07:02 UTC, jeremy approved these changes
🙌

2017-02-07 07:03 UTC, merged