Adding protect_from_forgery into ActionController::Base
rails/rails pull request #27362
Opened 2016-12-14 18:56 UTC by homakov

### Pre-history

Ever asked yourself why default `application_controller` looks like this?

```
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end
```

Like many things in Rails, it's just a tradition, not because it's the right thing to do. (Remember match ':controller/:action/:id' that left every single action vulnerable to CSRF?).

Let's figure out how exactly this innocent line is bad. First, <a href="http://homakov.blogspot.com/2014/12/blatant-csrf-in-doorkeeper-most-popular.html">we need to review a story with Doorkeeper</a> which left every Doorkeeper endpoint vulnerable to CSRF i.e. getting access token with any scope with unauthenticated POST request. Websites like Digital Ocean/Coinbase etc got a really bad bug because of 3rd party library.

The problem behind that was how Doorkeeper's ApplicationController inherited from Base w/o the protect_from_forgery part. Same thing happened to few other gems: it's very easy to forget to include that critical line of code. Many developers create new internal controllers (like AdminController) and also don't include that line. Long story short, I read a lot of Rails code in my life: **it's been a disaster.**

It's clear to everyone, protect_from_forgery must be ON by default. But the right place for it is in `base.rb`, not in the generated template. Base has everything that works with the browser: cookies, sessions, redirects, and to work properly with the browser it also must *always* verify the authenticity_token. It's not like we can routinely switch it on or of.

## CSRF protection 101: 

If the request has authenticity_token equal one from the session = request was initiated from our domain, session and cookies can be used.

If it lacks authenticity_token or it's invalid = nullify cookies/session. Do not raise any error - explicit API tokens can be used. Just pretend you didn't receive any cookies plus show a console warning "Received cookies without valid authenticity_token".

There's no use in two other options:

1. As you can see `with: :exception` breaks APIs - those would be just fine w/o cookies (and there wouldn't be tons of reports on StackOverflow from people trying to make API work on Rails and eventually switching that annoying thing off with skip_before_filter...).

2. :reset_session option would be equivalent to Log Out CSRF - very annoying low severity bug, makes no sense to use this one.

Recap:

1. We must add `protect_from_forgery with: :null_session` directly to `base.rb`, to the controlling talking to the browser. That would prevent dozens of gems out there being vulnerable to CSRF like Doorkeeper because they forgot to add "protect_me_from_csrf" line at some point

2. We should deprecate two other options :reset_session/:exception because they are useless and even somewhat dangerous.

2016-12-16 21:43 UTC, utilum requested changes
- CI failures are related, you need to tweak all those AP and AC tests that do not expect protection.
- Add tests to verify protection is on and does not raise etc...
- Edit the template to remove the `protect_from_forgery with: :exception` line from generated controllers.
- Document...

2016-12-17 18:05 UTC, eileencodes commented
cc/ @rails/security

2016-12-17 18:53 UTC, homakov commented
@utilum as you can see I'm not sending a patch, i'm raising an issue.

2016-12-17 19:19 UTC, utilum commented
@homakov I understand now. I'd be happy to make a more elaborate PR of this.

2016-12-18 20:46 UTC, homakov commented
@utilum this is something team should agree on, and I gave all the arguments. The fix itself is a one liner, with tiny tests/docs update

2016-12-27 04:13 UTC, homakov commented
Meanwhile many gems are still getting it wrong and insecure by default. Lets finally fix it?

https://blog.sourceclear.com/rails_admin-vulnerability-disclosure/

2016-12-27 15:20 UTC, eileencodes commented
Hey @homakov we're discussing this issue internally. It's a problem that outside gems are making applications insecure by leaving `protect_from_forgery out`, but your change would require users to skip the callback if there were controllers that they wanted to skip CSRF protection in. We have some ideas for better handling CSRF protection in Rails, but those require discussion, planning, and a migration path for existing applications.

So, we're in agreement that it's bad gems are making applications vulnerable, but we don't necessarily like this fix. Thanks for bringing this up and your patience as we figure out the best course of action.

2017-03-03 22:46 UTC, codelion commented
Given the large number of Ruby developers that are affected by this issue, I am hoping fixing this will get some priority:
https://www.sourceclear.com/blog/Over-50000-Ruby-developers-impacted-by-CSRF-attacks/

2017-07-10 21:26 UTC, rafaelfranca commented
Fixed by https://github.com/rails/rails/pull/29742

2017-07-10 21:26 UTC, closed without merging