ensure `#compact` of HWIDA to return HWIDA
rails/rails pull request #27392
Opened 2016-12-17 10:27 UTC by y-yagi

`Hash#compact` of Ruby native returns new hash.
Therefore, in order to return HWIDA as in the past version, need to
define own `#compact` to HWIDA.

Related: #26868

2016-12-17 15:33 UTC, rafaelfranca commented
Which class a subclass of hash returns?
On Sat, Dec 17, 2016 at 5:28 AM Ruby on Rails Bot <notifications@github.com>
wrote:

> r? @sgrif <https://github.com/sgrif>
>
> (@rails-bot <https://github.com/rails-bot> has picked a reviewer for you,
> use r? to override)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rails/rails/pull/27392#issuecomment-267755341>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAC66EIekz5h2JK9mJbwt1onk_GtouWuks5rI7k7gaJpZM4LP2rm>
> .
>

2016-12-17 23:35 UTC, y-yagi commented
Other than HWIDA, `OrderedOptions` is.
However, since `compact` of `OrderedOptions` is returned as hash originally, there is no problem.

2016-12-18 22:11 UTC, eugeneius commented
I think @rafaelfranca meant "what is returned when `#compact` is called on a subclass of Hash?"

```ruby
$ ruby --version
ruby 2.4.0preview3 (2016-11-07 trunk 56661) [x86_64-darwin16]
$ irb
irb(main):001:0> Hash.new.compact.class
=> Hash
irb(main):002:0> class SubclassOfHash < Hash; end
=> nil
irb(main):003:0> SubclassOfHash.new.compact.class
=> Hash
```

It returns a Hash, so this behaviour will differ from Ruby's implementation. However I think it's more important to preserve the previous behaviour of HWIDA, since users could be relying on it.

`#transform_values` had the same problem, and was fixed in https://github.com/rails/rails/pull/26895.

2017-01-03 17:31 UTC, sgrif requested changes

2017-01-03 17:31 UTC, sgrif commented on activesupport/lib/active_support/hash_with_indifferent_access.rb
> +      select { |_, value| !value.nil? }
Rather than reimplementing `compact` ourselves, can we just do `.dup.compact!`?

2017-01-06 08:54 UTC, y-yagi commented on activesupport/lib/active_support/hash_with_indifferent_access.rb
> +      select { |_, value| !value.nil? }
`.dup.comact!` looks good. I updated. Thanks!

2017-01-06 11:23 UTC, merged

2017-02-23 23:43 UTC, rwz commented on activesupport/lib/active_support/hash_with_indifferent_access.rb
> +      select { |_, value| !value.nil? }
For posterity, changing this originally correct solution to `dup.compact!` introduced a bug: https://github.com/rails/rails/pull/28138