Make ActiveRecord structure load/dump configurable
rails/rails pull request #27437
Opened 2016-12-22 15:45 UTC by kirs

Right now it's not possible to pass extra flags to
`mysqldump/pg_dump` when running `rake db:structure:dump` or `rake db:structure:load`

The following config variables (`structure_load_flags` and `structure_dump_flags`) make it better configurable.

Background: today at Shopify we have to monkey patch `ActiveRecord::Tasks::MySQLDatabaseTasks` to accommodate extra flags:

```ruby
module ActiveRecordDbCommandPatch
  def run_cmd(cmd, args, action)
    if cmd == "mysqldump"
      args.insert(0, "--no-defaults")
      args.concat(["--skip-add-drop-table"])
    elsif cmd == "mysql"
      args.insert(0, "--no-defaults")
    end

    super(cmd, args, action)
  end
end

ActiveRecord::Tasks::MySQLDatabaseTasks.prepend(ActiveRecordDbCommandPatch)
```

With this PR we can reduce amount of monkeypatches required to run Rails with MySQL at scale and make it more configurable.

2016-12-22 16:07 UTC, rafaelfranca requested changes

2016-12-22 16:07 UTC, rafaelfranca commented on activerecord/lib/active_record/core.rb
> +      mattr_accessor :structure_dump_flags, instance_accessor: false
I don't think this configuration should be at `ActiveRecord::Base` Maybe it is a better fit for the `DatabaseTasks` class?

2016-12-22 16:29 UTC, kirs commented on activerecord/lib/active_record/core.rb
> +      mattr_accessor :structure_dump_flags, instance_accessor: false
Yeah, I wasn't sure about `AR::Base` either. Should it be configurable with:

```ruby
ActiveRecord::Tasks::DatabaseTasks.structure_dump_flags = ["--noop"]
ActiveRecord::Tasks::DatabaseTasks.structure_load_flags = ["--noop"]
```

?

2016-12-22 16:57 UTC, rafaelfranca commented on activerecord/lib/active_record/core.rb
> +      mattr_accessor :structure_dump_flags, instance_accessor: false
Yeah. That looks better for me.

2016-12-22 17:07 UTC, kirs commented on activerecord/lib/active_record/core.rb
> +      mattr_accessor :structure_dump_flags, instance_accessor: false
I'm a bit concerned about introducing extra place with a config, but I like it too.

2016-12-22 19:14 UTC, kaspth commented on activerecord/lib/active_record/tasks/mysql_database_tasks.rb
> +        args.concat(Array(extra_flags)) if extra_flags.any?
This should probably just be `if extra_flags` like above.

2016-12-22 19:15 UTC, kaspth commented on activerecord/test/cases/tasks/mysql_rake_test.rb
> +
✂️

2016-12-22 19:15 UTC, kaspth commented on activerecord/test/cases/tasks/mysql_rake_test.rb
> +
✂️

2016-12-22 19:15 UTC, kaspth commented on activerecord/test/cases/tasks/postgresql_rake_test.rb
> +
✂️

2016-12-22 19:16 UTC, kaspth commented on activerecord/test/cases/tasks/mysql_rake_test.rb
> +          .returns(true)
We've been trying to move away from Mocha (admittedly stalled at the moment) and have introduced these assertions to help with that: https://github.com/rails/rails/blob/2fd3034bf1862bb8e40c0a0a162316b8ff564d0e/activesupport/lib/active_support/testing/method_call_assertions.rb

Can we switch to those in these new tests?

2016-12-23 14:48 UTC, kirs commented
Thanks everyone for review! I updated the PR.

2016-12-29 19:23 UTC, merged

2016-12-29 19:23 UTC, kaspth commented
Thanks!

2018-12-12 22:35 UTC, stoivo commented
I know it might be stupid to ask, but do you use this?

2018-12-22 15:49 UTC, kirs commented
Yep, we use `ActiveRecord::Tasks::DatabaseTasks.structure_dump_flags = ['--no-defaults', '--skip-add-drop-table']` at Shopify.

2021-12-02 15:17 UTC, mecampbellsoup commented
> Yep, we use `ActiveRecord::Tasks::DatabaseTasks.structure_dump_flags = ['--no-defaults', '--skip-add-drop-table']` at Shopify.

@kirs you just set this configuration in an initializer or something? Glad to have found this PR!