Add Symbol/Proc support to association autosave
rails/rails pull request #27443
Opened 2016-12-23 17:20 UTC by legendetm

### Summary

Add Symbol/Proc support to association autosave to conditionally disable `autosave` when creating model. In some situations I want to bulk import associations later, but want to assign them when initializing parent object.

```
class Measurement
  has_many :logs, autosave: :autosave_logs
  ...
end
```

2016-12-29 03:06 UTC, rafaelfranca requested changes
Could you add a changelog entry?

2016-12-29 03:06 UTC, rafaelfranca commented on activerecord/test/cases/autosave_association_test.rb
> +    assert p.persisted?
`assert_predicate`

2016-12-29 03:06 UTC, rafaelfranca commented on activerecord/test/cases/autosave_association_test.rb
> +    assert p.birds[0].new_record?
`assert_predicate`

2016-12-29 03:06 UTC, rafaelfranca commented on activerecord/test/cases/autosave_association_test.rb
> +    assert p.persisted?
`assert_predicate`

2016-12-29 03:06 UTC, rafaelfranca commented on activerecord/test/cases/autosave_association_test.rb
> +    assert p.birds[0].persisted?
`assert_predicate`

2016-12-29 03:06 UTC, rafaelfranca commented on activerecord/test/cases/autosave_association_test.rb
> +    assert p.persisted?
`assert_predicate`

2016-12-29 03:06 UTC, rafaelfranca commented on activerecord/test/cases/autosave_association_test.rb
> +    assert p.birds[0].new_record?
`assert_predicate`

2016-12-29 03:06 UTC, rafaelfranca commented on activerecord/test/cases/autosave_association_test.rb
> +    assert p.persisted?
`assert_predicate`

2016-12-29 03:06 UTC, rafaelfranca commented on activerecord/test/cases/autosave_association_test.rb
> +    assert p.birds[0].persisted?
`assert_predicate`

2016-12-29 06:57 UTC, matthewd requested changes
The `:autosave` option is read in a *lot* more places than this one. Have you really determined all the rest are fine as is?

2017-01-12 19:47 UTC, legendetm commented
I updated the code and now the `:autosave` option is evaluated everywhere, except in `ActiveRecord::Reflection#validate?`.

To use it there, I need to move the evaluation to a separate class, but as a workaround, it's possible to force the validation with `:validate` option.

2017-03-04 04:48 UTC, davidpatters0n commented
@rafaelfranca , @matthewd - Appears that @legendetm had addressed your comments. @legendetm your branch needs rebasing FYI. 😄

2017-03-12 19:41 UTC, legendetm commented
I will rebase it after I have received feedback that the solution in OK.

2019-12-25 13:39 UTC, closed without merging