Dump schema cache for custom connection
rails/rails pull request #27526
Opened 2016-12-31 17:19 UTC by kirs

Today `rake db:schema:cache:dump` only supports dumping cache for a
single connection (`ActiveRecord::Base.connection`). This doesn't work
for apps with multiple databases.

This PR makes `DatabaseTasks` to provide an API for dumping schema cache
for any connection.

The use case: today at Shopify we have to patch `rake db:schema:cache:dump` to accomodate dumping schema cache for multiple databases:

```ruby
sharded_connections.each do |conn|
  conn.schema_cache.clear!
  conn.data_sources.each { |table| conn.schema_cache.add(table) }
  filename = filename_for_conn(conn)
  open(filename, "wb") { |f| f.write(YAML.dump(conn.schema_cache)) }
end
```

This could be simplified with `ActiveRecord::Tasks::DatabaseTasks.dump_schema_cache` that the PR introduces.

@kaspth @rafaelfranca

2016-12-31 21:40 UTC, kirs commented on activerecord/lib/active_record/tasks/database_tasks.rb
> +      def dump_schema_cache(conn, filename)
Should I add rdoc for this method?

2017-01-01 19:32 UTC, rafaelfranca requested changes

2017-01-01 19:32 UTC, rafaelfranca commented on activerecord/lib/active_record/tasks/database_tasks.rb
> +      def dump_schema_cache(conn, filename)
Yes. If we want to make it public API is better to document.

2017-01-02 00:24 UTC, kirs commented
@rafaelfranca thanks! I've added the doc.

2017-01-02 03:55 UTC, merged

2017-01-02 20:32 UTC, kaspth commented
👍 but isn't this more of a stop gap because the database tasks are ill equipped when it comes to multiple databases in general?

2017-01-02 20:36 UTC, kirs commented
Good question. Should I work on getting database tasks ready for multiple
databases?

On Jan 2, 2017 3:33 PM, "Kasper Timm Hansen" <notifications@github.com>
wrote:

> 👍 but isn't this more of a stop gap because the database tasks are ill
> equipped when it comes to multiple databases in general?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rails/rails/pull/27526#issuecomment-270017374>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAf3qzRNr5V-ToG0qqk9mhQnGB4ASdtxks5rOV8SgaJpZM4LYlxQ>
> .
>

2017-01-04 02:55 UTC, rafaelfranca commented
> Good question. Should I work on getting database tasks ready for multiple databases?

:+1: