Clarify Bi-directional Associations docs
rails/rails pull request #27538
Opened 2017-01-01 18:29 UTC by davidsherline

### Summary

Rails automatically finds bi-directional associations between models
with well-named associations. However, when using non-standard naming,
you have to use :inverse_of to explicitly tell Rails about the bi-
directional association.

Addresses issue #27516

[ci skip]

2017-01-01 19:35 UTC, maclover7 requested changes
Few small changes, otherwise looks good to me!

2017-01-01 19:35 UTC, maclover7 commented on guides/source/association_basics.md
> +Active Record supports automatic identification for most associations with standard names. However, Active Record will not automatically identify bi-directional associations that contain the followin
`the following options` --> `any of the following options`

2017-01-01 19:35 UTC, maclover7 commented on guides/source/association_basics.md
> +Active Record provides the `:inverse_of` option so that you can declare bi-directional associations that it cannot recognize automatically:
Can we tighten this up to:

[...]  `:inverse_of` option so you can explicitly declare bi-directional associations.

2017-01-01 19:35 UTC, maclover7 commented on guides/source/association_basics.md
> +By including the `:inverse_of` option in the `has_many` declaration, Active Record will now recognize the bi-directional association:
`has_many` association declaration

2017-01-02 17:09 UTC, davidsherline commented
Great notes! Made the changes as requested.

2017-01-02 18:06 UTC, maclover7 approved these changes

2017-01-02 18:06 UTC, maclover7 commented
Can you just squash down to one commit, and then I'll merge? Thanks!

2017-01-03 15:17 UTC, davidsherline commented
Of course, it's down to one commit now

2017-01-03 18:45 UTC, merged