Use `count(:all)` in HasManyAssociation#count_records
rails/rails pull request #27561
Opened 2017-01-04 00:40 UTC by klaseskilson

Problem: Calling `count` on an association can cause invalid SQL queries to be created where the `SELECT COUNT(a, b, c)` function receives multiple  columns. This will cause a `StatementInvalid` exception later on.

Solution: Use `count(:all)`, which generates a `SELECT COUNT(*)...` query independently of the association.

Background: This appears to be previously an known problem, see https://github.com/rails/rails/issues/15138 and https://github.com/rails/rails/issues/13648.

Hit me with your feedback! 👍

2017-01-04 00:47 UTC, rafaelfranca requested changes
Code looks good to me and it make sense to be fixed but could you add a test case to make sure it doesn't break again?

2017-01-04 00:49 UTC, klaseskilson commented
Sure thing, I'll give it a whirl. 👍

2017-01-05 17:46 UTC, klaseskilson commented
Other things are craving for my attention right now. For some reason, I am unable to replicate the problem in a test case. From what I've understood, the issue appears when you call `size` on a `ActiveRecord::Associations::CollectionProxy`, for a `has_many` association.

The stack looks like this: 

```
activerecord (5.0.1) lib/active_record/connection_adapters/abstract_adapter.rb:578:in `translate_exception_class'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract_adapter.rb:591:in `rescue in log'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract_adapter.rb:589:in `log'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
activerecord (5.0.1) lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:225:in `execute_and_free'
activerecord (5.0.1) lib/active_record/connection_adapters/mysql/database_statements.rb:36:in `exec_query'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/query_cache.rb:93:in `block in select_all'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/query_cache.rb:108:in `cache_sql'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/query_cache.rb:93:in `select_all'
activerecord (5.0.1) lib/active_record/connection_adapters/mysql/database_statements.rb:10:in `select_all'
activerecord (5.0.1) lib/active_record/relation/calculations.rb:248:in `execute_simple_calculation'
activerecord (5.0.1) lib/active_record/relation/calculations.rb:207:in `perform_calculation'
activerecord (5.0.1) lib/active_record/relation/calculations.rb:121:in `calculate'
activerecord (5.0.1) lib/active_record/relation/calculations.rb:40:in `count'
activerecord (5.0.1) lib/active_record/associations/has_many_association.rb:79:in `count_records'
activerecord (5.0.1) lib/active_record/associations/collection_association.rb:323:in `size'
activerecord (5.0.1) lib/active_record/associations/collection_proxy.rb:767:in `size'
...
```

2017-01-05 18:13 UTC, klaseskilson commented
What I have so far in terms of test is 

```ruby
author = Author.create!(name: "A")
5.times { author.posts << Post.create!(title: "a", body: "b") }
same_authors_posts = Author.find(author.id).posts
assert_equal 5, same_authors_posts.size
```

The issue is that this works, and I'm not really sure what to do in order to actually end up in the same place as I do when the issue appears. Do you have any suggestions on how to proceed?

2017-01-06 09:36 UTC, rafaelfranca commented
I'm afraid I don't have any good suggestion how to proceed other than try to isolate the code in your application that trigger the bug and replicate in a Rails test case. Maybe there is a `select` being used in the application for the association?

2017-01-10 23:19 UTC, klaseskilson commented
@rafaelfranca Yes, there was a `select` in there, I missed it since it was hidden in a `default_scope`. 

There is now a test case here too. Thoughts?

2017-01-13 18:31 UTC, klaseskilson commented
@rafaelfranca Sorry to bother you again. Any chance you'll get to take a look at this anytime soon?

2017-02-07 19:15 UTC, klaseskilson commented
Hey @rafaelfranca, I rebased on top of `master`. Let me know if you still have any concerns regarding this.

2018-01-02 20:48 UTC, merged