Reduce `serialize` in `changed_in_place?`
rails/rails pull request #27589
Opened 2017-01-06 12:37 UTC by kamipo

If `raw_old_value` is needed `deserialize` to normalization, unneeded
`serialize` again because `new_value` is deserialized value.

2017-01-06 22:47 UTC, rafaelfranca commented
I'm sure @sgrif did this on purpose so I'll leave to him to review. r? @sgrif

2017-01-06 22:55 UTC, sgrif requested changes
Can you add a test to make sure the following still passes:

```ruby
json = JsonDataType.create!(payload: { foo: :bar })
json.reload
json.payload = { foo: :bar }
refute_predicate json, :changed?
```

2017-01-06 22:55 UTC, sgrif commented on activerecord/lib/active_record/connection_adapters/postgresql/oid/jsonb.rb
>              # the comparison here. Therefore, we need to parse and re-dump the
Please remove this comment since it is now incorrect

2017-01-07 09:50 UTC, kamipo commented
This is duplicated implementation in #27588 now. Closing.

2017-01-07 09:50 UTC, closed without merging