PostgreSQL JSONB columns do not preserve the key order of hashes
rails/rails pull request #27588
Opened 2017-01-06 10:19 UTC by bradleypriest

### Summary

PostgreSQL JSONB columns do not preserve the key order of hashes

https://www.postgresql.org/docs/9.6/static/datatype-json.html

Due to this setting a JSONB column to the same hash twice can cause `model.changed?` to return false positives

2017-01-06 10:29 UTC, rafaelfranca commented
r? @sgrif

2017-01-06 10:56 UTC, bradleypriest commented
Sorry, just realized this breaks for arrays in JSONB columns, will ping once I have a more comprehensive fix

2017-01-06 11:55 UTC, bradleypriest commented
Ok, it seems there's two possible solutions here:
a) Check for arrays and transform them separately - This updated PR (sorry for force-pushing, force of habit)
b) Compare the Ruby representations of the JSON objects instead of their serialized form, spike can be found here (https://github.com/rails/rails/compare/master...bradleypriest:jsonb-changed-ruby)

2017-01-06 14:03 UTC, maclover7 requested changes
Hmm, would it make sense to use the same solution as #27517 and compare deserialized values (so instances of `Hash`) here? Equality through that route won't be affected by different key orders; this might be easier as opposed to sorting keys and doing the serialize/deserialize dance.

2017-01-06 14:03 UTC, maclover7 commented on activerecord/CHANGELOG.md
> +*   Ignore key order when checking whether JSONB columns have changed in PostgreSQL
Can you add a blank line between the bullet point and your name?

2017-01-07 01:42 UTC, bradleypriest commented
@maclover7 thanks for pointing that out. As the logic was already repeated in the `hstore` and MySQL `json` types, I've just moved the logic up into the AbstractJSON type.

The only other type that inherits that is the Postgres JSON type, which shouldn't be detrimentally affected by this change in any way

2017-01-07 02:10 UTC, maclover7 commented on activerecord/test/cases/adapters/postgresql/json_test.rb
> +    json.payload = { "three" => "four", "one" => "two" }
Can we move these tests to a more generic area / make sure the new behavior in `AbstractJson` is being tested properly?

2017-01-07 04:05 UTC, bradleypriest commented on activerecord/test/cases/adapters/postgresql/json_test.rb
> +    json.payload = { "three" => "four", "one" => "two" }
This file is already mixed into both JSON & JSONB test suites, it looks like the MySQL json_test file is mostly a copy-paste of this one.

I've added a couple more commits, the first adds the same test into the MySQL tests as well.
The second extracts out all the shared tests into a shared module for both MySQL and PostgreSQL

2017-01-07 04:11 UTC, bradleypriest commented
My last comment got collapsed, but thanks to feedback from @maclover7 I've extracted out the shared JSON tests into a separate module to ensure both adapters using AbstractJSON are tested.

If that is too much for this PR, the extraction is isolated to just the last commit, so can be handled separately.

2017-01-07 08:34 UTC, ianks commented
I'm confused @bradleypriest. The documentation states this:

> Because the json type stores an exact copy of the input text, it will preserve semantically-insignificant white space between tokens, as well as the order of keys within JSON objects.

2017-01-07 11:14 UTC, bradleypriest commented
Hi @ianks, that's for the JSON type. For JSONB it continues 
> By contrast, jsonb does not preserve white space, does not preserve the order of object keys

2017-01-19 01:29 UTC, bradleypriest commented
Rebased on the latest CHANGELOG conflicts, let me know if there's anything more I can do

2017-03-15 03:25 UTC, bradleypriest commented
Rebased again, would love any feedback when someone has a chance.

2017-05-05 01:38 UTC, bradleypriest commented
Rebased again.
@sgrif if there's anything I can do to help get some eyes on this, I'd love to help.

2017-06-18 14:14 UTC, closed without merging

2017-07-14 11:33 UTC, jalberto commented
Hi, In which release this patch has been included?