Remove deprecated callbacks from ActionDispatch middlewares
rails/rails pull request #27587
Opened 2017-01-06 09:48 UTC by rafaelfranca

@matthewd I'm most seeking review for the documentation at `ActionDispatch::Reloader` since I'm not sure we want to add more information.

2017-01-06 11:14 UTC, kaspth commented on actionpack/lib/action_dispatch/middleware/reloader.rb
>    class Reloader < Executor
Curious: why not kill this class?

2017-01-06 14:06 UTC, maclover7 requested changes

2017-01-06 14:06 UTC, maclover7 commented on actionpack/lib/action_dispatch/middleware/reloader.rb
> +  # ActionDispatch::Reloader wraps the request with the ActiveSupport::Reloader
small english cleanup:

[...] wraps the request with callbacks provided by `ActiveSupport::Reloader`

2017-01-06 14:06 UTC, maclover7 commented on actionpack/lib/action_dispatch/middleware/reloader.rb
>    class Reloader < Executor
This is an interesting question... if all methods in a class are deprecated, does that mean that the class itself is deprecated? :grimacing:

2017-01-06 14:17 UTC, matthewd commented on actionpack/lib/action_dispatch/middleware/reloader.rb
>    class Reloader < Executor
Our middleware API assumes it can distinguish entries by their class.

2017-01-08 18:32 UTC, kaspth commented on actionpack/lib/action_dispatch/middleware/reloader.rb
>    class Reloader < Executor
Ah right, `insert_after ActionDispatch::Reloader, SomeMiddleware` and friends 👍

2017-01-31 20:52 UTC, rafaelfranca commented
Merged in 3f2b7d60a5

2017-01-31 20:52 UTC, closed without merging