Module#parent_name broken for frozen classes
rails/rails pull request #27713
Opened 2017-01-17 21:14 UTC by coreyward

Previously memoization inside of `Module.parent_name` resulted in a runtime error when called for the first time on a frozen module. This patch adds a regression test and refactors the method to resolve the issue. 

Note: introspection tests were previously lumped into `test/core_ext/module_test.rb` despite the code having been extracted to `core_exts/module/introspection.rb`. I isolated the tests similarly, following convention (e.g., `core_exts/module/anonymous.rb` to `test/core_ext/module/anonymous_test.rb`). In the process, I removed some old (over 10 years) setup objects that were no longer being referenced.

2017-01-17 21:47 UTC, maclover7 commented
ref #27637

2017-01-17 21:49 UTC, maclover7 requested changes
Can you squash down to one commit? Otherwise looks good to me. Thanks for working on this!

2017-01-17 22:47 UTC, coreyward commented
Done!

2017-01-17 23:08 UTC, maclover7 approved these changes

2017-01-18 04:07 UTC, rafaelfranca requested changes

2017-01-18 04:07 UTC, rafaelfranca commented on activesupport/lib/active_support/core_ext/module/introspection.rb
> +    return @parent_name if defined?(@parent_name)
Can we keep the `if/else` where. We prefer it over short-circuit returns.

2017-01-18 04:19 UTC, coreyward commented
@rafaelfranca Updated to reflect your concerns. 

Cheers!

2017-01-18 04:21 UTC, merged

2017-01-18 04:24 UTC, rafaelfranca commented
Backported 9f4fc671d7