Add examples for behaviour about redirection with and without options
rails/rails pull request #27730
Opened 2017-01-18 17:56 UTC by vipulnsward

Fixes #27715

2017-01-18 20:27 UTC, maclover7 requested changes
Just a small grammar change, otherwise looks good!

2017-01-18 20:27 UTC, maclover7 commented on actionpack/lib/action_dispatch/routing/redirection.rb
> +      # This causes redirection ignoring parts of the URI, query string, etc.
`This causes redirection` --> `This will redirect the user, while ignoring certain parts of the request, including...`

2017-01-18 20:27 UTC, maclover7 commented on actionpack/lib/action_dispatch/routing/redirection.rb
> +      # This causes redirection changing only the specified parts of URI, for example the `path` option in the last example.
Same comment as above

2017-01-21 14:54 UTC, merged

2017-01-21 21:21 UTC, jjb commented
🆒