Sandbox tagged logging
rails/rails pull request #27792
Opened 2017-01-24 12:49 UTC by tjoyal

### Summary

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

If you are updating any of the CHANGELOG files or are asked to update the
CHANGELOG files by reviewers, please add the CHANGELOG entry at the top of the file.

Finally, if your pull request affects documentation or any non-code
changes, guidelines for those changes are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation)

Thanks for contributing to Rails!

2017-01-31 20:02 UTC, arthurnn commented
I agree that `new` should return a new object, and not mutate the existent one.
@rafaelfranca @matthewd thoughts?
I am :+1: here

2017-01-31 20:58 UTC, rafaelfranca requested changes
LGTM too. A CHANGELOG entry will be required since this may be a breaking change.

2017-01-31 20:59 UTC, rafaelfranca commented on activesupport/lib/active_support/tagged_logging.rb
> +        logger.formatter.dup
Those lines should be aligned with the `if`. Rubocop is complaining.

2017-02-01 19:19 UTC, tjoyal commented
Updated, tell me if you are good with the changes.

2017-02-01 20:58 UTC, matthewd commented
Does this risk multiplying the number of live logger instances we have in an application?

That seems like it could affect what gets silenced, for example.

2017-02-02 14:14 UTC, tjoyal commented
> Does this risk multiplying the number of live logger instances we have in an application?

My thought of chain on this is when calling `new`, I expect to get a new object. 

I think it's a fair concern, and to some extent I would consider setting my `Rails.logger` to return a tagged logger from the ground up if I was planning to tag a lot of things. (vs re-init everywhere in the code leading to a lot of code duplication).

I think it would be possible to come up with a mutating method that is not named `new` that would have the old behaviour, but I don't see the need for it just yet.

> That seems like it could affect what gets silenced, for example.

Definitely (it's a new instance after all, unless `dup` decide to handle logic to bridge behaviour between instances).

But once again, I think this is expected from a method that is called `new`.

As proposed up there, if one was to use a lot of tagged logging in his application, I think it would be fair to consider setting it as the default logger.

In the cases where I wanted to use tagged logging, the desired behaviour was to do a `dup` like in this PR so my tags are only applied to the current context of the unit of code I'm wrapping, and not propagated to other unit of code that might be called in other classes.

Eg.: A fairly simple example 
```ruby
class Object
  def method_a
    logger = ActiveSupport::TaggedLogging.new(Rails.logger)
    logger.tagged("BCX") do
      logger.info "something" # I expected this to be tagged
      method_b
    end
  end

  def method_b
    Rails.logger.info "something else" # I do not expect this to be tagged
  end
end
```

2018-08-29 01:28 UTC, gmcgibbon reviewed
Still relevant in Rails 6 28e5085070f95f32a6a909cce6d77fd460c73885. I'll admit that when I first saw the source for `ActiveSupport::TaggedLogging.new` I thought it was being too clever. If we want to keep the mutation approach, could we just rename the `new` method to something more explanatory?

2018-09-11 23:35 UTC, merged

2020-12-07 14:14 UTC, orhantoy commented on activesupport/lib/active_support/tagged_logging.rb
> +      logger = logger.dup
Any special reason `#dup` was used here? I have opened https://github.com/rails/rails/pull/40759 to address a side-effect of not using `#clone`.