Bump bug report template versions to 5.0.1 in 5-0-stable
rails/rails pull request #27809
Opened 2017-01-26 09:42 UTC by etdsoft

### Summary

While investigating how to create a bug report for https://github.com/rails/rails/issues/27803 I realised the gem version numbers of the templates were slightly out of date.

HTH

2017-01-27 21:50 UTC, maclover7 approved these changes

2017-01-27 22:09 UTC, rafaelfranca requested changes

2017-01-27 22:09 UTC, rafaelfranca commented on guides/bug_report_templates/action_controller_gem.rb
> +  gem 'rails', '5.0.1'
Can we just make this `~> 5.0.1`?

2017-01-31 13:37 UTC, etdsoft commented on guides/bug_report_templates/action_controller_gem.rb
> +  gem 'rails', '5.0.1'
done

2017-01-31 21:13 UTC, merged

2017-01-31 21:14 UTC, arthurnn commented
Thanks