Update backtrace cleaner to use `Regexp#match?`
rails/rails pull request #27832
Opened 2017-01-28 04:07 UTC by bdewater

In https://github.com/rails/rails/commit/575dbeeefcaafeb566afc07cdd8b55603b698d9f a backport for Ruby 2.4's [`Regexp#match?`](https://bugs.ruby-lang.org/issues/8110) was introduced. On Ruby 2.4 this method [is about 13% faster](http://blog.bigbinary.com/2016/11/04/ruby-2-4-implements-regexp-match-without-polluting-global-variables.html) than `=~` because it doesn't allocate a MatchData object and sets the value of `$~`. Since the silencer only cares about a boolean return value, we should use `match?`.

2017-01-28 04:51 UTC, matthewd commented
For the documentation and tests, I think I prefer `=~`'s legibility. I recognise that will encourage people to write similarly wasteful expressions when following said docs, but we're talking about something that only happens (once) when we're cleaning up an exception for display anyway -- it's about as far from a hot path as one can get.

That said, I'm fine with changing the one in `backtrace_cleaner.rb`: it *is* a drop-in known-faster operation (so unlike something that is only faster most of the time, I don't feel the need for a supporting benchmark), and our own code generally favours the new spelling anyway.

We will need to `require` the backport's file, though -- which is another argument against using it in documentation at this stage.

2017-01-31 05:28 UTC, rafaelfranca requested changes
Agree with @matthewd on this one.

2017-02-13 02:11 UTC, rafaelfranca commented
For some reason railties tests are broken. Can you make sure this branch is updated?

2017-02-13 05:14 UTC, bdewater commented
Fixed and rebased. Not sure if the require is still needed because of 56832e791f3ec3e586cf049c6408c7a183fdd3a1 ?

2017-02-13 13:33 UTC, rafaelfranca commented
It should not be not needed, could you remove it?

2017-04-03 19:09 UTC, merged