Feature/active job test helper
rails/rails pull request #27850
Opened 2017-01-30 18:55 UTC by apauly

### Summary

This PR updates the `ActiveJob::QueueAdapters::TestAdapter` to add filtered jobs to the `enqueued_jobs` array. Prior to this change, skipped jobs were just ignored.

Refer to https://github.com/rails/rails/issues/27848

### Other Information

I've also updated the test suite.

2017-01-30 20:09 UTC, rafaelfranca requested changes
Looks great. Could you add a CHANGELONG entry?

2017-01-31 05:33 UTC, rafaelfranca requested changes
One more change and please squash your commits after.

2017-01-31 05:33 UTC, rafaelfranca commented on activejob/CHANGELOG.md
> +  *Alexander Pauly*
Needs two more spaces in this line

2017-01-31 06:39 UTC, apauly commented
Thanks for pointing that out! I've fixed the formatting issue and squashed everything into a single commit

2017-01-31 20:45 UTC, merged