Fix relation merger issue with `left_outer_joins`.
rails/rails pull request #27860
Opened 2017-01-31 17:24 UTC by meinac

**The problem:** If you want to merge a relation which contains `left_outer_joins` to another relation, AR tries to do left_outer_joins with base relation which is incorrect behaviour.

Here is the test script you can see current behaviour;
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '5.0.1'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :preferences, force: true  do |t|
    t.string  :author_id
    t.boolean :is_public
  end

  create_table :authors, force: true  do |t|
    t.string  :name
  end

  create_table :posts, force: true  do |t|
    t.string  :title
    t.string  :body
    t.integer :author_id
  end
end

class Preference < ActiveRecord::Base

  scope :some_scope, -> do
    where(id: nil).or(where(is_public: true))
  end

end

class Author < ActiveRecord::Base
  has_one  :preference
  has_many :posts

  scope :some_scope, -> do
    left_joins(:preference)
      .merge(Preference.some_scope)
  end

end

class Post < ActiveRecord::Base
  belongs_to :author
  has_many :comments

  scope :some_scope, -> do
    joins(:author).merge(Author.some_scope)
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    author = Author.create(name: 'John Doe')
    post   = Post.create(title: 'Foo', body: 'Bar', author: author)

    assert_equal Post.some_scope.count, 1
  end
end

```

Without this pr, AR tries to join Preference model with Post model and raises exception because there is no relation declared between Preference and Post directly.

Using merge to share logic between scopes are the best way to keep models clean so this is why I think this should work as expected. Btw I think this is not a regression since `left_outer_joins` presented. I think it is just forgotten.

2017-01-31 23:45 UTC, rafaelfranca requested changes

2017-01-31 23:45 UTC, rafaelfranca commented on activerecord/lib/active_record/relation/merger.rb
>                                                                               joins_dependency,
The indentation is wrong here now.

2017-01-31 23:45 UTC, rafaelfranca commented on activerecord/lib/active_record/relation/merger.rb
> +        def partition_join_dependencies(values) # :nodoc:
No need for a nodoc here.

2017-01-31 23:45 UTC, rafaelfranca commented on activerecord/lib/active_record/relation/query_methods.rb
> +            raise ArgumentError, "only Hash, Symbol, Array and JoinDependency are allowed"
JoinDependency is not public API and we don't want users to be using it in their applications so we should not talk about it here.

2017-02-01 11:18 UTC, meinac commented
Hey @rafaelfranca, I've made the changes and squashed.

2017-02-13 15:42 UTC, meinac commented
@rafaelfranca does this still need work? I think all changes done.

2017-10-04 14:05 UTC, rohpai commented
@meinac @rafaelfranca any idea why this PR hasn't been merged in yet? I'm still facing this issue on Rails 5.0.6 / mysql

2017-10-04 14:19 UTC, meinac commented
@rohpai I don't really know why this is not merged yet, I don't have write access to Rails repositories, if Rails team wants to merge this I can rebase and resolve conflicts again.

2018-01-14 18:28 UTC, kamipo commented
Can you rebase?

2018-01-15 15:53 UTC, meinac commented
done! There is a bit duplications between `merge_joins` and `merge_outer_joins` methods but I did not want to use reflection, it can be done without it though.

2018-01-15 16:39 UTC, merged