Fix collection_singular_ids= bug
rails/rails pull request #27865
Opened 2017-01-31 22:17 UTC by composerinteralia

When the association's primary key is set as a symbol,
CollectionAssociation#ids_writer fails to cast the ids to integers.
This is because AssociationReflection#association_primary_key_type
and ThroughReflection#association_primary_key_type rely on
ModelSchema.type_for_attribute, which only accepts a string.
The result is an ActiveRecord::RecordNotFound error.

Fixes #27864

2017-01-31 22:51 UTC, rafaelfranca requested changes
Thank you so much for the PR. I comment in the CHANGELOG to give you proper recognition of your change.

2017-01-31 22:51 UTC, rafaelfranca commented on activerecord/CHANGELOG.md
> +
Do you mind to add your name here?

2017-01-31 23:07 UTC, composerinteralia commented on activerecord/CHANGELOG.md
> +
sorry about that!

2017-01-31 23:11 UTC, composerinteralia commented
Oops, I can see now that my tests are no good. I will take another look. @rafaelfranca Is it better to keep this open or to close for now and open a new PR once I have this figured out?

2017-01-31 23:13 UTC, rafaelfranca commented
Let's keep this open

2017-01-31 23:20 UTC, kamipo commented on activerecord/test/cases/reflection_test.rb
> +    assert_equal ActiveModel::Type::String, Author.reflect_on_association(:essay_category).association_primary_key_type.class
How about `assert_equal :string, Author.reflect_on_association(:essay_category).association_primary_key_type.type`?

2017-02-01 03:16 UTC, composerinteralia commented on activerecord/test/cases/reflection_test.rb
> +    assert_equal ActiveModel::Type::String, Author.reflect_on_association(:essay_category).association_primary_key_type.class
Yeah, that makes sense to me. Thanks for your help!

2017-02-01 14:30 UTC, composerinteralia commented on activerecord/CHANGELOG.md
> +
Done!

2017-02-02 15:00 UTC, composerinteralia commented
@rafaelfranca I fixed my errors and rebased on master, but now I am getting new errors that seem to be related to this: https://github.com/rails/rails/commit/aa647b46cce55ec12f5895e403c0d1b85502c8e0
Any advice?

2017-02-03 03:48 UTC, composerinteralia commented
I can't recreate the failure on my end. Anyone want to help?

2017-02-03 15:16 UTC, eileencodes commented
I couldn't reproduce locally so I restarted the build and this time it passed. I think it was unrelated to your changes.

2017-02-03 15:16 UTC, merged

2017-02-03 20:45 UTC, eileencodes commented
Backported to 5-0-stable in https://github.com/rails/rails/commit/93a44497ed7b28f5691a5cb1685261af5dcf64c1