Get TODO done in `render_test`
rails/rails pull request #27870
Opened 2017-02-01 12:16 UTC by kenta-s

I examined the other TODO comment in `render_test.rb` .

The method checks that MissingTemplateError is raised if a partial with a non-existent extension is rendered.

This PR:
- renames the method to a better name.
- removes the comment.
- moves the method to a better place.
- changes `@view.formats=` to `@view.lookup_context.formats=` (`formats=` delegates to `lookup_context` in ActionView::Base). Because other test methods in `render_test.rb` use the latter style, and they should be consistent to be more readable.

2017-02-01 13:38 UTC, maclover7 approved these changes

2017-02-01 14:16 UTC, kaspth commented
I don't get how moving the test addresses the comment? Why don't we need to update the docs as the comment suggests?

2017-02-03 13:41 UTC, eileencodes requested changes
Yea I agree with Kasper, renaming the test doesn't fix what the comment suggests the problem is: that while there's a test there is no corresponding documentation for that behavior.

2017-02-04 14:55 UTC, kenta-s commented
I see. But I'm not sure where 'the docs' are located and not sure what is 'the docs' to be honest... I would appreciate if anyone tells me how (or sends me a link). 
I'm more than willing to update it :)

2017-02-05 15:52 UTC, kaspth commented
Seems the test was added way back in Rails 2.2: https://github.com/rails/rails/commit/6f5327013d6353c50cadfe2160d1b526ad687633

I think we'll need to update the rendering guide: http://guides.rubyonrails.org/layouts_and_rendering.html

2017-02-05 23:16 UTC, kenta-s commented
Thank you @kaspth ! I will update it :)

2017-02-06 12:51 UTC, kenta-s commented
Updated the docs. And renamed the test method (because I think the name should be clearer)

2017-02-11 20:47 UTC, merged

2017-02-11 20:47 UTC, kaspth commented
Nicely done, thanks!