Remove the top-level `HashWithIndifferentAccess` contant
rails/rails pull request #27925
Opened 2017-02-06 13:55 UTC by robin850

Hi,

This pull request removes the top level `HashWithIndifferentAccess` constant. It was kept for the sake of backward compatibility; it is still available under `ActiveSupport::HashWithIndifferentAccess`.

Furthermore, since Ruby 2.5 (https://bugs.ruby-lang.org/issues/11547) won't support top level constant lookup, people would have to update their code anyway.

I defined a `HashWithIndifferentAccess` constant inside tests to avoid polluting the log and make blames harder but let me know if I should rather update the different tests with the full constant qualifier.

Cross refs #27863.

Have a nice day !

2017-02-06 14:41 UTC, matthewd commented
This definitely needs a deprecation.

(And FWIW, 11547 doesn't affect this in any way I can see.)

2017-02-06 15:02 UTC, rafaelfranca commented
Also a lot of old applications may have top-level `HashWithIndifferentAccess` in their databases YAML encoded, so we need to add a yaml alias to it.

2017-02-06 17:11 UTC, robin850 commented
> This definitely needs a deprecation.

Wokay, I wasn't sure, this is now deprecated rather than completely removed.

> (And FWIW, 11547 doesn't affect this in any way I can see.)

I'm not sure I understand why. If people were referencing this constant in a controller for instance, Ruby would have to find it at the top level binding, no ?

> Also a lot of old applications may have top-level HashWithIndifferentAccess in their databases YAML encoded, so we need to add a yaml alias to it.

Sorry if I'm missing something but since the top level `HashWithIndifferentAccess` constant was just barely mapped to the one under `ActiveSupport`, there's no need to hook into YAML here, is there ?

~~~ruby
>> require 'active_support/all'
=> true
>> ActiveSupport::VERSION::STRING
=> "5.0.1"
>> h = HashWithIndifferentAccess.new
=> {}
>> h.to_yaml
=> "--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess {}\n"
~~~

2017-02-06 22:37 UTC, rafaelfranca commented
> there's no need to hook into YAML here, is there ?

Yeah, that is good.

2017-02-06 22:38 UTC, rafaelfranca commented on activesupport/lib/active_support/hash_with_indifferent_access.rb
> +HashWithIndifferentAccess = ActiveSupport::Deprecation::DeprecatedConstantProxy.new("HashWithIndifferentAccess", "ActiveSupport::HashWithIndifferentAccess")
This will broke the ability to inherit from this constant. Can you add a test for it and fix?

2017-02-07 17:16 UTC, robin850 commented
@rafaelfranca : Ah, fair point ! 👍 But YAML encoding should be fixed now haha. :trollface: I didn't find any better solution than instantiating a new `AS::HWIA`, I don't know if there's a better one.

2017-02-07 17:35 UTC, rafaelfranca requested changes

2017-02-07 17:35 UTC, rafaelfranca commented on activesupport/lib/active_support/hash_with_indifferent_access.rb
> +    coder.represent_object(nil, ActiveSupport::HashWithIndifferentAccess.new(self))
I think `Yaml.dump_tags[HashWithIndifferentAccess] = "!ruby/hash:ActiveSupport::HashWithIndifferentAccess"` would implement this.

2017-02-07 20:29 UTC, robin850 commented
@rafaelfranca : Actually that's a pretty weird case ; Psych [doesn't honor](https://github.com/ruby/psych/blob/8fc7a30f9e1920497c392ce34ee528bdbfc1f33c/lib/psych/visitors/yaml_tree.rb#L508) the values set in `dump_tags` for Hash sub-classes. Redefining `encode_with` may be the best solution we have here ! 😕

2017-02-11 20:38 UTC, kaspth commented
Ah yes, I ran into the same thing with `ActionController::Parameters`: https://github.com/rails/rails/blob/6401e03ef6285a93588a162e651e0b15fcb60a19/actionpack/lib/action_controller/metal/strong_parameters.rb#L603-L628

We're probably better off with `init_with` here as well. `encode_with` only lets us control the format going forward and not correct any past loading that could be broken once the constant is removed.

It's likely we also want to account for Psych 2.0.8 and below plus 2.0.9+ as the hash subclass storage was different as the comments mention.

2017-02-11 20:42 UTC, kaspth commented
Ah we're of course only deprecating the constant now, so `encode_with` can make sense and help writing it like it's supposed to for the future.

Then I think we ought to explain that people should make sure to find YAML instances that contain the old ref and load/dump them again. Otherwise their apps can start blowing up, when we later remove the constant.

2017-02-12 00:00 UTC, robin850 commented
> Then I think we ought to explain that people should make sure to find YAML instances that contain the old ref and load/dump them again.

Actually, since this constant has been mapped to `ActiveSupport::HashWithIndifferentAccess` [eight years ago](https://github.com/rails/rails/commit/0bd668fd8867b01c15f943613707b3c7eb59afff#diff-9f4b3d7342097a6f22290f147a09b77bR133), there's probably not any reference to the top level constant anymore nowadays, no ? If you think it's a problem, I can totally write a paragraph in the upgrade guide ; just want to make sure that it's worth it. :-)

2017-02-19 20:27 UTC, kaspth commented
Let's rebase this, then I'll merge. We can tackle the upgrade guide later 👍

2017-02-19 21:34 UTC, robin850 commented
> We can tackle the upgrade guide later

Okay, it should be good now then ! :-)

2017-02-20 08:36 UTC, merged

2017-02-20 08:36 UTC, kaspth commented
Thanks! ❤️