Skip record_name argument when using #fields_for helper with nested attributes
rails/rails pull request #27930
Opened 2017-02-07 02:31 UTC by st0012

Currently if we want to use `#fields_for` with nested attributes, we need to pass record's name before record object:
```ruby
<%= form_for @role, url: '' do |f| %>
  <%= f.fields_for :user, @role.user do |uf| %>
    <%= uf.email_field :email %>
  <% end %>
<% end %>
```
So we can get `role[user_attributes][email]` for email field's name.

And this PR allow we skip the first argument and just pass the object and get same result.
```ruby
<%= form_for @role, url: '' do |f| %>
  <%= f.fields_for @role.user do |uf| %>
    <%= uf.email_field :email %>
  <% end %>
<% end %>
```

This is inspired by #27892

2017-02-07 02:31 UTC, st0012 commented
r? @rafaelfranca

2017-02-07 02:32 UTC, st0012 commented on actionview/test/template/form_helper_test.rb
> +#   Not sure if we should support arel like objects without record_name given.
I'm not sure if we should support Arel like object in this case.

2017-02-07 09:18 UTC, dmitry requested changes

2017-02-07 09:18 UTC, dmitry commented on actionview/lib/action_view/helpers/form_helper.rb
> +        if !record_name.is_a?(String) && !record_name.is_a?(Symbol)
Not the best way to check for negative conditions. Better check if something is allowed.

2017-02-07 09:18 UTC, dmitry commented on actionview/lib/action_view/helpers/form_helper.rb
> +          record_object = record_name
Mostly not used at all.

2017-02-07 09:18 UTC, dmitry commented on actionview/lib/action_view/helpers/form_helper.rb
> +            if record_object.is_a?(Array)
Isn't it worked before with simply `param_key`?

2017-02-07 09:18 UTC, dmitry commented on actionview/test/template/form_helper_test.rb
> +#   Not sure if we should support arel like objects without record_name given.
What is `ArelLike.new`? Is it a model or it's an Arel visitor object, that creates where conditions?

2017-02-07 09:23 UTC, st0012 commented on actionview/lib/action_view/helpers/form_helper.rb
> +        if !record_name.is_a?(String) && !record_name.is_a?(Symbol)
I want to check by record's inheritance class. But test records I can use are not normal ActiveRecord objects, implement this also requires changing fake data.

2017-02-07 09:24 UTC, st0012 commented on actionview/lib/action_view/helpers/form_helper.rb
> +          record_object = record_name
What do you mean mostly not used at all?

2017-02-07 10:17 UTC, dmitry commented on actionview/lib/action_view/helpers/form_helper.rb
> +          record_object = record_name
Basically you may move usage of `record_name` to the ` object_for_model_name = record_object.last`, instead of `record_object`.

2017-02-07 10:18 UTC, dmitry commented on actionview/lib/action_view/helpers/form_helper.rb
> +        if !record_name.is_a?(String) && !record_name.is_a?(Symbol)
Might be someone else have a better idea... I just don't like how it looks like.

2017-03-02 14:05 UTC, st0012 commented
@rafaelfranca  do you have any thoughts about this feature?

2017-12-15 07:41 UTC, st0012 commented
It's been over half years, closing

2017-12-15 07:41 UTC, closed without merging