Make statement cache key contain current table name
rails/rails pull request #27953
Opened 2017-02-09 17:13 UTC by namusyaka

### Summary

In our project some exceptional, we have the function of dynamically swapping table names.
It hasn't been working since those features upgraded to rails-4.2 (or maybe latest 4.1?)
It is due to the implementation of Adequate Record which is a wonderful feature.
I solved this problem by including table names in cache key.

@tenderlove @rafaelfranca  Could you review my changes?

2017-02-09 21:23 UTC, jeremy requested changes

2017-02-09 21:23 UTC, jeremy commented on activerecord/test/cases/statement_cache_test.rb
> +    def test_tablename
Is there a more precise name for what we're demonstrating with this test?

2017-02-09 21:23 UTC, jeremy commented on activerecord/test/cases/statement_cache_test.rb
> +      end
Are these two assertions testing different things?

2017-02-09 21:23 UTC, jeremy commented on activerecord/test/cases/statement_cache_test.rb
> +      assert_equal book, Book.find_by(name: "my book")
Do we expect this finder to fail? Would limit assertions to just the expectations that would fail if this PR were reverted.

2017-02-09 21:23 UTC, jeremy commented on activerecord/test/cases/statement_cache_test.rb
> +      end
Ah, testing both forms of cached queries? If so, ensure that the test case communicates its intent, both with the test name and with comments on the assertions it's making.

2017-02-09 21:23 UTC, jeremy commented on activerecord/lib/active_record/core.rb
> +        statement = cached_find_by_statement("#{table_name}#{keys}") { |params|
The `table_name=` method already clears a lot of caches. It should probably clear these cached statements as well.

2017-02-10 02:59 UTC, namusyaka commented on activerecord/test/cases/statement_cache_test.rb
> +    def test_tablename
Omg, this is temporary test case name. Sorry.

2017-02-10 02:59 UTC, namusyaka commented on activerecord/test/cases/statement_cache_test.rb
> +      assert_equal book, Book.find_by(name: "my book")
Okay, removed.

2017-02-10 03:00 UTC, namusyaka commented on activerecord/test/cases/statement_cache_test.rb
> +      end
I've just separated two assertions to two test cases.

2017-02-10 03:03 UTC, namusyaka commented on activerecord/lib/active_record/core.rb
> +        statement = cached_find_by_statement("#{table_name}#{keys}") { |params|
Nope. The `table_name=` method doesn't clear statement cache Unfortunately, but your comment gave me inspiration. I changed my approach.

2017-02-10 03:04 UTC, namusyaka commented
@jeremy Thank you for a polite review. I added commit to reflect your comments.

2017-02-10 03:05 UTC, namusyaka commented
If this is ok, I'm going to squash the commits.

2017-02-10 06:07 UTC, jeremy commented on activerecord/test/cases/statement_cache_test.rb
> +    end
Nice. I think these still need some code comments explaining what's happening when we call `#find_by` and `#find` the first time (that we're warming the cache) and when we call `Book.table_name = …` (that changing the table name should change the query that's now cached).

2017-02-10 06:07 UTC, jeremy commented on activerecord/lib/active_record/model_schema.rb
> +          initialize_find_by_cache
Nice and simple.

I wonder: Should `reset_column_information` clear the find-by cache too?

2017-02-10 06:07 UTC, jeremy commented on activerecord/CHANGELOG.md
> +*   Make `table_name=` reset current statement cache.
Maybe add … "so queries aren't run against the previous table name." ?

2017-02-10 08:56 UTC, namusyaka commented on activerecord/test/cases/statement_cache_test.rb
> +    end
I added comments to the lines.

2017-02-10 08:57 UTC, namusyaka commented on activerecord/lib/active_record/model_schema.rb
> +          initialize_find_by_cache
Indeed, reset_column_information can contain cache clearing mechanism, I think.
Moved.

2017-02-10 08:57 UTC, namusyaka commented on activerecord/CHANGELOG.md
> +*   Make `table_name=` reset current statement cache.
Thanks :)

2017-02-10 09:11 UTC, namusyaka commented
@jeremy I relected your review and force pushed. Thanks!

2017-02-10 21:52 UTC, jeremy commented on activerecord/lib/active_record/model_schema.rb
> +        initialize_find_by_cache
/cc @tenderlove Make sense to clear find-by cache when we reset_column_information?

2017-02-10 23:18 UTC, tenderlove commented on activerecord/lib/active_record/model_schema.rb
> +        initialize_find_by_cache
Yes it does. If people swap out the table, then pretty much all caches are bad.

2017-02-12 07:00 UTC, namusyaka commented
@jeremy @tenderlove Do I need to more fix this patch?

2017-02-13 01:15 UTC, closed without merging

2017-02-13 02:25 UTC, jeremy commented
Backported to [5-0-stable](https://github.com/rails/rails/commit/c98f3b0f1f3ec2d63034d581568f18b61cc31875) and [4-2-stable](https://github.com/rails/rails/commit/a70fc0f3c8ba6d6c22de042c5d4bc8826a4f3e78).

2017-02-13 02:38 UTC, namusyaka commented
@jeremy Thank you so much!