Check for forced attribute changes
rails/rails pull request #27963
Opened 2017-02-10 17:01 UTC by alse

### Summary

AttributeMutationTracker#any_changes? only looked at model attribute
changes, and ignored any forced changes. Fixes #27956

2017-02-11 20:30 UTC, sgrif requested changes
I'm fine with the code change, but the test feels very off to me.

2017-02-11 20:30 UTC, sgrif commented on activerecord/test/models/parrot.rb
> +  end
Is there a simpler way we can test this? Perhaps just `parrot.name_will_change!; assert parrot.changed?`?

2017-02-11 22:02 UTC, alse commented on activerecord/test/models/parrot.rb
> +  end
You're right, I tried to simplify the test. The changed? method already accounts for changes to virtual attributes, so I used has_changes_to_save? instead.

2017-02-11 22:05 UTC, alse commented on activerecord/lib/active_record/attribute_mutation_tracker.rb
> +      attr_names.any? { |attr| changed?(attr) } || forced_changes.any?
Another way to fix this issue is to include virtual attributes in the attr_names. The changed? method already checks for forced changes

2017-02-11 22:14 UTC, sgrif commented on activerecord/lib/active_record/attribute_mutation_tracker.rb
> +      attr_names.any? { |attr| changed?(attr) } || forced_changes.any?
By "virtual attribute" are you referring to an `attr_accessor`? Those are not intended to work with dirty.

2017-02-11 22:15 UTC, sgrif commented
I looked more closely at this. This is not a bug.

2017-02-11 22:16 UTC, sgrif commented
Hm. I saw that this worked in Rails 5.0.1. I thought I had changed it then.

2017-02-11 22:49 UTC, closed without merging

2017-06-21 14:17 UTC, shioyama commented
It might be pointless to contest this change, but I'm going to try anyway.

I have a gem ([Mobility](https://github.com/shioyama/mobility)) which adds (virtual) translated attributes to a model, and one of the things I do is to support [dirty tracking](https://github.com/shioyama/mobility/blob/master/lib/mobility/backend/active_model/dirty.rb) on these virtual attributes (which may be stored in different formats in the db depending on the choice of backend).

Up until now, I have been able to mark changes using e.g. `title_en` for a change on the title in English, even though `title_en` is not a real attribute, and these changes would appear with changes to other ("real") attributes. This use of `attr_will_change!` is completely consistent with Active*Model* Dirty, and I found it very simple to apply to my situation.

Of course Active*Record* Dirty overrides all these methods and does slightly different things, but I managed to get around this with a minor [patch](https://github.com/lime/mobility/blob/64df13697927d884c17e571e539fc8740235266c/lib/mobility/active_record.rb#L15-L27).

But now, with this change, you are requiring me to declare all these attributes *upfront*. This essentially means that you can no longer leverage the flexibility of Active*Model* Dirty within an ActiveRecord model, because ActiveRecord overrides all these dirty methods. It almost seems like you might as well not even include `ActiveModel::Dirty` in `ActiveRecord::Dirty` anymore since the two at this point are so dissimilar.

I understand that #27956 was probably the kind of issue you don't want to deal with, but deprecating this "open-ended" use of attributes in AR models appears to be something that was already [in the plans](https://github.com/rails/rails/issues/27956#issuecomment-279179849). All things being equal, I would think that imposing as few requirements as possible would be the ideal to strive for. In my particular case, the change will probably require an actual change in how my gem works, because I do not want to have to specify all locales upfront (which I would need in order to specify the attributes).

Any chance this could be reconsidered, or alternatively could you explain why this is necessary in Dirty in particular? My preference woudl be for AR::Dirty to as much as possible stick to AM::Dirty, for consistency and flexibility's sake.