Add `blob` short-hand method for schema creation
rails/rails pull request #27978
Opened 2017-02-12 16:47 UTC by kamipo

Most backends have native blob type (mysql, sqlite3, oracle, etc).

2017-02-13 14:06 UTC, rafaelfranca requested changes
I think it is good to add a test for it to make sure the public API doesn't change without noticing. Could you add it?

2017-02-13 14:45 UTC, rafaelfranca approved these changes

2017-02-13 15:32 UTC, matthewd commented
Most backends have (say) a `varchar` type too, yet -- unless I'm confused -- we don't expose it by that name. I have mixed feelings about whether we should make an exception for blob.

2017-02-13 16:21 UTC, rafaelfranca commented
Good point. @kamipo what is your opinion about it?

2017-02-13 17:28 UTC, kamipo commented
Actually we already have `blob` method for MySQL tinyblob creation/dumping and using in tests.
(mysql2 adapter creates `t.binary :data, limit: 255` to `varbinary(255)`, not `tinyblob`)

* https://github.com/rails/rails/blob/b9bee5e895e218b17a5f4ad72c3cbf6204fa4145/activerecord/test/cases/schema_dumper_test.rb#L231
* https://github.com/rails/rails/blob/b9bee5e895e218b17a5f4ad72c3cbf6204fa4145/activerecord/test/cases/defaults_test.rb#L184

If we don't add `blob` method, only mysql2 adapter can use `blob` method in backends that have native blob type.

2017-02-13 23:42 UTC, rafaelfranca commented
This is a good point. If MySQL already have I think we should be consistent in the other adapters.

2017-02-14 15:39 UTC, rafaelfranca commented
@matthewd do you still have mixed feelings?

2017-02-14 23:52 UTC, jeremy commented
Note that we have string/text as well. Binary/blob would match that.

2017-02-17 11:34 UTC, matthewd commented
@jeremy  `string` and `text` are similar-sounding but intrinsically different SQL types -- `varchar` vs `text` -- across all RDBMS.

I'd argue that parallel makes this undesirable: it's all too easy for a reader to infer there's a similar difference between `binary` and `blob`. **Especially** given that half the databases in question have a `varbinary` type, which *we don't use* for `binary`, as well as their `blob` (which we'd use for both).

2017-02-17 13:19 UTC, jeremy commented
Agree. I'd expect these names to suggest varbinary/blob, too.
On Fri, Feb 17, 2017 at 04:34 Matthew Draper <notifications@github.com>
wrote:

> @jeremy <https://github.com/jeremy> string and text are similar-sounding
> but intrinsically different SQL types -- varchar vs text -- across all
> RDBMS.
>
> I'd argue that parallel makes this undesirable: it's all too easy for a
> reader to infer there's a similar difference between binary and blob.
> *Especially* given that half the databases in question have a varbinary
> type, which *we don't use* for binary, as well as their blob (which we'd
> use for both).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rails/rails/pull/27978#issuecomment-280627250>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAAAx7nUS2DpgSvfrhiBDTIvb3v9uMFCks5rdYXjgaJpZM4L-ikC>
> .
>

2020-09-30 23:03 UTC, jeremy commented
This still seems sensible to me, despite the conceptual mismatch, because BLOB is what people expect to reach for.

In any case, let's make a decision rather than linger.

2020-12-29 23:47 UTC, merged