Allow skipping of turbolinks for test dummy application
rails/rails pull request #28120
Opened 2017-02-23 06:08 UTC by vfonic

NOTE: I think this should be the expected behavior. At least that's what I
expected. Let me know if you think differently. Maybe this PR should be dropped
altogether?

When `rails new plugin` is invoked with `--skip-turbolinks`, turbolinks
should be skipped in the dummy application generated by the plugin
generator.

2017-02-23 21:16 UTC, rafaelfranca requested changes

2017-02-23 21:16 UTC, rafaelfranca commented on railties/lib/rails/generators/rails/plugin/plugin_generator.rb
> +      :skip_turbolinks, :database, :javascript, :quiet, :pretend, :force, :skip
Let's just set it by default to true.

2017-02-24 01:38 UTC, vfonic commented
Thanks @rafaelfranca! Should I squash these commits immediately and force push or wait until the PR has been approved or you usually do it?

2017-02-24 02:41 UTC, rafaelfranca approved these changes
Thank you! Please squash the commits

2017-02-28 01:35 UTC, vfonic commented
Squashed

2017-02-28 23:14 UTC, merged