[close #24435] Send user_supplied_options to server
rails/rails pull request #28137
Opened 2017-02-23 22:27 UTC by schneems

Currently when Puma gets a `:Port` it doesn't know if it is Rails' default port or if it is one that is specified by a user. Because of this it assumes that the port passed in is always a user defined port and therefor 3000 always "wins" even if you specify `port` inside of the `config/puma.rb` file when booting your server with `rails s`.

The fix is to record the options that are explicitly passed in from the user and pass those to the Puma server (or all servers really). Puma then has enough information to know when `:Port` is the default and when it is user defined. I went ahead and did this for all values rails server exposes as server side options for completeness.

The hardest thing was converting the input say `-p` or `--port` into the appropriate "name", in this case `Port`. There may be a more straightforward way to do this with Thor, but I'm not an expert here.

2017-02-23 22:28 UTC, schneems commented
cc/ @nateberkopec @evanphx

2017-02-23 22:37 UTC, rafaelfranca approved these changes
LGTM

2017-02-23 22:51 UTC, maclover7 requested changes
Looks good, can you squash down?

2017-02-23 22:57 UTC, matthewd commented on railties/lib/rails/commands/server/server_command.rb
>            ENV.fetch("PORT", options[:port]).to_i
Seems like `ENV["PORT"]` should count as user-supplied for our purposes here, too.

2017-02-23 23:08 UTC, schneems commented on railties/lib/rails/commands/server/server_command.rb
>            ENV.fetch("PORT", options[:port]).to_i
Good call.

2017-02-25 01:29 UTC, merged

2017-02-28 19:55 UTC, swrobel commented
Any chance of this making it into 5.0.2?

2017-02-28 19:58 UTC, schneems commented
We can backport it, however right now it does nothing until Puma is updated to deal with the extra information.

2017-02-28 20:11 UTC, rafaelfranca commented
5.0.2 is pass the backport phase out, but in 5.0.3 is possible