Remove #where with blank condition
rails/rails pull request #28290
Opened 2017-03-04 19:55 UTC by bogdanvlviv

```ruby
Post.where(false) # => ArgumentError: Unsupported argument type: false (FalseClass)
Post.where(true) # => ArgumentError: Unsupported argument type: true (TrueClass)
Post.where(nil) # => ArgumentError: Unsupported argument type:  (NilClass)
Post.where({})
# Post Load (0.6ms)  SELECT "posts".* FROM "posts" WHERE (1=0)
# => #<ActiveRecord::Relation []>

Post.find_by(false) # => ArgumentError: Unsupported argument type: false (FalseClass)
Post.find_by(true) # => ArgumentError: Unsupported argument type: true (TrueClass)
Post.find_by(nil) # => ArgumentError: Unsupported argument type:  (NilClass)
Post.find_by({})
# Post Load (0.8ms)  SELECT  "posts".* FROM "posts" WHERE (1=0) LIMIT ?  [["LIMIT", 1]]
# => nil

```

2017-03-05 01:47 UTC, rafaelfranca requested changes
Thank you for the pull request but we should not remove this without deprecating and ater disallowing empty arguments like is being done in all the other methods in this file. Can you deprecate saying that it will raise error in 5.3?

2017-03-05 06:26 UTC, bogdanvlviv commented
@rafaelfranca thanks for the review.
I have one question. Why don't we raise error in 5.2?

2017-03-05 07:54 UTC, matthewd commented
Why would we want to special-case the empty hash? :confused:

Seems to just complicate things for callers (because they have to check for an empty hash and avoid it), and us (because we have to check for an empty hash to raise).

2017-03-05 08:15 UTC, bogdanvlviv commented
I think it will look like
```diff
--- a/activerecord/lib/active_record/relation/query_methods.rb
+++ b/activerecord/lib/active_record/relation/query_methods.rb

     def where(opts = :chain, *rest)
       if :chain == opts
         WhereChain.new(spawn)
       elsif opts.blank?
+        # raise error
-        self
       else
         spawn.where!(opts, *rest)
```

2017-03-05 08:40 UTC, matthewd commented
But *why*?

2018-06-19 18:51 UTC, rafaelfranca commented
See https://github.com/rails/rails/issues/33081#issuecomment-398291786

2018-06-19 18:51 UTC, closed without merging

2018-06-19 22:56 UTC, matthewd commented
FWIW, my thinking on this has evolved slightly: while I continue to believe that `where({})` should be valid (and return all rows), I do feel that `where([])` should probably be an error, am 50-50 on `where("")`, and think `where(false)` should either be an error or return no rows.

2018-06-19 23:31 UTC, sikachu commented
Yeah, I think I mostly agree with @matthewd here. For me

* `where({})` should return all rows.
* `where([])` should raise ArgumentError.
* `where("")` should act the same as `{}` and return all rows.
* `where(false)` should do `1=0` internally and return no rows. (Similar to how we have `.none`)

2018-06-20 07:32 UTC, bogdanvlviv commented
If we want `where(false)` to return a chainable relation with zero records then I think `where(nil)` should do the same, in order to keep Ruby semantics.