Remove non-exists method delegation
rails/rails pull request #28356
Opened 2017-03-09 10:30 UTC by jasl

### Summary

The `ActiveModel::Type::Registry#add_modifier` has been removed at commit [4590d77](https://github.com/rails/rails/commit/4590d7729e241cb7f66e018a2a9759cb3baa36e5) but the delegation still there, so I remove it.

2017-03-09 13:48 UTC, maclover7 approved these changes

2017-03-09 14:46 UTC, jasl commented
Addition: I also remove the comment above `register`, because it's written for Active Record but actually no effect, for Active Record should call `ActiveRecord::Type#registry` instead.

2017-03-10 23:35 UTC, rafaelfranca requested changes

2017-03-10 23:35 UTC, rafaelfranca commented on activemodel/lib/active_model/type.rb
> -      # false+ will cause the native type to be used over yours if one exists.
Could you write a documentation on this that is not active record specific? Removing the documentation is not a good solution.

2017-03-11 01:53 UTC, jasl commented on activemodel/lib/active_model/type.rb
> -      # false+ will cause the native type to be used over yours if one exists.
sure I'll try later

2017-03-11 02:20 UTC, jasl commented on activemodel/lib/active_model/type.rb
> -      # false+ will cause the native type to be used over yours if one exists.
Updated, but I think there no need to say much, because ActiveModel itself doesn't use `Type`

2017-03-14 01:41 UTC, merged