[docs] fix sentence in AC::Base docs
rails/rails pull request #28381
Opened 2017-03-11 13:18 UTC by shime

2017-03-11 17:26 UTC, vijaydev commented
👍

2017-03-11 17:30 UTC, vijaydev commented
@shime seems that you are still adding new commits on this PR. Let us know when this is ready to be merged. Thanks :)

2017-03-12 08:50 UTC, shime commented
@vijaydev thanks, this is now ready to be merged.

2017-03-12 09:01 UTC, vipulnsward requested changes

2017-03-12 09:01 UTC, vipulnsward commented on actionpack/lib/action_controller/metal/data_streaming.rb
> +      # * <tt>:type</tt> - specifies a HTTP content type. Defaults to 'application/octet-stream'.
Previous version is correct, since we say H-T-T-P, the "H" sounding as a vowel.

2017-03-12 09:01 UTC, vipulnsward commented on actionpack/lib/action_controller/metal/flash.rb
> +      # other than the default <tt>alert</tt> and <tt>notice</tt> in
The "to create flash types" is a lead of for the "other than default", so lets keep this.

2017-03-12 09:01 UTC, vipulnsward commented on actionpack/lib/action_controller/metal/live.rb
> +    # this method except in Rails internals.
We can retain this 😄

2017-03-12 09:01 UTC, vipulnsward commented on actionpack/lib/action_controller/metal/redirecting.rb
> +    # function immediately after the +redirect_to+, use return.
Lets revert the wraps to 80 lines. It is cosmetic change and goes on along when there is a related change on the concerned lines.

2017-03-12 09:01 UTC, vipulnsward commented on actionpack/lib/action_controller/metal/request_forgery_protection.rb
> +      # session token. Essentially the inverse of +masked_authenticity_token+.
ditto

2017-03-12 09:01 UTC, vipulnsward commented on actionpack/lib/action_controller/test_case.rb
> +    # This is the problem in #23483.
Ditto

2017-03-12 09:02 UTC, vipulnsward commented
@shime please squash the commits.

2017-03-12 09:25 UTC, shime commented
@vipulnsward squashed everything into one commit and fixed issues you mentioned.

2017-03-12 09:29 UTC, kamipo commented on actionpack/lib/action_controller/metal/request_forgery_protection.rb
> +      # session token. Essentially the inverse of
CodeClimate said "Trailing whitespace detected."

2017-03-12 09:31 UTC, shime commented on actionpack/lib/action_controller/metal/request_forgery_protection.rb
> +      # session token. Essentially the inverse of
Yup, I've just fixed that.

2017-03-12 14:06 UTC, vipulnsward commented on actionpack/lib/action_controller/metal/redirecting.rb
> +    # There are two special accessors for the commonly used flash names
@shime can you revert these two line wrapping changes? Then we are good to merge.

2017-03-12 15:01 UTC, shime commented on actionpack/lib/action_controller/metal/redirecting.rb
> +    # There are two special accessors for the commonly used flash names
@vipulnsward reverted those two line wrapping changes.

2017-03-13 17:30 UTC, vipulnsward approved these changes

2017-03-13 17:30 UTC, merged

2017-03-13 17:30 UTC, vipulnsward commented
Thanks!

2017-03-13 18:01 UTC, shime commented
🎉