Fix rubocop
rails/rails pull request #28382
Opened 2017-03-11 13:41 UTC by shime

This pull request fixes some Rubocop issues I encountered when running

```
$ rubocop
```

from the root directory.

2017-03-11 13:46 UTC, matthewd commented on guides/rails_guides/markdown/renderer.rb
> +          end
This seems pretty terrible. Which rubocop setting thinks this is a good idea? Maybe we just need to change its mind.

2017-03-11 13:51 UTC, shime commented on guides/rails_guides/markdown/renderer.rb
> +          end
Yeah, I agree. The metric that is failing is called `Lint/EndAlignment`, so maybe we should just disable that for this method?

2017-03-11 13:52 UTC, shime commented
For some reason Code Climate is still reporting a lot of Rubocop issues.

2017-03-11 15:08 UTC, shime commented on guides/rails_guides/markdown/renderer.rb
> +          end
I've now disabled that Rubocop check for this method.

2017-03-11 18:10 UTC, kaspth commented on guides/rails_guides/markdown/renderer.rb
> +        # rubocop:disable Lint/EndAlignment
We don't want to start sprinkling these into our code base. The only allowed action is to fix our  rubocop rules.

2017-03-12 09:50 UTC, shime commented on guides/rails_guides/markdown/renderer.rb
> +        # rubocop:disable Lint/EndAlignment
How do we fix Rubocop rules? The only option is to exclude the file in `.rubocop.yml`, isn't it?

2017-03-14 00:10 UTC, rafaelfranca requested changes

2017-03-14 00:10 UTC, rafaelfranca commented on guides/rails_guides/markdown/renderer.rb
> +        # rubocop:disable Lint/EndAlignment
The fix to to change the code to follow what the rule is expecting.

2017-03-14 08:17 UTC, matthewd commented on guides/rails_guides/markdown/renderer.rb
> +        # rubocop:disable Lint/EndAlignment
@rafaelfranca https://github.com/shime/rails/commit/082b1fa61a5b880598fde854de559cd98d7926e4 ?!? :confused:

2017-03-14 08:25 UTC, kaspth commented on guides/rails_guides/markdown/renderer.rb
> +        # rubocop:disable Lint/EndAlignment
We could just follow the css_class variable assignment above. E.g. `path = \`

2017-03-14 08:59 UTC, matthewd commented on guides/rails_guides/markdown/renderer.rb
> +        # rubocop:disable Lint/EndAlignment
Sure.. but if rubocop is insisting on something dumb, we should use its config to tell it to not do that (and hopefully, to instead insist on something less eye-bleedingly wrong).

Using a tool to enforce arbitrary style choices is one thing; having it impose secret work-arounds ("oh, it does that, but you can ignore it, and just do this instead..") is quite another.

2017-03-14 09:18 UTC, kaspth commented on guides/rails_guides/markdown/renderer.rb
> +        # rubocop:disable Lint/EndAlignment
Yes, of course 👌

2017-03-15 15:35 UTC, rafaelfranca commented on guides/rails_guides/markdown/renderer.rb
> +        # rubocop:disable Lint/EndAlignment
Either way, this is not what this comment is doing right now.

2017-03-20 18:47 UTC, kaspth commented on guides/rails_guides/markdown/renderer.rb
> +        # rubocop:disable Lint/EndAlignment
@shime interested in fixing the Rubocop rule? 😊

2017-03-21 15:01 UTC, shime commented on guides/rails_guides/markdown/renderer.rb
> +        # rubocop:disable Lint/EndAlignment
@kaspth I'll try to find some time to do it, thanks for the feedback

2017-04-20 00:15 UTC, closed without merging