Add documentation about signature_key for MessageEncryptor.new [ci skip]
rails/rails pull request #28412
Opened 2017-03-14 18:21 UTC by benoittgt

### Summary

I spent some times trying [make a migration from ruby 2.3 to 2.4 with wrong signature_key for ActiveSupport::MessageVerifier.new](https://github.com/rails/rails/issues/28401). I think `ActiveSupport::MessageEncryptor` lacks of documentation about the `sign_secret` parameter.

2017-03-14 20:33 UTC, maclover7 requested changes
Left two grammar comments. Thanks for the PR!!

2017-03-14 20:33 UTC, maclover7 commented on activesupport/lib/active_support/message_encryptor.rb
> +    # First additionnal parameter is used as signature_key for +MessageVerifier+.
`First additional parameter is used as the signature key for +MessageVerifier+`

2017-03-14 20:33 UTC, maclover7 commented on activesupport/lib/active_support/message_encryptor.rb
> +    # You can specify a key to encrypt and a key to sign.
This allows you to specify keys to encrypt and sign data.

2017-03-15 07:58 UTC, benoittgt commented
Thanks @maclover7 for the review. I've updated the doc.

2017-03-15 15:32 UTC, merged