Fix typo in actionview error message in to_form_params helper method
rails/rails pull request #28450
Opened 2017-03-16 17:44 UTC by adamgamble

When creating a button without sanitized request params you would previously get this error message:

`ArgumentError: Attempting to generate a buttom from non-sanitized request parameters! Whitelist and sanitize passed parameters to be secure.`

now you get this message:

`ArgumentError: Attempting to generate a button from non-sanitized request parameters! Whitelist and sanitize passed parameters to be secure.`

2017-03-17 06:54 UTC, vipulnsward requested changes

2017-03-17 06:54 UTC, vipulnsward commented on actionview/CHANGELOG.md
> +    *Adam Gamble*
This does not need a changelog, please remove this change.

2017-03-18 03:13 UTC, maclover7 approved these changes

2017-03-21 15:56 UTC, adamgamble commented
@maclover7 @vipulnsward is there anything else you need from me?

2017-03-21 16:13 UTC, merged