fix migrate with empty version
rails/rails pull request #28485
Opened 2017-03-20 02:48 UTC by quantumlicht

Fixes #28359

Add stronger assertions to rake migration tasks to make sure the user is providing a numeric VERSION
An empty string was getting converted to version = 0. This would in turn pass the presence check.

### Summary

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

If you are updating any of the CHANGELOG files or are asked to update the
CHANGELOG files by reviewers, please add the CHANGELOG entry at the top of the file.

Finally, if your pull request affects documentation or any non-code
changes, guidelines for those changes are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation)

Thanks for contributing to Rails!

2017-03-20 02:49 UTC, quantumlicht commented
What's the procedure for backporting this fix to older versions of rails ?
Also, like I commented in the issue, I'd like to add some tests for the rake task themselves, but I could not find where they are in the codebase.

Thanks!

2017-03-20 18:31 UTC, quantumlicht commented
Cool I think I found what I was looking for in railties/test/application/rake/migrations_test.rb

2017-03-20 19:41 UTC, maclover7 commented
@quantumlicht Maybe try https://github.com/rails/rails/blob/master/railties/test/application/rake/migrations_test.rb?

2017-03-20 19:41 UTC, maclover7 commented
@quantumlicht Can you also take a look at the test failures when you get a chance?

2017-03-20 19:42 UTC, kaspth commented
r? @maclover7

2017-03-20 19:51 UTC, quantumlicht commented
Yes I am on it. Like I mentioned in the issue I just learned the about the test for the rake tasks.

2017-03-20 22:03 UTC, quantumlicht commented
@maclover7 I fixed the tests and added some. Can you please review to make sure this is satisfactory and meets the guidelines? Thanks1

2017-03-21 01:32 UTC, maclover7 requested changes
Left some comments, but overall looks pretty good to me.

2017-03-21 01:32 UTC, maclover7 commented on activerecord/lib/active_record/railties/databases.rake
> +
✂️ the empty line

2017-03-21 01:32 UTC, maclover7 commented on activerecord/lib/active_record/tasks/database_tasks.rb
> +
✂️ the empty line

2017-03-21 01:32 UTC, maclover7 commented on activerecord/lib/active_record/railties/databases.rake
> +      raise "VERSION is required - To go down one migration, run db:rollback" if !ENV["VERSION"].nil? && ENV["VERSION"].empty?
run --> use

2017-03-21 02:22 UTC, quantumlicht commented
@maclover7, I addressed your comments.

2017-03-21 17:03 UTC, rafaelfranca requested changes

2017-03-21 17:03 UTC, rafaelfranca commented on activerecord/lib/active_record/railties/databases.rake
>        if ENV["VERSION"]
Now this conditional doesn't seems to be used.

2017-03-21 17:03 UTC, rafaelfranca commented on activerecord/lib/active_record/railties/databases.rake
> +      raise "Empty VERSION provided" if !ENV["VERSION"].nil? && ENV["VERSION"].empty?
`if !ENV["VERSION"] || ENV["VERSION"].empty?`

2017-03-21 17:03 UTC, rafaelfranca commented on activerecord/lib/active_record/railties/databases.rake
>        version = ENV["VERSION"] ? ENV["VERSION"].to_i : nil
This conditional is not needed anymore.

2017-03-21 17:03 UTC, rafaelfranca commented on activerecord/lib/active_record/railties/databases.rake
>        version = ENV["VERSION"] ? ENV["VERSION"].to_i : nil
This conditional is not needed anymore

2017-03-21 17:03 UTC, rafaelfranca commented on activerecord/lib/active_record/tasks/database_tasks.rb
>          version = ENV["VERSION"] ? ENV["VERSION"].to_i : nil
This conditional is not needed anymore.

2017-03-21 17:15 UTC, quantumlicht commented on activerecord/lib/active_record/railties/databases.rake
>        version = ENV["VERSION"] ? ENV["VERSION"].to_i : nil
This one `version = ENV["VERSION"] ? ENV["VERSION"].to_i : nil` ? Can you explain why it's not required? I am not sure I understand.

2017-03-21 17:20 UTC, quantumlicht commented on activerecord/lib/active_record/railties/databases.rake
> +      raise "Empty VERSION provided" if !ENV["VERSION"].nil? && ENV["VERSION"].empty?
Just for my own understanding, is this proposed change to conform to the style guidelines or there's another reason to change the condition ?

2017-03-21 17:24 UTC, rafaelfranca commented on activerecord/lib/active_record/railties/databases.rake
> +      raise "Empty VERSION provided" if !ENV["VERSION"].nil? && ENV["VERSION"].empty?
Usually in ruby you don't need to check for `nil?` unless `false` have a different meaning, but in this case `nil` and `false` needs to have the same behavior so it is better to not check for `nil?`

2017-03-21 17:26 UTC, rafaelfranca commented on activerecord/lib/active_record/railties/databases.rake
> +      raise "Empty VERSION provided" if !ENV["VERSION"].nil? && ENV["VERSION"].empty?
Oh, but the behavior is now different. I think it should be `raise "Empty VERSION provided" if ENV["VERSION"] && ENV["VERSION"].empty?`

2017-03-21 17:27 UTC, rafaelfranca commented on activerecord/lib/active_record/railties/databases.rake
>        version = ENV["VERSION"] ? ENV["VERSION"].to_i : nil
oh, now I for it, VERSION as nil is still valid. I'll remove those comments

2017-03-21 18:10 UTC, quantumlicht commented on activerecord/lib/active_record/railties/databases.rake
> +      raise "Empty VERSION provided" if !ENV["VERSION"].nil? && ENV["VERSION"].empty?
Thanks for your explanation. I will change it

2017-03-21 18:37 UTC, kaspth commented on activerecord/lib/active_record/railties/databases.rake
> +      raise "Empty VERSION provided" if !ENV["VERSION"].nil? && ENV["VERSION"].empty?
Alternatively: `ENV["VERSION"].to_s.empty?`

2017-03-21 18:44 UTC, quantumlicht commented
@maclover7, @rafaelfranca , Can you tell me what's the procedure for backports? I am currently using Ruby 2.1.5 with rails 4.2.3 and i'd like to be able to use that fix. Is that likely to happen?

2017-03-21 18:47 UTC, kaspth commented
@quantumlicht our maintenance policy just got revised: http://weblog.rubyonrails.org/2017/3/20/Rails-5-1-rc1/

I think this is only likely for 5.0 though.

2017-03-21 18:48 UTC, rafaelfranca commented
We still can backport to 4.2 until the final version of Rails 5.1 is not released. But this will be the last 4.2 release with bugs fixes.

2017-03-21 19:37 UTC, quantumlicht commented
Can I assist in anyway to get this going ?

2017-03-21 19:41 UTC, kaspth commented
@quantumlicht address the feedback provided, then squash your commits down to 1, then we'll merge and backport 😊

2017-03-21 20:54 UTC, rafaelfranca commented
Could you squash the merge commit too?

2017-03-21 22:03 UTC, quantumlicht commented
Ok... I have to admit I am a bit confused about the procedure. When I clicked `update branch` it merged master into my branch. I did that because my tests were failing suddenly after squashing my commits. What is the command you usually perform to do this elegantly?

2017-03-24 13:37 UTC, quantumlicht commented
@rafaelfranca, When I do `pull rails-origin master --squash && commit`, it squashes all the next commits into a single one... Surely that's not what you want is it ?

2017-03-27 01:08 UTC, quantumlicht commented
I figured out how. It should be ready to merge. @maclover7 @kaspth

2017-03-27 21:07 UTC, merged

2017-03-27 21:08 UTC, rafaelfranca commented
Thank you so much! Backported in 8e91d23908

2017-03-27 21:23 UTC, quantumlicht commented
Thanks for your patience! Hopefully there will be more to come :)

2017-03-27 21:31 UTC, quantumlicht commented
@rafaelfranca The backport was in `5-1-stable` right? Is it too late to include in `4-2-stable` too ?

2017-03-27 21:34 UTC, rafaelfranca commented
oh, I forgot to backport to the other branch. I'll do

2017-03-27 21:40 UTC, rafaelfranca commented
Backported in a9d3bdb921 and ba95f5a225

2017-04-27 16:22 UTC, jrochkind commented
By swapping the order, I don't totally understand what you've fixed, but you seem to have broken arg checking altogether. 

~~~
raise "VERSION is required" if ENV["VERSION"] && ENV["VERSION"].empty?
version = ENV["VERSION"] ? ENV["VERSION"].to_i : nil
~~~

If there is no `ENV['VERSION']` at all: The raise does not happen (`if ENV["VERSION"] && ENV["VERSION"].empty?`); the next line winds up with local `version` of `nil`, which is then passed into subsequent code, resulting in a confusing `ActiveRecord::UnknownMigrationVersionError` instead of the as-intended "VERSION is required" warning.