ignore system test gems on Gemfile when execute with --skip-test option
rails/rails pull request #28541
Opened 2017-03-23 05:05 UTC by ota42y

### Summary
`rails new app_name -T` generate rails application without test.
But, generated Gemfile include `capybara` and `selenium-webdriver`.
So I fix don't generate these gems when test skip option add.

2017-03-23 05:22 UTC, rafaelfranca requested changes

2017-03-23 05:22 UTC, rafaelfranca commented on railties/lib/rails/generators/rails/app/templates/Gemfile
> +  <%- unless options.skip_system_test? || options.skip_test? || options.api? -%>
Can we create a method like `depend_on_listen` and move those conditionals there?

2017-03-23 06:11 UTC, ota42y commented on railties/lib/rails/generators/rails/app/templates/Gemfile
> +  <%- unless options.skip_system_test? || options.skip_test? || options.api? -%>
I did fix!

2017-03-23 20:16 UTC, eileencodes commented on railties/lib/rails/generators/app_base.rb
> +      def depend_system_test?
Can you make this `depend_on_system_test?` so it matches other methods in this file like `depend_on_listen?`

2017-03-24 01:21 UTC, ota42y commented on railties/lib/rails/generators/app_base.rb
> +      def depend_system_test?
fixed!

2017-03-24 19:21 UTC, eileencodes commented
Looks good. Can you squash your commits into one? Thanks!

2017-03-27 01:13 UTC, ota42y commented
I did squash!

2017-03-27 12:25 UTC, merged

2017-03-27 12:26 UTC, eileencodes commented
Thanks @ota42y! 😄

2017-03-27 12:27 UTC, eileencodes commented
Backported to 5-1-stable in 716a9fbae7ed89df807143a84eb104ba82f8bc04