Make Getting Started for ActiveRecord README.rdoc
rails/rails pull request #28566
Opened 2017-03-25 06:49 UTC by kanpou0108

# Background
Although there is a sample file for ActiveRecord, there is no procedure for executing sample file.
If there is a procedure, it is beneficial for beginner.
Existing sample file is below.
https://github.com/rails/rails/blob/master/activerecord/examples/simple.rb

# What I did
Append a description for executing sample file with ActiveRecord.

Please check.

2017-03-27 00:13 UTC, eileencodes requested changes

2017-03-27 00:13 UTC, eileencodes commented on activerecord/README.rdoc
> +1.install sqlite to your PC
Can you update these to have a space after the period and then make it capitalized?

Example: "1. Install SQLite on your computer"

2017-03-27 00:13 UTC, eileencodes commented on activerecord/README.rdoc
> +  $ ruby sample.rb
Should this be "simple.rb"?

2017-03-27 00:13 UTC, eileencodes commented on activerecord/README.rdoc
> +https://github.com/rails/rails/blob/master/activerecord/examples/simple.rb
I don't feel like this sentence makes sense. What do you mean by prepare simple.rb locally?

2017-03-27 22:08 UTC, rafaelfranca commented
Thank you for the pull request but we centralise all guides in the Rails guides, maybe we should move some of those instructions to one of the already existing guides?

2017-03-29 03:41 UTC, kanpou0108 commented on activerecord/README.rdoc
> +1.install sqlite to your PC
Thank you for pointing out. 
I used double quote because the number list couldn't be interpreted correctly by rdoc.
I updated content.

2017-03-29 03:41 UTC, kanpou0108 commented on activerecord/README.rdoc
> +https://github.com/rails/rails/blob/master/activerecord/examples/simple.rb
Sorry for vague sentence. 
I mean simply creating the simple.rb. 
I updated content.

2017-03-29 03:41 UTC, kanpou0108 commented on activerecord/README.rdoc
> +  $ ruby sample.rb
Yes. Sorry for misspelling.
I updated content.

2017-03-29 16:35 UTC, rafaelfranca commented
The README if for the users of the framework not for contributors. The instructions you are adding to the README is not useful for the users of the framework since they require the users to clone the rails repository. If we want to include these instruction somewhere I'd say it should be in the contributing guide, but even there I don't think there is any value in adding it.

Thank you so much for the pull request.

2017-03-29 16:35 UTC, closed without merging