Make `driven_by` overridable
rails/rails pull request #28586
Opened 2017-03-28 15:29 UTC by mtsmfm

Sometimes we want to use rack_test partially instead of selenium for test speed:

```ruby
class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  driven_by :selenium, using: :chrome, screen_size: [1400, 1400], options: {url: "http://chrome:4444/wd/hub"}
end

class WithJavascriptTest < ApplicationSystemTestCase
end

class WithoutJavascriptTest < ApplicationSystemTestCase
  driven_by :rack_test
end
```

In the abobe case, `WithoutJavascriptTest` uses selenium because
`SystemTestCase` calls superclass' driver on `#initialize` (`self.class.superclass.driver.use`).

Using `class_attribute` can handle inherited `driven_by`.

2017-03-28 15:37 UTC, rafaelfranca approved these changes

2017-03-28 15:41 UTC, eileencodes requested changes

2017-03-28 15:41 UTC, eileencodes commented on actionpack/test/dispatch/system_testing/system_test_case_test.rb
> +class OverrideDriverToRackTestTest < DrivenBySeleniumWithChrome
I was confused why this test was necessary when the test before works with `rack_test`. Can you rename it to `OverrideSeleniumSubclassToRackTestTest` so it's clearer?

2017-03-29 00:35 UTC, mtsmfm commented
@eileencodes I renamed the test class!

2017-03-29 11:22 UTC, eileencodes approved these changes

2017-03-29 11:53 UTC, merged

2017-03-29 11:54 UTC, eileencodes commented
Backported to 5-1-stable in 41412efda2fca3d3805d6deec8518bdd4f36aea2