[ci skip] Add console examples for each association type.
rails/rails pull request #28639
Opened 2017-04-01 19:48 UTC by marklocklear

For kinesthetic learners (doers) it is important to show concrete examples of how advanced concepts like associations work. What I have attempted to do here is (using the console) give examples of how each of the associations works based on the models and attributes for each. Existing text/examples were left in place and supplemented with console examples. Note that I did remove the published_at attribute in 2.1 belongs_to and 2.3 has_many and replace with :name as it seems to make more sense for the examples I am using. I also updated the diagrams/images that went along with these two examples.

2017-04-02 17:41 UTC, maclover7 requested changes
Did a first pass over the changes -- overall looks good. Left some grammar and stylistic comments.

2017-04-02 17:41 UTC, maclover7 commented on guides/source/association_basics.md
> +      t.string :name
Looks like when the graphs were regenerated, the arrows are now pointing from the wrong box 😬

2017-04-02 17:41 UTC, maclover7 commented on guides/source/association_basics.md
> +Note that we inserted the id of the author David Heinemeier Hansson into the `author_id` field of our book. With this association in place we can view this assocation from the perspective of the book
Can you add a comma after association

2017-04-02 17:41 UTC, maclover7 commented on guides/source/association_basics.md
> +Note that we inserted the id of the author David Heinemeier Hansson into the `author_id` field of our book. With this association in place we can view this assocation from the perspective of the book
Can you put the author's name in parentheses

2017-04-02 17:41 UTC, maclover7 commented on guides/source/association_basics.md
> +As an example, using the rails console, let's first create an author:
Can you try and standardize the top language; here it's "using the rails console", below it's "working from the console", etc...

2017-04-02 17:41 UTC, maclover7 commented on guides/source/association_basics.md
> +Note that the `supplier_id` (in this case 1) is inserted into the Accounts table. Now let's add a second account_number for this supplier:
Can you downcase accounts, and wrap it with tick marks

2017-04-02 17:41 UTC, maclover7 commented on guides/source/association_basics.md
> +Note that the `supplier_id` (in this case 1) is inserted into the Accounts table. Now let's add a second account_number for this supplier:
Can you add tick marks around account_number

2017-04-02 17:41 UTC, maclover7 commented on guides/source/association_basics.md
> +Now we see the true power of the `has_one` association. Notice that when we inserted another account_number for this same supplier into the database that two things happened. First, we inserted a new
in to --> into

2017-04-02 17:41 UTC, maclover7 commented on guides/source/association_basics.md
> +To see this association in action let's create a physician and a couple of patients:
Can you add a comma after action

2017-04-02 17:41 UTC, maclover7 commented on guides/source/association_basics.md
> +Note that an appointment contains both a physician and a patient, so Appointments acts as a join table. To see all patients assigned to a physician we can do:
Can you wrap appointments in tick marks

2017-04-02 17:41 UTC, maclover7 commented on guides/source/association_basics.md
> +As in our earlier [`has_one`](##the-has-one-association) example there is an insert statement for the new record that has a credit_rating of 789, but also notice the update statement that sets accoun
Comma after example

2017-04-03 15:22 UTC, marklocklear commented on guides/source/association_basics.md
> +      t.string :name
I am not sure I understand this one. The other suggestions look good. I will work on this and resubmit.

2017-04-03 17:50 UTC, marklocklear commented on guides/source/association_basics.md
> +Note that we inserted the id of the author David Heinemeier Hansson into the `author_id` field of our book. With this association in place we can view this assocation from the perspective of the book
A comma seems more appropriate here after place; as in " With this association in place, we can view this ". No?

2017-04-04 16:05 UTC, marklocklear reviewed
@maclover7 have made changes based on your review.  See also a couple of individual comments below.

2017-04-15 14:43 UTC, mjhoy commented
@marklocklear FYI: I noticed that some graphs were changed and have arrows now pointing from the wrong column (see the github diff).

2017-04-15 19:53 UTC, marklocklear commented
@mjhoy great catch! Just fixed and pushed. Tried to squash commits but ran into issues. If this is a problem someone shout and I will take another stab at it.

2017-04-16 14:53 UTC, mjhoy commented
@marklocklear has_many is fixed but it looks like belongs_to.png is still incorrect.

2017-04-17 15:53 UTC, marklocklear commented
@mjhoy updated belongs_to image. Me thinks my commit history is not right. Let me know if I need to clean up. Thanks!

2017-04-17 16:26 UTC, mjhoy commented
@marklocklear Yep, something is really off here!

I think you ended up with two branches from this that are both merged in somehow. Perhaps you did a `git pull origin master` against your branch once or twice?

I believe you just need to reset your branch head to `d2ce1d8`, and then force update the remote branch. You might also need to rebase against rails master. Let me know if you need help with this.

If your git index and working tree are "clean" i.e. everything is committed or stashed, I would run:

```sh
# Assuming you are on your association_doc_updates branch
git reset d2ce1d8 # set HEAD to before all the merges
git log # Inspect the history and make sure this is correct
# Maybe: git rebase [RAILS_REMOTE]/master
git push [REMOTE] association_doc_updates -f # force update the remote branch
```

2017-04-17 16:35 UTC, mjhoy commented
@marklocklear Also, if you haven't seen it, it's worth checking out the Rails Guides on pull requests and git usage, which has a good, simple workflow you can use. http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#update-your-branch

2017-04-17 16:56 UTC, marklocklear commented
@mjhoy thanks for being patient. I think commit history is clean now.

2017-04-22 13:10 UTC, marklocklear commented on guides/source/association_basics.md
> +      t.string :name
This is fixed now. See updated images.

2017-04-25 13:16 UTC, marklocklear commented
Hey folks, please let me know if there is anything else I need to do regarding this pull request. Thanks!

2017-05-10 21:48 UTC, sgrif commented
r? @maclover7

2019-12-25 12:38 UTC, closed without merging