Documented issue related before_destroy with dependent: :destroy
rails/rails pull request #28680
Opened 2017-04-06 07:30 UTC by vishalzambre

To address issues #3458, #20954, #670 It is good to have documented it at http://edgeguides.rubyonrails.org/active_record_callbacks.html

2017-04-08 14:03 UTC, maclover7 requested changes
Please update the text per my comment. Thank you for the PR!

2017-04-08 14:03 UTC, maclover7 commented on guides/source/active_record_callbacks.md
> +NOTE: `before_destroy` should placed before `dependent: :destroy` associations or use `prepend: true` to execute it before `dependent: :destroy`
`before_destroy` callback should be placed before `dependent: :destroy` associations (or use the `prepend: true` option), to ensure they execute before the records are deleted by `dependent: :destroy`.

2017-04-08 14:03 UTC, maclover7 commented
r? @maclover7

2017-04-09 04:11 UTC, vishalzambre commented
@maclover7 Updated text as per comment.

2017-04-10 01:19 UTC, maclover7 commented
Thanks @vishalzambre! Can you squash down your commits to one, and add `[ci skip]` to the commit message? Looks ready to merge after that.

2017-04-10 08:15 UTC, vishalzambre commented
@maclover7 squashed changes.

2017-04-10 14:28 UTC, maclover7 approved these changes

2017-04-10 14:28 UTC, maclover7 commented
:+1: Thank you for your contribution!

:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

2017-04-10 14:28 UTC, merged

2017-10-11 16:40 UTC, mstroming commented
I see this documented in the Edge guide, but not here:

http://guides.rubyonrails.org/active_record_callbacks.html

What's the difference between those two guides? When people are Googling for this stuff, they're not automatically going to understand the difference.