rails-ujs: missing default url for ajax requests.
rails/rails pull request #28722
Opened 2017-04-10 11:58 UTC by DmytroVasin

### Steps to reproduce
Hi!
I'm using rails 5.1.0.rc1 and faced with next unexpected behaviour.

According to documentation i can set `remote: true` on `select` element like next:
```
<%= select_tag( "user_id", some_collection, ..., data: { remote: true, url: users_path } %>
```
And in this case everything will work.

But actually i can remove `url` 

### Expected behavior
When we use `jquery_ujs` and use `$.ajax` function:
This `ajax` function provide [default value]() for `url` if it does not specified.

```
url (default: The current page)
Type: String
A string containing the URL to which the request is sent.
```

### Actual behavior
Currently if i remove `url` option from `select_tag` i will receive an error:

```javascript
rails-ujs.js:189 Uncaught TypeError: Cannot read property 'indexOf' of null
    at prepareOptions (rails-ujs.js:189)
    at Rails.ajax (rails-ujs.js:161)
    at HTMLSelectElement.Rails.handleRemote (rails-ujs.js:536)
    at HTMLDocument.<anonymous> (rails-ujs.js:137)
    at jQuery.fn.init.triggerNative (settings.js:96)
    at Object.<anonymous> (data-remote.js:435)
    at Test.run (qunit.js:1303)
    at qunit.js:1463
    at process (qunit.js:1016)
    at qunit.js:186
```

### System configuration
**Rails version**:
5.1.0.rc1
**Ruby version**:
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]

### Other Information
Maybe you had some reason not to do it.

Thanks.

2017-04-10 14:34 UTC, maclover7 commented
@DmytroVasin Would you be able to add a test for this behavior?

2017-04-10 14:41 UTC, DmytroVasin commented
Yes, i will

2017-04-10 22:18 UTC, rafaelfranca requested changes
Could you squash your commits?

2017-04-11 04:38 UTC, DmytroVasin commented
@rafaelfranca Done

2017-04-11 21:36 UTC, merged

2017-04-11 21:36 UTC, rafaelfranca commented
Backported c7493fe2e4