More connection locking
rails/rails pull request #28777
Opened 2017-04-17 07:02 UTC by matthewd

Address two failure modes for connection pool thread locking (yay) by making it more complicated (boo).

First, a deadlock between the pool lock and the connection lock, due to inconsistent lock acquisition order: `clear_query_cache` requires the connection lock, and is invoked by a checkin callback while holding the pool lock. (I don't think we should actually be invoking callbacks while holding the pool lock, but that's a matter for another time.)

Second, the less proximate cause of the above failure: the main thread could checkin its connection while another thread was still using it. The second thread would then unexpectedly change connections between two queries -- even while inside a transaction on the first one. 

---

We now keep track of who has borrowed the connection, and don't complete the "unlock" until they have released it. This also means that the lock only applies to connection acquisition: after that (and until it attempts to release it) the borrowing thread treats the connection as its own.

2017-04-17 07:07 UTC, matthewd commented
@KeithP this should hopefully tame that last deadlock you were seeing

2017-04-17 12:08 UTC, eileencodes commented
Hrm something isn't quite right. I'm seeing my test app run one test, do a rollback and then just sit there. No raise or anything. All the tests in my app should run, but only one is before it stalls and just sits there. Here's the logs.

```
   (0.3ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
   (0.2ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
   (0.2ms)  SELECT @@FOREIGN_KEY_CHECKS
   (0.1ms)  SET FOREIGN_KEY_CHECKS = 0
   (0.1ms)  BEGIN
  Fixture Delete (0.2ms)  DELETE FROM `companies`
  Fixture Insert (0.1ms)  INSERT INTO `companies` (`title`, `created_at`, `updated_at`, `id`) VALUES ('My Company', '2017-04-17 12:07:29', '2017-04-17 12:07:29', 980190962)
  Fixture Insert (0.1ms)  INSERT INTO `companies` (`title`, `created_at`, `updated_at`, `id`) VALUES ('Your Company', '2017-04-17 12:07:29', '2017-04-17 12:07:29', 298486374)
   (0.2ms)  COMMIT
   (0.1ms)  SET FOREIGN_KEY_CHECKS = 1
   (0.1ms)  BEGIN
-------------------------------------------------------
User::IndexTest: test_users_index_with_rails_assertions
-------------------------------------------------------
Started GET "/users" for 127.0.0.1 at 2017-04-17 08:07:30 -0400
Processing by UsersController#index as HTML
  Rendering users/index.html.erb within layouts/application
  User Load (0.4ms)  SELECT `users`.* FROM `users`
  Rendered users/index.html.erb within layouts/application (4.2ms)
Completed 200 OK in 60ms (Views: 51.7ms | ActiveRecord: 2.1ms)
Started GET "/assets/application-6f9276714fb0c092a05913d8250b6a6804ddc8b919759bf9af95cd7ff9f1b453.css" for 127.0.0.1 at 2017-04-17 08:07:31 -0400
Started GET "/assets/application-c1b7cd6555db8d4c769b8cb3024a3e73566a1a1212b5c99c233f8bdf6e835bcb.js" for 127.0.0.1 at 2017-04-17 08:07:31 -0400
   (0.2ms)  ROLLBACK
```

2017-04-18 00:23 UTC, thedarkone requested changes

2017-04-18 10:10 UTC, KeithP commented
@matthewd looks like we get the same failure as Eileen. 

Failure/Error: @cond.wait(@monitor.instance_variable_get(:@mon_mutex), timeout)
     fatal:   No live threads left. Deadlock?

.# /home/keithp/.rvm/gems/ruby-2.3.0@stock_positions/bundler/gems/rails-5de1e4f2c45e/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `block in lock_thread='
     .# /home/keithp/.rvm/gems/ruby-2.3.0@stock_positions/bundler/gems/rails-5de1e4f2c45e/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:368:in `lock_thread='
     .# /home/keithp/.rvm/gems/ruby-2.3.0@stock_positions/bundler/gems/rails-5de1e4f2c45e/activerecord/lib/active_record/fixtures.rb:1012:in `block in teardown_fixtures'
     .# /home/keithp/.rvm/gems/ruby-2.3.0@stock_positions/bundler/gems/rails-5de1e4f2c45e/activerecord/lib/active_record/fixtures.rb:1010:in `each'
     .# /home/keithp/.rvm/gems/ruby-2.3.0@stock_positions/bundler/gems/rails-5de1e4f2c45e/activerecord/lib/active_record/fixtures.rb:1010:in `teardown_fixtures'
     .# /home/keithp/.rvm/gems/ruby-2.3.0@stock_positions/bundler/gems/rails-5de1e4f2c45e/activerecord/lib/active_record/fixtures.rb:857:in `after_teardown'

2017-04-26 19:39 UTC, matthewd commented
I've pulled out the deadlock fix in ce2abffc0e29f562da26f89d7f07aeaf06a9cbcd and pushed that to master / 5-1-stable. We'll punt the larger change here to 5.1.1; I think I've just fixed the problem @eileencodes and @KeithP described above, but this is too risky to drop in post-rc2, when we're not expecting many users to encounter the original issue.

2019-12-25 12:39 UTC, closed without merging