assert_differences - for testing mutiple values that change at different rates
rails/rails pull request #28804
Opened 2017-04-19 22:15 UTC by kieraneglin

### Summary

(This is my first PR to a big project, so let me know if I missed anything!)

Several times, I've wanted to test that 2+ values are changed by an action.  But what if we expect `model_1` to change by +1, while `model_2` changes by -1?  You can nest calls to `assert_difference`, but what if you need to check 3 values?  That would get ugly fairly quickly.

That is why I worked on `assert_differences`.  Influenced *heavily* by [Malcolm at wholemeal](http://wholemeal.co.nz/blog/2011/04/06/assert-difference-with-multiple-count-values/), you can use it like so:

```ruby
assert_differences [ ['Foo.count', +1], ['Bar.count', -1], ['Baz.count', +2] ] do
  #...
end
```

I tried my best to emulate the code style of the existing `assert_difference`.  Furthermore, `assert_difference` now calls the new `assert_differences`.  

The API for `assert_difference` has not changed at all and should be 100% back-compatible.

### Other Information

#### The name

I've tested the waters on StackOverflow and /r/rails.  Devs really seem to like the idea of this, but some don't love the name, stating it's too close the the existing `assert_difference`.

While I'm not sold on the idea that having a similar name is an issue, I'm very open to a name change!

___

If there's anything I missed, please let me know :)

2017-04-19 22:22 UTC, kieraneglin commented on activesupport/lib/active_support/testing/assertions.rb
> +        end
I don't love the idea of this hash return.  The idea being that assigning `before` here cuts the need for another loop, like what was present in the original `assert_difference`.

If no-one minds me having 2 loops, I can modify that.

2017-04-19 22:23 UTC, kieraneglin commented on activesupport/lib/active_support/testing/assertions.rb
> +        expressions = [expressions] unless expressions.all? { |e| e.kind_of? Array }
`assert_differences` needs a 2-d array.  This line converts `['Foo']` into `[ ['Foo'] ]` while leaving arrays that are already 2-d untouched

2017-04-19 23:29 UTC, rafaelfranca commented
Instead of adding a new method, would be possible to make `assert_difference` also behaves like this? Right now it is already possible to pass an array of expressions but they both needs the same difference. Maybe we could make both cases works in the same method. What do you think?

2017-04-19 23:34 UTC, kieraneglin commented
I think it's doable!  But I don't think it'd be clean, since existing functionality would have to be maintained 100%.

Allowing for 
```ruby
assert_difference 'Foo.count', 1
assert_difference ['Foo.count'], 1
assert_difference ['Foo.count', 'Bar.count'], 1
assert_difference [ ['Foo.count', 1], ['Bar.count', 2] ]
```
Seems like it'd be a conditional mess.

At any rate, I'll play around and see if I can come up with something clean!

2017-04-19 23:53 UTC, kieraneglin commented
After playing around briefly, I don't think there's a clean way to allow for all the required behavior.  It's a mess of conditionals and the fact that the parameter `difference` would only sometimes do something (ie when emulating the old functionality of `assert_difference`), which I think is too confusing. 

If anyone has advice into combining these, I'd be happy to try it out! But until then I think the best option is to stick with 2 separate methods.

2017-04-19 23:58 UTC, rafaelfranca approved these changes
Could you add a CHANGELOG entry?

2017-04-20 00:06 UTC, kieraneglin commented
Sure thing!  To be clear, should I `[ci skip]` this?

2017-04-20 00:23 UTC, rafaelfranca requested changes
When you are done could you squash all your commits in one?

2017-04-20 00:23 UTC, rafaelfranca commented on activesupport/CHANGELOG.md
> +*   Add `assert_differences` to `ActiveSupport::Testing::Assertions`
Missing `.` at the end

2017-04-20 00:23 UTC, rafaelfranca commented on activesupport/lib/active_support/testing/assertions.rb
> +      # A lambda or a list of lambdas can be passed in and evaluated:
All other used `.` at the end so maybe this one should use it too?

2017-04-20 00:25 UTC, kieraneglin commented on activesupport/CHANGELOG.md
> +*   Add `assert_differences` to `ActiveSupport::Testing::Assertions`
Only 1 other has a period at the end.  Should I add periods to all while I'm at it?

2017-04-20 00:29 UTC, rafaelfranca commented on activesupport/CHANGELOG.md
> +*   Add `assert_differences` to `ActiveSupport::Testing::Assertions`
Oh, so it is fine. I'll change all of them when reviewing the CHANGELOG in the release

2017-04-20 00:35 UTC, kieraneglin commented
I did what the docs asked re: squashing.  Does everything look okay?

2017-04-20 02:46 UTC, matthewd commented
What's the advantage of this over

```ruby
assert_difference 'Article.count', 2 do
  assert_difference 'Post.count', 1 do
    post :create, params: { article: {...} }
  end
end
```

?

2017-04-20 04:12 UTC, kieraneglin commented
Nothing really.  But it's the same as asking what's the difference between the original `assert_difference` and a fancy `assert_equal`?  It's more sugar that I believe has real-world use. 

Plus, it greatly cleans up things like this: 
```ruby
assert_difference 'Foo.count', 1 do
  assert_difference 'Bar.count', -1 do
     assert_difference 'Bar.count', 2 do
       # ...
    end
  end
end
```
Which become
```ruby
assert_differences [ ['Foo.count', +1], ['Bar.count', -1], ['Baz.count', +2] ] do
  #...
end
```

2017-04-20 05:39 UTC, matthewd commented
> But what's the advantage of the original assert_difference over a fancy assert_equal?

It eliminates a local variable, and avoids writing the evaluated expression twice.

2017-04-20 05:46 UTC, kieraneglin commented
And this eliminates the need to write the `assert_difference` method twice, or thrice, or more.

I know this isn't a groundbreaking method, but it's useful nonetheless and every developer/forum I ran it by said they'd use it if it were available.

2017-04-21 13:57 UTC, kieraneglin commented
@rafaelfranca does everything look good to go?

2017-04-21 17:38 UTC, rafaelfranca commented
I'm waiting @matthewd opinion. I agree with his point of view. I don't see anything wrong with the nested scenario.

2017-04-21 17:57 UTC, kieraneglin commented
My concerns are twofold.  

1. Nesting 3+ `assert_difference` blocks seems needlessly verbose.  It's (slightly) analogous to chaining `if`s vs a `switch`.  Can they be functionally identical?  Sure. Do they still each have their own separate use-cases?  Also yes.

2. It's immediately easier to grok the meaning behind 1 `assert_differences` vs  3+ `assert_difference`.  I think simplicity and readability is worth a lot, especially in tests.

2017-04-22 06:18 UTC, matthewd commented
I disagree that the nested-array form improves simplicity or readability.. it also seems a fairly arbitrary thing to individually support such multi-calls on: wouldn't `belongs_tos [[:company], [:citizenship, model_name: "Country"]]` also eliminate the need to call `belongs_to` twice, and thus be easier to grok?

> If I were learning to use assert_difference and I found the only way to test multiple assertions was to nest them, I'd think "The Rails team doesn’t think I should be doing this."

I don't believe we generally hold opinions on this point, but it's worth noting that plenty of people would claim you generally *shouldn't* be making multiple assertions in a test.

I'd suggest that if you have a test or set of tests where this feels particularly necessary (i.e., it does involve more nesting than you're comfortable with), it's simple enough to include as a local helper:

```ruby
# untested, but sounds plausible
def assert_differences(pairs, &block)
  pairs.reverse.inject(block) { |inner, pair| lambda { assert_difference(*pair, &inner) } }.call
end
```

2017-04-22 06:35 UTC, gsamokovarov commented
@kieraneglin Have you seen [`assert_changes`](https://github.com/rails/rails/blob/b4c6f5ed08af89683ae69822bfb5a0920ea24405/activesupport/lib/active_support/testing/assertions.rb#L160-L219)? It's a more general `assert_difference` and it's pretty good for cases like those:

```ruby
assert_changes '[Foo.count, Bar.count, Baz.count]', to: [2, 0, 3] do
  # Do the test changes here.
end
```

2017-04-24 14:00 UTC, kieraneglin commented
@matthewd, @rafaelfranca Fair enough.  One final thing, would you be open to this PR if it had a similar syntax to @gsamokovarov's example of `assert_changes`?  

So there'd only be the old `assert_difference`, and not `assert_differences`.  And with `assert_difference`, you could optionally pass an array as a second argument which signifies what it should change to.

If you like it, I'll make something up!  Otherwise, I'll close the PR. Thanks!

2017-04-24 17:47 UTC, gsamokovarov commented
What I'm thinking is, do we need `assert_differences`, when we already have `assert_changes` that can cover this use case?

2017-04-24 19:48 UTC, kieraneglin commented
Unless I'm using fixtures incorrectly (which is very possible), they're all loaded in my default.  We may test like:

```ruby
user = user(:steve)

assert_difference 'User.count', -1 do
  user.destroy
end
```

But we may have anywhere from 1-10 different types of `User` fixtures.  So our test would look like this, correct?

```ruby
# Assuming 5 fixture types
user = user(:steve)

assert_change 'User.count', to: 4 do
  user.destroy
end
```

But if we add another fixture, all tests using this will break.  I could do something like `to: User.count -1`, but that gets unwieldy very quickly if you're testing multiple objects.

To fix this, we would need to specify not what it should change to, but what it should change *by*.

Adding something like:

```ruby
assert_change '[A.count, B.count, C.count]', by: [-1, 1, 2] do
  # ...
end
```

But that doesn't fit well with the current usage of `assert_change`.  I think allowing you to pass an array to `assert_difference` would be a good compromise without introducing a new function.

Something like 
```ruby
assert_difference ['A.count', 'B.count', 'C.count'], [-1, 1, 2] do
  # ...
end
```

___

Like I said, I understand where everyone is coming from.  I thought I'd throw in one more idea before closing this down.  Thanks :)

2017-05-01 14:26 UTC, kieraneglin commented
@rafaelfranca @matthewd Any thoughts on my recent proposal?  Or should I close this

2017-05-01 16:37 UTC, kaspth commented
@kieraneglin thanks but we'll be sticking with `assert_changes` which is already available and can solve the use case as @gsamokovarov suggested.

2017-05-01 16:37 UTC, closed without merging