Add type caster to `RuntimeReflection#alias_name`
rails/rails pull request #28961
Opened 2017-05-02 19:54 UTC by maclover7

### Summary

Since we have been using this `Arel::Table` since 111ccc832bc977b15af12c14e7ca078dad2d4373,
in order to properly handle queries, it's important that we properly type cast arguments.

### Other Information

Should fix #28959

2017-05-02 20:14 UTC, rafaelfranca requested changes

2017-05-02 20:14 UTC, rafaelfranca commented on activerecord/lib/active_record/reflection.rb
> +        Arel::Table.new(table_name, type_caster: TypeCaster::Map.new(klass))
Why not `klass.type_caster`?

2017-05-02 21:00 UTC, maclover7 commented on activerecord/lib/active_record/reflection.rb
> +        Arel::Table.new(table_name, type_caster: TypeCaster::Map.new(klass))
Sorry, I thought `type_caster` was a private method like the other Arel type methods. Updated my commit

2017-05-02 21:05 UTC, rafaelfranca commented on activerecord/test/models/book.rb
> -  has_many :authors
Do you need to change the association?

2017-05-02 21:10 UTC, maclover7 commented on activerecord/test/models/book.rb
> -  has_many :authors
The schema has the `_id` column on the `books` table, not `authors`, https://github.com/rails/rails/blob/master/activerecord/test/schema/schema.rb#L55-L61 versus https://github.com/rails/rails/blob/master/activerecord/test/schema/schema.rb#L91

2017-05-02 21:16 UTC, rafaelfranca approved these changes
Could you add a CHANGELOG entry?

2017-05-02 21:26 UTC, maclover7 commented
@rafaelfranca updated

2017-05-02 21:55 UTC, merged

2017-05-02 21:57 UTC, rafaelfranca commented
Backported in f644e7a6fd

2017-06-01 19:10 UTC, PelagicDev commented
Even after upgrading to Rails `5.1.1`, I'm still having this issue in my app.

```
# Model
class User < ApplicationRecord
  has_many :attendants, inverse_of: :user, dependent: :destroy
  has_many :event_joins, -> { where(attendee_status: [:joined, :checked_in]) }, class_name: 'Attendant'
  has_many :joined_events, through: :event_joins, source: :event
end
```
...and then when I try to find a user's event_joins like so, `user.event_joins`, I get the following error:

`ActiveRecord::StatementInvalid: ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "joined"`

...and the generated SQL is: 
`SELECT "users"."id" FROM "users" INNER JOIN "attendants" ON "users"."id" = "attendants"."user_id" WHERE "attendants"."event_id" = $1 AND "attendants"."attendee_status" IN ('joined', 'checked_in')`