[ci skip] explain async queue and rake tasks
rails/rails pull request #29020
Opened 2017-05-09 16:43 UTC by stevenchanin

[ci skip]
Small update to the guide for ActiveJob to point out a problem that might commonly occur in development when using the Async  Queue with rake tasks. Includes advice on how to solve it.

2017-05-09 22:34 UTC, maclover7 requested changes

2017-05-09 22:34 UTC, maclover7 commented on guides/source/active_job_basics.md
> +NOTE: Using the asynchronous queue from a rake task (for example, to
Can you capitalize all instances of Rake?

2017-05-09 22:34 UTC, maclover7 commented on guides/source/active_job_basics.md
> +`.deliver_now` or run a persistent queue in development as well.
✂️ `as well` ✂️

2017-05-09 23:12 UTC, matthewd commented
Can we/should we just fix this instead?

2017-05-10 00:22 UTC, stevenchanin commented
@maclover7 - done

2017-05-18 15:58 UTC, stevenchanin commented
@maclover7 -- do my changes look ok to you?

@matthewd -- I'm not sure how to go about fixing this. I think (?) it would involve modifying `rake` to not exit if there are still async threads running? If that's right, it sounds like a big change that would require a lot of discussion. In any case, since this is just a documentation modification, I think it would make sense to merge it. It can always be removed if an actual fix is agreed on & implemented. Thoughts?

2017-05-18 22:04 UTC, maclover7 commented
Going to merge as is -- better to get the docs fix in now :)

2017-05-18 22:04 UTC, maclover7 approved these changes

2017-05-18 22:04 UTC, merged