Fixed Frozen string error in actionpack
rails/rails pull request #29063
Opened 2017-05-12 18:48 UTC by sepehr500

Fixed string being modified in place during `encode` causing frozen string errors in Ruby 2.3.

2017-05-12 19:13 UTC, matthewd commented
It does seem like overreach for this class to mutate its parameter like that.

Can you add a test that shows the problem / ensures we don't regress in the future?

I think we might need a variation on this actual fix, too: it looks like the `force_encoding` below has the same risk. Perhaps we should `dup` the string around line 32 instead?

2017-05-12 21:09 UTC, sepehr500 commented
I will add some test. `dup` is also a good idea. I will give it a shot.

2017-05-12 21:25 UTC, sepehr500 commented
I will add some tests. Wouldn't we still be changing the string in place even in we did `dup`?

2017-05-12 21:35 UTC, sepehr500 commented
I can't find an alternative to `force_encoding` that returns a copy.

2017-05-13 06:26 UTC, matthewd commented
Yeah, as we're already having to `dup` for the `force_encoding`, we might as well remain consistent and use `encode!` to match, I think.

In-place mutation is fine once we're working with our own copy of the string.

2017-05-15 13:38 UTC, sepehr500 commented
I added a test and changed `encode` to use in-place mutation again.

2017-05-15 22:38 UTC, rafaelfranca requested changes

2017-05-15 22:38 UTC, rafaelfranca commented on actionpack/lib/action_dispatch/http/upload.rb
> +        if hash[:filename].nil?
Maybe:

```ruby
if hash[:filename]
  @original_filename = hash[:filename].dup

  begin
    @original_filename.encode!(Encoding::UTF_8)
  rescue EncodingError
    @original_filename.force_encoding(Encoding::UTF_8)
  end
else
  @original_filename = nil
end
```

and have only one conditional

2017-05-16 16:10 UTC, sepehr500 commented
I have made the requested change.

2017-05-16 17:31 UTC, rafaelfranca approved these changes

2017-05-17 19:04 UTC, merged

2017-05-17 19:08 UTC, rafaelfranca commented
Backported in 5405e3dcf5 and 68068acd2b