Respect `ignore_tables` in Postgres structure dump
rails/rails pull request #29060
Opened 2017-05-12 15:49 UTC by rustygeldmacher

When using `sql` as the schema format, or even just doing `rake
db:structure:dump`, it would be good to respect the list of ignored
tables that has been configured.

### Summary

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

If you are updating any of the CHANGELOG files or are asked to update the
CHANGELOG files by reviewers, please add the CHANGELOG entry at the top of the file.

Finally, if your pull request affects documentation or any non-code
changes, guidelines for those changes are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation)

Thanks for contributing to Rails!

2017-05-12 15:59 UTC, eileencodes requested changes
Added a question and a change requested by the linter.

2017-05-12 15:59 UTC, eileencodes commented on activerecord/test/cases/tasks/postgresql_rake_test.rb
> +any "cases/helper"
Why did this change?

2017-05-12 15:59 UTC, eileencodes commented on activerecord/lib/active_record/tasks/postgresql_database_tasks.rb
> +          args += ignore_tables.flat_map { |table| ['-T', table] }
Can you change this to use double quotes?

2017-05-12 16:01 UTC, rustygeldmacher commented on activerecord/test/cases/tasks/postgresql_rake_test.rb
> +any "cases/helper"
Whoops, typo. Thanks for catching.

2017-05-12 16:01 UTC, rustygeldmacher commented on activerecord/lib/active_record/tasks/postgresql_database_tasks.rb
> +          args += ignore_tables.flat_map { |table| ['-T', table] }
Will do!

2017-05-12 16:03 UTC, rustygeldmacher commented
@eileencodes  -- Made those changes, thanks!

2017-05-13 13:41 UTC, maclover7 commented
@rustygeldmacher Are any of the other database adapters affected by this? If so, would you be willing to make another PR to fix them as well?

2017-05-14 08:00 UTC, yawboakye commented
@rustygeldmacher Good stuff! @maclover7 there should be similar updates to the MySQL adapter. I'm not sure if it should be replicated in the SQLite3 adapter too. Here's the documentation for how to ignore tables in MySQL https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_ignore-table

2017-05-14 08:03 UTC, yawboakye commented
@rustygeldmacher Your changes have been included in https://github.com/rails/rails/pull/29077

2017-05-14 09:10 UTC, guilleiguaran commented
Closing this in favor of #29077.

@rustygeldmacher don't worry your changes will be included and you'll receive credits in the CHANGELOG and [Rails contributors app](http://contributors.rubyonrails.org/).

2017-05-14 09:10 UTC, closed without merging

2017-05-15 12:52 UTC, rustygeldmacher commented
Thanks @guilleiguaran -- looking forward to it being released!