Fix server-generated JS response processing on IE9
rails/rails pull request #29108
Opened 2017-05-16 10:58 UTC by inopinatus

### Summary

Fix for #29069, IE9's lack of `xhr.response`. With this in place, server-generated JS responses, Turbolinks redirects etc should now be executed by IE9 when given in response to a rails-ujs `remote: true` request.

### Other Information

This PR is not intended to make the rails-ujs test suite pass in IE9. That might be desirable, but it's more work than I could justify this week to nurse a dying browser. Tested with https://github.com/inopinatus/ujs-test-app instead.

1. Why not simply `xhr.response || xhr.responseText` in the call to `processResponse`? Because falsy values other than `null` are still valid response objects.
2. Why not a ternary operation like `xhrResponseObject = if xhr.response? then xhr.response else xhr.responseText`? I felt this way showed the intent more clearly.

2017-05-16 22:21 UTC, javan requested changes

2017-05-16 22:21 UTC, javan commented on actionview/app/assets/javascripts/rails-ujs/utils/ajax.coffee
> +    response = processResponse(xhrResponseObject, xhr.getResponseHeader('Content-Type'))
Think you can just do:
```coffee
response = processResponse(xhr.response ? xhr.responseText, xhr.getResponseHeader('Content-Type'))
```

2017-05-16 22:41 UTC, inopinatus commented on actionview/app/assets/javascripts/rails-ujs/utils/ajax.coffee
> +    response = processResponse(xhrResponseObject, xhr.getResponseHeader('Content-Type'))
If you're happy to drop type check, sure. That came from jQuery and appeared to be a workaround of other browser nasties, although I didn't dig too deep. Done.

2017-05-17 00:01 UTC, javan approved these changes

2017-05-28 15:15 UTC, merged

2017-05-28 15:16 UTC, kaspth commented
Thanks @inopinatus! 💪

@javan appreciate the help with the JS review too 😊