Ignore errors while loading db/structure into postgresql
rails/rails pull request #29110
Opened 2017-05-16 14:31 UTC by djcp

### Summary

This will allow the loading of db/structure.sql files with non-fatal
errors (like "set row security" or adding schema COMMENTs) to complete
without failure, similar to the behavior under rails < 5.

To use this, export IGNORE_PG_LOAD_ERRORS=1 when loading your
db/structure.sql, thusly:

    bundle exec rails IGNORE_PG_LOAD_ERRORS=1 db:structure:load

This is necessary because many rails developers work with postgres
connections that have superuser access, and the process of dumping
`structure.sql` will reflect that privilege level. This typically
happens on osx machines. This makes it hard to interoperate with
developers that use postgres connections that aren't configured as the
superuser - for instance, most default linux installs and most CI providers.

This isn't a perfect solution, but it allows us to at least function
similar to pre rails 5, where we'd do a "best effort" loading of the
structure. This generally worked OK.

### Other Information

RE: https://github.com/rails/rails/issues/29049

2017-05-16 14:46 UTC, djcp commented
On the codeclimate issues: I followed the indentation style throughout the codebase, I think.

2017-05-16 21:45 UTC, maclover7 commented
@djcp Is this something affecting other database adapters? If so, can we generalize the configuration option?

2017-05-16 22:09 UTC, djcp commented
@maclover7 I don't THINK so. It's specific to postgres, the app's permissions  and using the sql db structure format. 

We could perhaps name the ENV something more generic if it turns out to be a more generic problem. I'm not sure what makes sense here, though, as (AFAIK) it's only postgres that's effected.

* Do people use sql dump formats for mysql or other core databases?  (probably)
* MySQL permissions are just. . .different. I don't know enough about any features in MySQL that you'd only be able to restore via an sql schema dump.  If they exist, do they require admin privileges?  I have a feeling the set of users that use postgres are more likely to run into this issue than MySQL users, if it even exists.

2017-05-21 00:44 UTC, maclover7 commented
@djcp Ok, seems reasonable to keep to just Postgres for now.

Can you rebase, looks like there's a merge conflict with CHANGELOG.md.

2017-05-21 00:46 UTC, maclover7 requested changes
Left a few small comments about the CHANGELOG entry :)

2017-05-21 00:46 UTC, maclover7 commented on activerecord/CHANGELOG.md
> +*   Allow postgres errors to be ignored during the loading of db/structure.sql via the `IGNORE_PG_LOAD_ERRORS` ENV.
- `postgres` --> `PostgreSQL`
- can you wrap db/structure.sql in backticks
- can you add a comma after `.sql`

2017-05-22 14:33 UTC, djcp commented
@maclover7 Done. Thanks!

2017-05-24 23:22 UTC, maclover7 commented
@djcp Are you able to look at the CodeClimate failures, and then squash down to one commit?

2017-05-25 02:28 UTC, matthewd commented
We do not configure behaviour using environment variables.

2017-05-25 13:44 UTC, djcp commented
@matthewd Ok. What do you suggest, then?  It seems like there are plenty of examples where rake task behavior is changed via ENV, the most obvious being `RAILS_ENV`, but I'm happy to revisit this.

2017-05-25 13:47 UTC, djcp commented
@maclover7 on the codeclimate failures: it's complaining about the nesting of:
```
args = if ENV["IGNORE_PG_LOAD_ERRORS"]
  ["-v", "-q", "-f", filename]
else
  ["-v", ON_ERROR_STOP_1, "-q", "-f", filename]
end
```
but that's the style used through the codebase. I would generally format aligning the `else` and `end` with the `if`, but I was trying to be consistent.

2017-05-25 14:23 UTC, djcp commented
@maclover7 I pushed up an indentation fix, which should make codeclimate happy but doesn't appear to match the rest of the rails codebase for how assigning `if`s are formatted.

2017-05-28 18:17 UTC, warmwaffles commented
@djcp the Changelog has conflicts you need to resolve.

@maclover7 can your re-review this?

2017-05-30 14:36 UTC, djcp commented
@warmwaffles conflicts resolved, for now.

2017-06-13 20:47 UTC, djcp commented
@maclover7 Anything I can do to help move this forward?

2017-06-20 17:56 UTC, schneems commented
I think this is fine. Looks like all issues have been resolved. Any blockers?

2017-06-20 18:14 UTC, rafaelfranca commented on activerecord/lib/active_record/tasks/postgresql_database_tasks.rb
> +        args = if ENV["IGNORE_PG_LOAD_ERRORS"]
Like @matthewd said we don't use environment variables to change behavior. What about using the already existent configuration `structure_load_flags`
 https://github.com/rails/rails/blob/fe343dcae003022e4ae9d507e4e22afabf498b58/activerecord/lib/active_record/tasks/database_tasks.rb#L44?

As the default is `nil` we could check the value of those flags and only add `ON_ERROR_STOP_1` when it is `nil`. If that config is anything but `nil` we use the config.

2018-07-09 22:31 UTC, katyp commented
This would be a great addition to Rails; I have encountered this same error now with Rails 5.2 on CentOS. It would be great if it could become a priority to get it merged.

2019-09-08 11:24 UTC, dennyluan commented
Hello, I've come across this in Rails 5.1, and any Postgres newer than 9.6, dealing with CircleCI and brewed Postgres. Would be lovely to see this in an upcoming release soon.

2019-12-24 21:38 UTC, closed without merging