Add documentation to accessors in AbstractController::Base
rails/rails pull request #29134
Opened 2017-05-18 15:57 UTC by joshaidan

### Summary

Adds missing documentation to the three accessors in AbstractController::Base. Fixes #29084.

### Other Information

This is my first Rails patch.

2017-05-18 16:45 UTC, rafaelfranca requested changes
Great PR. Just a small comment about one requirement of our documentation guideline. Otherwise looks good.

2017-05-18 16:45 UTC, rafaelfranca commented on actionpack/lib/abstract_controller/base.rb
> +    # Returns the body of the HTTP response sent by the controller
mimsing `.` in the end of the lines.

2017-05-18 18:02 UTC, joshaidan commented
Thanks. I've added the missing punctuation. Let me know if there are any more changes I should make.

2017-05-18 21:48 UTC, maclover7 requested changes
One small comment, besides for that congrats on your first PR to Rails! :)

2017-05-18 21:48 UTC, maclover7 commented on actionpack/lib/abstract_controller/base.rb
> +    # Returns the formats processed by the controller.
Should this be "formats that can be processed by the controller"? IMHO the sentence is slightly ambiguous right now

2017-05-19 05:47 UTC, joshaidan commented on actionpack/lib/abstract_controller/base.rb
> +    # Returns the formats processed by the controller.
Yeah, I think you're right I'll update the PR. I was doing some testing and using the code @alexcameron89 suggested above to see when this accessor gets called and understand how it's used. At least when I try calling it from a controller, it doesn't seem to hit this accessor in AbstractController::Base. I think it hits the accessor in ActionView instead. When is this accessor for formats used?

2017-05-19 05:50 UTC, joshaidan commented
Updated the formats comment as per @maclover7.

2017-05-19 13:32 UTC, merged

2017-05-19 13:34 UTC, alexcameron89 commented
Thank you @joshaidan, and congratulations on your first PR contribution to Rails! 🎉