Update to Rails ujs readme
rails/rails pull request #29152
Opened 2017-05-19 21:24 UTC by djforth

### Summary

As Mentioned in #28992 An update to Rails ujs doc for user adding the rails-ujs through yarn/npm

2017-05-19 22:12 UTC, djforth commented
Confused why travis failed? I only updated a readme? Am I missing something?

2017-05-19 22:41 UTC, maclover7 requested changes
Left some small comments :)

2017-05-19 22:41 UTC, maclover7 commented on actionview/app/assets/javascripts/README.md
> +Add the following to your main js file.
`js` --> `JS`

2017-05-19 22:41 UTC, maclover7 commented on actionview/app/assets/javascripts/README.md
> +Usage with yarn/webpacker
`Usage with npm package` might be more general?

2017-05-22 08:06 UTC, djforth commented on actionview/app/assets/javascripts/README.md
> +Usage with yarn/webpacker
Sure will add, although thought it was important to mention yarn and webpacker as that's the recommended way now isn't it?.

2017-05-22 10:07 UTC, djforth commented on actionview/app/assets/javascripts/README.md
> +Usage with yarn/webpacker
Sorry I think I miss read it.  Can change it to  node_modules instead pf npm package, but do you think that may be confusing when you mention installing through Yarn previously in the readme?

I could update Installation using Yarn to include npm install instructions too then that might make it a little clearer maybe?

2017-05-24 23:26 UTC, maclover7 commented
@djforth Can you squash down to one commit

2017-05-26 09:51 UTC, djforth commented
Really sorry, something gone a bit crazy with my git when I try to rebase to squash the commits it tries to squash a whole bunch of commits that are nothing to do with me.  

I've tried tried everything else I can think off to fix it, but I think the best solution as the change is so small is to kill the pull request, re-fork then re-add the update then issue another pull request.  Unless you have any better solutions or rather I didn't do that?

2017-05-26 22:39 UTC, rafaelfranca commented
I merged manually at 51f912f1f3 and backported in d660b27e16. Thanks

2017-05-26 22:39 UTC, closed without merging

2017-05-28 19:35 UTC, djforth commented
Ok thanks