Allow skip_default_ids option to be set in form_with
rails/rails pull request #29439
Opened 2017-06-13 15:00 UTC by npezza93

Per https://github.com/rails/rails/commit/a6d065e39f9285119d75a05ee46c659f8b3c0db8, ids are not outputted by default in `form_with`.  Passing `skip_default_ids: false` will not set the option to false as it is currently overridden and forced to true within `form_with`. This change will allow ids to be outputted if `skip_default_ids: false` is passed.

2017-06-15 14:03 UTC, latortuga commented
Without the ability to set this to false, `form_with` doesn't really act like `form_for` and is not a replacement for it because labels do not automatically associate with fields. Interestingly enough, using `fields_for` inside of `form_with` results in correct behavior inside the `fields_for` block.

2017-06-15 21:08 UTC, rafaelfranca commented
I don't like the idea to make this option public. I'd prefer to always generates the ids, no matter what.

In my opinion not generating the ids is a bad default since you can't create labels that works automatically, neither Capybara tests can work when using the label text.

We already had to by pass this new default in the collection checkboxes and radio button because the labels needs to be correctly pointing to the inputs.

If we need to make possible to enable or disable ids I'd make at a configuration level. `form_with(model: @post, skip_default_ids: false)` doesn't looks like a great API for me.

cc @kaspth @dhh

2017-06-16 13:54 UTC, npezza93 commented
That works for me, @rafaelfranca!

2017-06-17 14:42 UTC, npezza93 commented
Hey @rafaelfranca, I think this is ready to go now. The only failing test seems to be an unrelated actioncable test. Let me know if there are any issues.

2017-06-19 19:03 UTC, rafaelfranca requested changes

2017-06-19 19:03 UTC, rafaelfranca commented on actionview/lib/action_view/helpers/tags/label.rb
>            def skip_default_ids?
Where this method is being used? It seems to not be used at all.

2017-06-19 19:03 UTC, rafaelfranca commented on railties/lib/rails/application/configuration.rb
> +            action_view.form_with_skip_default_ids = false
We need to keep it `true` since we are not going to change the current behavior in 5.1.

2017-06-19 19:03 UTC, rafaelfranca commented on railties/lib/rails/application/configuration.rb
> +            action_view.form_with_skip_default_ids = false
What do you think about `form_with_generates_ids` as the name?

2017-06-19 20:44 UTC, matthewd commented on railties/lib/rails/application/configuration.rb
> +            action_view.form_with_skip_default_ids = false
Aren't we? It was a conscious decision to skip them in 5.1 at the time, *but* if we're saying that change introduced a bug (and doesn't have any worse effect than making HTML slightly bulkier) ISTM we might reasonably backport the do-use-ids behaviour to fix the bug.

2017-06-19 20:49 UTC, rafaelfranca commented on railties/lib/rails/application/configuration.rb
> +            action_view.form_with_skip_default_ids = false
That is true. Let's change the default.

2017-06-19 21:24 UTC, npezza93 commented on actionview/lib/action_view/helpers/tags/label.rb
>            def skip_default_ids?
It is used on line 53 (https://github.com/rails/rails/pull/29439/files#diff-6f3573047e15b0e2eba56e404d6a03f5R53). It uses the id to make the `for` attribute. It is no longer needed though so I'll remove it.

2017-06-19 21:24 UTC, npezza93 commented on railties/lib/rails/application/configuration.rb
> +            action_view.form_with_skip_default_ids = false
Sounds good to me!

2017-06-19 21:24 UTC, npezza93 commented on railties/lib/rails/application/configuration.rb
> +            action_view.form_with_skip_default_ids = false
I like that a lot, makes it a little bit easier to read.

2017-06-19 21:27 UTC, npezza93 commented
I have made the requested changes. I also rebased it with master to keep it up to date so the newest commit with the changes starts at e7c0935.

2017-07-15 13:20 UTC, npezza93 commented
Hey @rafaelfranca, the build is now fixed and this should be ready to go now. Thanks!

2017-08-25 12:20 UTC, npezza93 commented
Hey @rafaelfranca, any idea when this might get merged in?

2017-10-14 14:37 UTC, npezza93 commented
Hey @rafaelfranca, any idea when this might get merged in? 😄

2017-11-22 04:20 UTC, bluz71 commented
Many of my Capybara tests fail when using `form_with` due to the missing `:id` between label text and form control as has already been noted above. I suspect quite a few of us are wanting to move to `form_with` but can't yet, not until this is merged.

I do hope this PR gets merged at some point.

2017-11-25 17:48 UTC, rafaelfranca commented
Merged in d3893ec

2017-11-25 17:48 UTC, closed without merging

2018-04-26 04:36 UTC, glaszig commented
in contrast to what the changelog suggests and this pr aimed to introduce (generate id by default again) **it does not do so** because of 21cd5b3 which was committed later. i had to explicitly set `config.action_view.form_with_generates_ids = true` to get this working. the default still is `false`.

> Change `form_with` to generates ids by default.
>
> When `form_with` was introduced we disabled the automatic generation of ids
> that was enabled in `form_for`. This usually is not an good idea since labels don't work
> when the input doesn't have an id and it made harder to test with Capybara.
>
> You can still disable the automatic generation of ids setting `config.action_view.form_with_generates_ids` to `false.`

2018-04-26 14:16 UTC, lcreid commented
It's also worth noting that in order to achieve proper formatting with Bootstrap 4, you don't wrap check boxes and radio buttons in their labels. Without the IDs, the labels are no longer clickable and the user has to click on the control itself, unless you use `config.action_view.form_with_generates_ids = true`.

2018-04-26 21:29 UTC, latortuga commented
Seems like the default should be reverted to true, given that it was the default in Rails 4.2 and 5.0. `form_with` was introduced in 5.1 and broke the automatic id functionality and should be viewed as an offender, not a default.

cc @rafaelfranca thoughts, since it was your commit that reverted the default?

2018-07-22 15:55 UTC, AlexVentura commented
@npezza93 is the `skip_default_ids: false` option possible to be used in `form_with`? Because I used it and my form does not get an autogenerated id.
```
<%= form_with(model: customer, local: true) do |form| %>
<% end %>

<form action="/customers" accept-charset="UTF-8" method="post">
</form>
```
No `id` attribute present in the html form element.

2018-07-31 16:00 UTC, AlexVentura commented
@kaspth Thank you, I see the point. So where it is supposed to set this configuration `config.action_view.form_with_generates_ids = true`? 
Does it goes in the `application.rb` file?

2018-07-31 16:18 UTC, latortuga commented
@AlexVentura `config.action_view.form_with_generates_ids = true`can be placed in any config block for Rails. Contrary to what @kaspth implied above, there is nothing special about the file `new_framework_defaults_5_2.rb`.

2018-07-31 16:52 UTC, AlexVentura commented
@latortuga Alright, so there's no problem to set it on the `application.rb` or any other initializer. Then, thinking about what @kaspth suggested, the `new_framework_defaults_5_2.rb` is a non existing file and it is supposed for anyone to create it right? And set it on the initializer folder, correct?

2018-07-31 17:07 UTC, latortuga commented
Rails will load all Ruby files in config/initializers/ when it starts up.
You can put your config in application.rb, any of the environment specific
config files, or you can add a new initializer or update an existing
initializer file.

On Tue, Jul 31, 2018, 11:55 AM Alejandro Ventura Contreras <
notifications@github.com> wrote:

> @latortuga <https://github.com/latortuga> Alright, so there's no problem
> to set it on the application.rb or any other initializer. Then, thinking
> about what @kaspth <https://github.com/kaspth> suggested, the
> new_framework_defaults_5_2.rb is a non existing file and it is supposed
> for anyone to create it right? And set it on the initializer folder,
> correct?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/rails/rails/pull/29439#issuecomment-409291405>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAAko-Ypl4t9--5l6MadNcHhDJ-0yxEOks5uMIvrgaJpZM4N4n28>
> .
>

2018-07-31 18:46 UTC, kaspth commented
@latortuga true, there's nothing special about `new_framework_defaults_5_2.rb` from a code perspective. But it's now an established convention that new framework defaults go in those initializers. And wouldn't you know it, look what's at the bottom here:

https://github.com/rails/rails/blob/ede8bc0c77016bb93b8a2957fdb941c3b2bb0e59/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults_5_2.rb.tt#L37-L38

@AlexVentura it's indeed true that you can place that config in any of the places @latortuga mentioned. I'd still recommend going with uncommenting the line in `new_framework_defaults_5_2.rb` because it's a) easier, b) we've documented with the new default does if you enable it, c) it's easier to see in pull requests that a new default is being enabled, some of which might be backwardsincompatible or require a more thorough review than the 1 line change suggests.

You don't have to create it yourself though, use `rails app:update`.

2018-08-01 14:40 UTC, AlexVentura commented
@kaspth Ok now it make sense. I didn't know about `new_framework_defaults_5_2.rb` file because it does not appear in my project even I'm working with **Rails 5.2.0** but now I got it. I need to update my Rails app with `rails app:update` inside my project folder, right @kaspth?

2018-08-01 15:07 UTC, matthewd commented
@AlexVentura yes. Please follow [the "Upgrading Ruby on Rails" guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) when you upgrade Ruby on Rails.

2018-08-02 18:49 UTC, kaspth commented
@AlexVentura yep! And Matthew already gave you the link. Thanks for upgrading, hope you like 5.2!