Update `working with javascript` readme to support rails-ujs behaviour.
rails/rails pull request #29442
Opened 2017-06-13 15:47 UTC by DmytroVasin

### Summary
Small addition to the Docs about current Rails-ujs event handlers.

As was discussed in the next stories - it would be good to have such description:

https://github.com/rails/rails/issues/29046
https://github.com/rails/rails/issues/29137

**Please Note:**
Stoppable event in rails-ujs does not work, so I did not add documentation about them.

[Stoppable Events](http://guides.rubyonrails.org/working_with_javascript_in_rails.html#stoppable-events)

Thanks.

2017-06-14 19:50 UTC, vipulnsward requested changes
Thanks for the changes!

I have added some grammar edits to be made.

2017-06-14 19:50 UTC, vipulnsward commented on guides/source/working_with_javascript_in_rails.md
> +In Rails 5.1 was introduced rails-ujs which drop jQuery as a dependency.
Rails 5.1 introduced rails-ujs and dropped jQuery as a dependency.

2017-06-14 19:50 UTC, vipulnsward commented on guides/source/working_with_javascript_in_rails.md
> +These introduction cause small changes into `custom events` fired during request:
`introductions`

2017-06-14 19:50 UTC, vipulnsward commented on guides/source/working_with_javascript_in_rails.md
> +These introduction cause small changes into `custom events` fired during request:
cause small changes to `custom events` fired during the request:

2017-06-14 19:50 UTC, vipulnsward commented on guides/source/working_with_javascript_in_rails.md
> +NOTE: Signature of calls to UJS’s event handlers has changed.
have changed

2017-06-14 19:50 UTC, vipulnsward commented on guides/source/working_with_javascript_in_rails.md
> +Unlike the version with jqeury-ujs, all custom events return only one parameter: `event`.
jquery

2017-06-14 19:50 UTC, vipulnsward commented on guides/source/working_with_javascript_in_rails.md
> +In this parameter there is an additional attribute `details` which contains an array of extra parameters.
comma after parameter

2017-06-14 19:50 UTC, vipulnsward commented on guides/source/working_with_javascript_in_rails.md
> +Example of usage:
Example usage:

2017-06-14 19:50 UTC, vipulnsward commented on guides/source/working_with_javascript_in_rails.md
> +  ref = event.detail, data = ref[0], status = ref[1], xhr = ref[2];
```javascript
var detail = event.detail; 
var data = detail[0], status = detail[1],  xhr = detail[2];
```

2017-06-15 07:12 UTC, DmytroVasin commented
@vipulnsward Done.

Thanks for corrections

2017-06-15 07:45 UTC, vipulnsward approved these changes

2017-06-15 07:45 UTC, merged

2017-06-15 07:46 UTC, vipulnsward commented
Thanks, we can polish it over. 

Please make sure to add [ci skip] in future for doc only changes.