Use bulk INSERT to insert fixtures
rails/rails pull request #29504
Opened 2017-06-20 03:00 UTC by kirs

This patch improves the performance of inserting fixtures from O(n) to O(1).
Previously it would require 50 queries to insert 50 fixtures. Now it takes only one query.

Disabled on sqlite which doesn't support multiple inserts.

Some benchmarks:

```
With two tables, each with 1k records. Time to insert fixtures on MySQL:
before: 0.7s
after: 0.2s
```

While 1k fixtures may sound unrealistic, at Shopify scale we have hundreds of tables, each having up to 100 fixtures. In our app this patch dramatically improved the performance of test helper. This patch would be especially helpful for those apps who use `fixtures(:all)` (I heard it's the case for Basecamp too).

🎉 🎉 🎉

Closes https://github.com/rails/rails/pull/26901

@rafaelfranca @matthewd

2017-06-20 03:02 UTC, kirs commented on activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb
> +        without_sql_mode('NO_AUTO_VALUE_ON_ZERO') { super }
In bulk insert, we rely on queries like `INSERT INTO users (id, name) VALUES (DEFAULT, 'David'), (DEFAULT, 'Rafael')`. This kind of query doesn't work with `NO_AUTO_VALUE_ON_ZERO` flag.

On MySQL adapter, we [enable](https://github.com/rails/rails/blob/87663ea14034a9a659a7dd617eb575df3fb9bb62/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L756) flag option by default. The solution is to temporary disable this flag to insert the fixtures.

2017-06-20 03:03 UTC, kirs commented on activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb
> +      def insert_fixtures(rows, table_name)
Fallback in Sqlite that doesn't support bulk inserts.

2017-06-20 15:25 UTC, rafaelfranca requested changes
This looks good to me. Could you pass rubocop on those files and add a CHANGELOG entry?

2017-06-20 17:22 UTC, kirs commented
Updated. Thanks for a quick review ❤️

2017-06-20 18:08 UTC, rafaelfranca approved these changes

2017-06-20 18:08 UTC, merged

2017-06-25 18:02 UTC, Envek commented
FYI, SQLite does support multi-row inserts since version 3.7.11 (released in 2012, see [changelog](http://sqlite.org/releaselog/3_7_11.html)), but in some CIs older versions are being used by default, so you need to upgrade SQLite first (like this: https://github.com/travis-ci/apt-package-whitelist/issues/368#issuecomment-198586476)

Maybe it worth adding a version check in implementation for SQLite?

2017-06-25 18:11 UTC, kirs commented
TIL. Thanks for the tip, I'll look into it!

On Jun 25, 2017 2:03 PM, "Andrey Novikov" <notifications@github.com> wrote:

> FYI, SQLite does support multi-row inserts since version 3.7.11 (released
> in 2012, see changelog <http://sqlite.org/releaselog/3_7_11.html>), but
> in some CIs older versions are being used by default, so you need to
> upgrade SQLite first (like this: travis-ci/apt-package-whitelist#368
> (comment)
> <https://github.com/travis-ci/apt-package-whitelist/issues/368#issuecomment-198586476>
> )
>
> Maybe it worth adding a version check in implementation for SQLite?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rails/rails/pull/29504#issuecomment-310917961>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAf3qxSnWtmDxfHJHs8jL7Dtso6tUB6zks5sHqDYgaJpZM4N_Byw>
> .
>

2017-06-30 22:01 UTC, kirs commented
@Envek  I just realized that there was another reason why I couldn't use SQLite for bulk insert.

As a placeholder for default values (those columns that were not specified in a fixture), we use `DEFAULT` keyword. For MySQL and Postgres the query looks like:

```
INSERT INTO people (id, name) VALUES (DEFAULT, "kir"), (DEFAULT, "alex");
```

I found that SQLite doesn't support `DEFAULT` placeholder per column value. It requires you to use either all defaults (`INSERT people DEFAULT VALUES`) either specify all values (`INSERT people VALUES ("value", "for", "every", "column")`).