Allow loading structure dumps from stdin
rails/rails pull request #29522
Opened 2017-06-21 21:41 UTC by mpapis

### Summary

When using large compressed file from production/staging
it allows loading from the compressed file directly.

Example:

    xz -dc dump.sql.xz | SCHEMA=- rake db:structure:load

2017-07-08 14:37 UTC, eileencodes requested changes
Changelog needs a fix but otherwise looks good to me 👍

2017-07-08 14:37 UTC, eileencodes commented on activerecord/CHANGELOG.md
> +
Can you fix the conflict in the CHANGELOG and also add your name here. Like this:

```
*   Allow loading database dumps from stdin with `-`.

    *Michal Papis*
```

2017-07-08 15:49 UTC, mpapis commented on activerecord/CHANGELOG.md
> +
rebased and updated :)

2017-07-08 20:43 UTC, mpapis commented on activerecord/CHANGELOG.md
> +
and had to update again... ;)

2017-07-08 20:57 UTC, matthewd commented
Where does/doesn't this work?

At a glance, `load('-')` seems unlikely to go well, as does the sqlite3 command... and I'm actually similarly doubtful of MySQL.

2017-07-09 23:17 UTC, mpapis commented
@matthewd you are right, I did check with `postgresql` and assumed it will work with all of them... it's not the case, I will update this PR with fixes for `sqlite` and `mysql`.

For your reference external programs are used:
- [mysql_database_tasks.rb](https://github.com/toptal/rails/blob/18e2c068bb8183d770eb86cc1fa910a6e5c4548d/activerecord/lib/active_record/tasks/mysql_database_tasks.rb#L74) - needs fixing
- [postgresql_database_tasks.rb](https://github.com/toptal/rails/blob/18e2c068bb8183d770eb86cc1fa910a6e5c4548d/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L81) - works already
- [sqlite_database_tasks.rb](https://github.com/toptal/rails/blob/18e2c068bb8183d770eb86cc1fa910a6e5c4548d/activerecord/lib/active_record/tasks/sqlite_database_tasks.rb#L53) - needs fixing

2018-02-06 23:05 UTC, mpapis commented
updated with working code for linux/osx, not sure about windows - is it a target in this command?

2018-02-06 23:17 UTC, mpapis commented
I'm also wondering if this should be documented in http://guides.rubyonrails.org/active_record_migrations.html#schema-dumping-and-you or somewhere else?

2018-02-15 08:50 UTC, mpapis commented
@matthewd fixed code and tests, there is one test failing unrelated to the change
@eileencodes the changelog is updated

2018-03-30 21:44 UTC, mpapis commented
anyone? is there anything else I need to do (except another rebase?

2018-08-21 22:48 UTC, mpapis commented
@matthewd or @eileencodes WDYT?

2019-02-21 16:40 UTC, seuros commented on activerecord/lib/active_record/tasks/mysql_database_tasks.rb
> +        run_cmd("(echo 'SET FOREIGN_KEY_CHECKS = 0;' ; cat #{filename} ; echo 'SET FOREIGN_KEY_CHECKS = 1;' ) | mysql", args, "loading")
This command won't work on windows.

2019-12-25 03:39 UTC, closed without merging