fixed no route matches favicon.ico for api projects welcome page. #29578
rails/rails pull request #29585
Opened 2017-06-27 08:58 UTC by davidrv

### Summary

When loading the welcome page after creating a new rails --api project it appears an error on the rails console:

`ActionController::RoutingError (No route matches [GET] "/favicon.ico")`

This PR fixes the error by stopping removing the favicon.ico file from the public folder when generating new rails --api projects.

You can also read the issue here: https://github.com/rails/rails/issues/29578

### Other Information

/railties/changelog.md updated:

*   Stop removing favicon.ico file when generating a new --api project.

    Fixes #29578.

    *David Ramirez*

2017-06-27 16:25 UTC, rafaelfranca requested changes
Instead of keeping the favicon in the applications. let's add the favicon to inside the framework and use it in the welcome page. That way how the application is organized doesn't change the framework behavior.

2017-06-27 16:45 UTC, davidrv commented
Sorry but I don't understand you... Does it make sense having different approaches for 'api' projects and 'non-api' ones regarding the favicon? Do you mean having for both the favicon at the same place inside the framework instead of generating it into the `public` folder? And, what does 'inside' the framework exactly mean? Thanks

2017-06-27 17:53 UTC, rafaelfranca commented
> Sorry but I don't understand you... Does it make sense having different approaches for 'api' projects and 'non-api' ones regarding the favicon?

Yes. API projects don't need favicon. For non-API projects we generate the favicon as an example so people can change it to their application.

> Do you mean having for both the favicon at the same place inside the framework instead of generating it into the public folder?

No. We still need to generate the example favicon for non-API projects, but the favicon in the public folder should not affect how the internal welcome page behaves. Let say you change the favicon in the public folder to the Django favicon the rails welcome page should still show the rails favicon.

> And, what does 'inside' the framework exactly mean?

Inside the framework means probably adding a new action in this controller for the favicon and rendering a template with its content https://github.com/rails/rails/blob/master/railties/lib/rails/welcome_controller.rb#L7.

2019-12-25 06:38 UTC, closed without merging

2020-02-14 17:53 UTC, btir commented
Hi @davidrv 
Is there any news about this pull request? Is there any chance to finish it?
thanks and sorry to ping