ActiveRecord: do not create "has many through" records that have been removed
rails/rails pull request #29593
Opened 2017-06-27 16:18 UTC by kratob

### Summary

If a record was built on a HasManyThroughAssociation, then removed, and
then the record was saved, the removed record would be created anyways.

Code would look like this:

```
class Post
  #...
  has_many_people through: :readers
end

post = Post.new
post.people.build(first_name: "Bob")
ted = post.people.build(first_name: "Ted")
post.people.delete(ted)
# post.people now expectedly contains only 'Bob'

post.save!
post.reload
# post.people now unexpectedly contains 'Bob' and 'Ted'
```

This happens because records and not removed from the hidden "through association" on the join table, in the case of unpersisted child records.

The fix is to remove this records from the "through association".

2017-06-27 17:35 UTC, rafaelfranca requested changes
Can you add a CHANGLOG entry?

2017-06-27 17:35 UTC, rafaelfranca commented on activerecord/test/cases/associations/has_many_through_associations_test.rb
> +    assert_equal ['Bob'], post.people.collect(&:first_name)
Could you use double quotes here?

2017-06-28 08:54 UTC, kratob commented
Done.

2017-06-28 11:35 UTC, eileencodes requested changes
Looks good, I requested a change to the change log.

2017-06-28 11:35 UTC, eileencodes commented on activerecord/CHANGELOG.md
> +    *Tobias Kraze*
`has_many_through` should be `has_many :through`. I also think the sentence is a little bit of a run on and would read clearer as:

> Previously when building records using a `has_many :through` association, if the child records were deleted before the parent was saved they would be persisted. Now if child records are deleted before the parent is saved on a `has_many :through` association the child records will now be deleted.

2017-06-28 12:16 UTC, kratob commented
I've updated the change log with a slight modification to your proposal. I changed "will be deleted" to "will not be persisted", as those records had never been persisted in the first place.

2017-06-28 12:20 UTC, eileencodes approved these changes

2017-06-28 12:20 UTC, merged

2017-06-28 12:21 UTC, eileencodes commented
Thanks for working on this @kratob!