Updates doc for ActionCable redis adapter
rails/rails pull request #29633
Opened 2017-06-29 19:52 UTC by padi

### Summary

Make it painfully obvious that you can pass a [redis url](https://www.iana.org/assignments/uri-schemes/prov/redis) a username, password etc. into the redis `:url` so that we won't see people stumbling [like this] again.

2017-06-30 03:38 UTC, Erol requested changes

2017-06-30 03:38 UTC, Erol commented on guides/source/action_cable_overview.md
> +  url: redis://user:secret@localhost:6381/12?foo=bar&qux=baz
Redis isn't supposed to receive a username at the moment. AUTH only accepts a password.

2017-06-30 06:45 UTC, padi commented on guides/source/action_cable_overview.md
> +  url: redis://user:secret@localhost:6381/12?foo=bar&qux=baz
Ah yes, you're right. While a multi-user feature is in the works, we're not quite there yet.

2017-06-30 07:13 UTC, Erol commented on guides/source/action_cable_overview.md
> +  url: redis://user:secret@localhost:6381/12?foo=bar&qux=baz
It may or may not happen. AFAIK there was only a draft proposal for multiple users and ACLs a few years ago.

2017-06-30 17:43 UTC, rafaelfranca commented on guides/source/action_cable_overview.md
> +  url: redis://:secret@localhost:6381/12?foo=bar&qux=baz
Better to only use real options.

2017-07-01 18:01 UTC, padi commented
@rafaelfranca not sure what you meant but I removed the localhost and the fake parameters.

2017-07-01 22:54 UTC, Erol commented
@padi I'm guessing @rafaelfranca meant the fake parameters.

2017-07-06 15:32 UTC, padi commented
That's what I though too. Removed that. 👍

2019-12-25 07:39 UTC, closed without merging