Update the working_with_javascript_in_rails guide page to use the new UJS arguments
rails/rails pull request #29703
Opened 2017-07-06 21:27 UTC by Empact

This removes the listing of the historical argument pattern and updates an example to use the
new argument patter of rails-ujs.

The new docs were added in 0cd957ef453d31218eb99c0149589814cc7ef685. Am I right in thinking the old ones are defunct?

2017-07-06 21:28 UTC, Empact commented
cc @DmytroVasin @robin850

2017-07-07 08:11 UTC, DmytroVasin commented
I am not sure if it is correct to remove jquery-ujs documentation. Because people still can use jquery-ujs.

Also documentation about beforeSent is only valid for jquery-ujs, because `return false` in rails-ujs beforeSend callback does not work now. 
So keeping documentation about beforeSent is not right without rails-ujs documentation.

I already did PR about that but did not get any response: https://github.com/rails/rails/pull/29127

Please correct me if I miss something.

2017-07-22 14:55 UTC, bananaappletw commented
I met the same problem.
I struggled a while of time to find out what is `rails-ujs`.
And found out `rails-ujs` != `jquery-ujs`
The details of how rails-ujs` deal with ajax request is different than `jquery-ujs` do.
Obviously not correspond with document says. 
Agree with documentation update.
But I think `rails-ujs` maybe did something wrong about its event format.
It's hard to use its format.
Such as 'ajax:error', function(event)
Only event parameter is given.
`event.detail[2].status` is its status code.

2017-07-23 07:55 UTC, bananaappletw requested changes
Some suggestions.
e => event
[data, status, xhr] = event.detail
e.detail[2].responseText => xhr.responseText
For better readability

2017-10-22 13:13 UTC, guilleiguaran commented on guides/source/working_with_javascript_in_rails.md
>  ```
IMHO, this looks better:

```coffeescript
$("#new_article").on("ajax:success", (e) ->
  [data, status, xhr] = event.detail
  $("#new_article").append xhr.responseText
)
```

2017-10-22 13:14 UTC, guilleiguaran commented on guides/source/working_with_javascript_in_rails.md
> -
Why was this whole section removed??

2017-10-22 13:24 UTC, bananaappletw commented on guides/source/working_with_javascript_in_rails.md
>  ```
e => event

2017-10-22 13:25 UTC, bananaappletw commented on guides/source/working_with_javascript_in_rails.md
> -
This is old way

2019-07-09 06:48 UTC, lachlanjc commented
It’s been 2 years with no updates here, I think this can be closed?

2019-07-10 02:22 UTC, closed without merging