Update rack-test dependency constraint
rails/rails pull request #29859
Opened 2017-07-19 23:08 UTC by dwightwatson

### Summary

This updates the dependency constraint for `rack-test` in `actionpack`. `rack-test` is the only gem that appears as outdated when running `bundle outdated` on a fresh installation of Rails.

I've checked the changelog for `rack-test` and it doesn't appear to have breaking changes, and the `actionpack` tests passed locally for me after the change.

### Other Information

This is my first Rails PR so I hope I'm doing it right - wasn't sure whether I should commit the updated `Gemfile.lock` as well or if I needed to update the changelog. Happy to be pointed in the right direction for any changes.

2017-07-21 21:57 UTC, rafaelfranca requested changes

2017-07-21 21:57 UTC, rafaelfranca commented on actionpack/actionpack.gemspec
> +  s.add_dependency "rack-test", "~> 0.7.0"
Is there any reason to disallow 0.6.3? If not this should be `s.add_dependency "rack-test", ">= 0.6.3"`

2017-07-21 23:19 UTC, dwightwatson commented on actionpack/actionpack.gemspec
> +  s.add_dependency "rack-test", "~> 0.7.0"
Nope, that's fair - updated. Thank you.

2017-07-24 05:05 UTC, rafaelfranca commented
Cloud you squash your commits?

2017-07-24 05:10 UTC, dwightwatson commented
Of course, done.

2017-07-24 20:49 UTC, merged

2017-08-04 13:24 UTC, mvz commented
This is not part of 5.1.3 😞

2017-08-04 17:21 UTC, rafaelfranca commented
@mvz why do you need it in 5.1? Is there anything in rack-test that require us to backport?

2017-08-05 08:04 UTC, mvz commented
@rafaelfranca only for the reason given for this PR:

>  rack-test is the only gem that appears as outdated when running bundle outdated on a fresh installation of Rails.

2017-08-08 17:32 UTC, rafaelfranca commented
Done

2017-08-09 06:46 UTC, mvz commented
Awesome, thanks!

2017-09-18 10:44 UTC, morgoth commented
This caused regression in new release https://github.com/rails/rails/issues/30570 because of https://github.com/rack-test/rack-test/issues/200