Integration session: Set CONTENT_TYPE only if available
rails/rails pull request #29895
Opened 2017-07-23 13:16 UTC by buehmann

By default an integration session puts a `CONTENT_TYPE` of `nil` into the request environment, which violates the Rack protocol:

> The CGI keys (named without a period) must have String values.
http://www.rubydoc.info/github/rack/rack/master/file/SPEC#The_Environment

The bug can be demonstrated like this:
```ruby
require "action_controller"

app = ->(env) { [200, {}, []] }
lint = Rack::Lint.new(app)

session = ActionDispatch::Integration::Session.new(lint)
session.get '/'
```
```
env variable CONTENT_TYPE has non-string value nil (Rack::Lint::LintError)
```
This made one of our middlewares (which proxies some requests to other apps) crash during tests.
First noticed with Rails 5.0.4; same in master (8ee9ace27b79a1e8d82e9e9482966781686d4851).

I am not quite sure where to add a test for this.

2017-07-24 22:01 UTC, rafaelfranca requested changes
You can add a test in https://github.com/rails/rails/blob/master/actionpack/test/controller/integration_test.rb

2017-07-24 22:01 UTC, rafaelfranca commented on actionpack/lib/action_dispatch/testing/integration.rb
> +        request_env["CONTENT_TYPE"] = content_type if content_type.present?
I think `if content_type` is sufficient here.

2017-07-25 09:17 UTC, buehmann commented on actionpack/lib/action_dispatch/testing/integration.rb
> +        request_env["CONTENT_TYPE"] = content_type if content_type.present?
Right, changed.

2017-07-28 14:35 UTC, buehmann commented
Looks like there were some networking errors during the Travis run.

2019-12-24 22:38 UTC, closed without merging