Stop creating ApplicationRecord on model generation
rails/rails pull request #29916
Opened 2017-07-24 18:36 UTC by lugray

Fixes #29407.

### Summary
When generating models, we created ApplicationRecord in the default location if no file existed there.  That was annoying for people who moved it to somewhere else in the autoload path.  At this point, the vast majority of apps should have either run the upgrade script or generated a model since upgrading.  For those that haven't the error message after generating a new model should be helpful:
```
NameError: uninitialized constant ApplicationRecord
```

### Other Information
To ease friction in that case, this also adds a generator for ApplicationRecord.

2017-07-24 18:43 UTC, rafaelfranca requested changes
This change will need a CHANGELOG entry

2017-07-24 18:43 UTC, rafaelfranca commented on activerecord/lib/rails/generators/active_record/application_record/application_record_generator.rb
> +require "rails/generators/active_record"
Missing frozen string literal comment

2017-07-24 20:03 UTC, lugray commented
Updated.

2017-07-25 01:12 UTC, rafaelfranca approved these changes

2017-07-25 11:51 UTC, merged

2017-07-25 11:51 UTC, eileencodes commented
Thanks @lugray! And also thank you for writing an excellent commit message 😸