Add a method to determine if query parameters are parsable
rails/rails pull request #29948
Opened 2017-07-25 21:21 UTC by xtina-starr

Addresses: https://github.com/rails/rails/issues/29947

Adding `#params_readable` is the proposed fix for addressing malformed query params that are unable to be parsed. We could use this method in the [request and response template](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb#L9) so the `DebugExceptions` middleware can avoid raising an exception if it's not parsable.

2017-07-31 20:59 UTC, yuki24 commented
I'm helping @xtina-starr fix a bug and contribute to Rails. We need this interface to fix https://github.com/rails/rails/issues/29947 properly and we are blocked by this PR being standing out for a long time. Could anyone have a quick look at this PR? https://github.com/rails/rails/issues/29947 is a real bug that completely kills the `DebugExceptions` middleware and is making debugging a lot harder.

2017-07-31 21:08 UTC, rafaelfranca commented
Thank you for the pull request but I don't think we should add a method to the public API just to fix a problem in the development environment. If #29947 is the problem we should rescue that exception inside the view.

2017-07-31 22:05 UTC, yuki24 commented
There are at least five places in Rails source code that need to check if params are readable, one of which is actual logic:

 * [`actionpack/lib/action_dispatch/http/mime_negotiation.rb:65`](https://github.com/rails/rails/blob/dfcc766/actionpack/lib/action_dispatch/http/mime_negotiation.rb#L63-L67)
 * [`actionpack/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb:4`](https://github.com/rails/rails/blob/59dbf68/actionpack/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb#L2)
 * [`actionpack/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb:4`](https://github.com/rails/rails/blob/59dbf68/actionpack/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb#L4)
 * [`actionpack/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb:9`](https://github.com/rails/rails/blob/083f657/actionpack/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb#L9)
 * [`actionpack/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb:2`](https://github.com/rails/rails/blob/a725a45/actionpack/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb#L2)

I'm not sure if it's a good idea to add rescue blocks to all these files. In addition to that, we do need to use that method in our rack middleware (inside [rack-attack](https://github.com/kickstarter/rack-attack/blob/8936cc647ac2d310b3cb49fc50fac87486795aff/examples/rack_attack.rb#L15) that often involves parameter checks). Right now we just `rescue ActionDispatch::ParamsParser::ParseError`. We use `ActionDispatch::Request` whenever possible because `Rack::Request` lacks a lot of useful methods, and being able to use `#params_readable` would make it easier to properly block brute force attacks rather than allowing them to trigger a lot of exceptions.

2017-08-01 04:02 UTC, rafaelfranca requested changes
Thank @yuki24, that makes sense. Let's move forward and implement this method. I made some comments about the implementation.

2017-08-01 04:02 UTC, rafaelfranca commented on actionpack/lib/action_dispatch/http/parameters.rb
> +        !!parameters
We avoid to write synthetic code just to return the singleton `true` or `false` so we don't need the `!!` here.

2017-08-01 04:02 UTC, rafaelfranca commented on actionpack/test/dispatch/request_test.rb
> +    assert request.params_readable?
`assert_predicate`

2017-08-01 04:02 UTC, rafaelfranca commented on actionpack/test/dispatch/request_test.rb
> +    assert_not request.params_readable?
`assert_not_predicate`

2017-08-01 19:15 UTC, yuki24 commented on actionpack/test/dispatch/request_test.rb
> +    assert request.params_readable?
Good catch, thanks 👍

2017-08-01 19:15 UTC, yuki24 commented on actionpack/test/dispatch/request_test.rb
> +    assert_not request.params_readable?
👍

2017-08-01 19:15 UTC, yuki24 commented on actionpack/lib/action_dispatch/http/parameters.rb
> +        !!parameters
Oh right, I recall the really long discussion about the double `!` operator... We will change that to just `parameters`.

(Although I personally don't think it's a good thing to keep doing)

c/ @xtina-starr

2017-08-01 21:06 UTC, xtina-starr commented
@rafaelfranca we've made your recommended changes. Let us know if there is any other feedback.

2017-08-01 21:25 UTC, rafaelfranca commented
Sounds, good. Can you also change the places that could use it to use it?

2017-08-02 12:08 UTC, matthewd commented
Hmm.. I'm still unconvinced it's useful to expose a method `x?` that just returns whether `x` will raise... especially if it determines that by calling `x` with a rescue. I'll hold final judgement for the full diff, but I'm curious to see how

```
if params_readable?
  use_these(parameters)
else
  something_else
end
```

reads usefully better than

```
begin
  use_these(parameters)
rescue BadRequest
  something_else
end
```

2017-08-03 21:31 UTC, yuki24 commented
If you have multiple checks then suddenly the code looks a lot more verbose:

#### With `#params_readable?`:

```ruby
v = if params_readable? && parameters.has_key?(:format)
   ...
elsif use_accept_header && valid_accept_header
  ...
end
```

#### Without:

```ruby
params_readable = begin
                    parameters[:format]
                  rescue ActionController::BadRequest
                    false
                  end

v = if params_readable
   ...
elsif use_accept_header && valid_accept_header
  ...
end
```

2017-12-29 20:54 UTC, yuki24 commented
https://github.com/rails/rails/issues/29947 is still present and I would like it fixed before 5.2 is out. I made an example commit https://github.com/rails/rails/commit/4c12b27630a79b238bdaa1bd406e86127b5fa1b0 to demonstrate how the `#params_readable` method could keep things cleaner. I also have sent https://github.com/rails/rails/pull/31594 to make it easier to get this PR merged in.

One tricky thing though is how we could backport this to 5.1 and 5.0. If a fix for #29947 depends on a new API, that would make it difficult to backport because backport commits should purely be bug fixes. Perhaps we should fix the bug first (though catching an exception in erb could be tricky) and merge this PR only to master as a refactor PR.

2019-05-08 10:51 UTC, kamipo commented
Closing in favor of #36196.

2019-05-08 10:51 UTC, closed without merging