Improved style guide conformation and removed trivialising language
rails/rails pull request #29962
Opened 2017-07-26 20:54 UTC by EmmaB

### Summary

Tidies up grammar, so that it conforms more closely to the style guide. Also removes terms such as "simply", "very easy", "painfully simple", and "just", which can be off-putting to both new and seasoned developers, who wouldn't be reading the Guide if it was "simple"!

2017-07-26 21:21 UTC, rafaelfranca requested changes

2017-07-26 21:21 UTC, rafaelfranca commented on guides/source/action_mailer_basics.md
> +Action Mailer 3.0 enables inline attachments.
We can remove the version here since it is not relevant anymore

2017-07-26 21:21 UTC, rafaelfranca commented on guides/source/action_mailer_basics.md
> +Note: As of July 15, 2014, Google increased [its security measures](https://support.google.com/accounts/answer/6010255) and now blocks attempts from apps it deems  insecure.
there is a extra space before insecure.

2017-07-26 21:32 UTC, EmmaB commented on guides/source/action_mailer_basics.md
> +Action Mailer 3.0 enables inline attachments.
Thanks, change committed!

2017-07-26 21:33 UTC, EmmaB commented on guides/source/action_mailer_basics.md
> +Note: As of July 15, 2014, Google increased [its security measures](https://support.google.com/accounts/answer/6010255) and now blocks attempts from apps it deems  insecure.
Thanks, change committed!

2017-07-26 21:33 UTC, rafaelfranca requested changes
Awesome work on this! Could you squash your commits in only one?

2017-07-26 22:01 UTC, EmmaB commented
Commits duly squashed, with thanks.

2017-09-24 09:48 UTC, EmmaB commented
Hello, can this PR be merged now? I've resolved a recent conflict.

2019-04-11 14:59 UTC, closed without merging