Set Ruby version in Gemfile and .ruby-version by default
rails/rails pull request #30016
Opened 2017-07-31 17:34 UTC by albertoalmagro

### Summary

This pull request sets current Ruby version in the Gemfile and .ruby-version by default.

When running `rails new my-app` the generated application will include by default:
* A `.ruby-version` file, containing the default Ruby version.
* An entry in the `Gemfile`, with the format `ruby '2.x.x'` with the same default Ruby version.

### Implications
Among other usages:
* `.ruby-version` will help ruby version manager tools such as `rbenv` to determine which Ruby version should be used for the current Rails project.
* The entry `ruby 'version'` in the `Gemfile` may be used by deployment tools (i.e. Heroku) to determine the Ruby version that should be used to run Rails.

2017-07-31 17:45 UTC, rafaelfranca requested changes

2017-07-31 17:45 UTC, rafaelfranca commented on railties/lib/rails/generators/rails/app/templates/Gemfile
> +ruby <%= "'#{RUBY_VERSION}'" %>
Could you put this after the `git_source` entry?

2017-07-31 17:53 UTC, albertoalmagro commented
@rafaelfranca Done. As it was a minor change I have already squashed commits. In case requested changes implied more lines, would you prefer first to review the changes? After it is done I would proceed squashing commits.

2017-07-31 17:54 UTC, rafaelfranca approved these changes
That is great! Could you add a CHANGELOG entry too and squash the commits?

2017-07-31 18:07 UTC, albertoalmagro commented
Done. @rafaelfranca

2017-07-31 18:18 UTC, guilleiguaran approved these changes
Looking good, waiting for CI to merge 😊

2017-07-31 18:52 UTC, deivid-rodriguez commented on railties/lib/rails/generators/rails/app/templates/Gemfile
> +ruby <%= "'#{RUBY_VERSION}'" %>
What about using `ruby RUBY_VERSION` here? Seems a bit DRYer.

2017-07-31 18:54 UTC, deivid-rodriguez commented on railties/lib/rails/generators/rails/app/templates/Gemfile
> +ruby <%= "'#{RUBY_VERSION}'" %>
I use this "trick", but I haven't tried it with `heroku`, so maybe it doesn't work well, not sure.

2017-07-31 19:04 UTC, merged

2017-07-31 19:20 UTC, albertoalmagro commented on railties/lib/rails/generators/rails/app/templates/Gemfile
> +ruby <%= "'#{RUBY_VERSION}'" %>
Thanks @deivid-rodriguez , I already tried that and generating the app with `bundle exec rails new ~/my-test-app --dev` caused the following error parsing the Gemfile:

```
[!] There was an error parsing `Gemfile`: unexpected fraction part after numeric literal - ruby 2.3.1
        ^
/Users/alberto.almagro/my-test-app/Gemfile:3: syntax error, unexpected tIDENTIFIER, expecting end-of-input
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
          ^. Bundler cannot continue.

 #  from /Users/alberto.almagro/my-test-app/Gemfile:2
 #  -------------------------------------------
 #  source 'https://rubygems.org'
 >  ruby 2.3.1
 #  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
 #  -------------------------------------------
```
I've surrounded it with single quotes, which is what is used in the line above for the source.

2017-08-09 11:28 UTC, greysteil commented
Nice! Would you be up for reading the Ruby version out of the `.ruby_version` file, rather than having it duplicated? For example, like the [ossfirday Gemfile](https://github.com/ossfriday/ossfriday/blob/master/Gemfile) does? I've seen applications get out-of-sync before...

Happy to put in a PR if so.

2017-08-09 11:33 UTC, deivid-rodriguez commented on railties/lib/rails/generators/rails/app/templates/Gemfile
> +ruby <%= "'#{RUBY_VERSION}'" %>
Sorry @albertoalmagro, totally forgot to answer this. What I meant is not to generate `ruby 2.3.1` without quotes, but to generate `ruby RUBY_VERSION`, which I think would be generated by using `ruby RUBY_VERSION` (wihout `<%=`, `%>` block).

2017-08-09 11:35 UTC, deivid-rodriguez commented
@greysteil What about `ruby RUBY_VERSION`? Is it something discouraged or not behaving as expected in some cases?

2017-08-09 12:04 UTC, greysteil commented
@deivid-rodriguez interesting. It makes an assumption about the Ruby manager respecting the `.ruby-version` file, but that should basically always be the case. Just tested on Heroku and it works there, too - I'd be 👍  on that change. @albertoalmagro - any thoughts?

2017-08-09 12:12 UTC, greysteil commented
I suppose one minor objection to the environment variable approach would be that it's less explicit where the Ruby version is being set. Might cause confusion, particularly for a newer developer? And if the `.ruby-version` file was deleted it would be left as a confusing remnant, rather than erroring.

2017-08-09 13:01 UTC, robin850 commented
ISTM that having `ruby RUBY_VERSION` isn't really useful.

Locally, hard-coding the Ruby version inside the Gemfile prevents it from resolving if someone is trying to `bundle install` with the wrong version but `ruby RUBY_VERSION` will always resolve.

As for Heroku, the `ruby` call inside the Gemfile allows Heroku to automatically pick the specified version. It ensures that people have a similar set-up between their local environment and the production one.

2017-08-09 13:08 UTC, greysteil commented
It should be useful - `RUBY_VERSION` will be set to whatever is in `.ruby-version`, but having a `ruby ...` line in the Gemfile still gives us the behaviour we want from Bundler and on Heroku. So we get equivalent behaviour, but without the hardcoding.

Given the confusion, I'm still not sure that's clear enough, though - I think I prefer reading the `.ruby-version` file explicitly in the Gemfile...

2017-08-09 13:11 UTC, greysteil commented
I'll create a new PR so we're not spamming poor @albertoalmagro. This is still a rad contribution though - nice one @albertoalmagro.

2017-08-09 13:31 UTC, albertoalmagro commented
Nice one @greysteil . Opportunities to learn something new and fresh ideas are never spam ;)

2017-08-09 14:47 UTC, greysteil commented on railties/lib/rails/generators/rails/app/templates/Gemfile
> +ruby <%= "'#{RUBY_VERSION}'" %>
@schneems - I can't see how that would happen, as long as the `.ruby_version` is committed. Am I missing something?

2017-08-09 15:23 UTC, robin850 commented
> RUBY_VERSION will be set to whatever is in .ruby-version before Bundler evaluates the Gemfile

Not everybody uses a Ruby version manager.

2017-08-09 15:54 UTC, schneems commented
I use chruby which does not use the .ruby-version file

2017-08-09 21:30 UTC, schneems commented
I reverted the change https://github.com/rails/rails/commit/a8f59044fb18ce718367ffe4cd3ec0259c766b5f.

The good news is you get to keep your contributor points for contributors.rubyonrails.org !! Reverts don't actually remove a commit, it adds an extra "undo" commit that changes back all your changes.

Thanks for the PR, sorry I wasn't paying more attention before. It's always better to have people involved earlier than later. I appreciate all the effort that went into making this.

2017-08-09 21:48 UTC, albertoalmagro commented
@schneems Lets get more on my next PR, which is already in CR. The most important thing is to make Rails better, thanks.

2017-08-09 22:34 UTC, dhh commented
I think we've crossed wires here a bit. Given that I originally requested this feature, perhaps I was unclear with the rational. I'm fine with the fact that the version is duplicated between .ruby-version and Gemfile. Just as long as they're set by default.

If at some point rbenv learns to read the version from a Gemfile, then we can drop the .ruby-version. But until that I'd like that to stay.

2017-08-09 22:37 UTC, dhh commented
Setting the Ruby version in the Gemfile just raises an exception if it doesn't match. You still need to ensure that the correct Ruby version is actually running, which is what .ruby-version supplies for rbenv and rvm.

2017-08-09 22:39 UTC, dhh commented
I reverted the revert. Sorry for the confusion! Happy to drop .ruby-version if the day should come that rbenv and rvm support parsing the Gemfile to get the Ruby version. But it seems uncertainty whether, and if so, when that would happen. In the mean time this will do.

2017-08-09 22:53 UTC, schneems commented
Ahh, yes. Sorry. I made the mistake here.

2018-03-21 09:31 UTC, n-rodriguez commented
@dhh rvm already support Ruby version detection through Gemfile : https://rvm.io/workflow/projects#supported-files

2018-04-19 21:00 UTC, headius commented
.ruby-version does not work the same way with JRuby and has led to #32639. It needs to be engine-engine_version to correctly be able to switch to JRuby.

I would strongly advocate *against* using .ruby-version, however, since we have many users on JRuby that use both JRuby and CRuby interchangeably for local development.

2018-04-19 21:06 UTC, rafaelfranca commented
Those users can remove the file, if they want. I don't think we should avoid using a good feature that make sure everyone in the same project is using the same version of Ruby that works in 80% of the cases just because it doesn't work for 20%.

2018-04-19 21:16 UTC, guilleiguaran commented
This .ruby_version is compatible with both CRuby and JRuby: https://github.com/rails/rails/pull/32649

2018-04-19 22:05 UTC, headius commented
@rafaelfranca Fair enough...we'll see if anyone cares.

2018-04-19 22:10 UTC, rafaelfranca commented
I mean, we should fix, with Guillermo PR, I don't think JRuby should be broken by default. I just think that the cases where you need to have different implementations, which is not common, should be handled differently.

One could say that if people want to use JRuby and CRuby for local development they can use `rbenv shell` feature (that I think have similars in the other version manager) to override the `.ruby-version` for the duration of the shell. This is what I do when upgrading Ruby for example in a repository that have a `.ruby-version` file.