Handling add/remove to/from migration edge cases
rails/rails pull request #30011
Opened 2017-07-31 12:04 UTC by guilherme

Making sure the table name is parsed correctly when an add/remove column migration have 'from'/'to'  in the attribute name.

2017-07-31 12:38 UTC, pixeltrix commented
@guilherme thanks for the PR - what happens when you do `rails g migration RemoveOriginallyFromFromUsers` or `AddSentToToUsers` ?

2017-07-31 13:10 UTC, guilherme commented
@pixeltrix it works fine. I've just updated the PR with the scenario that I am having the issue.

I tried to generalize and I thought the  test was failing for that generic case but it wasn't, just double checked. My bad.

2017-08-01 00:08 UTC, rafaelfranca requested changes
Tests are broken

2017-08-01 14:22 UTC, lugray commented on activerecord/lib/rails/generators/active_record/migration/migration_generator.rb
> +          when /^(add)_.*_(?:to)_(.*)/, /^(remove)_.*?_(?:to|from)_(.*)/
The same change (and test) should be made to allow `migration = "remove_email_address_from_sent_to_user"`

The uncaptured groups can then be removed entirely:
```ruby
when /^(add)_.*_to_(.*)/, /^(remove)_.*_from_(.*)/
```

2017-08-02 13:42 UTC, guilherme commented on activerecord/lib/rails/generators/active_record/migration/migration_generator.rb
> +          when /^(add)_.*_(?:to)_(.*)/, /^(remove)_.*?_(?:to|from)_(.*)/
thanks for the feedback! I was trying to come up with a table name with "to" on the title but couldn't find it :)

2017-08-02 13:48 UTC, lugray commented on railties/test/generators/migration_generator_test.rb
> +  def test_remove_migration_with_table_having_from_in_title
test_remove_migration_with_table_having_~from~**to**_in_title

2017-08-03 10:39 UTC, guilherme commented on railties/test/generators/migration_generator_test.rb
> +  def test_remove_migration_with_table_having_from_in_title
👍

2017-08-03 10:52 UTC, lugray approved these changes

2017-08-03 15:34 UTC, merged