Document public hooks in AS::Reloader
rails/rails pull request #30100
Opened 2017-08-06 18:43 UTC by kirs

This PR moves documentation for `AS::Reloader` hooks outside of hidden rdoc block.
I think it's important to at least document `#to_prepare`, as it can be quite useful.

@rafaelfranca

2017-08-08 22:37 UTC, rafaelfranca requested changes

2017-08-08 22:37 UTC, rafaelfranca commented on activesupport/lib/active_support/reloader.rb
> +    # Can be used to monkey patch reloaded constants.
I prefer to keep this second line out. It can be useful for a lot of things, so better to no specify.

2017-08-08 22:37 UTC, rafaelfranca commented
Great idea!

2017-08-09 02:23 UTC, matthewd commented
I think these should be documented as methods, not as hooks -- so, phrased in terms of what the method will do when called ("registers a block .." or something)... or at least as a "callback", which is both literally what they are, and how they're referred to elsewhere (see e.g. `after_action`, `after_commit`, `after_validation` for some variety, but also some consistency).

Let's keep the comprehensive enumeration where it is, too, though. (It's hidden because they're described in terms of their implementation, rather than their app-facing purpose. I agree we need app-facing documentation, but I think the internal one is useful too.)

2017-08-11 14:49 UTC, kirs commented
Thanks for feedback! I updated the PR.

2017-08-14 16:41 UTC, matthewd commented
It's a "callback", not a "hook".

2017-08-14 18:18 UTC, kirs commented
Thanks, fixed 👌

2017-08-14 18:51 UTC, rafaelfranca approved these changes

2017-11-17 09:03 UTC, merged