Mention eager loading in the guide
rails/rails pull request #30106
Opened 2017-08-07 07:46 UTC by kirs

Fixes https://github.com/rails/rails/issues/29920

Let's add some info about eager loading and `eager_load_paths` into the autoload guide.

2017-08-07 08:30 UTC, vipulnsward requested changes

2017-08-07 08:30 UTC, vipulnsward commented on guides/source/autoloading_and_reloading_constants.md
> +* What is `autoload_paths` and `eager_load_paths`
*are

2017-08-07 08:30 UTC, vipulnsward commented on guides/source/autoloading_and_reloading_constants.md
> +Use `eager_load_paths` to declare directories to be autoloaded in development and eager loaded in production.
this is confusing, saying it does different things in development vs production, can we rephrase it?

2017-11-06 22:45 UTC, rafaelfranca commented
@kirs can you work on @vipulnsward comments?

2017-11-06 22:46 UTC, rafaelfranca commented on guides/source/autoloading_and_reloading_constants.md
> +when cache classes is enabled (e.g. in production).
I think cache classes doesn't change the behavior or eager loading.

2018-02-03 09:06 UTC, kamipo commented
Closing this in favor of #31755.

2018-02-03 09:06 UTC, closed without merging