add missing collection.reload documentation [ci skip]
rails/rails pull request #30142
Opened 2017-08-08 20:34 UTC by yukideluxe

Hello!

I missed some documentation that I think is nice to have when I did https://github.com/rails/rails/pull/30125 and I noticed about this when I did the backport to 5-0-stable https://github.com/rails/rails/pull/30141

As promised, here is the extra bit 😄 

Sorry for the noise!

2017-08-08 20:49 UTC, sgrif requested changes

2017-08-08 20:49 UTC, sgrif commented on activerecord/lib/active_record/associations.rb
> +        #   Returns an array of all of the associated objects, forcing a database read.
Does this return an array? I'm pretty sure it just returns `self`

2017-08-08 20:49 UTC, sgrif commented on activerecord/lib/active_record/associations.rb
> +        #   An empty array is returned if none are found.
Same here -- I don't think this returns an array.

2017-08-08 21:01 UTC, yukideluxe commented on activerecord/lib/active_record/associations.rb
> +        #   Returns an array of all of the associated objects, forcing a database read.
Hi @sgrif, thanks for the feedback!

I based this on this documentation above https://github.com/yukideluxe/rails/blob/master/activerecord/lib/active_record/associations.rb#L1194-L1196

Both `collection` and `collection.reload` return an `ActiveRecord::Associations::CollectionProxy` so they behave the same. Does it mean that the documentation for `#collection` is also wrong? I'm not sure how to rephrase it, though 🙈

2017-08-08 21:02 UTC, yukideluxe commented on activerecord/lib/active_record/associations.rb
> +        #   Returns an array of all of the associated objects, forcing a database read.
updated the link, sorry :)

2017-08-08 21:11 UTC, sgrif commented on activerecord/lib/active_record/associations.rb
> +        #   Returns an array of all of the associated objects, forcing a database read.
Yes, that documentation is also wrong. It was last touched by https://github.com/rails/rails/commit/6e754551 9 years ago when the behavior was different. I would rephrase it by replacing `array` with `Relation`

2017-08-08 21:11 UTC, sgrif commented on activerecord/lib/active_record/associations.rb
> +        #   Returns an array of all of the associated objects, forcing a database read.
You could also just link to `Relation#reload`

2017-08-08 21:13 UTC, yukideluxe commented on activerecord/lib/active_record/associations.rb
> +        #   Returns an array of all of the associated objects, forcing a database read.
sure! Let me do the changes and I'll amend this commit! Thanks for the tip! :)

2017-08-08 21:26 UTC, yukideluxe commented on activerecord/lib/active_record/associations.rb
> +        #   Returns an array of all of the associated objects, forcing a database read.
@sgrif done here and in the backport https://github.com/rails/rails/pull/30141! ✌️

2017-08-08 21:53 UTC, merged

2017-08-09 15:29 UTC, tjschuck commented
@sgrif The (now merged) backport @yukideluxe mentioned (#30141) was to `5-0-stable` — this should also probably be backported to `5-1-stable`.