Test for the new exception of delegate_missing_to
rails/rails pull request #30191
Opened 2017-08-11 08:41 UTC by colorfulfool

A follow-up to the change to delegate_missing_to made in #30084.

2017-08-11 15:41 UTC, rafaelfranca requested changes
Based on @matthewd's comment in the original PR, can you change the implementation to only check for nil if `super` raises `NoMethodError`?

2017-08-11 20:44 UTC, colorfulfool commented
Done. I didn't go this way initially because the code turns out not pretty. Is there a better way to write this?

2017-08-11 20:49 UTC, rafaelfranca commented on activesupport/lib/active_support/core_ext/module/delegation.rb
> +        begin
You can remove the `begin` here.

2017-08-11 20:49 UTC, rafaelfranca commented on activesupport/lib/active_support/core_ext/module/delegation.rb
> +      def delegation_error_if_target_nil(target, method)
This method should be private, and starts with `_` to avoid conflicts with the methods in the including class.

2017-08-11 20:49 UTC, rafaelfranca commented
I think that is fine

2017-08-11 20:51 UTC, gsamokovarov commented on activesupport/lib/active_support/core_ext/module/delegation.rb
> +      def delegation_error_if_target_nil(target, method)
Should we extract the method at all, we're still monkey patching a core object here. Any pollution counts.

2017-08-11 20:56 UTC, rafaelfranca commented on activesupport/lib/active_support/core_ext/module/delegation.rb
> +      def delegation_error_if_target_nil(target, method)
Yeah, I don't think it is necessary. `begin/end` inside that else is good enough.

2017-08-11 21:11 UTC, colorfulfool commented
Is `delegate_missing_to` meant to be used several times on the same class? If not, I can eliminate most of `_delegation_error_if_target_nil` arguments.

I'd say it isn't, because you can instead do
```ruby
delegate_missing_to :person_responsible

def person_responsible
  president || chief || captain
end
```

2017-08-11 21:13 UTC, rafaelfranca commented
It is not, because only the last call is going to be used.

2017-08-11 21:13 UTC, rafaelfranca commented
I think we can go with the version without the private method just to avoid polluting the caller more

2017-08-12 22:22 UTC, rafaelfranca approved these changes

2017-08-12 22:23 UTC, merged

2017-08-12 22:23 UTC, rafaelfranca commented
This is amazing. Thank you for doing that.