Do not generate default alt text for images
rails/rails pull request #30213
Opened 2017-08-12 15:50 UTC by ckundo

### Summary

- Deprecate `image_alt` helper.
- Remove the call to `image_alt` from `image_tag`.

[Fixes #30096]

### Impact

- After this change, screen readers will fallback to default, expected, and user configurable behavior for missing alt text.
- Also with this change, automated linting and testing tools will correctly generate warnings.

### Motivation

- Auto-generating content from the filename of an image is not suitable alternative text.
- Alt text that isn't fully considered can be distracting and fatiguing for screen readers users (blind, low vision, dyslexic people).
- Setting a filename fallback short circuits screen reader default behavior and configuration for blank descriptions, and may be frustrating to the assistive technology user.
- Setting poor defaults also creates false negatives for linting tools, that makes it harder to improve application accessibility.

2017-08-12 19:44 UTC, ckundo commented
I'm working on fixing up test failures now, but I gist of the PR is the same.

2017-08-12 19:57 UTC, ckundo commented
Something to reiterate from the PR comment: this change will create warnings in some accessibility testing tools. These would be _correct_ failures, but new failures nonetheless. In some cases these warnings could potentially be part of CI suites, and, in an even more narrow subset of applications, may create build failures.

Is it worth introducing a configuration option to disable the correct behavior for folks that may need to fix failures when upgrading Rails? The alternative for those that want to delay fixes would be to monkey-patch the `image_tag` helper in their apps until they remediate the issue. @mgifford how did y'all handle this in Drupal?

2017-08-14 22:24 UTC, rafaelfranca requested changes
It looks good to me. Nice work. Can you add a CHANGELOG entry?

2017-08-14 22:24 UTC, rafaelfranca commented on actionview/lib/action_view/helpers/asset_tag_helper.rb
> +        ::ActiveSupport::Deprecation.warn("ActionView::Helpers::AssesTagHelper.image_alt is deprecated and will be removed from Rails 5.2. You must exlicitly set alt text on images.")
I think you can remove the first `::` here.

2017-08-15 13:11 UTC, georgeclaghorn commented on actionview/lib/action_view/helpers/asset_tag_helper.rb
> +        ActiveSupport::Deprecation.warn("ActionView::Helpers::AssesTagHelper.image_alt is deprecated and will be removed from Rails 5.2. You must exlicitly set alt text on images.")
`s/AssesTagHelper/AssetsTagHelper`, `s/exlicitly/explicitly`

2017-08-15 13:11 UTC, georgeclaghorn commented on actionview/lib/action_view/helpers/asset_tag_helper.rb
> +      # This method will be deprecated in future versions of Rails.
This method is deprecated now. It’ll be *removed* in Rails 5.2.

2017-08-15 14:16 UTC, kaspth commented on actionview/lib/action_view/helpers/asset_tag_helper.rb
> +      # This method will be deprecated in future versions of Rails.
No, it's deprecated in 5.2 and will be removed in 6.0.

2017-08-15 14:17 UTC, kaspth commented on actionview/lib/action_view/helpers/asset_tag_helper.rb
> +      # This method will be deprecated in future versions of Rails.
Though we let the deprecation warning itself suffice, so need for a comment here.

2017-08-15 14:25 UTC, georgeclaghorn commented on actionview/lib/action_view/helpers/asset_tag_helper.rb
> +      # This method will be deprecated in future versions of Rails.
I meant that the comment says this method will eventually be deprecated, when it’s actually deprecated in this PR.

The deprecation warning says this method be removed in 5.2; it should say 6.0.

2017-08-15 18:16 UTC, rafaelfranca requested changes

2017-08-15 18:16 UTC, rafaelfranca commented on actionview/lib/action_view/helpers/asset_tag_helper.rb
> +        ActiveSupport::Deprecation.warn("ActionView::Helpers::AssesTagHelper.image_alt is deprecated and will be removed from Rails 5.2. You must exlicitly set alt text on images.")
Don't need to talk about the module name too. Only `image_alt is deprecated` is good. And it is going to be removed from Rails 6.0.

2017-08-16 18:14 UTC, rafaelfranca requested changes
Looks good to me. Can you squash your commits?

2017-08-17 12:43 UTC, maclover7 requested changes

2017-08-17 12:43 UTC, maclover7 commented on actionview/lib/action_view/helpers/asset_tag_helper.rb
> +        options[:src] = path_to_image(source, skip_pipeline: skip_pipeline)
Why are we changing the method being used to generate `src`? Using `path_to_image` instead of `resolve_image_source` is causing CI to fail 😬

2017-08-17 12:43 UTC, maclover7 commented on actionview/CHANGELOG.md
> +    Fixes #30096
Can you add a period after the issue number

2017-08-17 14:27 UTC, ckundo commented
Thanks @maclover7, fixed. Good to squash?

2017-08-17 19:45 UTC, rafaelfranca commented
👍  squash again

2017-08-21 15:19 UTC, ckundo commented
Squashed and ready!

2017-08-23 14:58 UTC, ckundo commented
@rafaelfranca anything else I can add?

2017-08-23 16:00 UTC, merged