Fix RuboCop offenses
rails/rails pull request #30210
Opened 2017-08-12 11:34 UTC by koic

### Summary

This PR fixes the following offenses.

```console
% bundle exec rubocop

(snip)

Offenses:

activerecord/lib/rails/generators/active_record/application_record/application_record_generator.rb:19:11: C: Use 2 (not 36) spaces for indentation.
                                              "app/models/#{namespaced_path}/application_record.rb"
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
activerecord/lib/rails/generators/active_record/application_record/application_record_generator.rb:22:45: W: end at 22, 44 is not aligned with @application_record_file_name ||= if at 18, 10.
                                            end
                                            ^^^
activestorage/lib/active_storage/attached.rb:7:1: C: Incorrect indentation detected (column 0 instead of 2).
# classes that both provide proxy access to the blob association for a record.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
activestorage/test/models/attachments_test.rb:71:7: C: Redundant curly braces around a hash parameter.
      { io: StringIO.new("IT"), filename: "country.jpg", content_type: "image/jpg" })
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
activestorage/test/models/attachments_test.rb:80:7: C: Redundant curly braces around a hash parameter.
      { io: StringIO.new("IT"), filename: "country.jpg", content_type: "image/jpg" })
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
activestorage/test/models/attachments_test.rb:91:7: C: Redundant curly braces around a hash parameter.
      { io: StringIO.new("IT"), filename: "country.jpg", content_type: "image/jpg" })
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2324 files inspected, 6 offenses detected
```

2017-08-12 12:16 UTC, koic commented on activerecord/lib/rails/generators/active_record/application_record/application_record_generator.rb
> +          end
Hmm. There is no offenses in my local, but offense occurs in Code Climate.

https://codeclimate.com/github/rails/rails/activerecord/lib/rails/generators/active_record/application_record/application_record_generator.rb?from_sha=98360a96&to_sha=629158f3#source

With similar code offense has not occurred.

https://github.com/rails/rails/blob/98360a96cc1e0bb6ab9eb31f421a36439e66eefc/activejob/lib/rails/generators/job/job_generator.rb#L30-L37

2017-08-12 22:27 UTC, rafaelfranca requested changes

2017-08-12 22:27 UTC, rafaelfranca commented on activerecord/lib/rails/generators/active_record/application_record/application_record_generator.rb
> +          end
Unfortunately code climate runs a version of rubocop older than the one our config uses. This is why you fixed locally and broke in code climate.

2017-08-12 22:27 UTC, rafaelfranca commented on activestorage/test/models/attachments_test.rb
> +      io: StringIO.new("IT"), filename: "country.jpg", content_type: "image/jpg")
Can we add a rubocop comment disabling this role in those places. We discussed before and I agree for this case it is weird to have one with `{}` and others without. So we decided to keep both hashes consistent even that it goes against the rubocop rule

2017-08-13 04:45 UTC, matthewd commented on activestorage/test/models/attachments_test.rb
> +      io: StringIO.new("IT"), filename: "country.jpg", content_type: "image/jpg")
@rafaelfranca I think we should consider reverting 77be872819d6e9fd63f4253398dbfd6990166a7c, and fixing the other places affected. I didn't realise such an option existed (or maybe it didn't at the time?), and definitely recall that rule making some undesirable changes when it was first applied.

https://github.com/matthewd/rails/commit/962a01d1e67b9b76d23b8b61a760254d3622d80f feels more good than bad to me... there are some methods that take options after a hash parameter (e.g. `select` and friends), but most seem to be of the "two equally-important hashes" variety.

2017-08-13 11:21 UTC, koic commented on activerecord/lib/rails/generators/active_record/application_record/application_record_generator.rb
> +          end
Oh, It's all clear now. Is it better to revert this change according to Code Climate?

2017-08-13 12:15 UTC, koic commented on activestorage/test/models/attachments_test.rb
> +      io: StringIO.new("IT"), filename: "country.jpg", content_type: "image/jpg")
I see. Listening to it, I think `context_dependent` seems a good choice.

For reference, the following is the affect when `context_dependent` is enabled.

```diff
diff --git a/.rubocop.yml b/.rubocop.yml
index 2889acfdd1..cec4fcc71a 100644
--- a/.rubocop.yml
+++ b/.rubocop.yml
@@ -16,6 +16,7 @@ Style/AndOr:
 # method call.
 Style/BracesAroundHashParameters:
   Enabled: true
+  EnforcedStyle: context_dependent
```

Run `rubocop -a --only Style/BracesAroundHashParameters`.

```console
% rubocop -a --only Style/BracesAroundHashParameters
(snip)
% git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   .rubocop.yml
        modified:   actioncable/test/channel/stream_test.rb
        modified:   actionpack/test/controller/live_stream_test.rb
        modified:   actionpack/test/controller/redirect_test.rb
        modified:   actionpack/test/controller/resources_test.rb
        modified:   actionpack/test/controller/test_case_test.rb
        modified:   actionpack/test/dispatch/routing_assertions_test.rb
        modified:   actionpack/test/journey/router_test.rb
        modified:   actionview/test/actionpack/abstract/abstract_controller_test.rb
        modified:   actionview/test/template/date_helper_test.rb
        modified:   actionview/test/template/form_collections_helper_test.rb
        modified:   actionview/test/template/form_helper_test.rb
        modified:   actionview/test/template/form_options_helper_test.rb
        modified:   actionview/test/template/form_tag_helper_test.rb
        modified:   actionview/test/template/text_helper_test.rb
        modified:   activerecord/test/cases/attribute_set_test.rb
        modified:   activestorage/lib/active_storage/service/disk_service.rb
        modified:   activesupport/test/json/encoding_test.rb
        modified:   railties/lib/rails/engine/updater.rb
        modified:   railties/lib/rails/tasks/framework.rake
        modified:   railties/test/application/assets_test.rb
        modified:   railties/test/application/configuration_test.rb
        modified:   railties/test/application/mailer_previews_test.rb
        modified:   railties/test/application/middleware/cache_test.rb
        modified:   railties/test/application/middleware_test.rb
        modified:   railties/test/generators/api_app_generator_test.rb
        modified:   railties/test/generators/app_generator_test.rb
        modified:   railties/test/generators/create_migration_test.rb
        modified:   railties/test/railties/engine_test.rb
        modified:   railties/test/railties/mounted_engine_test.rb
```

It seems that there is much affect on the test codes now.

2017-08-14 20:07 UTC, rafaelfranca commented on activestorage/test/models/attachments_test.rb
> +      io: StringIO.new("IT"), filename: "country.jpg", content_type: "image/jpg")
Yeah, the changes in `select` and `form_tag` really annoys me. But since it is only on tests I'm fine with it.

2017-08-14 20:07 UTC, rafaelfranca commented on activestorage/test/models/attachments_test.rb
> +      io: StringIO.new("IT"), filename: "country.jpg", content_type: "image/jpg")
Lets apply that diff @koic

2017-08-15 00:04 UTC, koic commented on activestorage/test/models/attachments_test.rb
> +      io: StringIO.new("IT"), filename: "country.jpg", content_type: "image/jpg")
Thank you. I applied it.
08afe64e7a38085ba74b17cf6faaf18baaeca60c

2017-08-15 21:58 UTC, rafaelfranca commented
Could you squash your commits?

2017-08-16 08:30 UTC, koic commented
Oops. I squashed them.

2017-08-16 08:42 UTC, matthewd commented on activerecord/lib/rails/generators/active_record/application_record/application_record_generator.rb
> +          end
Is there a version that both are happy with? Maybe this?

```ruby
@application_record_file_name ||=
  if namespaced?
    "app/models/#{namespaced_path}/application_record.rb"
  else
    "app/models/application_record.rb"
  end
```

2017-08-16 09:21 UTC, koic commented on activerecord/lib/rails/generators/active_record/application_record/application_record_generator.rb
> +          end
I see! That is a wonderful solution. I updated it.

FYI, although the timing is unknown, Code Climate seems to be working to bump RuboCop to 0.49.1.

https://github.com/codeclimate/codeclimate-rubocop/issues/99#issuecomment-322381645

I think @matthewd suggestion is good now. Thank you.

2017-08-16 10:17 UTC, merged