Add `--skip-yarn` option to the plugin generator
rails/rails pull request #30238
Opened 2017-08-13 20:15 UTC by bogdanvlviv

2017-08-13 22:55 UTC, y-yagi commented on railties/test/generators/plugin_generator_test.rb
> +  def test_generator_for_yarn
Rather than adding a test to `PluginGeneratorTest`, how about moving the test at `AppGeneratorTest` to `SharedGeneratorTests`?

2017-08-14 21:32 UTC, rafaelfranca requested changes

2017-08-14 21:32 UTC, rafaelfranca commented on railties/test/generators/plugin_generator_test.rb
> +  def test_generator_for_yarn
:+1:

2017-08-15 07:32 UTC, bogdanvlviv commented on railties/test/generators/plugin_generator_test.rb
> +  def test_generator_for_yarn
The test `test_generator_for_yarn` in `railties/test/generators/app_generator_test.rb` different from `test_generator_for_yarn` in `railties/test/generators/plugin_generator_test.rb`

Expample:
```ruby
assert_file "package.json", /dependencies/ #  railties/test/generators/app_generator_test.rb
assert_file "test/dummy/package.json", /dependencies/ # railties/test/generators/plugin_generator_test.rb
```

2017-08-15 11:58 UTC, y-yagi commented on railties/test/generators/plugin_generator_test.rb
> +  def test_generator_for_yarn
How about letting specify the application path from each test? As described below. 

```diff 
diff --git a/railties/test/generators/app_generator_test.rb b/railties/test/generators/app_generator_test.rb
index ccb437c..cb46000 100644
--- a/railties/test/generators/app_generator_test.rb
+++ b/railties/test/generators/app_generator_test.rb
+
+    def application_path
+      destination_root
+    end
 end
diff --git a/railties/test/generators/plugin_generator_test.rb b/railties/test/generators/plugin_generator_test.rb
index bd76af8..f55b89a 100644
--- a/railties/test/generators/plugin_generator_test.rb
+++ b/railties/test/generators/plugin_generator_test.rb
@@ -150,6 +150,18 @@ def test_generating_adds_dummy_app_without_sprockets
     end
   end
 
+  private
+    def application_path
+      "#{destination_root}/test/dummy"
+    end
 end
diff --git a/railties/test/generators/shared_generator_tests.rb b/railties/test/generators/shared_generator_tests.rb
index c73b91e..d584fbb 100644
--- a/railties/test/generators/shared_generator_tests.rb
+++ b/railties/test/generators/shared_generator_tests.rb
@@ -114,6 +114,13 @@ def test_skip_git
     assert_no_directory(".git")
   end
 
+  def test_generator_for_yarn
+    run_generator([destination_root])
+
+    assert_file "#{application_path}/package.json", /dependencies/
+    assert_file "#{application_path}/config/initializers/assets.rb", /node_modules/
+  end
```

2017-08-15 16:18 UTC, bogdanvlviv commented on railties/test/generators/plugin_generator_test.rb
> +  def test_generator_for_yarn
@y-yagi I've just implemented it.
Itl definitely help me to do more dryer tests in this PR: https://github.com/rails/rails/pull/30101. 
Also, I've have prepared new changes to dry tests in `railties/test/generators/app_generator_test.rb` and `railties/test/generators/plugin_generator_test.rb`.
When it merges, I will open new PR with this changes.

Thank you!

2017-08-15 18:13 UTC, rafaelfranca commented
Could you squash your commits?

2017-08-15 19:37 UTC, bogdanvlviv commented
Done!

2017-08-15 20:02 UTC, rafaelfranca approved these changes

2017-08-15 20:50 UTC, merged