Make `restart` and `dev:cache` tasks work when customizing pid file path
rails/rails pull request #30332
Opened 2017-08-20 00:52 UTC by y-yagi

Originally, it hard-coded pid file path. It can not be removed when customizing pid file path.
But rake task can not get pid file path. Therefore, do not remove file in rake task, only file that tell them that restart is in progress are created, and pid file remove in server command.

Fixes #29306

2017-08-20 02:12 UTC, georgeclaghorn commented on railties/lib/rails/commands/server/server_command.rb
> +          FileUtils.rm_f("tmp/run_restart.txt")
Forgive me if I’m missing something, but I don’t follow why this is necessary. Doesn’t Puma’s `tmp_restart` plugin handle restarts independently? The `rails` command isn’t executed on restart, right?

2017-08-20 02:13 UTC, georgeclaghorn commented
There’s a [test failure](https://travis-ci.org/rails/rails/jobs/266405448#L1226) that seems relevant.

2017-08-20 02:52 UTC, georgeclaghorn commented on railties/lib/rails/commands/server/server_command.rb
> +          FileUtils.rm_f("tmp/run_restart.txt")
Never mind. We pass a `restart_cmd` to Puma, so the `rails server` *is* executed on restart.

2017-08-20 02:57 UTC, georgeclaghorn requested changes

2017-08-20 02:57 UTC, georgeclaghorn commented on railties/lib/rails/commands/server/server_command.rb
> +          FileUtils.touch("tmp/run_restart.txt")
It’d be clearer to include a flag that indicates a restart in the `restart_cmd`, then use that flag to determine whether to remove the PID file. Then we can keep `FileUtils.touch "tmp/restart.txt"` in `Rails::DevCaching.enable_by_file`.

2017-08-20 12:52 UTC, y-yagi commented on railties/lib/rails/commands/server/server_command.rb
> +          FileUtils.touch("tmp/run_restart.txt")
Seems fine. I added the `--restart` option and updated it to use it.

2017-08-20 12:56 UTC, y-yagi commented
I think the fail test probably relates to the following. 
https://github.com/puma/puma/pull/1206 
https://github.com/puma/puma/pull/1345 
But it does not reproduce locally...

2017-08-20 21:59 UTC, y-yagi commented
Hmm, the test passed...

2017-08-21 01:39 UTC, georgeclaghorn approved these changes

2017-08-21 01:40 UTC, merged