Retrive screenshot in relative path of current directory
rails/rails pull request #30421
Opened 2017-08-26 09:54 UTC by y-yagi

In Rails engine `Rails.root `returns the path of the dummy application.
Therefore, there is no `tmp` directly where the test is running, so can not get the screenshot.
For this reason, instead of directly specifying tmp, retrive screenshot by relative path from the current directory.

Fixes #30405

2017-08-26 22:52 UTC, matthewd commented
I think we should use the absolute path in `display_image` (for the non-message parts).

2017-08-27 03:41 UTC, y-yagi commented
Seems reasonable. I fixed.

2017-08-27 06:39 UTC, prathamesh-sonpatki requested changes
Please add CHANGELOG as well.

2017-08-27 11:46 UTC, y-yagi commented
I added CHANGELOG!

2017-08-27 19:14 UTC, merged

2017-08-27 19:21 UTC, eileencodes commented
@y-yagi Can you backport this to 5-1-stable, open a PR and ping me? It doesn't cleanly backport.