Update Rails Guides about  :autosave option
rails/rails pull request #30548
Opened 2017-09-08 12:55 UTC by chumakoff

Call attention to the fact, that If the `:autosave` option is not set (neither `true` nor `false`), it is not the same as `false`: only new loaded members are saved.

2017-09-09 20:02 UTC, eileencodes requested changes
Hey @chumakoff thanks for the PR!

I think this change is confusing for readers. I think it's not clear _what_ is not the same as `false`. What do you think about combining the original docs you linked to like this:

> If you set the `:autosave` option to `true`, Rails will save any loaded members and destroy members that are marked for destruction whenever you save the parent object. Setting `:autosave` to `false` is not the same as not setting the `:autosave` option. When the `:autosave` option is not present then new association records are saved but the updated association records are not saved.

2017-09-09 21:49 UTC, chumakoff commented
Hi! I agree with you. But I have one more thing to suggest. In the guide there is almost everywere "associated objects"wording. Sometimes it is "association members". In this paragraph it is "members" in the first sentence (I think it's not very clear what members), and "association records" further. So, let's use the same wording for uniformity and definiteness.

> If you set the `:autosave` option to `true`, Rails will save any loaded association members and destroy members that are marked for destruction whenever you save the parent object. Setting `:autosave` to `false` is not the same as not setting the `:autosave` option. If the `:autosave` option is not present, then new associated objects will be saved, but updated associated objects will not be saved.

What do you think?

2017-09-20 17:03 UTC, eileencodes commented
@chumakoff sounds good. Please update the PR and squash your commits. Thanks for working on this!.

2017-09-20 19:43 UTC, chumakoff commented
@eileencodes  Done. Thank you for your cooperation! )

2017-09-20 21:54 UTC, eileencodes approved these changes

2017-09-20 21:54 UTC, merged