Testing actioncable against websocket-driver 0.7.0
rails/rails pull request #30711
Opened 2017-09-25 15:39 UTC by jaredbeck

I just want to run the CI; I haven't done any analysis of changes in websocket-driver 0.7.0. I haven't even read their changelog. This PR is just to cause a CI run, but if people want to use it as a starting point for discussion, that's fine too.

2017-09-25 19:11 UTC, jaredbeck commented
Looks like the tests mostly pass. I'm not sure how reliable CI is .. are the failures intermittent? I don't know b/c I don't have permissions to retry a CI job.

2018-01-18 16:42 UTC, isuda commented
Could we get this dependency updated in actioncable soon? It fixes https://github.com/rails/rails/issues/30908.

2018-01-18 17:25 UTC, jaredbeck commented
@dhh Please assign someone to review this. I have no idea who to ask. Thanks.

2018-01-18 18:34 UTC, dhh commented
Why are we trying to run against the newer websocket-driver?

2018-01-18 18:52 UTC, isuda commented
This is due to me commenting that this version fixed a bug that was reported earlier, but it turns out that fix did not make it into this version. It is still unreleased.

https://github.com/rails/rails/issues/30908

and
https://github.com/faye/websocket-driver-ruby/issues/58
https://github.com/faye/websocket-driver-ruby/commit/2ec898c6a10f0b575f01a5e418652d05e27c3794


So it might not be worth updating to 0.7.0 now, but it would be good to see if a new version of websocket-driver could be released to fix that bug.

2018-01-18 19:17 UTC, dhh commented
I'm generally happy to see looser Gem bindings. So I'd take one that's just
open ended. Just specify our minimum required version.

On Thu, Jan 18, 2018 at 12:54 PM, Ian Suda <notifications@github.com> wrote:

> This is due to me commenting that this version fixed a bug that was
> reported earlier, but it turns out that fix did not make it into this
> version. It is still unreleased.
>
> #30908 <https://github.com/rails/rails/issues/30908>
>
> and
> faye/websocket-driver-ruby#58
> <https://github.com/faye/websocket-driver-ruby/issues/58>
> faye/websocket-driver-ruby@2ec898c
> <https://github.com/faye/websocket-driver-ruby/commit/2ec898c6a10f0b575f01a5e418652d05e27c3794>
>
> So it might not be worth updating to 0.7.0 now, but it would be good to
> see if a new version of websocket-driver could be released to fix that bug.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rails/rails/pull/30711#issuecomment-358745067>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAAKtbrt-5OWHVn57o5r-9c-E92ih38Oks5tL5NKgaJpZM4Pi7oH>
> .
>

2018-01-18 20:08 UTC, rafaelfranca requested changes

2018-01-18 20:08 UTC, rafaelfranca commented on actioncable/actioncable.gemspec
> +  s.add_dependency "websocket-driver", [">= 0.6.1", "< 0.8"]
Can you change it to `>= 0.6.1`?

2018-01-18 21:27 UTC, jaredbeck commented
> Can you change it to >= 0.6.1?

Changed, thanks.

2018-01-18 21:32 UTC, merged