Backport Capybara :puma defaults to 5.1.x
rails/rails pull request #30712
Opened 2017-09-25 18:17 UTC by maschwenk

### Summary

https://github.com/rails/rails/pull/30638 fixed potential Puma configs in `config/puma.rb` overriding the desirable stack for SystemTests but could not be pulled into `5.1.x` because it required a Capybara upgrade. This just backports the fix to 5.1.x by manually copying over the missing options.

cc @twalpole

2017-09-25 18:19 UTC, maschwenk commented on actionpack/lib/action_dispatch/system_testing/server.rb
> +              Threads: "0:4",
This should be fine without this `Theads` change, so happy to change this out

2017-09-26 02:02 UTC, maschwenk commented
I think this would make more sense to be assigned to @eileencodes

2017-09-26 11:49 UTC, eileencodes commented
Hey @maschwenk thanks for taking the time to open the PR.

We decided not to backport the change that @twapole made to master because it changes behavior. Are you experiencing a bug or wanted to make master and 5.1 the same?

2017-09-26 15:45 UTC, maschwenk commented
@eileencodes To me the way it was working in 5.1.x was a bug but I can see your point. The reason I opened it was because @twalpole 's original comment insinuated that the only reason it couldn't be backported was because from @twalpole (https://github.com/rails/rails/pull/30638#issuecomment-330266800):
> It does require an update to Capybara 2.15+ for the passing of the 'Silent' option to Capybaras registered puma server to work - so not sure whether backporting is acceptable or not.
So I figured that that was the reason you removed the 5.1.5 milestone. If I pull out the `Threads` change, then the only actual options being overridden are:
```
workers: 0,
daemon: false,
```
If a Rails user trying to use SystemTests is overriding those, then they are fundamentally breaking a feature that's On The Box™️. 

I can see your point but just figured I'd give some background on why I thought it constituted a bug. Thanks!

2017-09-26 15:56 UTC, twalpole commented
@eileencodes As @maschwenk mentions - my reasoning for why the master PR shouldn't have been backported was the requirement for a Capybara bump to support passing the `Silent` parameter to the Capybara registered :puma server.  This PR fixes the  issue of the :puma_rails server sometimes unintentionally running in clustered mode in 5.1 (which breaks connection sharing and capybara's "all requests complete" detection).

2017-09-27 12:44 UTC, eileencodes commented
@maschwenk can you add a changelog? This does technically change behavior and in case someone was relying on the threads or workers or whatever I'd like a note in the changelog.

2017-09-27 18:29 UTC, maschwenk commented
@eileencodes definitely. I'm going to remove the `Threads` change as well, just to reduce the number of potential surprises. Agree @twalpole ?

2017-09-27 18:54 UTC, twalpole commented
@maschwenk Sure

2017-09-27 21:47 UTC, maschwenk commented
Can rebase/squash these commits if needed

2017-09-27 21:50 UTC, eileencodes requested changes
Thanks for working on this! Can you make the minor change to the changelog I requested and then squash your commits? I'll merge after that.

2017-09-27 21:50 UTC, eileencodes commented on actionpack/CHANGELOG.md
> +    *Max Schwenk*
Can you clarify what settings changed? Something like "Ensure local dev and prod puma configs do not clobber  `ActionDispatch::SystemTesting` defaults. Adds `workers: 0` and `daemon: false`.

2017-09-28 12:16 UTC, eileencodes commented
Can you squash the changelog commit into the first commit? Thanks!

2017-09-28 12:16 UTC, eileencodes approved these changes

2017-09-28 17:05 UTC, maschwenk commented
@eileencodes Done, sorry for back and forth, wasn't sure if you meant all the commits squashed or just the intermediates. 📈

2017-09-28 17:55 UTC, merged

2017-09-28 17:56 UTC, eileencodes commented
No worries at all @maschwenk! Congrats on your first Rails contribution 🎉