Only preload misses on multifetch cache
rails/rails pull request #31250
Opened 2017-11-28 02:42 UTC by lsylvester

### Summary

When rendering a collection with `cached: true` for an `ActiveRecord::Relation` that has `preload` values, the preload would normally only be required for rendering the partial when it misses the cache and nor required for generating the cache key.

Currently, we have to chose between using preload, which loads unused `ActiveRecord` instances when the have a high cache hit rate, or not preloading the associations, which can result in `N + 1` queries when there are a large number of cache misses. 

This PR attempts to optimise this be only preloading the associations for the records that miss the cache.

An example application to demonstrate this behaviour is at https://github.com/lsylvester/multifetch-demo. An example from the log demonstrating this behaviour is:

```
  Rendering categories/index.html.erb within layouts/application
  Category Load (0.1ms)  SELECT "categories".* FROM "categories"
  Product Load (0.4ms)  SELECT "products".* FROM "products" WHERE "products"."category_id" IN (?, ?, ?, ?)  [["category_id", 4], ["category_id", 5], ["category_id", 8], ["category_id", 9]]
  Rendered collection of categories/_category.html.erb [18 / 22 cache hits] (57.9ms)
```

Without this change, we would either so a query for each of the categories that miss the cache, or have to load products for every category.

### Concerns and Further Work

There may be instances where we want to preload the associations for generation of cache keys, or we may want to have all of the associations loaded because the collection is used in other contexts other than the current rendering.

Currently there is no API to support this, but it is possible to acheive the load behaviour by calling `load` on the association before it is passed to the `render` call.

I am looking for feedback on:

- Is preloading associations only for models that miss the cache reasonable default behaviour? Or should this be explicitly opted into when calling render?
- If it is default behaviour, is calling `load` on the relation before rendering a suffient API for opting out, or should an additional option to the render call be added.

If it is ok to be default behaviour then I assume that I would need to add some application config to control this behavour to prevent breaking existing application and to provide deprication warnings.

I am also not sure about the structure of this code is it is very tightly connected to both ActionView and ActiveRecord, so any feedback in that area is welcome.

2017-11-28 03:05 UTC, matthewd commented
Wow, this is super neat!

The tight coupling does seem less than ideal, but the basic principle of highlighting the subset of records that are "active" and only applying the preload to those is great!

2017-11-28 05:14 UTC, rafaelfranca requested changes
We need to fix a lot of rubocop violations

2017-11-28 05:14 UTC, rafaelfranca commented on activerecord/lib/active_record/relation.rb
> +    def preload_associations(records = @records)
can we make the arguments always required?

2017-11-28 05:14 UTC, rafaelfranca commented on activerecord/lib/active_record/railtie.rb
> +    initializer "active_record.collection_cache_assoication_loading" do
`collection_cache_association_loading`.

2017-11-28 05:16 UTC, rafaelfranca commented
I think the coupling is fine at this level. Of course, it would be better if we can find a way to avoid it, but if not we are using the right mechanisms and it is similar to what we are doing with the controller runtime logs.

2017-11-28 23:00 UTC, lsylvester commented
@rafaelfranca The rubocop violations have been fixed and other suggestions implemented.

2018-03-15 19:49 UTC, merged

2018-03-15 19:49 UTC, kaspth commented
Thanks!

2022-03-04 17:31 UTC, ghiculescu commented
This PR creates a potential problem if you are using a custom cache key for the `cached: `option. For example:

```ruby
@view.render partial: "test/partial", collection: @post, cached: proc { |post| [post, post.author] }
```

In this case it might not sense to use Russian-doll caching, as in, you may not want to update every single `post` when an `author` is changed. Instead you can use `post.author` in your cache key to ensure that the view is updated correctly if the author changes.

But if you do this you get an n+1 on `post.author` if you do `@posts = Post.preload(:author)` in your controller. As a workaround you can do `@posts = Post.preload(:author).to_a`.

I think this PR is great if you do `cached: true`, but is problematic if you do `cached: proc {}`. Would you accept a PR that modifies it so this logic only applies when doing `cached: true`?

2022-03-04 17:38 UTC, eileencodes commented
@ghiculescu can you open a new issue with a reproduction? Or a PR with a repro that fixes this? Otherwise the notification from this will get lost and forgotten.

2022-03-04 17:55 UTC, ghiculescu commented
@eileencodes I haven't tested it thoroughly but this is what I had in mind: https://github.com/rails/rails/pull/44616

2022-05-07 12:20 UTC, ghiculescu commented
> @eileencodes I haven't tested it thoroughly but this is what I had in mind: #44616

Took a bit longer than I planned, but this is now a green build and should be a fix for the issue 👍