If association is a hash-like object preloading fails
rails/rails pull request #31819
Opened 2018-01-29 09:28 UTC by bpohoriletz

### If association is a hash-like object preloading fails

If you pass a hash-like object to preload associations (for example ActionController::Parameters)
preloader will fail with the ArgumentError.
This change allows passing objects that may be converted to a Hash,
Symbol or String into a preloader

### Other Information

` bundle exec ruby -Itest test/cases/associations/eager_test.rb` passes

2018-01-29 11:41 UTC, bpohoriletz commented
`bundle exec rake test:sqlite3` passes

2018-01-29 11:53 UTC, composerinteralia requested changes
Thanks for the PR! This may be making the method more flexible than it needs to be, but  I suppose if an object is hash-like or string-like enough to respond to `to_hash` or `to_str` you might expect it to work here.

Could you also squash this into one commit?

~~Don't worry about the Travis failures on Ruby 2.5.0 `av:ujs` and `railties`. There is a Travis bug that has caused them to fail for a while.~~ Should be fixed now

2018-01-29 11:53 UTC, composerinteralia commented on activerecord/lib/active_record/associations/preloader.rb
> +          when true == association.respond_to?(:to_hash)
I think we should get rid of the `true ==` and use `if/elsif`

2018-01-29 11:53 UTC, composerinteralia commented on activerecord/test/cases/associations/eager_test.rb
> +    post_id = Comment.where(author_id: nil).where.not(post_id: nil).first.post_id
Does the specific `post_id` matter in these tests? Can we use `Post.preload(...).first` instead?

2018-01-29 11:53 UTC, composerinteralia commented on activerecord/test/cases/associations/eager_test.rb
> +  test "preloading works when object that responds to :to_hash is passed" do
Could avoid the passive voice here and write `"preloading works with object that responds to :to_hash"`

2018-01-29 11:53 UTC, composerinteralia commented on activerecord/test/cases/associations/eager_test.rb
> +    custom_symbol = (1..10)
If this specific range is not important to the test, you can use `Object.new`. You could also just use a string or some other object that already responds to `to_sym`.

2018-02-01 04:39 UTC, bpohoriletz commented
thank you for the review @composerinteralia, I've made requested changes

2018-03-03 19:51 UTC, composerinteralia commented
@bpohoriletz it might be worth rebasing this on `master` so you can get a passing travis build.
@eileencodes I left an initial review, but this still needs review by a committer.

2018-03-26 08:10 UTC, bpohoriletz commented
@composerinteralia thank you for the advise, done now

2018-09-26 05:42 UTC, oniofchaos commented
@bpohoriletz looks like this just fell through the cracks, can you fix up the merge conflict?

2018-09-26 12:32 UTC, bpohoriletz commented
@oniofchaos done

2018-09-26 15:28 UTC, oniofchaos commented
@eileencodes would you be able to give this a review? Thanks 💝

2018-09-26 15:40 UTC, merged

2018-09-26 15:42 UTC, eileencodes commented
@bpohoriletz thanks for rebasing.

@oniofchaos I know you mean well, but please don't ping reviewers - I already got one email that Bohdan finished rebasing. Thanks for understanding! ❤️

2018-10-02 07:29 UTC, faucct commented on activerecord/test/cases/associations/eager_test.rb
> +
These aren't the cases you are fixing: the tests work just fine without the changes.