Docs: add_column(.. limit: ) re: datetime
rails/rails pull request #31864
Opened 2018-02-01 17:54 UTC by jaredbeck

Explain the effects of the `limit:` option on `:datetime` columns.

[ci skip]

2018-02-01 22:09 UTC, kamipo commented
Working `:datetime` with `limit` is for backword compatibility.
Should use `precision` instead.

https://github.com/rails/rails/blob/2417f3c53f3e5fb1fbc1f8ba3a75ce65349dc11c/activerecord/test/cases/date_time_precision_test.rb#L38-L44

https://github.com/rails/rails/blob/2417f3c53f3e5fb1fbc1f8ba3a75ce65349dc11c/activerecord/test/cases/time_precision_test.rb#L30-L37

2018-02-01 22:48 UTC, jaredbeck commented
Thanks Ryuta and Rafael, I will make the requested changes.

2018-02-02 17:06 UTC, jaredbeck commented
The requested changes have been made, please review.

2018-02-09 20:48 UTC, jaredbeck commented
> The requested changes have been made, please review.

One week ping, please review. Just docs, should be a quick review.

2018-06-26 17:40 UTC, jaredbeck commented
Four month ping, please review. Just docs, should be a quick review.

2018-06-27 00:54 UTC, sikachu requested changes
Thank you for your patch. I came across your issue and have one small comment.

2018-06-27 00:54 UTC, sikachu commented on activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb
> +      #   * <tt>:datetime</tt> - Number of digits of fractional seconds
Since it's deprecated, I think it's okay to not talking about setting limit on`:datetime` column

2018-06-27 12:03 UTC, jaredbeck commented
> Since it's deprecated, I think it's okay to not talking about setting limit on:datetime column

I believe the goal of documentation is to help people. People have questions about deprecated functionality. Therefore, documentation of deprecated functionality should exist.

2018-10-30 23:08 UTC, jaredbeck commented
Nine month ping. Please merge this helpful docs-only patch, thanks.

2018-12-21 06:02 UTC, jaredbeck commented
>> Since it's deprecated, I think it's okay to not talking about setting limit on:datetime column

> I believe the goal of documentation is to help people. People have questions about deprecated functionality. Therefore, documentation of deprecated functionality should exist.

@sikachu Prem, if you insist, I will remove that line, even though I believe it will help people. Please advise. Let's get *something* into the docs here. Thanks.

2019-12-18 17:21 UTC, jaredbeck commented
> This pull request has been automatically marked as stale ..

Not stale. IIRC, needs a decision re: whether deprecated (but still active) behavior deserves documentation.

2020-03-17 17:43 UTC, jaredbeck commented
Not stale

2020-06-04 01:51 UTC, yskkin commented on activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb
> +      #  # MySQL will use `datetime` and "the default precision is 0"
This is obsolete since #34970

2020-06-04 17:10 UTC, closed without merging