Deprecate `update_attributes` and `update_attributes!`
rails/rails pull request #31998
Opened 2018-02-15 03:07 UTC by elebow

`update_attributes` and `update_attributes!` have been aliases for `update` and `update!` since https://github.com/rails/rails/pull/8705 in 2013. That PR says it was a "soft deprecation" and that the longer method names would be removed in the future.

This would be a desirable change because:
  1. It makes application code easier to read by reducing confusion with `update_attribute`/`update_attribute!`, and
  1. The more direct names help new users understand that these are the "normal" ways to modify attributes of an Active Record object.

Is this still the intention? `update_attributes` is still used in a few tests and one place in `ActiveRecord::InternalMetadata`, and mentioned in the AR Callbacks guide; I can change them to the newer forms in this PR if that is the goal.

2018-02-15 03:56 UTC, sikachu commented
5 years ago, wow ... 

r? @guilleiguaran

2018-02-17 04:39 UTC, rafaelfranca commented
Yeah, I think it is time to deprecate them. Can you remove all the usages and add tests to check if those methods are deprecated?

2018-02-17 17:17 UTC, guilleiguaran requested changes
Please replace all the usages of `update_attributes` with `update` in the test suite

2018-02-17 17:25 UTC, elebow commented on activerecord/test/cases/persistence_test.rb
>      assert_equal topic.title, Topic.find(1234).title
Some of these cases were present in `test_update_attributes` but not in `test_update`. They are now moved to `test_update`.

2018-02-17 20:42 UTC, guilleiguaran approved these changes

2018-02-17 22:01 UTC, closed without merging

2018-02-17 22:04 UTC, jeremy commented
Thanks @elebow!

2018-02-17 22:35 UTC, sgrif commented
Are these aliases causing some sort of maintenance burden? If we actually fully deprecate/remove these methods we are breaking a *lot* of code for virtually no reason. I'm all for keeping them soft-deprecated, but if they aren't causing a maintenance burden I see no reason to actually remove them.

2019-03-02 07:39 UTC, pat commented
Just chiming in to raise the same concerns as @sgrif - I think removing these methods could break a significant amount of code in so many gems, and that feels unwise to me.

I personally didn't know `update` was actually the preferred style until maybe early 2018 - there'd never been any warnings about `update_attributes`, so I know I've taken the 'outdated' approach for quite a long time, and I'm sure plenty of other gem developers have as well.