Add `use_year_name` option to date_select tag
rails/rails pull request #32190
Opened 2018-03-07 15:27 UTC by liwii

### Summary

Add `use_year_name` option to date_select tag.
This option makes it possible to customize year names. Example:

```ruby
    date_select('user_birthday', '', start_year: 1998, end_year: 2000, use_year_names: ["Heisei 10", "Heisei 11", "Heisei 12"])
```

The HTML produced:

```HTML
    <select id="user_birthday__1i" name="user_birthday[(1i)]">
    <option value="1998">Heisei 10</option>
    <option value="1999">Heisei 11</option>
    <option value="2000">Heisei 12</option>
    </select>
    /* The rest is omitted */
```

### Other Information

In Japan, Wareki, the Japanese calender, is used as often as Western Calender. For example, 2000 A.D. is Heisei 12 in Wareki. It is even used in official documents. Therefore, there is a need for date select box with Wareki years. Some other countries like Israel and Thailand also have their own calenders, so I think the number of people who need this `use_year_names` option is not small.

2018-03-07 23:13 UTC, yskkin commented
I also patched `date_select` to achieve this use case and found `year_format_string: "Heisei %d"` is better since we don't have to repeat "Heisei" and it is consistent with `month_format_string` option.

`year_format_string: "%d年"` (meaning "Year %d") or `year_format_string: "FY %d"` is another use case for this feature.

2018-03-07 23:25 UTC, rafaelfranca commented
I agree with @yskkin. But if you need to mix different names it feels like you would be better served with an helper in your application.

2018-03-07 23:35 UTC, yskkin commented
Ah, Western calendar and Japanese calendar are different so we can't handle with `%d`...
I was wrong but still feels that `["Heisei 10", "Heisei 11", "Heisei 12"]` is not a right way.
Now I don't know what is appropriate API...

2018-03-08 07:44 UTC, liwii commented
@yskkin @rafaelfranca @sikachu 
Thanks for your reviews!
Well, I understand what you say. I don't think that this `use_year_names` option is the best way to achieve this goal, either. So at first I thought about implementing this option using `%d` as  @yskkin says, but I couldn't find a simple way to pass different number in `%d` and value of option tag, so I used array. It's the same way as `use_month_names` option, which already exists.
And as @sikachu says, it is true that Wareki is unique problem in Japan. However, I still think that rails needs an option like I proposed (though I don't stick to the format in this PR). In the case of Thai Buddhist calender, to store data properly, the HTML options should be like:

```HTML
<option value="2008">2551</option>
<option value="2009">2552</option>
<option value="2010">2553</option>
```

But now `year` field in date_select doesn't have a way to use different number in option value and what is displayed. Since Western Calender is not the only format of year, I think rails at least needs a way to put different value in these two as in `month` field.

2018-03-08 08:08 UTC, sikachu commented
Actually, one good way that we can achieve this is maybe letting user pass in a proc?

```ruby
date_select('user_birthday', '', start_year: 1998, end_year: 2000, labels_for_year_options: ->{ |year| convert_year_to_wareki(year) ))
```

2018-03-08 08:15 UTC, liwii commented
It seems much better for me. I try to revise my codes in this way.

2018-03-08 09:47 UTC, liwii commented
Adopting @sikachu 's suggestion, I changed my codes and now the option takes Lambda as the argument. If the change is approved, I will squash the commits and change my comment on the commit.

2018-03-08 12:33 UTC, sikachu requested changes
There're just a few issues with the code style. I've left comments in-line.

After reading though it, I feel like `labels_for_year_options` actually a bit mouthful though. I think we can get away with `label_for_year: -> {...}` for brevity.

Nothing else has stood out for me, but if someone who's native English speaker can double check the documentation that'd be superb. I think this is a nice addition! 👍

2018-03-08 12:33 UTC, sikachu commented on actionview/lib/action_view/helpers/date_helper.rb
> +          options[:labels_for_year_options]    = @options[:labels_for_year_options]
I think this line was tagged by code climate. I _think_ we stopped aligning operators, so you can just leave 1 space before `=`.

2018-03-08 12:33 UTC, sikachu commented on actionview/lib/action_view/helpers/date_helper.rb
> +        # If <tt>use_year_names</tt> option is not passed,
Do you mind updating this row to reflect the new setting name?

2018-03-08 12:33 UTC, sikachu commented on actionview/lib/action_view/helpers/date_helper.rb
> +
Code style: Do you mind removing this empty blank line?

2018-03-08 12:33 UTC, sikachu commented on actionview/lib/action_view/helpers/date_helper.rb
> +
Code style: Do you mind removing this empty blank line too?

2018-03-09 01:35 UTC, liwii commented
@sikachu 
I adopted all your suggestion and changed my code style. Thanks for you reviews a lot! As you say, now I wait for some native speakers reviewing my documentation.

2018-03-12 02:03 UTC, matthewd commented
I think there's room to more closely mirror the month handling:

* I suggest we call the option `:year_format`, similar to the existing `:month_format_string`.
* A `year_name(number)` method can take care of the lambda, and also fall back to `number` -- better to always use one code path instead of sometimes using `build_options`.

However, I'm a bit unsure whether it's worthwhile for us to support this... it's absolutely true that there are a number of other calendar systems, but this only helps the (small?) subset of those that still use Gregorian day/month numbering, and [at least approximately] agree that the year starts on Jan 1.

On balance I think it's probably okay -- we do already provide a lot of formatting options on this helper.

2018-03-15 10:34 UTC, sikachu commented
Yeah, I feel like it's worthwhile to add support for this as well. And yeah, I agree with calling the option `:year_format`.

@liwii would you mind updating the PR per @matthewd's request and update your branch? I think it needs a rebase as well due to CHANGELOG conflict. Thanks!

2018-03-15 14:56 UTC, liwii commented
@matthewd 
Thanks for your review. I agree that your suggestion will make my new option more close to existing month handling. I will adopt your suggestion and update my branch soon.
@sikachu 
Thanks for making comments a lot of times.  Of course I don't mind adopting @matthewd's request and resolving conflicts. I will commit the change immediately.

2018-03-15 15:24 UTC, liwii commented
@matthewd @sikachu 
I adopted all your suggestions and squashed all the commits!

2018-04-03 15:12 UTC, liwii commented
@sikachu @matthewd 
I also resolved conflicts heppened during waiting the reviews. Do I need to do anything addtionally?

2018-06-08 08:41 UTC, sikachu approved these changes
Thank you for updating the patch!

@matthewd do you mind taking care of this forward? I think this is good to go.

2018-06-10 11:50 UTC, liwii commented
I found needles `options[:year_format] = @options[:label_for_year]` in `DatetimeSelector#select_year`, so I removed it. Tracis CI started to fail, but the error doesn't seem relevant to my modification...

2018-06-10 11:58 UTC, kamipo commented
CI failure has been addressed at 691addbffad10aa249d5fb1b0e47b46a086e5332.

2018-06-10 11:59 UTC, kamipo commented on actionview/lib/action_view/helpers/date_helper.rb
> +        #   month_name(1998) # => 1998
`year_name(1998)`

2018-06-10 11:59 UTC, kamipo commented on actionview/lib/action_view/helpers/date_helper.rb
> +        #   month_name(1998) # => "Heisei 10"
`year_name(1998)`

2018-06-10 12:10 UTC, liwii commented
@kamipo 
Thanks for your review! Now I took `691addb` into my branch so maybe CI problem is resolved.
I also fixed the typo you pointed out.

2018-06-21 01:11 UTC, sikachu commented
@kamipo do you have any further feedback? Is this ready to be merged in?

2018-06-21 07:28 UTC, kamipo commented
Yeah, I think this is ready to be merged in.

2018-06-21 07:28 UTC, kamipo approved these changes

2018-06-21 07:31 UTC, sikachu commented
@kamipo would you mind merging this in? (I'm in issues team so I don't have permission to merge 🙇)

2018-06-21 08:04 UTC, merged