Add assertion methods for Rails loggers to public API
rails/rails pull request #32234
Opened 2018-03-13 04:40 UTC by JackMc

This adds two assertion methods for asserting logging behaviour.

### Summary

When working on a gem internally, I found that there are no methods in Rails to check if a message has been logged to the Logger, but that one already existed in one of ActionView's test suite helper: https://github.com/rails/rails/blob/309bb6c4d068b0d480681cf4ef1b90158527dfe5/actionview/test/template/digestor_test.rb#L304-L317 This pulls them up into public API.

### Questions

* Are there tests for these methods? I can't find any but am totally willing to write them if they're tested.

2018-04-21 23:02 UTC, georgeclaghorn requested changes
Yes, these methods need tests. You can add them to [this file](https://github.com/rails/rails/blob/a7491b73f830be093fd35740c377d65235078321/activesupport/test/test_case_test.rb).

2018-04-21 23:02 UTC, georgeclaghorn commented on activesupport/lib/active_support/testing/assertions.rb
> +          assert_match message, log.read, message
I think you intend to pass `regex` as the first argument here (and perhaps accept an optional `message` parameter above).

2018-04-21 23:02 UTC, georgeclaghorn commented on activesupport/lib/active_support/testing/assertions.rb
> +          assert_no_match message, log.read
Ditto: you intend to pass `regex` here. If `assert_logs` accepts a message parameter, so should `assert_no_logs`.

2018-04-21 23:02 UTC, georgeclaghorn commented on activesupport/lib/active_support/testing/assertions.rb
> +      end
Let’s move these methods to the bottom of the file.

2018-10-11 15:47 UTC, rafaelfranca commented
This is by design. I don't recall when we decided this but the idea is that applications should not care about asserting logs. If the logs are so important that meeds to be asserted they should be using notifications and a logger subscriber that already has public test helpers https://github.com/rails/rails/blob/2fe995eb278e833251bc39533a61cd87a99b84e3/activesupport/lib/active_support/log_subscriber/test_helper.rb.

Thank you for the pull request.

2018-10-11 15:47 UTC, closed without merging