Permit using the AWS Credentials Provider chain for S3 storage
rails/rails pull request #32270
Opened 2018-03-16 15:20 UTC by brianknight10

### Summary

Allow the use of the AWS Credentials Provider chain for S3 storage. If an explicit AWS `access_key_id` and `secret_access_key` are not provided in `storage.yml`, attempt to use environment variables, shared credentials, or IAM (instance or task) role credentials. Order of precedence is determined by the AWS SDK.

Access key ids and secret keys provided in `storage.yml` take precedence over any other credentials. Therefore, this change will not have any upgrade impact.

**Thank you for the consideration**

2018-03-16 16:29 UTC, pixeltrix commented
@brianknight10 thanks for this - we should also allow the region to be set from the shared config.

2018-03-16 17:53 UTC, brianknight10 commented
Thanks @pixeltrix - I've added that functionality in another commit. This one is a little trickier because not all shared credentials may have a `region` specified.

The code now looks in the following order:

1. The `region` setting in `storage.yml`
2. The `AWS_REGION` environment variable
3. The `AWS_DEFAULT_REGION` environment variable
4. Uses the `us-east-1` region by default - that is the "AWS Standard" region for S3.

Again, this should not have any impact on existing users because the `region` setting is required currently.

2018-03-17 03:47 UTC, georgeclaghorn commented on activestorage/lib/active_storage/service/s3_service.rb
> +
:scissors: this blank line.

2018-03-19 12:20 UTC, brianknight10 commented on activestorage/lib/active_storage/service/s3_service.rb
> +
OK - blank line ✂️

2018-03-19 12:58 UTC, pixeltrix commented
@brianknight10 I wonder if we're going about this the wrong way - the S3 client will do all of this credential resolution for us if we don't supply the access_key_id, secret_access_key and region options. What if we just change the `initialize` method to this:

``` ruby
def initialize(bucket:, upload: {}, **options)
  @client = Aws::S3::Resource.new(**options)
  @bucket = @client.bucket(bucket)

  @upload_options = upload
end
```

This allows you to specify a profile in your storage.yml file then, e.g:

``` yaml
s3:
 service: S3
 bucket: "activestorage"
 profile: "rails"
```

Also the all the environment vars will work too without us having to think about it. If you still want to explicitly add the access details to the YAML file then that still works too.

2018-03-19 13:13 UTC, brianknight10 commented
@pixeltrix - that certainly is much cleaner. I'll push another commit to make it so.

2018-03-19 13:50 UTC, pixeltrix requested changes
👍 - can you just fix the last few changes. Also we should [update the guides as well].(http://edgeguides.rubyonrails.org/active_storage_overview.html#amazon-s3-service)

2018-03-19 13:50 UTC, pixeltrix commented on activestorage/lib/active_storage/service/s3_service.rb
> +require "aws-sdk-core"
Can you remove this require - it's not needed

2018-03-19 13:50 UTC, pixeltrix commented on activestorage/test/service/s3_service_test.rb
> +if SERVICE_CONFIGURATIONS[:s3] && SERVICE_CONFIGURATIONS[:s3][:service].present?
I think we can just change this to `if SERVICE_CONFIGURATIONS[:s3]`

2018-03-19 13:50 UTC, pixeltrix commented on activestorage/CHANGELOG.md
> +
Can you update this entry to reflect the final changes, thanks.

2018-03-19 14:33 UTC, brianknight10 commented
Absolutely - these changes have been made (including the Edge guide)

2018-03-19 14:44 UTC, pixeltrix approved these changes

2018-03-19 15:25 UTC, merged

2018-03-19 15:29 UTC, pixeltrix commented
Backported in 2a4a97b96c3a3aa0dfbc2007b06084a50fdf3443