Flip the order of the after_create callbacks
rails/rails pull request #32317
Opened 2018-03-22 03:17 UTC by dwightwatson

### Summary

This is an attempt to fix #32247 by flipping the after_create callbacks to avoid a race condition. Because `after_create_commit` calls it's callbacks in reverse order we should identify the blob before queuing any jobs.

2018-03-22 22:15 UTC, rafaelfranca approved these changes
This make sense to me. Can we add a test case in some way.

2018-03-22 23:33 UTC, dwightwatson commented
Hard thing to write a test but I managed to write a failing test and then made it green by flipping the order like this PR does. It looks like `create_file_blob` already identifies the blob so I forcefully clear it's metadata and then let the callbacks run. I then check to ensure that the metadata for identification and analysation are both present.

2018-03-23 02:03 UTC, georgeclaghorn requested changes

2018-03-23 02:03 UTC, georgeclaghorn commented on activestorage/test/models/attachments_test.rb
> +    end
The situation in which we actually take this code path is attaching a directly-uploaded blob, so I‘d prefer to simulate a direct upload like we do in the test above (`test "identify newly-attached, directly-uploaded blob"`). This is a good opportunity to extract a new helper method with an intention-revealing name for both tests to use.

2018-03-23 03:17 UTC, dwightwatson commented
Thanks George, I've broken out a new test helper called `simulate_direct_upload_blob` which is now used in both tests.

2018-03-27 01:19 UTC, georgeclaghorn requested changes

2018-03-27 01:19 UTC, georgeclaghorn commented on activestorage/test/test_helper.rb
> +    end
Parameterize the blob attributes so this method may be used for other file fixtures without modification:

```ruby
def directly_upload_file_blob(filename: "racecar.jpg", content_type: "image/jpeg")
  file = file_fixture(filename)
  byte_size = file.size
  checksum = Digest::MD5.file(file).base64digest

  create_blob_before_direct_upload(filename: filename, byte_size: byte_size, checksum: checksum, content_type: content_type).tap do |blob|
    ActiveStorage::Blob.service.upload(blob.key, file.open)
  end
end
```

2018-03-27 01:19 UTC, georgeclaghorn commented on activestorage/test/models/attachments_test.rb
> +    blob = simulate_direct_upload_blob
It’s relevant to this test and the new one below it that the directly-uploaded blob’s content type is `"application/octet-stream"`. They should both pass that value in as a parameter.

2018-03-27 01:52 UTC, georgeclaghorn approved these changes
Could you please squash your commits into one?

2018-03-27 02:34 UTC, merged

2018-03-27 13:13 UTC, georgeclaghorn commented
Backported in 7370307.