Don't hardcode the master key path in its generator
rails/rails pull request #32580
Opened 2018-04-15 12:07 UTC by davidstosik

Instead, do as [`Rails::Generators::CredentialsGenerator`](https://github.com/rails/rails/blob/5-2-0/railties/lib/rails/generators/rails/credentials/credentials_generator.rb) and get the path from `credentials.key_path`.

2018-04-16 05:55 UTC, y-yagi commented
We already have the encrypted command to manage the credentials for each environment.
https://github.com/rails/rails/blob/master/railties/lib/rails/commands/encrypted/encrypted_command.rb
http://api.rubyonrails.org/classes/Rails/Application.html#method-i-encrypted

Is there something wrong with this?

2018-04-16 06:29 UTC, davidstosik commented
> We already have the encrypted command to manage the credentials for each environment.

Indeed, with the encrypted command (which I just learned about, thanks!), I could do this:

```sh
bin/rails encrypted:edit config/foobar.yml.enc
# Edit a new encrypted file using the master key

RAILS_MASTER_KEY=`cat config/master.development.key` bin/rails encrypted:edit config/credentials.development.yml.enc
# Edit development credentials
```

I guess it's mainly about convenience and consistency.
With the suggestion I have in this PR, and following the customisation I have in my post above, at the application level, I'd be able to run `bin/rails credentials:edit` anywhere, assuming that `RAILS_ENV` is set.

Also it feels a bit weird to me that the `master.key` filename/path would be hardcoded in multiple places in the app. Relying on want is already defined somewhere else, when it is, feels like an improvement to me?

2018-04-19 20:32 UTC, rafaelfranca requested changes

2018-04-19 20:32 UTC, rafaelfranca commented on railties/lib/rails/generators/rails/master_key/master_key_generator.rb
> +          @master_key_path ||= if Rails.respond_to?(:application)
Having to check for `Rails.respond_to?(:application)` here is a smell that this is in the wrong place. Generators have configs, so if we want to respect an application config in a generator, the application that should be passing the config to the generate, not the generator asking for the application.

2018-04-23 15:55 UTC, dixpac commented
This looks great. One thing I'm not sure about is, whether development credentials need to be encrypted !?

2018-07-08 11:56 UTC, kaspth commented
Really nice simple way of giving people the opportunity to have per-env credentials! Won't the credentials generator need to be updated as well?

2019-01-31 07:49 UTC, morgoth commented
@davidstosik is this still relevant after https://github.com/rails/rails/pull/33521 being merged?

2019-01-31 08:13 UTC, davidstosik commented
@morgoth Oooh, that looks pretty good! I believe your PR answers my main issue. 👍

2019-01-31 08:13 UTC, closed without merging