Convert ActionCable library from CoffeeScript to JavaScript
rails/rails pull request #33380
Opened 2018-07-17 16:57 UTC by varyonic

In response to #33331

2018-07-17 18:24 UTC, rafaelfranca commented
If we would do this, and only if, it would be to use ES6 like Active Storage do. Changing CoffeScript with ES5 is not buying us anything,

2018-07-17 20:13 UTC, javan commented
I agree with @rafaelfranca and suggest using the exact rollup+babel+eslint rig from Active Storage: https://github.com/rails/rails/blob/e13e16f5adf3221f4a95e7d105efb2d5e56c0b53/activestorage/package.json#L35-L38

2018-07-17 22:40 UTC, rafaelfranca commented
Great! @varyonic are you going to work on it?

2018-07-20 15:06 UTC, varyonic commented
@javan Does Blade need to be replaced with Karma or similar here? If so any examples I should look at for guidance?

2018-07-27 21:35 UTC, javan requested changes
Great start!

Generally, the code feels like a direct translation of the CoffeeScript and not necessarily how you'd write it from scratch in ES6.

> Does Blade need to be replaced with Karma or similar here?

Yes, please. :) We should remove Blade / Sprockets dependencies entirely. I'll try to find you a good example to reference.

2018-07-27 21:35 UTC, javan commented on actioncable/app/javascript/actioncable/helpers.js
> +    return this.logger.log("[ActionCable]", ...Array.from(messages))
Don't need `Array.from()` here: `this.logger.log("[ActionCable]", ...messages)`

2018-07-27 21:35 UTC, javan commented on actioncable/app/javascript/actioncable/connection_monitor.js
> +let clamp = undefined
No need to start these out `undefined` and then set them later (immediately, basically).

2018-07-27 21:35 UTC, javan commented on actioncable/app/javascript/actioncable/helpers.js
> +}
The `debugging` flag should only be set on the top level object, but these will set it on whatever happens to be `this`. I'd avoid using `this` in helpers, generally.

2018-07-27 21:35 UTC, javan commented on actioncable/app/javascript/actioncable/index.js
> +    url = (left = this.getConfig("url")) != null ? left : this.INTERNAL.default_mount_path }
Is `INTERNAL` defined anywhere? Will need some kind of setup to replace: https://github.com/rails/rails/blob/45903be1344992b1f0156cd88c351067bdc93726/actioncable/app/assets/javascripts/action_cable.coffee.erb#L5-L6

2018-07-27 21:35 UTC, javan commented on actioncable/app/javascript/actioncable/subscriptions.js
> +      for (let subscription of Array.from(this.findAll(identifier))) {
I *think* there are browsers that support `WebSocket`, but not `Array.from()` so we should avoid using it if possible.

2018-08-03 16:08 UTC, varyonic commented on actioncable/app/javascript/actioncable/connection.js
> +  static initClass() {
Is this valid ES6? The code feels like a direct translation because it is. I was hoping to have working tests before refactoring.

2018-08-03 16:15 UTC, varyonic commented
I added and configured karma-qunit but the tests are erroring "Uncaught Error: pushFailure() assertion outside test context" I think that's something to do with mock-socket not being setup correctly but I don't understand how to troubleshoot it.

2018-08-12 15:58 UTC, javan commented on actioncable/app/javascript/actioncable/connection.js
> +  static initClass() {
Not yet… You can use the [transform-class-properties](https://babeljs.io/docs/en/babel-plugin-transform-class-properties/) Babel plugin. Or, just assign those properties after the class definition:
```js
export class Connection {  
  // …
}

Connection.reopenDelay = 500
```

2018-08-12 16:09 UTC, javan commented
For the Karma setup, I think it'd be more straightforward to compile a single .js file *first* and then start the runner. That way you don't need to muck around with requirejs and stash a list of a files globally. See https://github.com/josh/selector-observer for a good example of this.

2018-09-28 06:14 UTC, oniofchaos commented
Two thoughts:

1) Is this something that could be done on a more incremental level so it's not one big PR that sits around for ages?

2) Does it need to be tagged with the Rails 6 milestone?

2018-09-28 12:31 UTC, closed without merging

2018-11-16 18:38 UTC, varyonic commented
See #34177