Document best practices with old migrations
rails/rails pull request #33474
Opened 2018-07-30 15:03 UTC by olivierlacan

The copy here is of course up for discussion but it feels like we need
to address the issue of old migrations in the Migration guide because
other than mentioning the canonical nature of schema.rb/structure.sql
or the actual database compared to migration files, it seems like more
guidance would help.

Here's a sample of the kinds of question people seem to often ask about
old Rails migrations:

- https://stackoverflow.com/questions/20119391/delete-old-migrations-files-in-a-rails-app
- https://www.reddit.com/r/rails/comments/4ayosd/compacting_migrations_files_or_delete_them/
- https://stackoverflow.com/questions/4248682/is-it-a-good-idea-to-purge-old-rails-migration-files
- https://stackoverflow.com/questions/707013/is-it-a-good-idea-to-collapse-old-rails-migrations
- https://stackoverflow.com/questions/1981777/rails-remove-old-models-with-migrations
- https://stackoverflow.com/questions/3343534/rebase-rails-migrations-in-a-long-running-project

The common theme seems to be: "I've got old migrations, should I keep
them around on an old project?".

My personal stance is that as long as migrations run and don't take too long do
so, you should keep them around since it allows people working on the Rails
project with you to seamlessly upgrade their local development database
without having to do a `db:drop db:schema:load` and lose all their seed data.

While writing down this suggested new section it felt like I was describing a
very cumbersome process that could be address with a rake task like:

```bash
rails db:migrate:remove VERSION=20121201123456
```

It rollback to the version just before `20121201123456`, delete the migration
file, and run `db:migrate` to get back to the latest migration.

This of course doesn't address a situation when someone would want to delete or
merge all migrations prior to a certain date, which is addressed by
[squasher](https://github.com/jalkoby/squasher).

I'm not sure this is something we want to encourage people to do. Although I
feel like with more and more production Rails apps over 5-years old, it's
definitely a concern we should address.

2018-07-30 19:46 UTC, eileencodes requested changes

2018-08-03 11:00 UTC, olivierlacan commented
@matthewd Let me know if the copy seems reasonable to you now.

2018-08-03 13:15 UTC, matthewd commented
Immediate thoughts are 
1) it might be worth adding an "and that's okay" to the new bit about missing files -- i.e., that while that message will show up, it's not alarming, and as long as you're expecting it, doesn't indicate anything bad; and 
2) if we're going to acknowledge that deleting the files is reasonable, we should perhaps include a warning to be sure the migration has been run on all extant environments: the big danger in deleting migrations is that if you delete a middle migration that has been run in some places but not others, you will end up with two databases that both think they're up to date, but are structurally different.

2018-08-11 19:54 UTC, schneems commented
I agree with MD. I also think this is a good place to start. Thanks for the PR!

2018-08-11 19:54 UTC, merged