Allow users to supply a non-global binary for dumps/loads
rails/rails pull request #34399
Opened 2018-11-07 21:33 UTC by krainboltgreene

### Summary

Subshells can have a very difficult time with localized binaries, see: asdf or similar. `run_cmd()` eventually calls `Kernel.system()` which uses `/bin/sh`, which has it's own path.  This can cause a lot of frustration as it uses the wrong/nonexistant global-to-sh `pg_dump` or `psql`. Instead, the user should be allowed to specify the location of the command.

Here's what's left for this PR:

  - Do this for all other db tasks
  - (possibly) Store this as part of database.yml instead of env variable?
  - (possibly) Make this metamagicy AKA `run_cmd("psql", ...)` automatically looks up `PSQL_PATH` or something?

2018-11-07 21:38 UTC, krainboltgreene commented
To test this locally you can do:

```
PG_DUMP_COMMAND=`which pg_dump` bin/rake db:structure:dump
```

2018-11-09 23:49 UTC, gmcgibbon requested changes
Please add tests and a changelog entry to ActiveRecord for this to be mergeable.

2018-11-10 01:14 UTC, rafaelfranca commented
I'm not sure if we want this in the codebase. If this is a problem with those executables I'm pretty sure it will be a problem to others too. I don't think we should be spreading a lot of environment variables through the code to support wrong/nonexistant global-to-sh executables. Rails assumes those things are in your path. If they are not you should put it.

2018-11-10 01:34 UTC, krainboltgreene commented
Yeah, I specifically only wrote the bare implementation because this is very much not usual for rails and I wanted insight before committing time.

@rafaelfranca It's not so easy to put those in the path because Kernal.system() uses `sh` which has it's own path.

Would it be reasonable to look at `bin/pg_dump` before trying for a *global* command?

2018-11-10 01:41 UTC, rafaelfranca commented
Yes, but what would we do in case it is not existent? We would still have to raise an error and in the case point users to add things to the path of `sh`.

2018-11-10 04:10 UTC, krainboltgreene commented
I spent an hour in vain trying to do exactly that and couldn't get it to
work. It doesn't help that sh carries over environment variables making it
seem like I'm in my normal shell.

On Fri, Nov 9, 2018, 5:42 PM Rafael França <notifications@github.com wrote:

> Yes, but what would we do in case it is not existent? We would still have
> to raise an error and in the case point users to add things to the path of
> sh.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rails/rails/pull/34399#issuecomment-437547162>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAUb2TFuKrF-aQFIbQXpP_CrKw7kfZtJks5uti78gaJpZM4YTYiS>
> .
>

2018-11-13 18:29 UTC, rafaelfranca commented
Can't you set in the `/etc/profile` file?

2018-11-13 20:24 UTC, krainboltgreene commented
I guess that's the one thing I didn't do. I did ~/.profile, ~/.bashrc, and ~/.bash_profile. I also spent half an hour thinking it was using my zsh setup, so ~/.zshrc, ~/.zlogin, and ~/.zprofile.

In the end, because I didn't have a global binary, I should have forced my global profile to have something specific to my user.

2019-12-25 05:39 UTC, closed without merging