Fixes unscoping the where clause when it has an array `default_scope`…
rails/rails pull request #34679
Opened 2018-12-11 19:34 UTC by jemminger

### Summary

Fixes https://github.com/rails/rails/issues/30967

2018-12-14 21:47 UTC, jemminger commented on activerecord/test/models/post.rb
> +class PostWithArrayDefaultScope < ActiveRecord::Base
In my testing, the bug only arises when the model has the array where condition in a default_scope.

2018-12-14 21:48 UTC, jemminger commented on activerecord/test/cases/scoping/default_scoping_test.rb
> +  def test_unscoping_an_array_default_column
In my testing, the bug only arises when the model has the array where condition in a default_scope.

2018-12-14 21:50 UTC, jemminger commented on activerecord/lib/active_record/relation/where_clause.rb
> +          relevant_nodes = [Arel::Nodes::Between, Arel::Nodes::In, Arel::Nodes::NotIn, Arel::Nodes::Equality, Arel::Nodes::NotEqual, Arel::Nodes::LessThan, Arel::Nodes::LessThanOrEqual, Arel::Nodes::
Yes, I misunderstood and made the node tester a constant.  Will fix

2018-12-14 21:50 UTC, jemminger commented on activerecord/lib/active_record/relation/where_clause.rb
> +      NODE_TESTER = -> (node, columns) {
Will fix

2018-12-14 21:55 UTC, jemminger commented on activerecord/lib/active_record/relation/where_clause.rb
> +              node.each do |n|
Will do

2018-12-20 17:48 UTC, jemminger commented
@gmcgibbon Can you take a quick look at this?  I don't think my changes are causing the CI failures.

2019-11-12 18:24 UTC, adbatista commented
@gmcgibbon I'm having the same problem, is there a chance of this being released any time soon?

2019-11-12 18:28 UTC, stanleeDK commented
Hi Alessandro,

Would you mind removing Stan Lee from this repo. He no longer works at
BuildZoom, but his github is associated with this email and we haven't been
able to get him unsubscribed so we are getting frequent mails to our
catchall.

Thanks!

On Tue, Nov 12, 2019 at 10:26 AM Alessandro Dias Batista <
notifications@github.com> wrote:

> @gmcgibbon <https://github.com/gmcgibbon> I'm having the same problem, is
> there a chance of this being released any time soon?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rails/rails/pull/34679?email_source=notifications&email_token=ADDPT7WS75YI56KSRFFGHQDQTLYNJA5CNFSM4GJYLUGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOED3JUGQ#issuecomment-553032218>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADDPT7X5ZZOQSL5IBGWGHATQTLYNJANCNFSM4GJYLUGA>
> .
>

2019-11-13 22:47 UTC, gmcgibbon requested changes

2019-11-13 22:47 UTC, gmcgibbon commented on activerecord/lib/active_record/relation/where_clause.rb
> +            when *EXCEPT_PREDICATE_NODES
This works, but I think it obfuscates the real problem. `Arel.fetch_attribute` doesn't parse attributes from node groups correctly. You can do something like this to fix that more directly with recursion:
```diff
--- a/activerecord/lib/arel.rb
+++ b/activerecord/lib/arel.rb
@@ -46,10 +46,18 @@ def self.arel_node?(value) # :nodoc:
     value.is_a?(Arel::Node) || value.is_a?(Arel::Attribute) || value.is_a?(Arel::Nodes::SqlLiteral)
   end

-  def self.fetch_attribute(value) # :nodoc:
+  def self.fetch_attribute(value, &block) # :nodoc:
     case value
-    when Arel::Nodes::Between, Arel::Nodes::In, Arel::Nodes::NotIn, Arel::Nodes::Equality, Arel::Nodes::NotEqual, Arel::Nodes
::LessThan, Arel::Nodes::LessThanOrEqual, Arel::Nodes::GreaterThan, Arel::Nodes::GreaterThanOrEqual
-      yield value.left.is_a?(Arel::Attributes::Attribute) ? value.left : value.right
+    when Arel::Nodes::Between, Arel::Nodes::In, Arel::Nodes::NotIn, Arel::Nodes::Equality,
+         Arel::Nodes::NotEqual, Arel::Nodes::LessThan, Arel::Nodes::LessThanOrEqual,
+         Arel::Nodes::GreaterThan, Arel::Nodes::GreaterThanOrEqual
+      if value.left.is_a?(Arel::Attributes::Attribute)
+        block.call(value.left)
+      else
+        block.call(value.right)
+      end
+    when Arel::Nodes::Grouping
+      fetch_attribute(value.expr.left, &block) unless value.expr.is_a?(Arel::Nodes::SqlLiteral)
     end
   end
```

2019-11-13 22:47 UTC, gmcgibbon commented on activerecord/test/cases/scoping/default_scoping_test.rb
> +  def test_unscoping_an_array_default_column
I think this is better put in `relations_test`, you also don't need a subclass or scope:

```ruby
def test_unscope_grouped_where
  posts = Post.where(
    title: ["Welcome to the weblog", "So I was thinking", nil]
  )

  assert_equal 2, posts.count
  assert_equal Post.count, posts.unscope(where: :title).count
end
```

2019-11-21 22:47 UTC, closed without merging