lazy init response parser
rails/rails pull request #34684
Opened 2018-12-12 08:56 UTC by abhisheksarka

### Summary
Issue: https://github.com/rails/rails/issues/34676

2018-12-12 17:30 UTC, gmcgibbon requested changes
Can you give @tbuehlmann credit since you're just applying his diff? Also can you add a test and changelog entry?

2018-12-12 17:45 UTC, kamipo commented
Also, can you add a test case?

2018-12-13 03:57 UTC, abhisheksarka commented
Makes sense! Will do!

2018-12-13 10:56 UTC, kaspth commented on actionpack/lib/action_dispatch/testing/test_response.rb
> -      @response_parser = RequestEncoder.parser(content_type)
No reason to keep the initialize method after this.

2018-12-13 19:33 UTC, tbuehlmann commented
Not sure how to feel about this. But well, go ahead.

2018-12-13 19:42 UTC, brandondees commented
consider https://help.github.com/articles/creating-a-commit-with-multiple-authors/ ?

2018-12-13 22:08 UTC, kaspth commented
@abhisheksarka it's great that you want to contribute, but unfortunately you've hit a somewhat unspoken truth in open source: it's not just about the code, but also how the code gets contributed.

Which brings us to how to attribute credit to a change. And sidestepping @tbuehlmann after @rafaelfranca specifically asked him to open a PR, copying his suggested patch without at least an attempt to also give credit leaves a sour taste for the PR context.

As such, I've decided to let @tbuehlmann take over in his own PR first and should that stall we can put it up for grabs. Thanks!

2018-12-13 22:08 UTC, closed without merging

2018-12-14 03:50 UTC, abhisheksarka commented
@tbuehlmann Go ahead man, my bad to begin with. @kaspth It makes perfect sense and I agree with you guys. Just started with the rails source code and thought of taking up the small stuff so came across this PR. Did not give a lot of thought to how it is being contributed. Will keep this in mind going forward

2018-12-14 04:09 UTC, abhisheksarka commented
@tbuehlmann Go ahead man, my bad to begin with. @kaspth Just started with the rails source code and thought of taking up the small stuff so came across this PR. Did not give a lot of thought to how it is being contributed. Will keep this in mind going forward