Add more Ruby `2.6.0` and `head` on CI matrix
rails/rails pull request #34802
Opened 2018-12-26 23:17 UTC by bogdanvlviv

This PR adds a few builds on CI with Ruby `2.6.0` and `head` versions.

2018-12-26 23:20 UTC, georgeclaghorn requested changes

2018-12-26 23:20 UTC, georgeclaghorn commented on .travis.yml
> +      env: "GEM=actionview:ujs"
The UJS tests don’t cover any Ruby code, so they don’t need to run against all supported Ruby versions.

2018-12-27 10:57 UTC, bogdanvlviv commented on .travis.yml
> +        - "GEM=activerecord:mysql2 MYSQL=mariadb"
I see. I thought that we are missing these build for the latest stable Ruby, unintentionally. Seems like adding those build for `ruby-head` still makes sense, right?

2018-12-27 11:13 UTC, kamipo commented on .travis.yml
> +        - "GEM=activerecord:mysql2 MYSQL=mariadb"
IMO no. sqlite3_mem and mariadb are for just exercising the difference sqlite3/sqlite3_mem and mysql/mariadb.
I'd say the filling matrix for them is expensive for that purpose.

2018-12-27 11:17 UTC, bogdanvlviv commented on .travis.yml
> +        - "GEM=activerecord:mysql2 MYSQL=mariadb"
Gotcha. I'm closing this PR for now.

2018-12-27 11:17 UTC, closed without merging