Fix 35114
rails/rails pull request #35145
Opened 2019-02-03 15:48 UTC by st0012

### Summary
This is for #35114 
Partial caching doesn't return the right collection when some of the items are repeated.

Let's say we have this template:

```erb
<%= cached_set.first %> | <%= cached_set.second %> | <%= cached_set.third %> | <%= cached_set.fourth %> | <%= cached_set.fifth %>
```

And a `cached_set` collection:

```ruby
[1,2,3,4,5],
[1,2,3,4,4],
[1,2,3,4,5],
[1,2,3,4,4],
[1,2,3,4,6]
```

On current master, the rendered result will be
```
      "1 | 2 | 3 | 4 | 5",
      "1 | 2 | 3 | 4 | 4",
      "1 | 2 | 3 | 4 | 6"
```

The duplicated items are ignored.

This is because we only use hash to maintain the result. So when the key are the same, the result would be skipped.

2019-04-01 14:06 UTC, st0012 commented
@amatsuda are you willing to give this a quick scan if you have time? I'd really appreciate it 🙇

2019-04-03 00:00 UTC, rafaelfranca commented on actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb
> +        @ordered_keys = []
Instead of building this instance variable here and using in other methods we should return it and pass around.

2019-04-03 02:32 UTC, st0012 commented
@rafaelfranca updated

2019-04-03 21:33 UTC, rafaelfranca requested changes
Can you squash your commits?

2019-04-04 02:00 UTC, st0012 commented
@rafaelfranca done

2019-04-04 03:03 UTC, merged