Update links and code examples in the guides to use HTTPS
rails/rails pull request #35492
Opened 2019-03-06 03:05 UTC by nsuchy

### Summary

Since many of the guide articles were initially written, HTTPS adoption on the internet has skyrocketed. Likewise many hosts that used to not, now do support HTTPS. This patch goes through links in the guides and changes them to use HTTPS.

Additionally if in a code example in a guide article references a website with http that supports https, the link inside the code example was changed to use HTTPS.

### Other Information

N/A

2019-03-06 06:31 UTC, sikachu requested changes
I found some typos. Would you mind fixing them so I can merge in?

Thank you for the patch!

2019-03-06 06:31 UTC, sikachu commented on guides/source/i18n.md
> +Rails contains infrastructure for "centralizing dynamic decisions about the URLs" in its [`ApplicationController#default_url_options`](s/classes/ActionDispatch/Routing/Mapper/Base.html#method-i-defau
This one has a typo.

```suggestion
Rails contains infrastructure for "centralizing dynamic decisions about the URLs" in its [`ApplicationController#default_url_options`](https://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Base.html#method-i-default_url_options), which is useful precisely in this scenario: it enables us to set "defaults" for [`url_for`](https://api.rubyonrails.org/classes/ActionDispatch/Routing/UrlFor.html#method-i-url_for) and helper methods dependent on it (by implementing/overriding `default_url_options`).
```

2019-03-06 06:31 UTC, sikachu commented on guides/source/routing.md
> +******DO NOT READ THIS FILE ON GITHUB, GUIDES ARE PUBLISHED ON https://guides.rubyonrails.org.**
Would you mind undo this change?

```suggestion
**DO NOT READ THIS FILE ON GITHUB, GUIDES ARE PUBLISHED ON https://guides.rubyonrails.org.**
```

2019-03-06 14:38 UTC, vipulnsward commented
Hi @nsuchy please squash your commits

2019-03-06 14:59 UTC, nsuchy commented
Isn’t that what GitHub’s squash and merge is for? I can squash on my end if necessary although context on why would be nice. I have to attend a meeting (about 90 minutes) then I’ll take care of final touches to this PR :))

Cordially,
Nathaniel Suchy



Mar 6, 2019, 9:54 AM by notifications@github.com:

>
> Hi > @nsuchy <https://github.com/nsuchy>>  please squash your commits
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, > view it on GitHub <https://github.com/rails/rails/pull/35492#issuecomment-470130567>> , or > mute the thread <https://github.com/notifications/unsubscribe-auth/AH2LOX1co9ATjTu5chsJa_yS5DTHQepfks5vT9aOgaJpZM4bf88u>> .
>

2019-03-06 20:23 UTC, nsuchy commented
@vipulnsward Per your request the commits were squashed on my end.

2019-03-06 20:45 UTC, merged

2019-03-08 09:58 UTC, abhaynikam commented
@sikachu @vipulnsward : Sorry for tagging on close PR. I can still see `http` links in some places like 
- https://github.com/rails/rails/blob/master/.github/pull_request_template.md
- https://github.com/rails/rails/blob/master/actioncable/actioncable.gemspec#L18

Is it fine if I update those to `https` and raise a PR?

2019-03-08 10:20 UTC, vipulnsward commented
Sure, please do

On Fri, Mar 8, 2019 at 3:28 PM Abhay Nikam <notifications@github.com> wrote:

> @sikachu <https://github.com/sikachu> @vipulnsward
> <https://github.com/vipulnsward> : Sorry for tagging on close PR. I can
> still see http links in some places like
>
>    -
>    https://github.com/rails/rails/blob/master/.github/pull_request_template.md
>    -
>    https://github.com/rails/rails/blob/master/actioncable/actioncable.gemspec#L18
>
> Is it fine if I update those to https and raise a PR?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/rails/rails/pull/35492#issuecomment-470872285>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAipSkq5pYYNmDn0JhBywnfZRFBFjoe4ks5vUjRBgaJpZM4bf88u>
> .
>