Cache database version in schema cache
rails/rails pull request #35795
Opened 2019-03-29 19:55 UTC by alimi

### Summary

This PR comes out of the feedback in #35767. I opened this as a new PR because I didn't want to get tripped up by my previous work.

In this PR, the database version will be cached in the schema cache. To take advantage of this caching, the database version check moved out of the connection adapters initializers and into the connection pool. When new connections are checked out of the pool, they're assigned the schema cache that was saved to file with the cached database version. So we'll defer the database version check until the connections get the saved schema cache.

When apps aren't saving schema caches, we'll run a query to get the database version. This will then be cached on the schema cache object.

To facilitate this change, all connection adapters now implement `#get_database_version` and `#database_version`. `#database_version` returns the value from the schema cache.

### Other Information

In #35767, I added some tests to verify the database version check was happening in the connection pool. I had to do some stubbing to get them to work, but this wasn't working for sqlite3. Since they were kinda funky, I decided against adding those tests here.

/cc @eileencodes @tenderlove @matthewd

2019-04-02 13:15 UTC, eileencodes requested changes
Can you nodoc the methods added and the ones moved out from the `private` namespace.

2019-04-02 13:15 UTC, eileencodes commented on activerecord/lib/active_record/connection_adapters/abstract_adapter.rb
> +      def check_version
Let's mark these "private" 

```suggestion
      def check_version # :nodoc:
```

2019-04-02 13:15 UTC, eileencodes commented on activerecord/lib/active_record/connection_adapters/abstract_adapter.rb
> +      def database_version
```suggestion
      def database_version # :nodoc:
```

2019-04-02 13:15 UTC, eileencodes commented on activerecord/lib/active_record/connection_adapters/abstract_adapter.rb
> +      def get_database_version
```suggestion
      def get_database_version # :nodoc:
```

2019-04-02 13:15 UTC, eileencodes commented on activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb
> +      def check_version
```suggestion
      def check_version # :nodoc:
```

2019-04-02 13:15 UTC, eileencodes commented on activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb
> +      def check_version
```suggestion
      def check_version # :nodoc:
```

2019-04-02 13:15 UTC, eileencodes commented on activerecord/lib/active_record/connection_adapters/schema_cache.rb
> +      def database_version
```suggestion
      def database_version # :nodoc:
```

2019-04-02 13:15 UTC, eileencodes commented on activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb
> +      def get_database_version
```suggestion
      def get_database_version # :nodoc:
```

2019-04-02 13:15 UTC, eileencodes commented on activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb
> +      def check_version
```suggestion
      def check_version # :nodoc:
```

2019-04-02 13:37 UTC, abhaynikam commented on activerecord/test/cases/connection_adapters/schema_cache_test.rb
> +        # cached in both mysql and postgresql outside of the schema cache.
```suggestion
        # cached in both MySQL and PostgreSQL outside of the schema cache.
```

2019-04-03 15:01 UTC, eileencodes approved these changes
Can you squash your commits into 1 and then I'll merge?

2019-04-03 15:19 UTC, alimi commented
All the commits have been squashed into https://github.com/rails/rails/pull/35795/commits/1c6e508ade793b5f2676e9218ab2f4cc9474f9ce. 🚀

2019-04-03 15:23 UTC, merged