Don't determine `always_write_cookie` based on environment
rails/rails pull request #35849
Opened 2019-04-04 05:20 UTC by hlcfan

### Summary

In development environment, it allows to write cookie, while it doesn't in other environments. This is a bit confusing. Upon writing cookies - such general behavior, discrepancy across environments should be better smoothed.

By updating docs, people would know this configuration directive
`config.always_write_cookie` to control the conditions to write cookies.

### Other Information
Related code:
+ Writing cookies upon Rails env introduced in   https://github.com/rails/rails/commit/2d5a12a50bcd83fcc99865de759b82e661b28698
+ `always_write_cookie` flag introduced in https://github.com/rails/rails/pull/3739
+ Conditions to control whether to write cookies or not https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/cookies.rb#L450

Google forum post:
https://groups.google.com/forum/?fromgroups&hl=en#!topic/rubyonrails-core/bNd_QfZJ6_8

2019-04-04 21:08 UTC, rafaelfranca requested changes
Unless I'm missing something, this will be a huge breaking behavior. After this change, no cookies will be written in development, because development is not using ssl and all cookies are secure by default. While I agree it is bad to have this config hidden enabled in development we should generate the `development.rb` with it set to `true` and also take care of applications upgrading since they will not have the explicit config.

2019-04-05 00:21 UTC, hlcfan commented
Thanks for review. 

Sorry, what do you mean by  `development is not using ssl and all cookies are secure by default`? If Rails app is under non-ssl mode, cookies with secure attribute will be outputted into response headers still, however won't be written into browsers.

2019-04-16 13:55 UTC, hlcfan commented
@pixeltrix Would you mind reviewing this? Let me know your idea, thanks!

2019-12-25 01:39 UTC, closed without merging

2019-12-25 14:47 UTC, hlcfan commented
@rafaelfranca In development, cookies still can be written into browsers, as the behavior is defined by `request.ssl? || !cookie[:secure] || always_write_cookie`, see https://github.com/rails/rails/blob/abf0465b0997ff2945f4de4bcd493000dfc9636e/actionpack/lib/action_dispatch/middleware/cookies.rb#L431. In development by default the second condition (`!cookies[:secure]`) will apply. 

As for the new configuration directive `config.action_dispatch.always_write_cookie`, since  most of the time, user won't touch this configuration, that's why to make it a silent configuration.

Please share your idea, thanks!