Allow specifying fixtures to be ignored in "_fixture" section
rails/rails pull request #36303
Opened 2019-05-19 03:31 UTC by gaotongfei

### Summary

Currently, there is a "DEFAULTS" key we can use in fixtures file for attributes inheriting and fixture named DEFAULTS will not be created.

This PR introduces a new configuration option in `_fixture` section: `ignore`.

It allows us to specify what fixtures can be ignored. For example:

    # users.yml
    _fixture:
      ignore:
        - base
      # or use `ignore: base` when there is only one fixture needs to be ignored.

    base: &base
      admin: false
      introduction: "This is a default description"

    admin:
      <<: *base
      admin: true

    visitor:
      <<: *base

In the above example, "base" fixture will not be created. This is helpful when you want to use some base fixtures for attributes inheriting without actually creating them.

2019-06-03 10:44 UTC, gaotongfei commented
Anyone cares to take a look at this PR? Anything i can work on to improve it or this feature will not be merged?
Not sure who should i ping, maybe @eileencodes ? Thanks!

2019-07-26 20:09 UTC, rafaelfranca requested changes

2019-07-26 20:09 UTC, rafaelfranca commented on activerecord/lib/active_record/fixtures.rb
> +        @ignored_fixtures = begin
you don't need the `begin` here

2019-07-27 08:48 UTC, gaotongfei commented on activerecord/lib/active_record/fixtures.rb
> +        @ignored_fixtures = begin
Right, I have updated my code

2019-07-28 01:12 UTC, merged