Raise error when not available option in :only and :except options for resource routing
rails/rails pull request #36457
Opened 2019-06-10 18:10 UTC by madding

### Summary

Added error for not available optins in :except and :only options for resource routing. It fix anoyning typo in action name. For example index action for resource routing. If I can drop warning in logs here, I will prefer adding this solution.

2019-07-28 03:47 UTC, rafaelfranca requested changes

2019-07-28 03:47 UTC, rafaelfranca commented on actionpack/test/dispatch/mapper_test.rb
> +          Mapper::Resources::Resource.new(:test_route, false, false, only: [:wrong_action])
Those tests should go though the public API like `mapper.resource`.

2019-07-28 03:47 UTC, rafaelfranca commented on actionpack/test/dispatch/routing_test.rb
> -      scope except: :index do
Because of this change this test is not testing what it should be testing. Maybe we should change the `:index` to `:delete`?

2019-07-28 03:50 UTC, rafaelfranca commented on actionpack/lib/action_dispatch/routing/mapper.rb
> +                ":only option contain #{(Array(options[:only]).map(&:to_sym) - default_actions)}"\
```suggestion
                ":only option contains #{(Array(options[:only]).map(&:to_sym) - default_actions)}"\
```

2019-07-28 03:50 UTC, rafaelfranca commented on actionpack/lib/action_dispatch/routing/mapper.rb
> +                " not available action, available actions: #{default_actions}"
```suggestion
                " that are not valid. The available valid are: #{default_actions}"
```

2019-07-28 03:50 UTC, rafaelfranca commented on actionpack/lib/action_dispatch/routing/mapper.rb
> +                ":except option contain #{(Array(options[:except]).map(&:to_sym) - default_actions)} not "\
```suggestion
                ":except option contains #{(Array(options[:except]).map(&:to_sym) - default_actions)} "\
```

2019-07-28 03:50 UTC, rafaelfranca commented on actionpack/lib/action_dispatch/routing/mapper.rb
> +                "available action, available actions: #{default_actions}"
```suggestion
                "that are not valid. The valid actions are: #{default_actions}"
```

2019-07-28 03:50 UTC, rafaelfranca commented on actionpack/test/dispatch/mapper_test.rb
> +      def test_raising_error_when_only_option_contains_not_available_action
```suggestion
      def test_raising_error_when_only_option_contains_not_valid_action
```

2019-07-28 03:50 UTC, rafaelfranca commented on actionpack/test/dispatch/mapper_test.rb
> +      def test_raising_error_when_except_option_contains_not_available_action
```suggestion
      def test_raising_error_when_except_option_contains_not_valid_action
```

2019-07-28 03:50 UTC, rafaelfranca commented on actionpack/test/dispatch/routing_test.rb
> +            resource  :chairman, only: [:show]
Again, this test is not testing what it should be testing. Maybe changing `:index` to `:edit`?

2019-07-30 19:17 UTC, madding commented
@rafaelfranca I fixed all notes by review.

2019-12-18 04:03 UTC, madding commented
You are welcome

2020-04-30 08:27 UTC, closed without merging

2020-04-30 09:05 UTC, madding commented
@rafaelfranca can you check my PR?

2021-10-21 08:24 UTC, noma4i commented
Bump! @rafaelfranca