Allow using env var to specify pidfile
rails/rails pull request #36486
Opened 2019-06-14 15:36 UTC by benthorner

Previously it was only possible to specify the location of the pidfile
for the 'rails server' command with the '-P' flag. This adds support for
specifying the pidfile using a PIDFILE env var, which can still be
overridden by the '-P' flag and with the default pidfile path unchanged.

The motivation for this feature comes from using Docker to run multiple
instances of the same rails app. When developing a rails app with
Docker, it's common to bind-mount the rails root directory in the
running container, so that changes to files are shared between the
container and the host. However, this doesn't work so well with the
pidfile and it's necessary to (remember to) add a '-P' flag to the
'rails server' command line; being able to specify this flag using an
env var would make developing with Rails+Docker a bit simpler.

### Summary

### Other Information

2019-06-15 07:26 UTC, y-yagi requested changes

2019-06-15 07:26 UTC, y-yagi commented on railties/CHANGELOG.md
> +   - Support using environment variable to set pidfile
Please use `*` and add your name. Please refer to other CHANGELOG files.
https://github.com/rails/rails/blob/master/activesupport/CHANGELOG.md
https://github.com/rails/rails/blob/master/activerecord/CHANGELOG.md

2019-06-15 07:26 UTC, y-yagi commented on railties/lib/rails/commands/server/server_command.rb
> -      class_option :pid, aliases: "-P", type: :string, default: DEFAULT_PID_PATH,
This change affected to an output of help. Please add a default value to desc like `port` and `binding`.

2019-06-15 07:28 UTC, y-yagi commented
You should need to fix `prepare_restart`  also.
https://github.com/rails/rails/blob/c8a84603e2fa97822407bf4a1c8ac0308a899163/railties/lib/rails/commands/server/server_command.rb#L263-L265

2019-06-17 09:10 UTC, benthorner commented
@y-yagi thanks for your comments - first time working on Rails and I missed a few things :-). I've addressed them all - couldn't find a particular test for the `prepare_restart` method, but I changed it to use the `pid` method now.

2019-06-18 22:55 UTC, y-yagi commented
I missed to point out `user_supplied_options`. Can you fix to `user_supplied_options` when`PIDFILE` env is specified?
  
https://github.com/rails/rails/blob/aeba121a83965d242ed6d7fd46e9c166079a3230/railties/lib/rails/commands/server/server_command.rb#L208-L210

2019-06-19 13:32 UTC, benthorner commented
@y-yagi sure, done :-).

2019-06-20 02:52 UTC, merged

2019-06-20 02:52 UTC, y-yagi commented
@benthorner Thanks!!