Remove stacktrace from ActiveJob logging callback halts
rails/rails pull request #37994
Opened 2019-12-16 23:52 UTC by bibstha

### Summary

ActiveJob will log the entire backtrace when one of the enqueue
callbacks fail. This is not necessary and increases noise. When there is
an Exception object, the object gets bubbled up eventually anyways.

### Solution

Remove `Array(ex.backtrace).join("\n")` from `def enqueue` and `def
enqueue_at`.

2019-12-17 14:53 UTC, rafaelfranca commented on activejob/lib/active_job/log_subscriber.rb
> +          "Failed enqueuing #{job.class.name} to #{queue_name(event)}: #{ex.class} (#{ex.message})"
Can we add the backtrace as a debug log entry?

2019-12-17 14:54 UTC, rafaelfranca requested changes
I agree with this change but we should keep the backtrace in the debug level.

2019-12-17 15:47 UTC, Edouard-chin commented
If we change the log level to debug when enqueuing fail then we should change it when we perform a job as well https://github.com/rails/rails/pull/37994/files#diff-8635308536838d97326f048daedc0629L57

IMHO error as log level make sense. 
> There are valid cases where enqueue can fai

Then you should `throw(:abort)` not raise an error

2019-12-18 23:10 UTC, bibstha commented
I've documented the behavior and double logging in a sample app here: https://github.com/bibstha/myrails/issues/1

> I agree with this change but we should keep the backtrace in the debug level.

Since it's already logged somewhere else, do we really need to log it in debug?

2019-12-18 23:28 UTC, Edouard-chin commented
Ah yeah I see what you mean, then yes I agree we should remove the backtrace

2019-12-19 15:27 UTC, merged