Yield `Tags::Label::LabelBuilder#translations`
rails/rails pull request #38549
Opened 2020-02-22 16:26 UTC by seanpdoyle

When translating a `<label>` element's contents, it is difficult (or
"possible", yet undocumented) to make the translation text available to
a block scope.

For instance, when rendering a `rich_text_area`, passing the
`aria-label` attribute might be important.

Prior to this commit, doing so would require a double lookup of the
translation key:

```erb
<%# one time here, implicitly %>
<%= form.label(:content) do %>
  <%= form.rich_text_area(
    :content,
    # one time here, explicitly
    "aria-label" => translate("helpers.label.post.content"),
  ) %>
<% end %>
```

The current implementation of the `#label` helper method already yields
an instance of `ActionView::Helpers::Tags::Label::LabelBuilder`, but
that class is undocumented. Instance of that class respond to
`#translation` calls, which will return the translated text content.

By aliasing `#translation` to `#to_s`, we're able to expose that value
without the burden of exposing an additional class to the public API.
Instead, view-level interpolation (either `<%= %>`, `#{ }`, or direct
calls to [`capture`][capture] will coerce the value to a String, and
implicitly invoke `#translation`.

The new view code might look something like this:

```erb
<%= form.label(:content) do |label| %>
  <%= form.rich_text_area(:content, "aria-label" => label) %>
<% end %>
```

Callers of the helper are still free to omit the block parameter.

[capture]: https://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html#method-i-capture

2020-04-16 04:37 UTC, jonathanhefner commented
Is adding `aria-label` the primary use-case for this feature?  If so, it looks like [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute) might give you what you need without juggling the translation string:

```erb
<%= form.label :content, id: "content-label" %>
<%= form.rich_text_area :content, "aria-labelledby" => "content-label" %>
```

2020-04-16 14:24 UTC, seanpdoyle commented
@jonathanhefner ooooh, I hadn't cosidered `aria-labelledby`. 

I like it, but it feels like a reversal of the `label[for]`-`input[id]` relationship that Rails typically builds by default:

```html
<label for="input-id">Label text</label>
<input id="input-id">
```

Conceptually, that feels better to me than passing around the contents of the translations, but it still feels like a band-aid.

Ideally, we'd treat `rich_text_area` calls the same as other labelled inputs:

```html+erb
<%= form.label :content %>
<%= form.rich_text_area :content %>
```

However, there are some limitations with the current way that `<trix-editor>` elements get built by calls to `rich_text_content`. I've also opened https://github.com/rails/rails/pull/38551 to attempt to address this disconnect, but it's also a half measure.

Maybe this work is better suited as a pull request against Trix itself?

2020-05-22 13:09 UTC, composerinteralia commented
```rb
<%= form.label :content %>
<%= form.rich_text_area :content %>
```

does seem attractive. This PR and the existing method both require the developer to explicitly add the aria attribute—a lot of people won't do this. Accessibility by default would be my preference, if we can make it happen.

@seanpdoyle do you have a sense of what changes would need to be made in Trix to get the ideal API here? It seems worth exploring further.

2020-05-22 13:28 UTC, composerinteralia reviewed
This is such a minimal code change, and as you mentioned without any change to the public API, so I think it would be fine to merge.

Even if there may be other ways of handling the specific example with `rich_text_area`, having the translation available here may also be useful for other cases.

2020-05-22 13:28 UTC, composerinteralia commented on actionview/lib/action_view/helpers/form_helper.rb
> +      #     raw('Accept <a href="/terms">#{translation}</a>.')
```suggestion
      #     raw("Accept <a href=\"/terms\">#{translation}</a>.")
```
Double quotes for interpolation

2020-08-20 14:12 UTC, composerinteralia commented
Removing the Stale label for now, since I know Sean is going to be working on some Rails-related accessibility things and this PR may make sense as part of that.

2020-08-26 00:22 UTC, rafaelfranca requested changes
I think we only need to expose the class in the public API. The commit that introduced this builder class already had as goal to allow users to get the translation inside the block. See https://github.com/rails/rails/commit/ce8e4a43b353b7e36a1c9f98561dc7ed23e16c93.

That being said this change should be only a documentation change.

2020-08-26 11:02 UTC, seanpdoyle commented
> The commit that introduced this builder class already had as goal to allow users to get the translation inside the block. 

The guidance provided by the [CHANGELOG entry for that commit](https://github.com/rails/rails/commit/ce8e4a43b353b7e36a1c9f98561dc7ed23e16c93#diff-d5f0229b1e83113a6aedf860e32398f9) describes calling `builder.translation`. The `ActionView::Helpers::Tags::Label::Base::LabelBuilder` public API is currently only `#translation` and `#object`. That feels useful enough for more complicated blocks.

The intent behind this changeset was to provide a means of embedding the block argument directly into the template (by being String coerce-able via `#to_s`), without needing to learn about a new interface. It could simplify what have been the most common `<label>` with block content scenarios I encounter.

> I think we only need to expose the class in the public API. 

@rafaelfranca 👍 should I include that documentation change in this PR?

2020-08-26 17:37 UTC, rafaelfranca commented
> The intent behind this changeset was to provide a means of embedding the block argument directly into the template (by being String coerce-able via `#to_s`), without needing to learn about a new interface.

Good point. Let's keep the code changes them.



> @rafaelfranca 👍 should I include that documentation change in this PR?

Yes, please. Let's document translation and object in this same PR.

2020-09-01 17:32 UTC, seanpdoyle commented
@rafaelfranca I've pushed up changes to include the documentation. This is ready for re-review.

2020-10-30 20:00 UTC, seanpdoyle commented
@rafaelfranca is this worth considering for 6.1?

2020-10-30 20:09 UTC, merged