Add support for `if_not_exists` to indexes
rails/rails pull request #38555
Opened 2020-02-22 17:50 UTC by prathamesh-sonpatki

When we try to create a table which already exists which also adds
indexes, then the `if_not_exists` option passed to `create_table` is
not extended to indexes. So the migration results into an error if the
table and indexes already exist.
This change extends the `if_not_exists` support to `add_index` so that
if the migration tries to create a table which also has existing
indexes, error won't be raised.
Also as a side-effect individual `add_index` calls will also accept
`if_not_exists` option and respect it henceforth.

### Summary

### Other Information

2020-02-22 18:56 UTC, prathamesh-sonpatki commented
Found out that there was similar PR to this code change - https://github.com/rails/rails/pull/34567. Gave credit to @jaggederest in the commit message.

2020-02-22 19:30 UTC, jaggederest commented
Thanks! I feel like this might be useful as a default on PG, certainly useful in situations where you create an index manually on production and then add a migration for dev/test/staging to be up to date.

2020-02-24 15:17 UTC, eileencodes requested changes
This is great, I was going to add this feature. Can you add support for `if_exists` on the `remove_index` as well and a CHANGELOG?

2020-02-24 15:18 UTC, eileencodes approved these changes
Oh nevermind, I see, this is only on create table to propgate the features down.

Can you add a CHANGELOG and then I'll merge. You can ignore my other comment 😄

2020-02-24 19:42 UTC, rafaelfranca approved these changes

2020-02-25 11:57 UTC, prathamesh-sonpatki commented
@eileencodes @rafaelfranca I found out that MySQL does not support "CREATE INDEX IF NOT EXISTS". Should we check the presence of index using `index_exists?` in case of Mysql2 adapter or just be no-op?
I have kept it `no-op` for now - https://github.com/rails/rails/pull/38555/files#diff-98ce5dc0cd01f8b0435ff6feac10d8a8

2020-03-03 03:39 UTC, prathamesh-sonpatki commented
Hey @eileencodes Did you get a chance to look at updated code?

2020-03-05 14:29 UTC, eileencodes commented
> Should we check the presence of index using index_exists? in case of Mysql2 adapter or just be no-op?

Yes I think this should check the presence of index_exists for mysql2, I don't think a no-op is the best way to handle this.

2020-03-05 19:03 UTC, prathamesh-sonpatki commented
👍 I will update the code for mysql2 adapter.

2020-03-14 15:09 UTC, prathamesh-sonpatki commented
@eileencodes Added check for mysql adapter using `index_exists`

2020-03-28 20:04 UTC, prathamesh-sonpatki commented
@eileencodes I have updated the code to check index exists or not for MySQL2 adapter.

2020-03-29 14:30 UTC, eileencodes commented
Merged manually in 975a4470665b1192b2f0a4453d8f3f506ce86a6b so I could fix the conflict locally. Thanks @prathamesh-sonpatki!

2020-03-29 14:31 UTC, closed without merging

2020-03-29 14:52 UTC, prathamesh-sonpatki commented
@eileencodes Thanks, can we also add this change to 6-0-stable as well as `if_not_exists` option was added for `create_table` migrations in 6.0.

2020-04-18 21:47 UTC, jaber78 reviewed
github.com 
هذا الموقع هو الذي يمنعني من إتمام خلاصتي لانه يطالبني بإرسال بريدي الالكتروني لتنشيط حسابي وكلما أرسلت بريدي الالكتروني يرد علي بأنه قد تم إرسال رسالة تحتوي على الرابط ولا أدري إلي اي قطب يرسل انها لاتاتيني ولا أدري هل أترك هذا الموقع واقلغه حتي تستريحوا

2020-04-18 21:50 UTC, jaber78 reviewed
github.com 
هذا الموقع هو الذي يمنعني من إتمام خلاصتي لانه يطالبني بإرسال بريدي الالكتروني لتنشيط حسابي وكلما أرسلت بريدي الالكتروني يرد علي بأنه قد تم إرسال رسالة تحتوي على الرابط ولا أدري إلي اي قطب يرسل انها لاتاتيني ولا أدري هل أترك هذا الموقع واقلغه حتي تستريحوا