Deprecate use of non-existent enum in query
rails/rails pull request #38826
Opened 2020-03-26 19:16 UTC by ak15

### Summary
Suddenly raising error for using non-existent enum in query could cause a bad user experience. We need to deprecate this behaviour first. 

### Other Information
https://github.com/rails/rails/pull/38737#issuecomment-604579396
Deprecating use of non-existent enum , will raise Argument Error in next Rails versions

2020-03-26 19:24 UTC, eileencodes requested changes
Thanks for the quick turn around @ak15! 

Can you add a test asserting that this is deprecated? You can use your previous test and instead of assert raises call `assert_deprecated`.

2020-03-26 19:24 UTC, eileencodes commented on activerecord/lib/active_record/enum.rb
> +            will be removed in Rails 6.2.
Can you update this to include the bad enum value? Something like:

```
#{value} is not a valid enum value. Passing a non-existent enum
value in a query is deprecated and raise an error in Rails 6.2.
```

2020-03-27 15:41 UTC, ak15 commented
> Thanks for the quick turn around @ak15!
> 
> Can you add a test asserting that this is deprecated? You can use your previous test and instead of assert raises call `assert_deprecated`.

Hi @eileencodes 

The **test cases failed** , because in mysql2 we have not handled non-existent enum values to raise error ,  issue raised in detail here #38687.

Will you please help me on this?

2020-04-01 15:58 UTC, ak15 commented
Hi @eileencodes ,
Since it is only for MySql and deprecation test cases are failing for Postgres,  should I close this pull request now ? . Please can you help in further steps for this issue.

Reference #38737

2020-04-01 16:00 UTC, eileencodes commented
@ak15 please be patient with reviews, I have a million things on my plate right now. I will eventually get around to this.

2021-04-21 21:13 UTC, closed without merging