Add search to Rails Guides
rails/rails pull request #39299
Opened 2020-05-15 15:35 UTC by LukasSkywalker

For better discoverability and to prevent users from having to leave
the Guides webiste, this commit implements a client side search based
on the open **lunr** library.

Different libraries were compared:

* lucaong/minisearch, where it was not possible to pre-build an index.
  Building it on the fly would take about 3 seconds and render the
  browser unresponsive.
* krisk/Fuse, where it was possible to pre-build an index, but the
  fuzzy search was very slow and would block for about 600ms.
* olivernn/lunr.js, where the index cloud be pre-built and the fuzzy
  search could be disabled.

The new search uses Lunr with a pre-built index and by using a lookup
table where the id of the documents are mapped to their respective url
to keep the index size small.

To build the index, the Guides HTML is parsed and split into documents
that are then indexed using ExecJS. This generates an index of about
3.3 MB in size which is only loaded when the user focuses the search
input.

The index is then stored in the browsers localstorage for up to a week
for performance.

[Demo here](http://codefabrik-rails-demo.s3-website-us-west-2.amazonaws.com/)

![image](https://user-images.githubusercontent.com/282447/82068594-7a74e080-96d2-11ea-88c1-2a286a7aefeb.png)

### Summary

### Other Information

2020-05-17 15:13 UTC, lebalz requested changes
Thanks for this addition, nice job!

2020-05-19 08:25 UTC, LukasSkywalker commented
cc @fxn

2020-05-27 08:52 UTC, rolandasb commented
Nice work 👍 I'm not sure about the positioning between navigation items. Maybe it would make sense to put that in the top bar?

<img width="714" alt="Screenshot 2020-05-27 at 11 49 35" src="https://user-images.githubusercontent.com/1409998/82998504-7faa2780-a010-11ea-883d-54a4b4b33ce2.png">

2020-05-27 14:38 UTC, LukasSkywalker commented
@rolandasb  I was thinking about that as well, but thought it was a bit of a mismatch – the content of the top bar references items outside the Guides while the red navigation bar references things contained in the Guides. Since the search only works inside the Guides, but not on rubyonrails.org, I put it in the lower bar.

2020-06-16 19:26 UTC, p8 commented
Is anyone else getting an endless "Please wait.."?
<img width="740" alt="image" src="https://user-images.githubusercontent.com/28561/84819263-02267580-b018-11ea-8d5a-199590f1e353.png">

2020-06-19 11:53 UTC, LukasSkywalker commented
@p8 It should work if you try again. The "Please wait..." indicator appears the first time you use the search since the index needs to be downloaded. Due to the size (3.2MB) it is lazily loaded.

2021-03-30 15:17 UTC, jaredcwhite commented
What can we do to push this along? I think search would be hugely welcome addition to the Rails guides. Better documentation and onboarding seems to be top of mind for a number of Rubyists these days and this could help. @rafaelfranca @fxn

2021-11-08 14:23 UTC, yorch commented
I don't really understand the lack of interest for adding search capabilities from the maintainers. For those of us not extremely familiar with the guides, search is a huge help, and as other have commented before, many other projects have embraced adding searching capabilities to their docs.

2021-11-08 15:12 UTC, fxn commented
/cc @zzak

2022-07-20 05:40 UTC, Austio commented
Bump :) seems like a really great addition

2022-10-05 10:33 UTC, Schwad reviewed
A good hunk of this leans on vanilla JS which isn't my forte so will defer to others for their opinions on how it's put together 😅 

But from a product feel this seems like a big win to me. would be a nifty addition for Rails 7.1!

As I haven't generated the guides to tophat a change in a while can someone link me the quick TLDR on tophatting this locally? Thanks!

When going through the demo - I think one of the guides strengths already is to navigate via headers. 

But what I could really use is searching by text - e.g. `form_with` returns nothing. How hard would it be to search text body so I can search code snippets to find the right guide?

2022-10-05 10:35 UTC, Schwad commented
Also 10/10 for giving us a working demo!

2022-10-05 12:41 UTC, skipkayhil commented
> As I haven't generated the guides to tophat a change in a while can someone link me the quick TLDR on tophatting this locally? Thanks!

https://guides.rubyonrails.org/ruby_on_rails_guides_guidelines.html#html-guides-generation
Under `/guides` run `$ bundle exec rake guides:generate` which puts them in `/guides/output`. To serve them you can use any static file server, I like this ruby one liner (in the output folder): `ruby -run -ehttpd . -p8000 -b0.0.0.0`

2022-10-06 13:52 UTC, p8 commented
For consistency I think it would be nice if it used the same styles as the index dropdown.
Something like:
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/28561/194330291-f937b448-3cce-41eb-9747-3211e222da35.png">


We could probably also remove the "Contribute" item from the menu as it's already present in the top menu:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/28561/194330677-fa1121e5-95ff-4250-a9e2-f0c0516fc5ea.png">

2023-03-01 04:04 UTC, JohnAnon9771 commented
There is a version of the guide for Brazilian Portuguese where this search is already implemented, maybe it will be a good reference.

https://guiarails.com.br/

2023-10-10 09:17 UTC, akirataguchi115 commented
One idea that hasn't been mentioned here yet is the way Ruby on Rails API implements search functionality: https://api.rubyonrails.org/.

Right now I'll have to use the Google web search operators f.ex. site:guides.rubyonrails.org destroy.

2023-10-10 10:09 UTC, akirataguchi115 commented
> There is a version of the guide for Brazilian Portuguese where this search is already implemented, maybe it will be a good reference.
> 
> https://guiarails.com.br/

This is great and I would definitely implement this and make a pull request to this repository. The translation however is not forked and (thus) not licensed, so the contributors own the copyright to the search implementation.

2025-11-16 02:00 UTC, nerijunior commented
👁️ What happened with this?

2026-08-31 19:17 UTC, closed without merging