[ci skip] Append some description about advance constraints
rails/rails pull request #39886
Opened 2020-07-20 11:06 UTC by lanzhiheng

### Summary

Simple changes of the document for better describing the usage of routes's constraints.

2020-07-21 16:37 UTC, eileencodes requested changes
I've added some suggestions to clarify the language.

2020-07-21 16:37 UTC, eileencodes commented on guides/source/routing.md
> +#### advance in a block form
```suggestion
#### Constraints in block form
```

2020-07-21 16:37 UTC, eileencodes commented on guides/source/routing.md
> +Of course, you can specify this kind of constraints in a block form. Especially, when you need to apply same rule to several routes. Just like
```suggestion
You can specify constraints in a block form. This is useful for when you need to apply the same rule to several routes. For example
```

2020-07-21 16:37 UTC, eileencodes commented on guides/source/routing.md
> +You also can apply `lambda` version.
```suggestion
You also use a `lambda`:
```

2020-07-29 09:21 UTC, lanzhiheng commented
@eileencodes Thanks for your advice, I have updated all of them.

2020-08-17 12:45 UTC, eileencodes approved these changes
Thanks for making the changes, and apologies for the delay in re-reviewing.

2020-08-17 12:45 UTC, merged