The abstract parent class file generated via generator should not be pluralized
rails/rails pull request #39969
Opened 2020-08-01 15:24 UTC by abhaynikam

The change was introduced in: #39866

Currently, the file generated via the generator is pluralized
but the parent class is singular.

Example: `bundle exec rails g scaffold Pet name:string --database=animals`

The above command should generate: `apps/models/animals_record.rb`
but the pets model would inherit from: `AnimalRecord` as
`"animals".classify` would be `Animal`

This will throw the `uninitialized constant AnimalRecord Did you mean? AnimalsRecord`
error. This PR fixes the issue by making the abstract parent class file as singular.

2020-08-02 15:49 UTC, eileencodes requested changes
The abstract class should match the database name regardless of whether it's plural or singular. I'd prefer this PR fix the inherited class than try to singularize everything.

2020-08-02 16:41 UTC, abhaynikam commented
Got it. I'll fix it right away and send a PR your way. Thanks for the feedback @eileencodes 😊 🎉

2020-08-03 12:41 UTC, abhaynikam commented
@eileencodes : Done the changes suggested. Could you please review it once?

2020-08-03 12:44 UTC, eileencodes approved these changes

2020-08-03 12:44 UTC, merged

2020-08-03 12:44 UTC, eileencodes commented
Looks great, thank you!