Fix ActiveRecord::PendingMigrationError action not dumping schema.
rails/rails pull request #40001
Opened 2020-08-07 08:20 UTC by tgxworld

2020-08-07 08:22 UTC, tgxworld commented
@kaspth Do you mind reviewing this for me? I took your suggestion in https://github.com/rails/rails/pull/34788/files#r264059772 and implemented it as part of the fix.

2020-08-26 00:11 UTC, rafaelfranca requested changes

2020-08-26 00:11 UTC, rafaelfranca commented on activesupport/lib/active_support/actionable_error.rb
> +require "rails/command"
Active Support can't depend on Railties. We should register the command as the action to run on that exception in a Railtie if we want to use Rails Commands for them.

2020-08-26 07:32 UTC, tgxworld commented
@rafaelfranca I've updated the PR to not use Rails command as it seems to be dependent on the current path which it is executed from. Also, using Rails command means we lose multi-database support for check pending errors as well.

2020-08-26 18:00 UTC, rafaelfranca approved these changes

2020-08-26 18:00 UTC, merged

2020-08-26 19:11 UTC, philipbjorge commented
Thanks @tgxworld -- Looking forward to getting this to our dev team!

2020-08-27 01:08 UTC, tgxworld commented
Thank you for reviewing @rafaelfranca :+1: