Option to mute multiple database yml error
rails/rails pull request #40449
Opened 2020-10-25 01:23 UTC by OmriSama

### Summary

This merge request allows users to suppress the warning shown by `        ActiveRecord::Tasks::DatabaseTasks.setup_initial_database_yaml`.

### Other Information

@eileencodes mentioned here that she would be open to merging this, if someone built it: https://github.com/rails/rails/pull/36560#issuecomment-559180204

2020-10-26 13:02 UTC, eileencodes requested changes

2020-10-26 13:02 UTC, eileencodes commented on railties/CHANGELOG.md
> +    *Omri Gabay*
This should be in Active Record since it's an active record configuration option.

2020-10-26 13:02 UTC, eileencodes commented on activerecord/lib/active_record/tasks/database_tasks.rb
> +          unless Rails.application.config.active_record.suppress_multiple_database_warning
This doesn't need to access `Rails`, we can get the value from Active Record directly.

```suggestion
          unless ActiveRecord::Base.suppress_multiple_database_warning
```

2020-10-26 13:08 UTC, eileencodes commented
When you're done making changes, please squash your commits into one 😄

2020-10-26 18:21 UTC, OmriSama commented
@eileencodes I made the changes and for some reason the `railties` checks failed. I ran the suite locally and it worked ok. Should I re-push? I didn't see an option to restart the pipeline.

2020-10-29 20:59 UTC, eileencodes commented
Merged this manually in https://github.com/rails/rails/commit/77087bbc1535075134b2aa25eb9cb859143e59d3

2020-10-29 20:59 UTC, closed without merging