Add strict loading for active storage
rails/rails pull request #40623
Opened 2020-11-15 00:56 UTC by dcangulo

### Summary
Adds `strict_loading` to ActiveStorage model.

### Other Information
```ruby
has_one_attached :logo, strict_loading: true
has_many_attached :images, strict_loading: true
```

2020-11-15 13:55 UTC, tahsin352 approved these changes

2020-11-15 13:56 UTC, tahsin352 reviewed
build fails??

2020-11-15 14:25 UTC, dcangulo commented
@tahsin352 I'm also not so sure why is that. Running `cd activejob && bundle exec rake test` locally doesn't have an error. See: https://gist.githubusercontent.com/dcangulo/bf55f985708892fc4bb99378362d6a65/raw/880d67d098d00208e8c8f7b55f4660953e20e933/logs.txt

2020-11-15 14:28 UTC, eugeneius commented
That flaky test was just fixed in https://github.com/rails/rails/commit/65d7aa5811075cccf1f0b7504372cad2ed3f8e7f, if you rebase it will pass in CI.

This change looks reasonable, but it needs API documentation and tests.

2020-11-15 16:49 UTC, dcangulo commented
@eugeneius Rebased, added tests, and documentation.

2020-11-16 13:46 UTC, eileencodes requested changes
I left a comment about docs, otherwise this looks good.

2020-11-16 13:46 UTC, eileencodes commented on activestorage/lib/active_storage/attached/model.rb
> +      # If you need to enable +strict_loading+ to raise an error when N+1 query happens,
It does more than this, we usually say in the docs that it raise for lazily loaded queries.

2020-11-16 13:46 UTC, eileencodes commented on activestorage/lib/active_storage/attached/model.rb
> +      # If you need to enable +strict_loading+ to raise an error when N+1 query happens,
Same comment as above here.

2020-11-16 14:30 UTC, dcangulo commented
@eileencodes Docs has been updated. Please check. Thanks.

2020-11-16 15:30 UTC, merged