ActiveRecord::AttributeMethods::Query respect getter overwrites in the model
rails/rails pull request #40782
Opened 2020-12-10 15:55 UTC by feliperaul

### Changelog
*   Makes ActiveRecord::AttributeMethods::Query respect the getter overrides defined in the model. 

    Fixes #40771

    Before:

    ```ruby
      class User

        def admin
          false # Overriding the getter to always return false
        end

      end

      user = User.first
      user.update(admin: true)

      user.admin # false (as expected, due to the getter overwrite)
      user.admin? # true (not expected, returned the DB column value)

    ```

    After this commit, `user.admin?` above returns false, as expected.

### Summary

As discussed in #40771 , `ActiveRecord::AttributeMethods::Query` didn't respect the getter overrides defined in the model. 

Assuming the User model has boolean column named admin:

```ruby
class User

  def admin
    false # Overriding the getter to always return false
  end

end

user = User.first
user.update(admin: true)

user[:admin] # true (as expected)
user.read_attribute(:admin) # true (as expected)

user.admin # false (as expected)
user.admin? # true (not expected)

```

This commit is a one-liner that makes https://github.com/rails/rails/blob/46337faa795fa40dedb1b9b906bec1793358d7f3/activerecord/lib/active_record/attribute_methods/query.rb#L12 use `value = public_send(attr_name)` instead of `value = self[attr_name]`, so instead of going directly to the column value, it goes through the model to respect any getter overwrites.

I also updated tests and documentation. 

Pinging @rafaelfranca as we had initiated a discussion on the issue above.

2020-12-18 21:59 UTC, rafaelfranca requested changes
Just a few changes required. After that, can you rebase your PR against master and squash all commits in one?

2020-12-18 21:59 UTC, rafaelfranca commented on activerecord/CHANGELOG.md
> +*   Makes ActiveRecord::AttributeMethods::Query respect the getter overrides defined in the model.
```suggestion
*   Makes `ActiveRecord::AttributeMethods::Query` respect the getter overrides defined in the model. 
```

2020-12-18 21:59 UTC, rafaelfranca commented on activerecord/CHANGELOG.md
> +    Fixes #40771
```suggestion
    Fixes #40771.
```

2020-12-18 21:59 UTC, rafaelfranca commented on activerecord/test/cases/attribute_methods_test.rb
> +    def topic.approved() false end
```suggestion
    def topic.approved; false; end
```

2020-12-28 20:04 UTC, feliperaul commented
@rafaelfranca Done, rebased on master and squashed in a single commit

2020-12-28 23:39 UTC, merged

2023-05-26 06:02 UTC, pixeltrix commented
LOL, just realised that this broke a behaviour I've relied on for years when overriding accessors, e.g.

``` ruby
def foo
  foo? ? do_stuff(super) : nil
end
```

Now generates a `SystemStackError: stack level too deep` 😂 

(Not a problem, just documenting the fact should anyone else get puzzled by SystemStackError exceptions when upgrading to 7.0)