ActiveStorage upgrade command
rails/rails pull request #40791
Opened 2020-12-10 19:15 UTC by michelson

### Summary

ActiveStorage::Blob is generating error when upgrading from rails 6.0.3.4 to 6.1 without the proper migration
https://github.com/rails/rails/pull/34935#issuecomment-742715565

2020-12-10 20:23 UTC, bogdanvlviv commented
Hi, thanks for raising this issue. Actually, I don't think we should mention this.

If follow basing instructions of how to upgrade rails app to a new version, a user should execute `bin/rails app:update`
(see https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#the-update-task). According to this change(https://github.com/rails/rails/commit/2bad3f46cdd8decee7d2d9b804ac7c75b5a1cc5d#diff-cab1d0cb70e3e5672120311993d2196ba6fdc82244bd697a7bdfa80f6d6768b9R5 it should trigger `update:active_storage` task.

2020-12-11 17:26 UTC, georgeclaghorn commented
Agree that we shouldn’t mention `active_storage:update`, but it’s probably still worth noting the multi-service changes and that they require a new column.

2020-12-13 23:35 UTC, michelson commented
@georgeclaghorn I've change the release notes, but added the rails update command in the notes, if you want I can remove that part.

question: what will happen to the files that are already uploaded, I mean before the db migrations to multiservice column ? in production application should we take some precautions ?

2020-12-14 14:07 UTC, DmitryTsepelev commented
> question: what will happen to the files that are already uploaded, I mean before the db migrations to multiservice column ? in production application should we take some precautions ?

The generated [migration](https://github.com/rails/rails/pull/34935/files#diff-07ef0a019eb0be7f78b64041f49d5821147e6fec2c6b54dacb68d37ac198f04aR7) will update all existing blobs with the current configured service name. However, I've realized that updating a lot of data (which might be a case for the `blobs` table) as well as adding a `null: false` constraint might take a lot of time, should we add a note suggesting to review the generated migration and change it if needed? (e.g., updating images in batches instead of `update_all`)

2020-12-14 21:23 UTC, michelson commented
@dmitry I agree, I have an application already updated with a lot of images. I will check how long it takes and add some notes here if maintainers are agree

2020-12-15 00:42 UTC, michelson commented
well I thought that I had more blobs that I actually have. I'd run the migrations and the process was smooth for ~1000 records. 
```
== 20201210184517 AddServiceNameToActiveStorageBlobs: migrated (0.0610s) ======
== 20201210184518 CreateActiveStorageVariantRecords: migrated (0.0259s) =======
```

2020-12-15 14:20 UTC, DmitryTsepelev commented
Well 1000 images is not a big deal, I feel like 100k could be a problem

2020-12-16 23:12 UTC, rafaelfranca requested changes

2020-12-16 23:12 UTC, rafaelfranca commented on guides/source/6_1_release_notes.md
> +*   ActiveStorage::Blob#service_name column was added, ( `bin/rails app:update` required ).
```suggestion
*   `ActiveStorage::Blob#service_name` column was added. It is required that a migration is run after the upgrade. Run `bin/rails app:update` to generate that migration.
```

2020-12-17 19:27 UTC, merged

2022-11-28 02:11 UTC, reachlin commented
we have more than 100k images, what's the recommended steps here?