Ignore strict loading violations on instances loaded through fixtures
rails/rails pull request #40792
Opened 2020-12-10 20:01 UTC by ghiculescu

Fixes an issue reported here: https://discuss.rubyonrails.org/t/how-to-eager-load-fixture-associations-in-rails-6-1/76645

2020-12-10 20:02 UTC, ghiculescu commented on activerecord/test/cases/fixtures_test.rb
> +    assert_raises(ActiveRecord::StrictLoadingViolationError) do
this assertion is just to show that strict loading is enabled on this model. by contrast, the next line doesn't crash.

2020-12-10 20:05 UTC, ghiculescu commented
@eileencodes just wondering if this was expected behavior with strict loading? It feels like a bug to me.

2020-12-10 21:19 UTC, eileencodes requested changes
Thanks for the fix, I left some requested changes.

2020-12-10 21:19 UTC, eileencodes commented on activerecord/lib/active_record/fixtures.rb
> +      # through a fixture method.
Can you shorten this comment to "Fixtures can't be eagerly loaded"

2020-12-10 21:19 UTC, eileencodes commented on activerecord/test/cases/fixtures_test.rb
> +    # by constrast, loading the record without a fixture call raises
```suggestion
```

2020-12-10 21:19 UTC, eileencodes commented on activerecord/test/cases/fixtures_test.rb
> +    strict_zines(:going_out).interests.to_a
Can you assert the contents of this array or remove it? Then you don't need the comment below.

2020-12-10 21:19 UTC, eileencodes commented on activerecord/test/cases/fixtures_test.rb
> +  test "strict loading violations are ignored on fixtures" do
Can you move this test to the strict loading test file?

2020-12-10 21:24 UTC, ghiculescu commented
Thanks @eileencodes - I made the requested changes.

2020-12-11 01:03 UTC, merged

2020-12-11 01:03 UTC, eileencodes commented
Thank you @ghiculescu!

2020-12-11 04:24 UTC, ghiculescu commented
Thanks @eileencodes - is there a way to get that fix into the next 6.1.x release?

2020-12-11 13:23 UTC, eileencodes commented
Yes, thank you for the reminder. I backported it in ddec53519e2c61665761e26d8c91a18724570b96

2021-02-10 13:07 UTC, sedubois commented
With this PR merged, once `strict_loading` is used, the danger is that there is no more parity between test and prod, as existing tests using fixtures will still run fine but `ActiveRecord::StrictLoadingViolationError` can be raised in prod. In a way, any test that uses fixtures can't really be trusted any more.

What is the testing strategy to be able to use `strict_loading`? Do we need to rewrite all our tests to remove fixtures?

2021-02-10 15:55 UTC, ghiculescu commented
@sedubois this PR should only remove prevent `ActiveRecord::StrictLoadingViolationError` on instances of fixtures you access directly, eg `strict_zines(:going_out)`. If you access objects through an AR query (`StrictZine.first`) strict loading still applies. And if you write controller/integration tests, any strict loading violations in the app should still raise.

Do you have an example of a test that's problematic with this change?

2021-02-10 18:16 UTC, sedubois commented
@ghiculescu thanks very much. I probably misunderstood as I can't reproduce right now, otherwise I will get back with an example.