Use image/jpeg instead of non-standard image/jpg
rails/rails pull request #40899
Opened 2020-12-21 10:32 UTC by c960657

### Summary

`image/jpg` is [not a valid content type](https://stackoverflow.com/questions/33692835/is-the-mime-type-image-jpg-the-same-as-image-jpeg). Using this in examples and default configuration will mislead developers into using this instead of proper `image/jpeg`.

2020-12-30 00:01 UTC, rafaelfranca requested changes
I agree we should not document or use this, but I don't think we need to break applications that are using this incorrect mime type at this point. I commented where we should keep the references.

2021-01-01 19:36 UTC, c960657 commented on activestorage/lib/active_storage/engine.rb
> -      image/jpg
Done.

I suggest we remove it in Rails 7, so we don't have to carry this cruft around forever.

2021-02-26 19:28 UTC, georgeclaghorn commented
Tests are failing. Not sure all of the failures are legit, but the Action Mailbox ones are.

2021-03-02 07:27 UTC, c960657 commented
Ah, I didn't realise that the Action Mailbox failure was introduced by my changes. The other failures disappeared when I merged `main` into my branch.

2021-03-05 18:14 UTC, merged