Update`form_with` and`form_for` API documentation to reflect new local method default [ci skip]
rails/rails pull request #40946
Opened 2020-12-27 00:40 UTC by kylekeesling

### Summary

Now that Rails 6.1 defaults forms to use local requests rather than remote requests, I realized the documentation wasn't updated to reflect that.

Please let me know if I missed anything or tweaks are needed.

2020-12-28 05:13 UTC, rafaelfranca commented
Thank you for the pull request but since this value is configurable the documentation is actually correct for those with the configuration unset. We need to change the documentation to tell that this is configurable instead of saying "By Default". Can you change the PR?

2020-12-28 14:28 UTC, kylekeesling commented
Perhaps I've got my wires crossed, but according to [the changelog](https://github.com/rails/rails/blob/v6.1.0/actionview/CHANGELOG.md#rails-610-december-09-2020) starting in 6.1 the default will be changed to non-remote:

> Change form_with to generate non-remote forms by default.
> 
> form_with would generate a remote form by default. This would confuse users because they were forced to handle remote requests.
> 
> All new 6.1 applications will generate non-remote forms by default. When upgrading a 6.0 application you can enable remote forms by default by setting config.action_view.form_with_generates_remote_forms to true.

That being the case shouldn't the docs reflect the non-configured default?

At any rate I completely understand and agree that explaining that `config.action_view.form_with_generates_remote_forms` would be very beneficial.

I'll push up the changes to explain the flag, and if I have interpreted the changelog wrong, I'll revert back my other changes.

2020-12-29 00:37 UTC, rafaelfranca requested changes
It is the default only for applications generated with Rails 6.1, or for applications that already are using the `config_for('6.1')`. For all existing applications that didn't change the defaults yet the default is still remote forms.

2020-12-29 00:37 UTC, rafaelfranca commented on actionview/lib/action_view/helpers/form_helper.rb
> +      #   Enable remote and unobtrusive XHRs submits with <tt>local: false</tt>. Remote forms may be enabled by default by setting <tt>config.action_view.form_with_generates_remote_forms = true</tt>
```suggestion
      #   Enable remote and unobtrusive XHRs submits with <tt>local: false</tt>.
      #   Remote forms may be enabled by default by setting
      #   <tt>config.action_view.form_with_generates_remote_forms = true</tt>.
```

2020-12-29 00:37 UTC, rafaelfranca commented
When you are done with the last changes please squash all committs in one.

2020-12-29 12:29 UTC, kylekeesling commented
Suggestion applied and commits squashed.

2020-12-29 22:54 UTC, merged