Action Text rich text area tag should use to_trix_html value
rails/rails pull request #41514
Opened 2021-02-22 05:22 UTC by abhaynikam

Related to: https://github.com/rails/rails/issues/38027#issuecomment-783082920

This PR aims to suggest to use `to_trix_html` instead of action text `to_s` when using `rich_text_area_tag`. Added a delegate in the model to make `to_trix_html` method available easier similar to `to_s` or `to_plain_text`. Not sure if this would require changelog entry. Please do let me know and I'll add the changelog if needed 😊

2021-02-27 02:14 UTC, georgeclaghorn commented
I think we should have `rich_text_area_tag` call `to_trix_html` automatically instead:

```ruby
input_tag = hidden_field_tag(name, value.try(:to_trix_html) || value, id: options[:input])
```

/cc @javan

2021-02-27 13:45 UTC, abhaynikam commented
@georgeclaghorn Thank you for the feedback. Implemented the suggested changes. `rich_text_area_tag` value would automatically call `to_trix_html` now. 😊

2021-02-27 23:31 UTC, georgeclaghorn requested changes

2021-02-27 23:31 UTC, georgeclaghorn commented on actiontext/test/template/form_helper_test.rb
> +      rich_text_area_tag :content, message.content.to_trix_html, { input: "trix_input_1" }
```suggestion
      rich_text_area_tag :content, message.content, { input: "trix_input_1" }
```

2021-02-27 23:31 UTC, georgeclaghorn commented on actiontext/test/template/form_helper_test.rb
> +    form_with model: message, scope: :message do |form|
We generally prefer to leave blank lines around multiline method calls:

```suggestion
    message = Message.new

    form_with model: message, scope: :message do |form|
```

2021-02-28 08:04 UTC, abhaynikam commented
@georgeclaghorn Addressed all the comments. Please have another look 😊

2021-02-28 16:21 UTC, merged

2021-03-01 19:26 UTC, javan commented
> I think we should have `rich_text_area_tag` call `to_trix_html` automatically instead

A belated 👍 from me