Encodes the uploaded file's headers - Closes #38080
rails/rails pull request #41517
Opened 2021-02-22 15:51 UTC by brunoarueira

### Summary

This pull request address the issue #38080

2021-02-22 19:48 UTC, marivaldo requested changes

2021-02-22 19:48 UTC, marivaldo commented on actionpack/lib/action_dispatch/http/upload.rb
> +        @content_type      = hash[:type]
```suggestion
        @content_type = hash[:type]
```

2021-02-22 19:48 UTC, marivaldo commented on actionpack/lib/action_dispatch/http/upload.rb
> +          @headers           = hash[:head].dup
```suggestion
          @headers = hash[:head].dup
```

2021-02-22 20:09 UTC, brunoarueira commented
@marivaldo I've applied the suggested changes!

2021-05-23 21:16 UTC, brunoarueira commented
@zzak @rafaelfranca Someone could review this PR? 😄

2021-05-23 23:51 UTC, zzak reviewed
🤔 This approach seems reasonable to me, but I'm not sure I have enough context to give it a 👍

2021-07-22 14:26 UTC, jessetuglu commented
Hey any status on this PR?

2021-07-22 14:58 UTC, brunoarueira commented
It's depending on the rails core team to review yet

2021-10-20 15:12 UTC, marcelolx commented
+1

2022-01-18 16:31 UTC, brunoarueira commented
waiting for the rails team to review 😃 

ping @rafaelfranca

2022-04-18 17:36 UTC, brunoarueira commented
still waiting for the rails team 😃

2022-09-09 20:05 UTC, merged