[ci skip] Improve Readability of Guides on Multiple Databases
rails/rails pull request #41670
Opened 2021-03-13 15:53 UTC by aeroastro

### Summary

While reading the Rails Guides, I noticed there are some rooms for improvement
for guides on Multiple Databases.

* Add comma after the introductory clause.
* Add backtick for the symbols used in the program.
  * `primary`
  * `false`
* Add descriptive information on ambiguous words.
  * users => database users
  * use the first configuration => use the first configuration as default
  * a recent write => a recent write by the requesting user
  * for an environment => for each environment
  * both a `role` and `shard` => both a `role` and a `shard`
* Remove duplicate description from the wrong place.
  * Note on replica specification is mentioned previously in the context of `ApplicationRecord`.
* Add missing period at the end of a sentence.

and misc improvement that I think helps readers to understand the Rails more.

2021-03-13 16:06 UTC, aeroastro commented on guides/source/active_record_multiple_databases.md
> -
Sorry, but I noticed that this is not fully addressed at the previous document.
So, I will revert this removal and squash the commit. (Maybe we can find the best place afterwards)

2021-03-23 17:22 UTC, aeroastro commented
I have fixed the title because this PR is rather fixing grammatical errors (punctuations) and ambiguous wording than just an enhancement.

2021-03-24 04:47 UTC, rafaelfranca requested changes

2021-03-24 04:47 UTC, rafaelfranca commented on guides/source/active_record_multiple_databases.md
> +there is no configuration named `primary`, Rails will use the first configuration as default
```suggestion
there is no configuration named `"primary"`, Rails will use the first configuration as default
```

2021-03-24 07:32 UTC, aeroastro commented
Thank you for reviewing this 🐱 
I have committed the suggestion.

2021-03-25 03:36 UTC, merged