Convert ActiveRecord::Base.legacy_connection_handling to not use a class variable
rails/rails pull request #41807
Opened 2021-03-31 07:50 UTC by casperisfine

This accessor is very frequently accessed in production, and we often see it around 1% of production runtime.

Class variable are very slow, and [even though it might get better in Ruby 3.1](https://bugs.ruby-lang.org/issues/17763), until then it is better to only use them if absolutely necessary.

Here `legacy_connection_handling` is never called on descendants, it is basically just a global, hence doesn't need the inheritance semantic of class variables.

So by moving it to be a regular instance variable of a module, it can be almost 3x faster:

```ruby
require 'benchmark/ips'
require 'active_support/all'

class CVarBase
  mattr_accessor :legacy_connection_handling, instance_writer: false, default: true

  def self.connection_handlers
    unless legacy_connection_handling
      raise NotImplementedError, "The new connection handling does not support accessing multiple connection handlers."
    end

    @@connection_handlers ||= {}
  end

  def self.connection_handlers=(handlers)
    unless legacy_connection_handling
      raise NotImplementedError, "The new connection handling does not setting support multiple connection handlers."
    end

    @@connection_handlers = handlers
  end
end

class CVarChild < CVarBase
end

class RefactorBase
  module Config
    extend self
    attr_accessor :legacy_connection_handling
    @legacy_connection_handling = true

    attr_accessor :connection_handlers
    @connection_handlers = {}
  end

  def self.legacy_connection_handling
    Config.legacy_connection_handling
  end

  def self.legacy_connection_handling=(enabled)
    if (Config.legacy_connection_handling = enabled)
      Config.connection_handlers ||= {}
    else
      Config.connection_handlers = false
    end
  end

  def self.connection_handlers
    Config.connection_handlers or raise NotImplementedError, "The new connection handling does not setting support multiple connection handlers."
  end

  def self.connection_handlers=(handlers)
    unless legacy_connection_handling
      raise NotImplementedError, "The new connection handling does not setting support multiple connection handlers."
    end

    Config.connection_handlers = handlers
  end
end

class RefactorChild < RefactorBase
end

Benchmark.ips do |x|
  x.report('cvar') { CVarChild.connection_handlers }
  x.report('const_ivar') { RefactorChild.connection_handlers }
  x.compare!
end
```

```
Warming up --------------------------------------
                cvar   547.633k i/100ms
          const_ivar     1.458M i/100ms
Calculating -------------------------------------
                cvar      5.418M (± 1.7%) i/s -     27.382M in   5.054881s
          const_ivar     14.576M (± 1.6%) i/s -     72.907M in   5.003221s

Comparison:
          const_ivar: 14576090.3 i/s
                cvar:  5418439.1 i/s - 2.69x  (± 0.00) slower
```

cc @eileencodes because cvars and connection handlers.
cc @tenderlove because we talked about this yesterday.
cc @jhawthorn @rafaelfranca just because.

2021-03-31 13:07 UTC, eileencodes requested changes
> This accessor is very frequently accessed in production, and we often see it around 1% of production runtime.

I'd be surprised if this was more expensive than it was before legacy_connection_handling, since `connection_handlers` is/was accessed for every request before legacy_connection_handling. In my performance testing before merging, there was no difference between main and my branch that introduced this. Since this changes both which are both class vars, it will make a big difference. I'd like to know if there are any blockers to moving to the new handling in Shopify though, happy to help / improve Rails if it's not straightforward.

2021-03-31 22:04 UTC, rafaelfranca reviewed
Speaking on migrating of `legacy_connection_handling`, is there a plan to remove it?

2021-03-31 22:23 UTC, eileencodes commented
> Speaking on migrating of legacy_connection_handling, is there a plan to remove it?

Yea that's the plan after 7.0. It's not very useful to keep around since the new handling behaves exactly the same if you keep using Base.connected_to.

2021-03-31 22:51 UTC, rafaelfranca commented
So should we deprecate in 7.0? That would force Shopify to remove :trollface:

2021-03-31 22:55 UTC, eileencodes commented
> So should we deprecate in 7.0? That would force Shopify to remove :trollface:

Yea I thought I did but realized I didn't yet deprecate it. I'll add that tomorrow in https://github.com/rails/rails/blob/main/activerecord/lib/active_record/railtie.rb#L214-L216. Doing it there will prevent it from firing on every request.

2021-04-01 07:34 UTC, casperisfine commented
> I'd be surprised if this was more expensive than it was before legacy_connection_handling

I have no historical profiles to compare, so indeed I don't know. This isn't so much about reclaiming lost performance than it is about claiming some.

> In my performance testing before merging, there was no difference between main and my branch that introduced this.

It's entirely possible that our app might be calling these methods way more than it should. Maybe a more vanilla Rails app spend very little time in here, I should investigate on our side.

2021-04-02 16:13 UTC, casperisfine commented
> It's entirely possible that our app might be calling these methods way more than it should.

Ok, so indeed we're going through the connection handler much more than a regular Rails app would. We'll have to fix that on our side.

Let me know if you think this change is still worth it anyway.

2021-06-17 06:59 UTC, closed without merging