WIP Log a warning when running SQLite in production
rails/rails pull request #42191
Opened 2021-05-10 11:05 UTC by intrip

### Summary

Logs a warning message when running SQlite in production.
The warning can be disabled by setting `config.active_record.sqlite3_production_warning=false`.

Closes #34715

2021-05-10 14:37 UTC, SkipKayhil commented on activerecord/lib/active_record/railtie.rb
> +    initializer "sqlite3_production_warning" do
```suggestion
    initializer "active_record.sqlite3_production_warning" do
```

I think all of the other initializers in here are prefixed

2021-05-11 12:29 UTC, eileencodes requested changes
Can you add a changelog entry?

2021-05-11 12:29 UTC, eileencodes commented on railties/test/application/configuration_test.rb
> +    test "doesn't log a warning when running SQlite3 in production and sqlite3_production_warning=false" do
```suggestion
    test "doesn't log a warning when running SQLite3 in production and sqlite3_production_warning=false" do
```

2021-05-11 14:30 UTC, intrip commented
@eileencodes thanks for the review! I've applied the suggestion and added the CL entry

2021-05-11 14:55 UTC, eileencodes approved these changes

2021-05-11 14:55 UTC, merged

2021-06-02 15:47 UTC, strzibny commented
I find this change a bit strange. SQLite is a good production-like database. Shouldn't this change be about reporting mismatch between dev and production environment rather than suggesting that SQLite is not a good database?

2021-06-03 06:48 UTC, intrip commented
You can find all the conversations + the reasons of this change in https://github.com/rails/rails/issues/34715

2021-06-03 10:28 UTC, strzibny commented
I reread it and I am very disappointed. Seriously folks! The argument is that SQLite doesn't scale beyond a certain point? As long as it's a supported database in Rails, this change should be reverted.

2021-06-03 13:59 UTC, zzak commented
@strzibny That's fair, and there is nothing stopping you from using SQLite in production. This warning is intended to notify people who might not be as comfortable managing that database in a production environment, if you're comfortable choosing that database as your preferred solution more power to you.

2021-06-03 15:20 UTC, strzibny commented
@zzak The problem is that you got it backward I think.

Managing SQLite is **super simple** whereas making a production-grade MySQL/PostgreSQL deployment is _much more daunting_. A lot of beginners have trouble making even a development environment work -- I know, because in my early days I used some Mac OS app to do it for me, and it was something I didn't understand. 

Nobody shouldn't be forced to suddenly stop - and go learn about production-grade PostgreSQL deployment only to finish the deployment of their simple projects on a virtual server. They could just carry on with SQLite. It's a great first step. I and you understand that the warning is in fact wrong, but those starting would take it as a serious recommendation.

I always liked that Rails supported SQLite so that beginners (but also professionals) can make a simple app/showcase and also put it into production with very little effort. I compare it with Phoenix where we still don't have a good SQLite story and it's in fact a bit annoying. Deploying databases is not an easy feat! It requires some studying to do it right. But for SQLite? No issue. Can you manage a file? Then you can manage SQLite.

2021-06-03 16:23 UTC, strzibny commented
I am trying to recheck the guides https://guides.rubyonrails.org/getting_started.html#creating-a-new-rails-project-installing-rails and there is nothing about SQLite not being supported for production.

I think this is about expectations. Is SQLite supported as a production database in Rails? If yes, there **cannot** be a warning about using it in production. If not, I would expect we change the docs to mention it.

Users (especially beginners) shouldn't find out the database they chose is not supported once they actually go and deploy. That's very unergnomic.

2021-06-03 16:24 UTC, eileencodes commented
@strzibny I appreciate your perspective and concern, but the core team discussed this on the issue and came to a consensus to add this logged warning. It doesn't prevent you from using sqlite. We don't have plans to revert this at the moment.

2021-06-03 16:24 UTC, strzibny commented
Okay. It's unfortunate, but it's up to you.

2021-06-03 16:27 UTC, strzibny commented
@eileencodes can you please confirm or deny whether SQLite is still supported for production use in Rails? The guides mention SQLite all the time, but it's actually not clear to me if this is supported now or not.

2021-06-03 16:50 UTC, eileencodes commented
@strzibny it's a single warning issued on boot in the production env. Nothing is _preventing_ you from using SQLIite in any environment. It is still supported the same as it was before, just with a little warning in your logs.

All the reasoning for adding this was explained in the issue. You're free to dislike it and you're free to keep using sqlite. However, please stop arguing with us about this. We are not reverting this change and I will lock this PR if you keep arguing with us.