Add Range serializer for ActiveJob
rails/rails pull request #42219
Opened 2021-05-13 16:25 UTC by fsateler

### Summary

This change adds an ActiveJob serializer for the core ruby Range object.

### Other Information

Missing Range support means users need to add start/finish pair of arguments instead of simply passing a Range object.

2021-05-15 14:00 UTC, pixeltrix requested changes
Looks good - just a few tweaks and can you add a CHANGELOG entry please? 👍🏻

2021-05-16 03:28 UTC, fsateler commented on activejob/lib/active_job/serializers/range_serializer.rb
> +      end
`serialize` would allocate one extra array (the one returned by zip). I don't know how relevant that is (I mean, if you are enqueueing jobs, there will be plenty of time spent communicating with the backend), so I changed it to your suggestion.

2021-05-16 07:35 UTC, pixeltrix approved these changes

2021-05-16 07:38 UTC, merged

2021-05-16 07:38 UTC, pixeltrix commented
@fsateler thanks for your contribution and speedy turnaround on the changes! 👍🏻