Fix documentation for ActiveRecord#create_with [ci skip]
rails/rails pull request #42530
Opened 2021-06-18 01:48 UTC by ur5us

### Summary

As per documentation `users.create_with(nil)` will reset attributes to be used when creating new records from a relation object. However, the example `users.new.name` was wrongly stating that `'Oscar'` will be returned when in fact it’s `nil`.

2021-06-18 03:33 UTC, zzak approved these changes

2021-06-18 03:46 UTC, zzak requested changes
Sorry I didn't mean to approve this. Was still testing it locally and I found the behavior to be correct:

```
Loading development environment (Rails 7.0.0.alpha)
>> users = User.where(name: 'Oscar')
   (2.6ms)  SELECT sqlite_version(*)
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."name" = ?  [["name", "Oscar"]]
=> []
>> users.new.name
=> "Oscar"
>> users = users.create_with(name: 'DHH')
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."name" = ?  [["name", "Oscar"]]
=> []
>> users.new.name
=> "DHH"
>> users = users.create_with(nil)
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."name" = ?  [["name", "Oscar"]]
=> []
>> users.new.name
=> "Oscar"
```

This was with a fresh Rails install, and `bin/rails g model User name:string` and `db:migrate`.

2021-08-29 15:26 UTC, simi commented
I can confirm documentation is alright using Rails 6.1.4 as well.

```ruby
User.where(name: 'Oscar').create_with(name: 'DHH').new.name
=> "DHH"

User.where(name: 'Oscar').create_with(name: 'DHH').create_with(nil).new.name
=> "Oscar"
```

2021-08-29 22:13 UTC, ur5us commented
@zzak @simi Ah, you are both correct. I was reading the docs differently. When the instructions are followed top to bottom it all works exactly as documented. My bad, I did:

```ruby
users = User.create_with(name: 'DHH')
users.create_with(nil).new.name # => nil
```

So I left out the first step (`User.where(name: 'Oscar'`) assuming that it won’t change the outcome. 

I still believe the docs are at least misleading:

> Sets attributes to be used when creating new records from a relation object.

but that’s a different issue potentially requiring a different change. Reading that sentence without the example code I’d expect 

```ruby
User.where(name: 'Oscar').create_with(name: 'DHH').create_with(nil).new.name 
```

to return `nil` but that could be me.

2021-08-29 22:13 UTC, closed without merging