Fix invalid parts after sum of Durations
rails/rails pull request #42806
Opened 2021-07-17 14:34 UTC by martinjaimem

## Summary
Closes #42802 

Nowadays when performing a division of AS Duration, it may happen that the "`duration._parts`" end up being empty but that doesn't mean that the duration has less than 1 second. This is because the Division of a Duration and an Integer create a Duration object with parts formed by Integers and not by Floats.

As an example: 
```
pry(main)> (1.hour / 10).parts
=> {}
pry(main)> (1.hour * 0.1).parts
=> {:hours=>0.1}
```

Apart from that, the `def +(other)` method doesn't handle sum of objects with empty `._parts` as it just ignores them, so:

`(1.hour / 10 + 1000.seconds).inspect`
would be equal to 
`(1000.seconds).inspect`
.

## Proposed solution: 
In the proposed solution, the empty parts are treated as the real value of the duration expressed in seconds, which is similar to what the `inspect` method does.

```
def inspect #:nodoc:
      return "#{value} seconds" if @parts.empty?
      ...
```

I'm still not sure if I'm missing some edge cases, so any feedback would be awesome 😄 

### Other possible solution: 

Another option would have been to manage Floats instead of Integers while doing a division. This would bean rewriting the `def /(other)` method to:
```
# Divides this Duration by a Numeric and returns a new Duration.
    def /(other)
      if Scalar === other
        Duration.new(value / other.value, @parts.transform_values { |number| number.to_f / other.value }, @variable)
      elsif Duration === other
        value.to_f / other.value
      elsif Numeric === other
        Duration.new(value / other, @parts.transform_values { |number| number.to_f / other }, @variable)
      else
        raise_type_error(other)
      end
    end
```
But this has its drawbacks as it affects the result of the Division that in the tests is specifically tested that the result of the Division is an `Integer`. Also, this would mean that the result of doing `(1.day / 24).inspect`
would be `"0.041666666666666664 days`.

2021-07-17 16:02 UTC, ysugiyama12 commented
Hi, @martinjaimem. Thanks for investigating the issue I proposed!
On your current implementation, outputs seem to be as follows:

```
# invalid when `Integer + Duration` 
pry(main)> 1 + 1.hour/10
=> 1 second

# valid when `Duration + Integer`
pry(main)> 1.hour/10 + 1
=> 361 seconds
```
Any good ideas about that?

2021-07-18 00:32 UTC, ysugiyama12 commented
Maybe you should apply the same change to subtraction, which affects the result of `(370 - 1.hour/10).inspect`

https://github.com/rails/rails/blob/ef4b3fc5854454e20364422bb1206fffadcbddfc/activesupport/lib/active_support/duration.rb#L53-L64

2021-07-18 12:28 UTC, martinjaimem commented
good call @ysugiyama12 , thanks!

2021-08-02 22:54 UTC, ghiculescu requested changes
This looks good, can you squash your commits?

2021-11-08 17:22 UTC, closed without merging