Remove some Node/Yarn mentions from guides [ci-skip]
rails/rails pull request #43121
Opened 2021-08-28 10:51 UTC by p8

### Summary

The Getting Started guide currently mentions installing Node and Yarn,
but these are no longer required dependencies for getting started.

The ActionText install instructions also mentions "Yarn package", which
isn't used anymore by default. Instead we can use a more generic
"Javascript packafe".

### Other Information

The development_dependencies_install guides still mention Yarn but I'm
not sure those can be deleted yet.

2021-09-19 18:59 UTC, dhh commented
We need a way to state that these are still requirements when using js bundling. But not for the default path.

2021-09-20 20:17 UTC, rafaelfranca requested changes

2021-09-20 20:17 UTC, rafaelfranca commented on guides/source/action_text_overview.md
> +Run `bin/rails action_text:install` to add the Javascript package and copy over the necessary migration. Also, you need to set up Active Storage for embedded images and other attachments. Please refe
```suggestion
Run `bin/rails action_text:install` to add the JavaScript package and copy over the necessary migration. Also, you need to set up Active Storage for embedded images and other attachments. Please refer to the [Active Storage Overview](active_storage_overview.html) guide.
```

2021-09-22 10:02 UTC, p8 commented
@dhh @rafaelfranca  I've moved the Node.js and Yarn instructions to the Webpacker guide for now, as these are requirements for Webpacker.
I'm not familiar enough yet with the js bundling to add that to the guides.

2021-09-22 10:18 UTC, dhh commented
Not sure it makes sense fiddling with the webpacker guide in isolation, since that's not part of the Rails 7 story. Think we a complete rewrite with a new guide ala JavaScript with Rails that can explain our three paths per https://world.hey.com/dhh/rails-7-will-have-three-great-answers-to-javascript-in-2021-8d68191b.

2021-09-22 22:31 UTC, rafaelfranca commented
Right. I think rewriting https://github.com/rails/rails/blob/main/guides/source/working_with_javascript_in_rails.md is a good start.

2021-11-12 22:21 UTC, schmijos commented
We also need to think about the binstub `bin/yarn`. Who should provide this in Rails 7? `railties or `jsbundling-rails`?

2021-11-14 20:02 UTC, zarqman commented
> We also need to think about the binstub `bin/yarn`. Who should provide this in Rails 7? `railties` or `jsbundling-rails`?

@schmijos, `bin/yarn` is no longer created by Rails 7 as of #42999. `jsbundling-rails` calls `yarn build` directly, relying on the PATH to locate yarn. There is some legacy stuff related to `bin/yarn` in the`yarn:install` task which is pending clean up via #43641.

2021-12-22 09:20 UTC, p8 commented
Closing in favor of #43957

2021-12-22 09:20 UTC, closed without merging