add section for host header attack prevention in rails security guide
rails/rails pull request #43330
Opened 2021-09-29 08:33 UTC by aka47

This PR fixes rails/rails#42817

2021-10-06 17:58 UTC, p8 commented
This looks great, thanks!
Also great find with that incorrect `host_configuration` in `configuring.md`.

2021-10-06 18:48 UTC, p8 requested changes

2022-01-05 17:32 UTC, rafaelfranca commented on guides/source/security.md
> +It is recommended to use the ActionDispatch::HostAuthorization middleware to guard against DNS rebinding and other Host header attacks. It is enabled by default in the development environment, you ha
```suggestion
It is recommended to use the `ActionDispatch::HostAuthorization` middleware to guard against DNS rebinding and other Host header attacks. It is enabled by default in the development environment, you have to activate it in production and other environments by setting the list of allowed hosts. You can also configure exceptions and set your own response app.
```

2022-01-05 17:32 UTC, rafaelfranca commented on guides/source/security.md
> +You can read more about it in the [ActionDispatch::HostAuthorization middleware documentation](/configuring.html#actiondispatch-hostauthorization)
```suggestion
You can read more about it in the [`ActionDispatch::HostAuthorization` middleware documentation](/configuring.html#actiondispatch-hostauthorization)
```

2022-04-12 17:47 UTC, p8 requested changes
Sorry this has taken so long @aka47 😞 
This looks great.
Just some small changes, and this is good to go.

2022-04-12 17:47 UTC, p8 commented on guides/source/security.md
> +#### DNS rebinding and Host header attacks
Most words are capitalized in headings:
https://guides.rubyonrails.org/ruby_on_rails_guides_guidelines.html#headings
```suggestion
#### DNS Rebinding and Host Header Attacks
```

2022-04-12 17:47 UTC, p8 commented on guides/source/security.md
> +It is recommended to use the `ActionDispatch::HostAuthorization` middleware to guard against DNS rebinding and other Host header attacks. It is enabled by default in the development environment, you
As this middleware is optional on production (as most will be running Rails behind a proxy), I think we can reword it a little to make it less prescriptive. Maybe something like:
```suggestion
It is recommended to use the `ActionDispatch::HostAuthorization` middleware to guard against DNS rebinding and other Host header attacks. It is enabled by default in the development environment. To enable it in production and other environments set the list of allowed hosts. You can also configure exceptions and set your own response app.
```

2022-05-20 18:12 UTC, merged

2022-05-20 19:51 UTC, p8 commented
Thanks @aka47 ! 🙌