Remove glob pattern from app/channels load path
rails/rails pull request #43570
Opened 2021-10-29 18:42 UTC by mctaylorpants

### Summary

For some reason, the Rails Engine configuration adds a glob pattern to the load path for `app/channels`. This causes channel classes themselves to be included on the load path, as opposed to just the directory:

```
$> ActiveSupport::Dependencies.autoload_paths.grep(/channels/)
=> ["/my_rails_app/app/channels", "/my_rails_app/app/channels/test_channel.rb"]
```

It was my understanding that load paths should represent _paths_, not files, so this seems a bit odd. 

### Other Information

This glob pattern has necessitated at least one change in Zeitwerk (https://github.com/rails/rails/issues/36461), which fixed it by working around the fact that files were present in a list of directories.

This also causes issues with users of [packwerk](https://github.com/Shopify/packwerk). Packwerk maintains a list of the application's load paths in its config file, and the fact that channel files appear in the load path means the files themselves need to be added to the list.  

I'm unsure if there's a reason for this glob pattern, but I could be missing something. In case it helps trip someone's memory, it was added during [this refactor](​​https://github.com/rails/rails/pull/23505).

2021-11-01 23:17 UTC, rafaelfranca commented
Thank you for the pull request. `Path` object are allowed to contain globs and thus return files. I think the proper fix would be to filter those files before setting the load paths instead of removing globs.

2021-11-01 23:17 UTC, rafaelfranca requested changes
Thank you for the pull request. Path object are allowed to contain globs and thus return files. I think the proper fix would be to filter those files before setting the load paths instead of removing globs.

2021-11-01 23:20 UTC, rafaelfranca commented
Ah, but all the code that depended on this glob was removed. In that case let's remove. Can we remove the workaround added in #36461 as well in this PR or that is till needed?

2021-11-02 20:42 UTC, mctaylorpants commented
@rafaelfranca thanks for taking a look!

I took a look at the zeitwerk commit which originally worked around the issue: https://github.com/rails/rails/commit/43ae74f6f66999671b3cd2a6747e3d8fecf09b1c. The current implementation is below. I believe it might make sense to keep it as-is since it would continue to guard against any user-defined load paths which might match against files. Let me know what you think.

https://github.com/rails/rails/blob/dd5a49c14082b559355b1f4d8bc5b686e8f67e3f/railties/lib/rails/tasks/zeitwerk.rake#L55-L57

2021-11-02 20:52 UTC, merged

2021-11-02 20:52 UTC, rafaelfranca commented
Makes sense to me.