Enable open struct cop
rails/rails pull request #44473
Opened 2022-02-17 23:48 UTC by gmcgibbon

In https://github.com/rails/rails/pull/44328 I noticed we don't have the `Performance/OpenStruct` cop enabled. This PR enables it, enables performance cops in tests, and corrects its use in tests. 

Enabling performance cops in tests may be controversial. Rails' test suite isn't slow, and maybe this is over-optimization. However, I think tests should default to be written with the same expectations and quality standards library code is.

I'm happy to adjust the approach to just enable `Performance/OpenStruct` for library code and leave tests out of it, or continue fixing the TODOs in another PR if we agree to keep it as-is. Let me know what you think!

2022-02-18 10:24 UTC, matthewd commented
Performance cops are unsafe for our test suite, and must be disabled. (I'm a little surprised those todos are the only violations being reported, but perhaps that's just because we have most performance cops disabled globally.)

I have no strong feelings on openstruct in particular... it really just feels like slightly more noise when tests want a one-off "I don't care, just make it respond to these methods", and that's what ostruct provides.

2022-02-18 15:06 UTC, kaspth commented
Skimming through the tests, those OpenStruct uses are fine and seem to state the intent clearer to me. I don't think it's worth changing those.

Was it Ruby core that discouraged the OpenStruct use in lib (and tests?) or just RuboCop?

2022-02-18 19:52 UTC, gmcgibbon commented
> Performance cops are unsafe for our test suite, and must be disabled. 

Could you clarify why?

> Skimming through the tests, those OpenStruct uses are fine and seem to state the intent clearer to me. I don't think it's worth changing those.

Personally I find the named structs more helpful (especially [here](https://github.com/rails/rails/blob/159ce6921550f363b46625c243faa6ddad995579/actionview/test/template/form_helper_test.rb#L278)), but I can see most usages don't really make a big difference in terms of readability.

> Was it Ruby core that discouraged the OpenStruct use in lib (and tests?) or just RuboCop?

There is a new cop in rubocop core that references [this doc](https://docs.ruby-lang.org/en/3.0/OpenStruct.html#class-OpenStruct-label-Caveats) and says it is ["officially discouraged"](https://github.com/rubocop/rubocop/blob/9f82e0fb2a581283e588a7161839a10c77a2509c/lib/rubocop/cop/style/open_struct_use.rb#L6).

Seems like maybe I should just keep the first commit and remove the rest?

2022-02-22 22:17 UTC, rafaelfranca requested changes
(wrong review)

2022-02-22 22:17 UTC, rafaelfranca reviewed
While this cop is in the performance department I think the value of not allowing OpenStruct in tests is mostly a lint. OpenStruct respond to everything, so typos are hard to identify, we also have better objects to "I don't care, just make it respond to these methods" in test suites, the stubs. So I think it makes sense to get rid of all OpenStruct we have an push people to write better tests using stubs, mocks, or even named objects.

2022-02-22 22:17 UTC, rafaelfranca approved these changes
While this cop is in the performance department I think the value of not allowing OpenStruct in tests is mostly a lint. OpenStruct respond to everything, so typos are hard to identify, we also have better objects to "I don't care, just make it respond to these methods" in test suites, the stubs. So I think it makes sense to get rid of all OpenStruct we have an push people to write better tests using stubs, mocks, or even named objects.

2022-02-22 22:22 UTC, merged

2022-02-23 01:12 UTC, matthewd commented
> Could you clarify why? I'd like to understand this better.

A performance cop autocorrecting "use `foo` instead of `bar`, it has the same result and is faster" is actively unhelpful in a test of our `bar` method. (Likewise in a test of our `foo` method, where we're deliberately doing the less-efficient `bar` to check the result.)