fix namespaced schema load ignoring protected env
rails/rails pull request #44631
Opened 2022-03-07 16:31 UTC by SkipKayhil

### Summary

This makes the task requirements for db:schema:load:namespace the same
as db:schema:load (adding check_protected_environments)

### Other Information

Fixes #44630

2022-03-07 17:05 UTC, eileencodes requested changes
Thank you for the fix!

Can you add a test in this file? railties/test//application/rake/multi_dbs_test.rb

2022-03-08 00:48 UTC, SkipKayhil commented
> Can you add a test in this file? railties/test//application/rake/multi_dbs_test.rb

Added a test (and also one for single db), let me know if you think anything should be changed

2022-03-08 07:36 UTC, delphaber commented
Thanks for the fast fix :) Can this be backported to Rails 6 too?

2022-03-08 14:15 UTC, eileencodes approved these changes

2022-03-08 14:18 UTC, merged