Fix `#version` method docs and some typos [ci-skip]
rails/rails pull request #44693
Opened 2022-03-15 00:41 UTC by ghousemohamed

### Summary

Made the doc for the `#version` method more consistent and fixed a few typos.

### Other Information

2022-03-15 20:11 UTC, rafaelfranca requested changes

2022-03-15 20:11 UTC, rafaelfranca commented on actionpack/lib/action_pack/version.rb
> +  # Returns the version of the currently loaded Action Pack as a <tt>Gem::Version</tt>.
```suggestion
  # Returns the currently loaded version of Action Pack as a <tt>Gem::Version</tt>.
```

2022-03-15 20:11 UTC, rafaelfranca commented on actionview/lib/action_view/version.rb
> +  # Returns the version of the currently loaded Action View as a <tt>Gem::Version</tt>.
```suggestion
  # Returns the currently loaded version of Action View as a <tt>Gem::Version</tt>.
```

2022-03-15 20:11 UTC, rafaelfranca commented on activerecord/lib/active_record/version.rb
> +  # Returns the version of the currently loaded Active Record as a <tt>Gem::Version</tt>.
```suggestion
  # Returns the currently loaded version of Active Record as a <tt>Gem::Version</tt>.
```

2022-03-15 20:11 UTC, rafaelfranca commented on activestorage/lib/active_storage/version.rb
> +  # Returns the version of the currently loaded Active Storage as a <tt>Gem::Version</tt>.
```suggestion
  # Returns the currently loaded version of Active Storage as a <tt>Gem::Version</tt>.
```

2022-03-15 20:11 UTC, rafaelfranca commented on activesupport/lib/active_support/version.rb
> +  # Returns the version of the currently loaded Active Support as a <tt>Gem::Version</tt>.
```suggestion
  # Returns the currently loaded version of Active Support as a <tt>Gem::Version</tt>.
```

2022-03-15 20:23 UTC, ghousemohamed commented
@rafaelfranca I've made the changes as you have suggested.
I have a query related to the `#version` and `#gem_version` methods. Both the methods return the same value. Shouldn't there be a distinction between the two methods? For example, in `railties`, I can see that `#version` returns `VERSION::STRING` whereas `#gem_version` returns Gem::Version.new VERSION::STRING`. Here there is a clear distinction between the two methods. Should this be the case for all other gems?

2022-03-15 20:27 UTC, rafaelfranca commented
No. [The Rails `version` returns a string because of backwards compatibility. `version` is also in the other components there also for backwards compatibility since it doesn't add much value deprecate i](https://github.com/rails/rails/pull/14101)t. We could say `version` should return strings, but that will break someones code and it is not worth it.

2022-03-15 20:28 UTC, merged

2023-02-13 22:06 UTC, Caoxokhuyen reviewed
5c1bd20f0d80bc71caf807432ba1c3936f3f3fb3