Add error wrapper when rich_text_area is required
rails/rails pull request #44786
Opened 2022-03-28 20:01 UTC by kaiquekandykoga

It is wrapping trix-editor with a div like other ActionView helpers when invalid.

https://github.com/rails/rails/issues/44762

2022-05-30 17:48 UTC, p8 requested changes

2022-05-30 17:48 UTC, p8 commented on actiontext/app/helpers/action_text/tag_helper.rb
> +      end
Would it be possible to reuse the implementation of `ActiveModelInstanceTag`?
https://github.com/rails/rails/blob/27d24e9caa1942fb29f87bc14f66b5a0aaf53773/actionview/lib/action_view/helpers/active_model_helper.rb#L28

```suggestion
      error_wrapping(html_tag)
```
If not, can we maybe we include that helper?

2022-10-05 17:25 UTC, jonathanhefner reviewed
This seems to be an oversight rather than intentional, so I think it makes sense to add. :+1:  But we should add a CHANGELOG entry, since it can affect the HTML output.

2022-12-22 18:27 UTC, merged

2022-12-22 18:27 UTC, jonathanhefner commented
I pushed a commit to clarify the CHANGELOG:

```diff
diff --git a/actiontext/CHANGELOG.md b/actiontext/CHANGELOG.md
index 4e17365fb6..a15da7ee62 100644
--- a/actiontext/CHANGELOG.md
+++ b/actiontext/CHANGELOG.md
@@ -1,4 +1,4 @@
-*   Wrap trix-editor with a div like other ActionView helpers when invalid
+*   Apply `field_error_proc` to `rich_text_area` form fields.

     *Kaíque Kandy Koga*
```

and to [squash the commits](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits).

Thank you, @kaiquekandykoga! :spiral_notepad: