Allow unscoping of preload and eager_load associations
rails/rails pull request #45147
Opened 2022-05-21 18:20 UTC by dmorehouse

### Summary

Adds the ability to unscope preload and eager_load associations.
This is the same functionality as `unscope(:includes)` which
may chose to use eager_loading or preloading based on the
overall query complexity.

### Other Information

In cases where the type of association
loading is explicit (eager_load and preload), this allows for
unscoping the explicit association loading.  This is helpful when
taking an existing query and performing an aggregate when
has_many associations have explicitly asked for eager_load or
preload. In the example below, unscoping the two has_many
associations removes the extra preload query and eager_load
join.

        query.eager_load!(:has_many_association1)
        query.preload!(:has_many_association2)
        query.unscope(:eager_load, :preload).group(:id).select(:id)

There are also cases where depending on the aggregation
and select the explict preload fails when the select does not
include the preload association key. This issue led me to
write this fix.

2022-05-25 13:49 UTC, dmorehouse commented
Squashed my commits for formatting changes made after the initial PR.

2022-11-07 07:55 UTC, p8 requested changes
Thanks for contributing to Rails @dmorehouse !
This makes sense to me.
Could you rebase to main?

2022-11-07 07:55 UTC, p8 commented on activerecord/CHANGELOG.md
> +    includes, joins, SEE ActiveRecord::QueryMethods::VALID_UNSCOPING_VALUES
```suggestion
    includes, joins, etc. See ActiveRecord::QueryMethods::VALID_UNSCOPING_VALUES
```

2022-11-12 14:13 UTC, dmorehouse commented on activerecord/CHANGELOG.md
> +    includes, joins, SEE ActiveRecord::QueryMethods::VALID_UNSCOPING_VALUES
Suggestion added to rebased PR

2022-11-12 14:27 UTC, dmorehouse commented
The build failure looks to be unrelated as a previous markdown only PR failed on the same test with the same reason. See build https://buildkite.com/rails/rails/builds/90914#0184692a-b4b4-4f26-b217-beb2fc76166c for PR https://github.com/rails/rails/pull/46479/files

2022-11-12 14:30 UTC, dmorehouse commented
@p8 Thank you for taking the time to review my PR and the feedback so that I can get this into the next release of Rails. Really appreciate it.

2022-11-13 10:11 UTC, p8 commented
Thanks @dmorehouse !

2022-11-14 23:33 UTC, merged

2022-11-14 23:45 UTC, rafaelfranca commented
> I've noticed that the activerecord/CHANGELOG is already out of date, do I need to keep rebasing and updating it or do the Rails committers do that since that file changes so much and there are multiple activerecord related PRs with the ready label.

In those cases I usually resolve the conflicts myself, so you as a contributor doesn't have the burden to keep updating the PR. If the conflicts are bigger than CHANGELOG we usually ask here for a rebase to the author.

2022-11-15 13:28 UTC, dmorehouse commented
@rafaelfranca Thanks for the insight into the workflow. The first accepted PR is alway the hardest. I'm looking forward to my next contribution!

2022-11-15 19:22 UTC, p8 commented
Thanks @dmorehouse !