MemCacheStore shorten keys properly
rails/rails pull request #45245
Opened 2022-06-02 15:59 UTC by akostadinov

The logic for shortening long keys in MemCacheStore
is broken since the time it stopped using MD5 checksumming.

Memcached supports keys up to 250 chars length. The reason
things worked I believe is because the underlying Dalli
library is doing it's own key shortening. Which uses its own
hashing function and in fact limits keys to 249 chars, see
petergoldstein/dalli@74b2625f11ff56dd6f55c7316bc115bc5a29be5f

This patch in a similar way properly truncates keys to 250
characters and avoids double hashing on Dalli side. Also
makes key name more predictable and independent from the
underlying Dalli version.

2022-06-07 07:26 UTC, byroot requested changes

2022-06-07 07:26 UTC, byroot commented on activesupport/lib/active_support/cache/mem_cache_store.rb
> +            key_max_size = 250
We should make this a constant.

2022-06-07 07:26 UTC, byroot commented on activesupport/lib/active_support/cache/mem_cache_store.rb
> +            if key.size > key_max_size
We probably want to use `bytesize` here, as some keys might contain multi-bytes characters.

2022-06-07 07:26 UTC, byroot commented on activesupport/lib/active_support/cache/mem_cache_store.rb
> +              key = "#{key[0, key_trim_size]}#{key_separator}#{key_hash}"
Similarly here, if the key contain multi-byte characters, we might be off. We could use `byteslice`, but it may cause some strings to be invalid.

2022-06-07 07:26 UTC, byroot commented on activesupport/test/cache/stores/mem_cache_store_test.rb
> +    assert_equal short_key, @cache.send(:normalize_key, short_key, { namespace: nil })
I'd love a test with some multi-byte chars here.

2022-06-09 11:47 UTC, akostadinov commented on activesupport/lib/active_support/cache/mem_cache_store.rb
> +            key_max_size = 250
done

2022-06-09 11:47 UTC, akostadinov commented on activesupport/test/cache/stores/mem_cache_store_test.rb
> +    assert_equal short_key, @cache.send(:normalize_key, short_key, { namespace: nil })
added

2022-06-09 12:03 UTC, akostadinov commented
I have also split tests into separate methods. Thank you for the input.

2022-06-09 12:20 UTC, akostadinov commented
squashed, thanks!

2022-06-09 12:21 UTC, merged