Scaffold destroy action returns status code 303
rails/rails pull request #45383
Opened 2022-06-16 22:38 UTC by t27duck

### Summary

The default controller scaffolding currently sends back a 302 for its destroy action.

Since Hotwire is the default for Rails going forward, this can be problimatic. Turbo uses the fetch API internally which is particular on how it handles redirects.

As outlined in this table in this Turbo issue, https://github.com/hotwired/turbo/issues/84#issuecomment-862656931, Turbo making a DELETE request (not POST + hidden _method field) and recieving a 303 back will result in another DELETE request instead of a GET request for the redirect.

This updates the controller template used for the scaffold generator to send back the 302 see other for the destroy action.

### Other Information

For consistancy-sake, the Action Controller Overview guide examples were also updated. The main Getting Started guide page already has see other used in its example destroy action.

For non-Hotwire users, the browser will still properly redirect on a 303 as it does with a 302.

2022-10-13 19:26 UTC, p8 commented
Thanks @t27duck !
As this same change was applied to the Getting Started guide in https://github.com/rails/rails/pull/43974 I think it makes sense to add it to the scaffolds as well.

2022-10-13 19:30 UTC, p8 requested changes

2022-10-13 19:30 UTC, p8 commented on railties/CHANGELOG.md
> +*   Send 303 see other status code back for the destroy action on newly generated
Capitalizing "See Other" is a bit easier to read I think. Maybe also the [official](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303) notation?
```suggestion
*   Send 303 See Other status code back for the destroy action on newly generated
```

2022-10-13 20:29 UTC, t27duck commented
@p8 - Conflict rebased and suggested change applied.

2022-10-14 07:14 UTC, fschwahn commented
Since https://github.com/hotwired/turbo-rails/pull/370 (which was released in [turbo-rails 1.3.0](https://github.com/hotwired/turbo-rails/releases/tag/v1.3.0)) this problem has been fixed. So maybe changing the documentation / scaffold generator in rails is not required after all?

2022-10-14 14:00 UTC, p8 approved these changes

2022-10-14 14:01 UTC, p8 commented
@jonathanhefner since you've also worked on https://github.com/rails/rails/pull/45393 can you review this?

2022-10-14 17:13 UTC, merged

2022-10-14 17:13 UTC, jonathanhefner commented
I'll go ahead and merge this now, and backport to `7-0-stable`.  I'll revert the changes in #45393 when / if that gets merged.

Thank you @t27duck and @p8! :smile: