Defer constant loading of `ActionMailer::MailDeliveryJob` until ActiveJob and ActionMailer is loaded
rails/rails pull request #45486
Opened 2022-06-28 22:24 UTC by bensheldon

Sibling PR to #45476, where this was initially split off from.

Connects to #45434.

2022-06-28 22:38 UTC, rafaelfranca requested changes
A better fix would always accept strings in the configuration and only convert to a constant in the first time the value is used, and cache it.

2022-06-28 22:38 UTC, rafaelfranca commented on actionmailer/lib/action_mailer/base.rb
> +    class_attribute :delivery_job, default: nil
This should not be `nil` by default.

2022-06-29 04:37 UTC, bensheldon commented
Just wanted to note that I discovered there is a hard dependency between ActionMailer and ActiveJob, introduced in #16598, and necessary given the current implementation:

https://github.com/rails/rails/blob/c3c747547a85937e67bc62cfb9f466948fb631ad/actionmailer/lib/action_mailer/railtie.rb#L3

By using a String-deferral strategy, I think it's possible to drop the `require`.

2022-08-08 16:32 UTC, bensheldon commented
Closing this for now.

2022-08-08 16:32 UTC, closed without merging