Improve ActiveRecord::QueryMethods.readonly doc
rails/rails pull request #45654
Opened 2022-07-25 05:56 UTC by shouichi

> Sets readonly attributes for the returned relation.

The current documentation gives the impression that it can manipulate
`attr_readonly`.

2022-09-06 07:08 UTC, p8 requested changes

2022-09-06 07:08 UTC, p8 commented on activerecord/lib/active_record/relation/query_methods.rb
> +    # Mark relation as readonly. Attempting to update a record will result in
```suggestion
    # Mark the relation as readonly. Attempting to update a record will result in
```

2022-09-06 07:08 UTC, p8 commented on activerecord/lib/active_record/relation/query_methods.rb
> +    # To make readonly relation writable, pass +false+.
```suggestion
    # To make the readonly relation writable, pass +false+.
```

2022-10-07 08:31 UTC, shouichi commented
@p8 Committed your suggested changes and squashed commits. Could you take a look again? (Sorry for the late reply. I missed your reply.)

2022-10-08 16:07 UTC, merged

2022-10-08 16:08 UTC, p8 commented
Thanks @shouichi 🎉