Documented the options available for image processing
rails/rails pull request #45885
Opened 2022-08-25 11:50 UTC by iainbeeston

### Summary

I've added a simple table of the available options for image processing (taken largely from the image processing docs) to the active storage guide

### Other Information

2022-08-30 19:07 UTC, p8 requested changes

2022-08-30 19:07 UTC, p8 commented on guides/source/active_storage_overview.md
> +| `crop` | `crop: [20, 50, 300, 300]` | Extracts an area from an image. The first two arguments are left and top edges of area to extract, while the last two arguments are the width and height of are
```suggestion
| `crop` | `crop: [20, 50, 300, 300]` | Extracts an area from an image. The first two arguments are the left and top edges of area to extract, while the last two arguments are the width and height of the area to extract. |
```

2022-09-05 09:04 UTC, iainbeeston commented
@p8 I've incorporated your changes and squashed down the commits, could you please take another look at this?

2022-09-10 11:25 UTC, merged

2022-09-10 11:26 UTC, p8 commented
Thanks @iainbeeston 🙌