add documentation for assocation scope block with owner argument
rails/rails pull request #45980
Opened 2022-09-09 11:21 UTC by braindeaf

I was looking for a way include the using the association_proxy.owner in a the scope for an association. Little did I know that it was already there in *associaton.rb* just seemingly not documented in the guide. So...adding.

```
def self.build_scope(scope)
  if scope && scope.arity == 0
    proc { instance_exec(&scope) }
  else
    scope
  end
end
```

2022-09-09 11:43 UTC, fschwahn commented on guides/source/association_basics.md
> +scope block in situations where you need even more control over the association
Maybe mention that this makes preloading impossible, as it is an important caveat.

2022-09-09 12:01 UTC, braindeaf commented
Of course. Obviously I didn't realise that because I was too excited I
didn't have to try and hack this to work for myself. WIll do.

On Fri, 9 Sept 2022 at 12:44, Fabian Schwahn ***@***.***> wrote:
>
> @fschwahn commented on this pull request.
>
> ________________________________
>
> In guides/source/association_basics.md:
>
> > @@ -2661,6 +2661,18 @@ Extensions can refer to the internals of the association proxy using these three
>  * `proxy_association.reflection` returns the reflection object that describes the association.
>  * `proxy_association.target` returns the associated object for `belongs_to` or `has_one`, or the collection of associated objects for `has_many` or `has_and_belongs_to_many`.
>
> +### Association Scoping using the Association Owner
> +
> +The owner of the association can be passed the owner as a single argument to the
> +scope block in situations where you need even more control over the association
>
> Maybe mention that this makes preloading impossible, as it is an important caveat.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-01-11 20:07 UTC, p8 requested changes

2023-01-11 20:07 UTC, p8 commented on guides/source/association_basics.md
> +The owner of the association can be passed the as a single argument to the scope
```suggestion
The owner of the association can be passed as a single argument to the scope
```

2023-01-11 20:11 UTC, p8 commented
Thanks @braindeaf ! I'll merge it after the typo fix.

2023-01-11 20:32 UTC, p8 commented
@braindeaf Sorry, could you squash your commits to a single commit as well? 🙇

2023-01-11 20:44 UTC, braindeaf commented
Hmmmzzz...I need to work out what I've done as I've merged master in too. I need to do this more often.

2023-01-11 21:03 UTC, braindeaf commented
@p8 managed to nuke all the commits on this branch (and it's auto closed). But have just created a fresh commit

2023-01-11 21:08 UTC, merged

2023-01-11 21:08 UTC, p8 commented
Thanks @braindeaf !