Add upcase option for deterministically encrypted case insensitive unique constraints
rails/rails pull request #46123
Opened 2022-09-24 19:21 UTC by alextaujenis

### Motivation / Background

This Pull Request has been created because I would like to add case insensitive unique constraints to deterministically encrypted columns with the option to store the values as `upcase` in the database without having to separately store the case information in another column (see https://guides.rubyonrails.org/active_record_encryption.html#ignoring-case). 

The current implementation only allows `downcase`, which is great for things like email columns, but there are other data types that naturally exist as `upcase`, such as a vehicle license plate, or vin number, that could benefit from this natural addition to the API.

### Detail

This Pull Request adds the `upcase` option to ActiveRecord `encrypts` when `deterministic: true`.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] There are no typos in commit messages and comments.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Feature branch is up-to-date with `main` (if not - rebase it).
* [x] Pull request only contains one commit for bug fixes and small features. If it's a larger feature, multiple commits are permitted but must be descriptive.
* [x] Tests are added if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [x] PR is not in a draft state.
* [x] CI is passing.

2022-09-26 20:27 UTC, jorgemanrubia requested changes
Thanks for working on this @alextaujenis.

The approach you took make a lot of sense, considering the existing `downcase:` option. But I am not super happy with that option in the first place, and I am not very keen of extending the approach with new options. Let me explain.

I added that `downcase:` option as a quick patch when AR encryption was part of HEY and we shipped the encryption technology to production. We had a problem where some emails included email addresses in upcase, and we failed to recognize them because we had lost the implicit "ignore case" approach we had with MySQL when we encrypted them. I implemented the `downcase:` option as a first patch. Eventually, I added `ignore_case:` for the scenario where you care about keeping the case in place, but I was never super happy with `downcase:` in the first place.

The bottom line is that I don't think transforming strings is an encryption concern. You can make a case for downcase, upcase, upcase initials, and even other transformations such as truncation. I don't think we should extend the encryption API to support those.

Alternatively, I'd consider using a separated type for this transformation. This way, you can make it work with encryption or without it, as it's a separated concern. Not super tested but something like this should work:

```ruby
class UpcaseStringType < ActiveModel::Type::String
  def changed_in_place?(raw_old_value, new_value)
    super(upcase(raw_old_value), upcase(new_value))
  end

  def serialize(value)
    upcase(super(value))
  end

  private
    def cast_value(value)
      upcase(super(value))
    end

    def upcase(value)
      value&.upcase
    end
end

ActiveRecord::Type.register(:upcase, UpcaseStringType)

class Post
  attribute :title, :upcase
  encrypts :title
end

post = Post.create(title: "hello")
post.title #=> "HELLO"
```

The good thing of this approach is that this would work also with queries if you are using deterministic encryption. So, if `title` was encrypted deterministically, you could do `Post.where title: "hello"` or `Post.where title: "HELLO`. 

You could also consider adding some syntax sugar to make the declaration more concise:

```ruby
upcase :title # declares the attribute under the hood
```

But, in any case, I think this approach makes more sense. It would be the one I would take instead of adding the `downcase:` option if I went back.

2022-09-27 01:14 UTC, alextaujenis commented
Thank you @jorgemanrubia for reviewing this PR and suggesting an alternative. I agree this is a slippery slope implementing different transformations to satisfy deterministic unique constraints.

I've used the Rails attributes API before, but didn't realize it behaved this way and could be used like this. This is great! I'll give it a shot revising this PR that way.

One thing that sticks out right away would be the API interface for the `attribute`. I see you gave the example of 

``` ruby
class Post
  attribute :title, :upcase
  encrypts :title
end
```

But after quickly looking over the API I am leaning towards this:
``` ruby
class Post
  attribute :title, upcase: true
  encrypts :title
end
```

Any suggestions are welcome.

2022-09-27 11:08 UTC, jorgemanrubia commented
@alextaujenis I think the attributes API is fine as it is. So I wouldn't try to modify it to accommodate that new syntax `upcase: true`. My suggestion was in the line of internal usage in your application, since the API is directly usable. I wrote [an article about this API](https://world.hey.com/jorge/rails-attributes-an-essential-api-you-can-probably-ignore-27147cc2) back in the day if it serves.

A nice Rails contribution IMO would be some kind of API to accommodate such transformations. Such as validations, but for transformations. For example:

```ruby
transforms :title, upcase: true
transforms :title, truncate_to: 120
```

Under the hood, they could configure a type. This would be a nice syntax sugar for dealing with these common transformations. But that would be a whole new API and a different PR and discussion. For this case in particular, I'd close the PR and leave the AR encryption API unchanged.

Regarding removing the `downcase:` option, the problem is that it would a be a breaking change, so we'd need to plan carefully, with proper deprecation warnings and such. It's not something we can just remove and ship. I don't see it as a priority at this point.

2022-09-27 14:59 UTC, closed without merging

2022-09-27 17:37 UTC, jonathanhefner commented
#43945 may be of interest.  With #43945, the example would look like:

```ruby
class Post
  normalizes :title, with: :upcase
end
```

Note that there is a minor performance pitfall when executing transformations in a type's `cast` method, because `cast` may be called multiple times when assigning and serializing an attribute.  (To see an example, change the `upcase` method in the [`UpcaseStringType` example](https://github.com/rails/rails/pull/46123#pullrequestreview-1120859743) to `value&.concat("!")`.)

#43945 contains a workaround for that.  I am also working on a more general solution in #44625, but it will be for internal use only (for now, at least).