ActiveJob: Add parent option to Active Job guides [ci-skip]
rails/rails pull request #46194
Opened 2022-10-04 17:22 UTC by sampatbadhe

### Motivation / Background

This Pull Request has been created because there is currently no description of the ActiveJob --parent option introduced in https://github.com/rails/rails/pull/45528 in the rails guide

### Detail

ActiveJob: Add parent option to Active Job guide

### Checklist

Before submitting the PR make sure the following are checked:

* [ ] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [ ] There are no typos in commit messages and comments.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Feature branch is up-to-date with `main` (if not - rebase it).
* [ ] Pull request only contains one commit for bug fixes and small features. If it's a larger feature, multiple commits are permitted but must be descriptive.
* [ ] Tests are added if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [ ] PR is not in a draft state.
* [ ] CI is passing.

2022-10-16 15:59 UTC, p8 requested changes

2022-10-16 15:59 UTC, p8 commented on guides/source/active_job_basics.md
> +  end
You can remove the extra whitespace:
```suggestion
class ProcessPaymentJob < PaymentJob
  queue_as :default

  def perform(*args)
    # Do something later
  end
end
```

2022-10-16 16:23 UTC, sampatbadhe commented on guides/source/active_job_basics.md
> +  end
Thank you for the review @p8
Done!

2022-10-17 17:46 UTC, merged

2022-10-17 17:46 UTC, p8 commented
Thanks @sampatbadhe 🙌