adds documentation for flag --primary-key-type=uuid passed to Rails model generator
rails/rails pull request #46228
Opened 2022-10-12 14:55 UTC by jasonfb

2022-10-12 14:57 UTC, jasonfb commented on guides/source/active_record_postgresql.md
> +
```suggestion
```

2022-10-12 15:01 UTC, jasonfb commented on guides/source/active_record_postgresql.md
> +When building a foreign key that will reference this a UUID, treat `uuid` as the field type, for example:
```suggestion
When building a foreign key that will reference this UUID, treat `uuid` as the native field type, for example:
```

2022-10-12 15:50 UTC, eileencodes requested changes
Hey @jasonfb thanks for the PR. This needs some changes before it's mergable.

1) Docs should be wrapped to 80 characters
2) New line code examples should be wrapped in a "```ruby" block, see above code for an example.
3) I've added some wording changes to make the language clearer.
4) When you're done squash your commits into 1 commit, we don't merge PRs with multiple commits unless they tell a specific and clear story.

Thanks!

2022-10-12 15:50 UTC, eileencodes commented on guides/source/active_record_postgresql.md
> +To use the Rails model generator to make a table with UUID as the primary key, pass `--primary-key-type=uuid` as a flag to the model generator.
```suggestion
To use the Rails model generator for a table using UUID as the primary key, pass `--primary-key-type=uuid` to the model generator.
```

2022-10-12 15:50 UTC, eileencodes commented on guides/source/active_record_postgresql.md
> +When building a foreign key that will reference this UUID, treat `uuid` as the native field type, for example:
```suggestion
When building a model with a foreign key that will reference this UUID, treat `uuid` as the native field type, for example:
```

2022-10-12 15:50 UTC, eileencodes commented on guides/source/active_record_postgresql.md
> +`rails generate model Case device_id:uuid`
This needs a new line but also needs to be code-blocked with ruby like the above examples.

```suggestion
`rails generate model Case device_id:uuid`

```

2022-10-15 11:24 UTC, jasonfb commented
ok thanks @eileencodes for the feedback. I squashed it down. Not sure what you mean by "Docs should be wrapped to 80 characters"? I think all the lines I added are under 80 characters long. thanks.

2022-10-15 14:31 UTC, eileencodes requested changes
Wrapped to 80 characters means that lines shouldn't exceed 80 characters in length. I've left a code suggestion so you can see where the breaks should be 👍🏼

2022-10-15 14:31 UTC, eileencodes commented on guides/source/active_record_postgresql.md
> +To use the Rails model generator for a table using UUID as the primary key, pass `--primary-key-type=uuid` to the model generator.
```suggestion
To use the Rails model generator for a table using UUID as the primary key, pass
`--primary-key-type=uuid` to the model generator.
```

2022-10-15 14:31 UTC, eileencodes commented on guides/source/active_record_postgresql.md
> +When building a model with a foreign key that will reference this UUID, treat `uuid` as the native field type, for example:
```suggestion
When building a model with a foreign key that will reference this UUID, treat `uuid`
as the native field type, for example:
```

2022-10-16 15:41 UTC, jasonfb commented
oh, I got it. thank you. this is hard-wrapped to 80 chars now.

2022-10-17 12:19 UTC, merged

2022-10-17 12:19 UTC, eileencodes commented
Thank you @jasonfb!

2022-12-18 14:11 UTC, jasonfb commented
@eileencodes - you know I discovered a bug that makes this wrong — it appears to create a table that **_does_** have a ` id: :uuid ` set in the create_table definition, but then the generated migration doesn't actually contain the fields specified. 

so I guess the bug is that you can't use the flag and also pass fields to the model generator?

2022-12-19 01:21 UTC, skipkayhil commented
> so I guess the bug is that you can't use the flag and also pass fields to the model generator?

If you have reproduction steps, can you open a new issue? Replying to old PRs usually won't get as much visibility