Includes use of `RAILS_STRICT_WARNING` in Contribution doc - Fix #46263
rails/rails pull request #46272
Opened 2022-10-18 22:54 UTC by aviralsomani

### Motivation / Background

This Pull Request has been created because there should be information in the Contributing to Ruby on Rails guideline on enabling tests identical to CI during development. This information could enable contributors to iterate fewer times on broken CI tests by virtue of having the knowledge to set the `RAILS_STRICT_WARNING` flag. Enabling this flag would surface errors that need to be addressed ahead of time.

### Detail

This Pull Request changes the Contributing to Ruby on Rails markdown

### Additional information

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] There are no typos in commit messages and comments.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Feature branch is up-to-date with `main` (if not - rebase it).
* [x] Pull request only contains one commit for bug fixes and small features. If it's a larger feature, multiple commits are permitted but must be descriptive.
* [x] Tests are added if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [x] PR is not in a draft state.
* [ ] CI is passing.

2022-10-18 23:16 UTC, yahonda commented on guides/source/contributing_to_ruby_on_rails.md
> +An important note is that while developing locally it is helpful to set `RAILS_STRICT_WARNINGS` to replicate Rails CI behavior. This ensures that there are no surprise failures in the CI results for
"This ensures that there are no surprise failures" is not clear what 'surprise failures' means.
Would you clarify that by setting `RAILS_STRICT_WARNINGS`, the test suite fails if warnings are raised?

2022-10-18 23:59 UTC, yahonda commented
The update looks good. Would you squash your commits? https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits

2022-10-19 13:13 UTC, eileencodes requested changes
Thanks for the PR. I think the original wording is a bit of a mouthful and we can say what to do in a clearer way.

2022-10-19 13:13 UTC, eileencodes commented on guides/source/contributing_to_ruby_on_rails.md
> +An important note is that while developing locally it is helpful to set `RAILS_STRICT_WARNINGS` so that the testing suite will fail if any warnings are raised. This replicates Rails CI behavior and w
```suggestion
Rails CI will raise if warnings are introduced. To implement the same behavior locally set `RAILS_STRICT_WARNINGS=1` when running the test suite.
```

2023-01-28 22:50 UTC, zzak commented
Combined into #47170, thanks!

2023-01-28 22:50 UTC, closed without merging