Clarify how to use a standalone Action Cable server
rails/rails pull request #46679
Opened 2022-12-08 22:21 UTC by ghiculescu

While trying to set up an Action Cable server, I noticed the guide doesn't really answer the question of how to set up a standalone server. This PR fleshes out the example a bit more fully.

2022-12-09 11:39 UTC, p8 requested changes

2022-12-09 18:17 UTC, ghiculescu commented
Thanks @p8! I made those fixes.

2022-12-09 23:06 UTC, zzak approved these changes

2022-12-10 11:05 UTC, merged

2022-12-10 11:05 UTC, p8 commented
Thanks @ghiculescu and @zzak 👋 !