Run through Active Record Migrations guide
rails/rails pull request #46777
Opened 2022-12-19 23:41 UTC by zzak

Similar to #46700, I'm continuing through the guides this time with [Active Record Migrations](https://guides.rubyonrails.org/active_record_migrations.html).

There are several changes batched up into this PR.

2023-01-04 20:27 UTC, p8 requested changes

2023-01-04 20:27 UTC, p8 commented on guides/source/active_record_migrations.md
> +### Making the irreversible possible
```suggestion
### Making the Irreversible Possible
```

2023-01-04 20:27 UTC, p8 commented on guides/source/active_record_migrations.md
>  --------------------
```suggestion
Generating Migrations
----------------------
```

2023-01-04 20:27 UTC, p8 commented on guides/source/active_record_migrations.md
> +### Removing columns
```suggestion
### Removing Columns
```

2023-01-04 20:27 UTC, p8 commented on guides/source/active_record_migrations.md
> +### Adding new columns
```suggestion
### Adding New Columns
```

2023-01-04 20:27 UTC, p8 commented on guides/source/active_record_migrations.md
> +### Creating new tables
```suggestion
### Creating New Tables
```

2023-01-04 20:29 UTC, p8 commented
Thanks @zzak!
This was a bigger change to review 😄 
I think most of these are an improvement.

2023-01-07 23:01 UTC, zzak commented
Failures are unrelated to this PR

2023-01-07 23:02 UTC, merged