ActiveRecord multiple databases extended doc
rails/rails pull request #46835
Opened 2022-12-27 10:55 UTC by Salanoid

Example of implementation for MyCookieResolver class in the active record multiple databases documentation similar to ActiveRecord::Middleware::DatabaseSelector::Resolver::Session.

This Pull Request has been created because #46693.

### Detail

This Pull Request changes documentation (guides/source/active_record_multiple_databases.md).

2023-01-03 16:04 UTC, eileencodes requested changes
Thanks for working on this! I've left some comment about areas I'd like changed.

2023-01-03 16:04 UTC, eileencodes commented on guides/source/active_record_multiple_databases.md
> +  # code example for your cookie class
Since this is now documented we don't need this comment

```suggestion
  # code example for your cookie class
```

2023-01-03 16:04 UTC, eileencodes commented on guides/source/active_record_multiple_databases.md
>  class MyCookieResolver
The original documentation is incorrect, this should inherit from the Active Record's default Resolver so you don't need to reimplement all the methods below, you would only need to reimplement the ones that are different.

Then you should delete docs for the following methods:
* `convert_time_to_timestamp`
* `convert_timestamp_to_time`

2023-01-03 16:04 UTC, eileencodes commented on guides/source/active_record_multiple_databases.md
> +    @cookeis = cookies
```suggestion
    @cookies = cookies
```

2023-01-05 19:08 UTC, eileencodes commented
Can you squash your commits?

2023-01-06 11:40 UTC, Salanoid commented
> Can you squash your commits?

All done, thank you!

2023-01-06 13:08 UTC, merged