Store correct environment in `internal_metadata` when run `rails db:prepare`
rails/rails pull request #46879
Opened 2023-01-03 22:15 UTC by fatkodima

Fixes #46845.

My suggestion (https://github.com/rails/rails/issues/46845#issuecomment-1370057047) was to have something like
```diff
--- a/activerecord/lib/active_record/migration.rb
+++ b/activerecord/lib/active_record/migration.rb
@@ -1427,7 +1427,7 @@ def migrate_without_lock
       def record_environment
         return if down?

-        @internal_metadata[:environment] = connection.migration_context.current_environment
+        @internal_metadata[:environment] = connection.pool.db_config.env_name
       end

       def ran?(migration)
```

But that did not worked out, because `db_config.env_name` is envs (top level keys) from the `database.yml`, but the rake task tries to store basically the `RAILS_ENV`, which could not be the same? Several test cases started to fail, for example, https://github.com/rails/rails/blob/c70a8f75d7a41212cbe358b2a0122a28321b040d/activerecord/test/cases/migration_test.rb#L691-L713

So I went with my original suggestion (https://github.com/rails/rails/issues/46845#issuecomment-1366646524) and enhanced it a bit to not depend on the rails' application presence.

It is not very elegant, but it works.

cc @eileencodes

2023-01-04 14:07 UTC, eileencodes requested changes

2023-01-04 14:07 UTC, eileencodes commented on activerecord/lib/active_record/tasks/database_tasks.rb
> +        def with_env(env)
I'm going to take a look at this this week. We can't merge this method as is, we need to do this without accessing Rails env at all.

2023-01-04 17:31 UTC, eileencodes commented
I think the tests that are failing when using `db_config.env_name` are wrong.

Let's say you have an environment "foofoo" and try to run migrations. You'll get an error because there is no configuration corresponding to the "foofoo" environment. Locally with a demo app if I try to run mgirations against an env that does not exist, and therefore does not have a matching config I get this error:

```
$ RAILS_ENV=foofoo bin/rails db:migrate
rails aborted!
ActiveRecord::AdapterNotSpecified: The `foofoo` database is not configured for the `foofoo` environment.

  Available database configurations are:

  default
development: primary, primary_replica, animals, animals_replica
test: primary, primary_replica, animals, animals_replica

Tasks: TOP => db:migrate => db:load_config
(See full trace by running task with --trace)
```

I get the same error with `db:prepare`. So in a real world example we can't set the env to a config that does not exist. The tests should be updated so we can get the env from the db_config. It's how we do it when we set the environment in `load_schema`. `record_environment` should match that behavior. https://github.com/rails/rails/blob/main/activerecord/lib/active_record/tasks/database_tasks.rb#L362

2023-01-04 22:39 UTC, fatkodima commented
@eileencodes Made suggested changes, thank you for the review. 
CI failed 1 job due to timeout - not sure if this is caused by this PR or not.

2023-01-05 14:33 UTC, eileencodes approved these changes
Re-ran the build and it passed. I doubt it is related - we see timeouts occasionally. More likely something on the buildkite end. 

Thank you for working on this!

2023-01-05 14:33 UTC, merged

2023-01-05 14:39 UTC, eileencodes commented
Hey @fatkodima do you know if to fix this on 7-0-stable do we need both https://github.com/rails/rails/pull/45464 and this change? Do you want to work on a backport?

2023-01-05 14:41 UTC, fatkodima commented
> If not I can do it, just wanted to ask first.

Please feel free to do so 🙏

2023-01-07 00:24 UTC, zzak commented
@eileencodes Do you think this is worth a changelog?

2023-01-09 14:08 UTC, eileencodes commented
> Do you think this is worth a changelog?

No, it's fixing a bug and we usually only put features / major changes in the changelog.

2023-01-09 21:32 UTC, eileencodes commented
The backport wasn't straight forward, ended up reimplementing the commits because they didn't backport cleanly. Backport commit: 4505c2f508418e40c2cf82701cc9144cb7e4e83d