Move AR::Callbacks docs under the class
rails/rails pull request #47008
Opened 2023-01-14 08:53 UTC by zzak

This removes one level of indirection from our docs, which is a win IMO.

Originally added in #40565.

2023-01-14 22:46 UTC, jonathanhefner requested changes
I documented these methods on `ActiveRecord::Callbacks::ClassMethods` because they are class methods of any class that has `include ActiveRecord::Callbacks`.

By documenting these methods on `ActiveRecord::Callbacks`, you are saying that they are instance methods of any class that has `include ActiveRecord::Callbacks`.

Basically, if we were to define these methods manually (i.e. not via metaprogramming), where would we put them?

2023-01-16 00:24 UTC, zzak commented
@jonathanhefner Thanks for taking a look! I wasn't sure the best situation here, but I feel it's better UX for the docs.

> RE: class vs. instance

Since we're using `:method:` here, I believe RDoc treats them as instance methods, but we could use `:singleton-method:` instead? How do you think?

> Basically, if we were to define these methods manually (i.e. not via metaprogramming), where would we put them?

I think there is a line we have to draw between accuracy and visibility, we can document these methods here and improve their visibility, but we shouldn't publish inaccurate docs just for that.

If it makes sense to put them here, and is still technically accurate (e.g. if I include this class, then those methods are available, etc). let's aim for that.

2023-01-16 16:54 UTC, jonathanhefner commented
> Since we're using `:method:` here, I believe RDoc treats them as instance methods, but we could use `:singleton-method:` instead? How do you think?

Do you mean like the following?

```ruby
module ActiveRecord
  module Callbacks
    ##
    # :singleton-method: after_initialize
    #
    # :call-seq: after_initialize(*args, &block)
    #
    # Registers a callback to be called after a record is instantiated.
  end
end
```

Wouldn't that be the same as:

```ruby
module ActiveRecord
  module Callbacks
    def self.after_initialize(*args, &block)
    end
  end
end
```

Which is not the API that we are defining.

It would be possible to add `:singleton-method:` docs to `ActiveRecord::Base`, but (1) that moves the documentation far away from its implementation, (2) that obscures the fact that the methods come from the `ActiveRecord::Callbacks` module, and (3) the `ClassMethods` pattern is well established and [widely used throughout the public API](https://api.rubyonrails.org/?q=ClassMethods) already.

Why do we want treat `ActiveRecord::Callbacks::ClassMethods` differently than other `ClassMethods` modules?

Also, going forward, if we were to `def` a new public method in `ActiveRecord::Callbacks::ClassMethods` (using `def`, not metaprogramming), would we add docs to the new method or add a `:singleton-method:` doc with the others in `ActiveRecord::Base`?

Is this something we can address in SDoc by making all `ClassMethods` modules more prominent?  Where is the line between SDoc and RDoc?

2023-01-17 05:53 UTC, zzak commented
Ok, I didn't realize this pattern was so widely used. I'm really glad that I asked!

Also good points about keeping the definitions and documentation aligned, definitely don't want to create a scenario like you've described. Thanks for your time and explaining the situation to me.

> Is this something we can address in SDoc by making all ClassMethods modules more prominent?

Currently the ClassMethods appear under the "Namespace" section of a module. Maybe this is enough? The current design for the API docs seems like it could use some work, but I don't have any concrete ideas atm.

In any case, this PR won't be accepted so let's close it. We can think about better API docs design outside of this thread. :bow:

2023-01-17 05:53 UTC, closed without merging