`ActiveRecord::Base#signed_id`: raise if called on a new record
rails/rails pull request #47027
Opened 2023-01-17 01:01 UTC by ghiculescu

Currently you can call `signed_id` on a new record, and it will generate a token. But the token won't work when you call `find_signed` since it was based on the ID being `nil`.

This PR makes `signed_id` raise an error to warn you about this, rather than letting the incorrect code subtly slip into use.

Similar to https://github.com/rails/rails/pull/47017#issuecomment-1383323996 I'm open to making this a deprecation first, but went with an error because currently the functionality just doesn't work.

2023-01-17 01:13 UTC, ghiculescu commented
Red tests don't seem related.

2023-01-18 18:49 UTC, rafaelfranca requested changes

2023-01-18 20:29 UTC, merged

2023-01-19 06:55 UTC, zzak commented
@ghiculescu Does this change the behavior described here?

https://github.com/rails/rails/blob/847cc9f8cbdaef59fc43efe78ef74eb4b769fa6c/activerecord/CHANGELOG.md?plain=1#L683-L716

2023-01-20 21:41 UTC, ghiculescu commented
@zzak no, I don't think so. That API [also doesn't work with new records](https://github.com/rails/rails/blob/be400c3ca2b86111766d840979478fc026679368/activerecord/lib/active_record/token_for.rb#L25), so perhaps a warning there is also a good idea. Thoughts @jonathanhefner ?