Use infinitive form for all task descriptions verbs
rails/rails pull request #47309
Opened 2023-02-08 10:49 UTC by 4geru

### Motivation / Background

The previous pull request changed to infinitive form.
The infinitive form has not used some commands.
So fixed it in this pull request.

#### previous pull request

> All the common rails commands and some extended commands use the infinitive form for the verb in the description:
"Generate ...", "Start ...", "Run ...", instead of "Generates ...", "Starts ...", "Runs ...".
This changes the remaining tasks to use the infinitive form for the verb as well, for consistency.

https://github.com/rails/rails/pull/47215

#### before
```sh
$ git grep "desc: \S*s "
railties/lib/rails/commands/credentials/credentials_command.rb:        desc: "Enrolls project in credentials file diffing with `git diff`"
railties/lib/rails/commands/credentials/credentials_command.rb:        desc: "Disenrolls project from credentials file diffing"
railties/lib/rails/commands/dbconsole/dbconsole_command.rb:        desc: "Specifies the database to use."
railties/lib/rails/commands/server/server_command.rb:        desc: "Runs Rails on the specified port - defaults to 3000.", banner: :port
railties/lib/rails/commands/server/server_command.rb:        desc: "Binds Rails to the specified IP - defaults to 'localhost' in development and '0.0.0.0' in other environments'.",
railties/lib/rails/commands/server/server_command.rb:        desc: "Uses a custom rackup configuration.", banner: :file
railties/lib/rails/commands/server/server_command.rb:        desc: "Runs server as a Daemon."
railties/lib/rails/commands/server/server_command.rb:        desc: "Specifies the Rack server used to run the application (thin/puma/webrick).", banner: :name
railties/lib/rails/commands/server/server_command.rb:        desc: "Specifies the PID file - defaults to #{DEFAULT_PIDFILE}."
railties/lib/rails/commands/server/server_command.rb:        desc: "Specifies whether to perform caching in development."
railties/lib/rails/commands/server/server_command.rb:      class_option :early_hints, type: :boolean, default: nil, desc: "Enables HTTP/2 early hints."
railties/lib/rails/generators/rails/resource/resource_generator.rb:                             desc: "Actions for the resource controller"
railties/lib/rails/generators/rails/scaffold_controller/scaffold_controller_generator.rb:                         desc: "Generates API controller"
railties/lib/rails/generators/test_unit/scaffold/scaffold_generator.rb:                         desc: "Generates API functional tests"
```

#### after

```sh
$ git grep "desc: \S*s "
NONE
```

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

2023-02-08 21:12 UTC, p8 requested changes

2023-02-08 21:12 UTC, p8 commented on railties/lib/rails/commands/dbconsole/dbconsole_command.rb
> +        desc: "Specifie the database to use."
```suggestion
        desc: "Specify the database to use."
```

2023-02-08 21:12 UTC, p8 commented on railties/lib/rails/commands/server/server_command.rb
> +        desc: "Specifie the PID file - defaults to #{DEFAULT_PIDFILE}."
```suggestion
        desc: "Specify the PID file - defaults to #{DEFAULT_PIDFILE}."
```

2023-02-08 21:12 UTC, p8 commented on railties/lib/rails/commands/server/server_command.rb
> +        desc: "Specifie the Rack server used to run the application (thin/puma/webrick).", banner: :name
```suggestion
        desc: "Specify the Rack server used to run the application (thin/puma/webrick).", banner: :name
```

2023-02-08 21:12 UTC, p8 commented on railties/lib/rails/commands/server/server_command.rb
> +        desc: "Specifie whether to perform caching in development."
```suggestion
        desc: "Specify whether to perform caching in development."
```

2023-02-08 21:12 UTC, p8 commented on railties/lib/rails/generators/rails/resource/resource_generator.rb
> +                             desc: "Action for the resource controller"
This is currently correct as Actions is a noun here.
```suggestion
                             desc: "Actions for the resource controller"
```

2023-02-09 00:35 UTC, 4geru commented
@p8 thank you for reviewing.
I fixed the codes and pushed them.

2023-02-09 16:56 UTC, merged