Fix docs about the return value of authenticate_with_http_token [ci-skip]
rails/rails pull request #47489
Opened 2023-02-24 04:21 UTC by sato11

### Motivation / Background
The current documentation says it returns boolean, which reads contradictory with [this sample](https://github.com/rails/rails/blob/v7.0.4.2/actionpack/lib/action_controller/metal/http_authentication.rb#L387). Shall we fix it with the wordings borrowed straight from [Token.authenticate](https://github.com/rails/rails/blob/v7.0.4.2/actionpack/lib/action_controller/metal/http_authentication.rb#L450-L451)?

2023-02-27 23:02 UTC, skipkayhil commented
Hey @sato11, thanks for the PR! This change looks good to me so I'll mark it as ready for review by a committer

2023-03-02 14:59 UTC, p8 requested changes

2023-03-02 14:59 UTC, p8 commented on actionpack/lib/action_controller/metal/http_authentication.rb
> +        # token is found. Returns <tt>nil</tt> if no token is found.
An example could clarify things a bit here as well:
```suggestion
        # token is found. Returns <tt>nil</tt> if no token is found.
        #
        #   authenticate_with_http_token { |token, o| User.for_token(token, o) }
        #   => #<User id: 1 ..>
```

Or maybe, it's clearer to link to Token documentation as we do for `authenticate_or_request_with_http_token`.

```suggestion
        # token is found. Returns <tt>nil</tt> if no token is found.
        #
        # See ActionController::HttpAuthentication::Token for example usage.
```

2023-03-02 15:03 UTC, matthewd commented
I think this is fine / consistent with our documentation practices as is. Note it says "true", not "`true`" -- https://guides.rubyonrails.org/api_documentation_guidelines.html#booleans

2023-03-03 23:21 UTC, closed without merging

2023-03-03 23:22 UTC, rafaelfranca commented
Thank you for the pull request. What Matthew said is correct and there is nothing wrong with the documentation as is. We don't want to commit to document we return the value of `login_procedure`.

2023-03-04 10:28 UTC, p8 commented
@rafaelfranca Should the following example that uses the return value be changed then?
https://github.com/rails/rails/blob/v7.0.4.2/actionpack/lib/action_controller/metal/http_authentication.rb#L387

2023-03-06 22:13 UTC, rafaelfranca commented
oh, in that case, we should merge this.

2023-03-06 22:13 UTC, rafaelfranca commented
I can't reopen since the branch was deleted, but feel free to send a new one (or repush the branch)