Zenspider/ar core hash  take2
rails/rails pull request #47994
Opened 2023-04-19 22:49 UTC by zenspider

This tries to address probems found via #47864. See discussion on that PR for details.

### Motivation / Background

AR#== and #hash both check against id and then compute their values... but an instance that is a new_record? can have an id even if not saved if the schema has a default value associated with id.

This Pull Request has been created because [REPLACE ME]

### Detail

This PR modifies `primary_key_values_present?` to check against the default value for id rather than plain truthiness. This method is used in both AR#== and AR#hash and should fix problems of having new records w/ non-nil ids

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

2023-04-19 23:55 UTC, zenspider commented
@nvasilevski I've resurrected your test changes for this variant of the PR (the other one got reverted). But I had to change some assertions. @tenderlove also told me to go ahead and delete your core hash test. Happy to go back and forth on this stuff.

I'm prolly gonna collapse these commits down and give it a better commit message before this is all said and done.

2023-05-01 19:33 UTC, zenspider commented
nudge... @jhawthorn @tenderlove @eileencodes

2023-05-01 19:38 UTC, byroot commented
> nudge...

We were waiting for you to cleanup the commits. Other than that, yeah the change look good.

2023-05-01 20:25 UTC, zenspider commented
Squashed down to 2 commits (hash vs eq) and reworded the eq commit a bit better.

2023-05-01 21:23 UTC, jhawthorn commented on activerecord/test/schema/schema.rb
> +    t.bigint :id, default: 123
One issue I see is that this isn't a primary key (which means there's no uniqueness constraint)

2023-05-01 21:32 UTC, jhawthorn commented
I'm still unconvinced this schema can or should be supported by Rails.

The schema in the test actually does not create a primary key column, just a column with the name "id". It's possible to make it a primary key without auto_increment but [auto_increment and a default are mutually exclusive](https://github.com/rails/rails/pull/47864#issuecomment-1515457877).

Let's say we're able to save these records (we can with the given schema, because there is not a primary key so there is no uniqueness validation). We're then going to have the same problem with equality tests/hashing/replacing an associations members the ids are equal so we assume the records are equal.

I can see an argument that Active Record is wrong to get as far as it does (where it assumes `id` is a primary key where here it isn't), but I have a hard time seeing a solution other than erroring earlier.

2023-05-01 21:36 UTC, jhawthorn requested changes
Ah. Here's a more concrete example of a problem.

```
> PkWithDefault.create!
 DEBUG -- :   TRANSACTION (0.2ms)  SAVEPOINT active_record_1
 DEBUG -- :   PkWithDefault Create (0.4ms)  INSERT INTO "pk_with_defaults" DEFAULT VALUES
 DEBUG -- :   TRANSACTION (0.0ms)  RELEASE SAVEPOINT active_record_1
=> #<PkWithDefault:0x00007fcdab656e10 id: 123>
> PkWithDefault.create!
 DEBUG -- :   TRANSACTION (0.0ms)  SAVEPOINT active_record_1
 DEBUG -- :   PkWithDefault Create (0.2ms)  INSERT INTO "pk_with_defaults" DEFAULT VALUES
 DEBUG -- :   TRANSACTION (0.0ms)  RELEASE SAVEPOINT active_record_1
=> #<PkWithDefault:0x00007fcdab67f658 id: 123>
> PkWithDefault.first.eql?(PkWithDefault.first)
 DEBUG -- :   PkWithDefault Load (0.1ms)  SELECT "pk_with_defaults".* FROM "pk_with_defaults" LIMIT ?  [["LIMIT", 1]]
 DEBUG -- :   PkWithDefault Load (0.0ms)  SELECT "pk_with_defaults".* FROM "pk_with_defaults" LIMIT ?  [["LIMIT", 1]]
=> false
> PkWithDefault.first.eql?(PkWithDefault.second)
 DEBUG -- :   PkWithDefault Load (0.1ms)  SELECT "pk_with_defaults".* FROM "pk_with_defaults" LIMIT ?  [["LIMIT", 1]]
 DEBUG -- :   PkWithDefault Load (0.1ms)  SELECT "pk_with_defaults".* FROM "pk_with_defaults" LIMIT ? OFFSET ?  [["LIMIT", 1], ["OFFSET", 1]]
=> false
```

I believe `PkWithDefault.first.eql?(PkWithDefault.first)` needs to return true and `PkWithDefault.first.eql?(PkWithDefault.second)` needs to return false if we want to be able to use an association correctly, otherwise we're just working around the first problem we run into but won't then end up with a working association. I don't think there's any way we can do that with the proposed schema.

2023-06-22 21:50 UTC, zenspider commented
It took about 2 months to do... but we've migrated our schema so this is no longer an issue. Closing.

2023-06-22 21:50 UTC, closed without merging

2023-06-22 22:40 UTC, zenspider commented
Hrm... I dunno maaaan... I removed our monkeypatches and have new errors all based around this. IDGI