Raise retryable exception class on abrupt Postgres connection closure
rails/rails pull request #48093
Opened 2023-04-28 16:23 UTC by shayonj

### Motivation / Background & Details

👋 Hi team! Fresh off RailsConf here. Enjoyed some of the convos with matthewd and figured I'd check out the new connection and query retry feature on rails@main. We have monkey patched ActiveRecord internally to perform query retry and connection retry to recover from failures automatically with Postgres.

While testing, I came across the following issue:

Postgres can at times throw the following error.
```
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

This can happen during a database crash or a failover, or when connections are intentionally terminated. When this happens, an already checked out ActiveRecord would raise `ActiveRecord::StatementInvalid: PG::UnableToSend: server closed the connection unexpectedly`.

Raising an `ActiveRecord::StatementInvalid` means that the query will not get retried, even when `allow_retry` is set to `true` because only `ConnectionNotEstablished` or `ConnectionFailed` are considered for retries (via `retryable_connection_error?`).

Hence, with this change, we will now also throw a `ConnectionNotEstablished` by extending the already existing error message matching for when Postgres is down.

### Additional information

In this PR, we also use `pg_terminate_backend` to recreate the a database failover scenario in the test. Which would prompt `pg` gem to throw `PG::UnableToSend: server closed the connection unexpectedly`. Accordingly we rest and retry and recover from the queries.

**Question**: Should this change be logged in CHANGELOG?

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

2023-04-29 13:59 UTC, shayonj commented
The diff is probably easier to read with white space off - https://github.com/rails/rails/pull/48093/files?diff=split&w=1

2023-05-12 19:58 UTC, shayonj commented
👋🏾 Hello team! Curious if there is any feedback on thoughts on this proposed change? Thanks!

2023-05-17 14:08 UTC, eileencodes requested changes
Hey @shayonj thanks for the PR. I left a comment that I think we can simplify the conditionals so they are clearer and there are less branches. This also needs a CHANGELOG entry in activerecord/CHANGELOG.md

2023-05-17 14:55 UTC, matthewd commented
Sorry for the delay in review, I've had variable availability especially while travelling.

I don't think this is a safely retryable error:

> This probably means the server terminated abnormally before **or while processing** the request.

2023-05-17 16:50 UTC, shayonj commented
Thank you for the reviews everyone, really appreciate it!

Regarding 
> I don't think this is a safely retryable error...
> This probably means the server terminated abnormally before or while processing the request.

Thats a good call out, let me share my understanding here and please let me know if I am missing anything

**Retrying queries when not in transaction**
In this case, like select or read queries. I believe its safe to retry those? I also see that we decouple the concept connection retries and query retries inside `with_raw_connection`. That way, we will be performing a new connection for every retry. 

**Retrying queries when within transaction**
With this things get a bit tricky. Lets say if we did want to support retries for transaction (not in this PR) it could still potentially, because say if the database goes down mid transaction and comes back up, it likely hadn't committed (`COMMIT`) the transaction and if its not committed yet, then other queries won't see that version of the row in Postgres. 

Here is an example of uncommitted transaction:
```ruby
ActiveRecord::Base.transaction do
  SomeModel.update(foo: "bar")
  ActiveRecord::Base.connection.execute("select pg_sleep(10)")
end
```

Now if in those 10seconds, if the database were to go down, we would not see the the `foo` column being updated. 

That said, as far as retries go for select/read queries, this feel like a retryable exception?  Let me know if I am not following something 🙏🏾

2023-05-17 17:16 UTC, shayonj commented
Thats fair, I get it now. Thanks!

Yeah, internally we are patching `exec_cache` and `exec_no_cache` to raise when [`in_transaction?`](https://github.com/rails/rails/blob/77ce7d6f940f76df6c65488f976bad5366ddc263/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L905) and then do something like the following to perform a backoff retry by using custom logic for inspecting the exception message.

```ruby
module RetryableTransaction
  def self.wrap(*args, &block)
    sleep_times = ::RailsPgAdapter.configuration.reconnect_with_backoff.dup
    begin
      ActiveRecord::Base.transaction(*args, &block)
    rescue ::ActiveRecord::StatementInvalid,
           ::ActiveRecord::ConnectionNotEstablished,
           ::ActiveRecord::NoDatabaseError => e
      raise unless ::RailsPgAdapter::Patch.failover_error?(e.message)
      sleep_time = sleep_times.shift
      raise(e) unless sleep_time
      sleep(sleep_time)
      retry
    end
  end
end
```

And then use `RetryableTransaction` in parts of the app. 

Thanks @matthewd and @eileencodes . I will close the PR for now.

2023-05-17 17:16 UTC, closed without merging