Improve `strict_loading` documentation [ci skip]
rails/rails pull request #49850
Opened 2023-10-30 15:42 UTC by ansonhoyt

* Update ActiveRecord::StrictLoadingViolationError API docs to
  reference the guide to help beginners learn how to resolve the error.
* Update Active Record Query Interface guide to cover configuration and
  the association option.

### Motivation / Background

This Pull Request has been created to improve the docs and guides.

### Detail

This Pull Request changes:

1. ActiveRecord::StrictLoadingViolationError API docs to link to the guide.
2. Active Record Query Interface guide to cover other facets of `strict_loading`.

### Additional information

Explains the association option, highlighted in Chris Oliver's excellent Rails World talk [Powerful Rails Features You Might Not Know](https://youtu.be/iPCqwZ9Ouc4?si=oFrWz5Db6zZYTYUN&t=134).

Continues the nice additions in https://github.com/rails/rails/pull/49329

I was inspired by @zzak's comment on https://github.com/rails/rails/pull/49741

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

2023-10-30 16:02 UTC, eileencodes requested changes

2023-10-30 16:02 UTC, eileencodes commented on activerecord/lib/active_record/errors.rb
> +  # {strict_loading}[rdoc-ref:QueryMethods#strict_loading].
```suggestion
  # {ActiveRecord::Base.includes}[rdoc-ref:QueryMethods#includes].
```

If someone turned it on it doesn't make sense to document changing the setting IMO.

2023-10-30 16:02 UTC, eileencodes commented on guides/source/active_record_querying.md
> +To send violations to the logger instead, change
```suggestion

To send violations to the logger instead, change
```

2023-10-30 16:13 UTC, akhilgkrishnan approved these changes

2023-10-30 17:38 UTC, eileencodes commented
Thanks, can you squash your commits into one commit?

2023-10-30 18:39 UTC, ansonhoyt commented
@eileencodes Done! Thanks for bearing with my ~~Codespaces~~ learning curve.

P.S. I enjoyed your talk [The Magic of Rails](https://www.youtube.com/watch?v=nvuPisDQ1hI). It piqued my curiosity to explore Active Storage code as I write a small API client.

2023-10-30 18:48 UTC, eileencodes approved these changes

2023-10-30 18:48 UTC, merged

2023-10-31 08:18 UTC, zzak commented
Thanks for working on this! Good additions. 👏 

> The API Documentation Guidelines' [Links](https://edgeguides.rubyonrails.org/api_documentation_guidelines.html#links) section doesn't cover when or how we should link to the guides from API docs.
> 
> I think it would help me if I got this error, but I couldn't find any existing links from API docs to Guides, so let me know if I did a bad thing 😬

There is a tiny blurb about it here, if you mean what I think you mean:
https://edgeguides.rubyonrails.org/ruby_on_rails_guides_guidelines.html#linking-to-the-api

In short, `api.` and `guides.` get turned into `edge*` during generation. So we don't have to type "edge" unless we really mean it.