fix LocalCache#read_multi_entries not namespacing keys & not deserializing raw values correctly
rails/rails pull request #50276
Opened 2023-12-05 20:07 UTC by fusion2004

### Motivation / Background

This Pull Request has been created because there are several issues w/ `read_multi` on cache stores with an active local cache:
- If using a namespace, it does not normalize the keys before looking them up in the cache and thus always falls back to looking them up in the real cache store
- If trying to lookup raw values with a client that fully supports them (like memcache or redis), it would always silently fail and return `nil` for the values _if it found them in the local cache_ (this was hidden in the current tests by the above issue)

### Detail

This Pull Request changes `read_multi_entries` on `LocalCache` to normalize the keys before looking them up in the local cache & to pass the options down to `deserialize_entry` to correctly deserialize raw values for memcache and redis stores. It also changes the `ActiveSupport::Cache::Store#deserialize_entry` signature to account for options being passed to it (from memory, null, & file stores).

### Additional information

On any rails app configured to use :mem_cache_store and no namespace (or do have a namespace and run with the changes from the first commit), run this code in a rails console:

```ruby
class LetsMakeItBreak
  def boom
    log_it = -> { puts "@data: #{::ActiveSupport::Cache::Strategy::LocalCache::LocalCacheRegistry.cache_for(Rails.cache.send(:local_cache_key)).instance_variable_get(:@data).inspect}" }

    Rails.cache.with_local_cache do
      log_it.call
      puts "fetch_multi: #{Rails.cache.fetch_multi("blep:one", raw: true) { 1 }}"
      log_it.call
      puts "increment: #{Rails.cache.increment("blep:one", 1, raw: true)}"
      log_it.call
      puts "read: #{Rails.cache.read("blep:one", raw: true)}"
      log_it.call
      puts "read_multi: #{Rails.cache.read_multi("blep:one", raw: true)}"
      log_it.call
    end
  end
end

LetsMakeItBreak.new.boom
```

The output should look like:

```ruby
@data: {}
Dalli::Server#connect 127.0.0.1:11211
fetch_multi: {"blep:one"=>1}
@data: {"blep:one"=>"1"}
increment: 2
@data: {"blep:one"=>"2"}
read: 2
@data: {"blep:one"=>"2"}
read_multi: {"blep:one"=>nil}
@data: {"blep:one"=>"2"}
```

You can see the problem on the `read_multi` output! Suddenly, a `nil` appears instead of `"2"`.

If we turn on logging for the cache, we can see a bit more of what is happening:

```ruby
Rails.cache.clear
Rails.cache.logger = Logger.new($stdout)
LetsMakeItBreak.new.boom
# ...
D, [2023-12-05T11:30:47.089666 #29076] DEBUG -- : Cache read_multi: 1 key(s) specified ({:compress=>true, :compress_threshold=>1024, :raw=>true})
W, [2023-12-05T11:30:47.089719 #29076]  WARN -- : Unrecognized payload prefix "2"; deserializing as nil
read_multi: {"blep:one"=>nil}
```

The culprit here is that the local cache strategy code was not accounting for the mem cache and redis stores expecting to pass the `raw: true` all the way down to the `deserialize_entry` method. This PR fixes that, and adjusts the overall signature of `ActiveSupport::Cache::Store#deserialize_entry` so the fix doesn't break other built-in stores like file, memory, & null.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
  * I tried to split this into 2 PRs, but fixing the first issue immediately makes the existing tests fail by exposing the second issue
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]` 
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

2023-12-05 20:14 UTC, jonathanhefner requested changes
@fusion2004 This PR doesn't seem radically different than #50274, so I don't think there was a need to open a new PR.

You may also wish to read my feedback from https://github.com/rails/rails/pull/50200#discussion_r1408189078 regarding tests.

And I would still like to hear from @sbfaulkner regarding a follow up to https://github.com/rails/rails/pull/50200#issuecomment-1832190587.

2023-12-05 20:36 UTC, fusion2004 commented
Yeah, looking at #50200 it pretty much did all things this does fix-wise. I can try and figure out exactly what the right tests for this are and make sure they're in `LocalCacheBehavior`.

2023-12-05 21:54 UTC, fusion2004 commented
@jonathanhefner Alrighty, now pushed up tests into `LocalCacheBehavior`!

<details>
<summary>On main, they fail just one test exposing the namespace issue</summary>
```
Failure:
ActiveSupport::Cache::RedisCacheStoreTests::RedisCacheStoreWithDistributedRedisTest#test_local_cache_of_fetch_multi [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:227]:
--- expected
+++ actual
@@ -1 +1 @@
-{"d9e631ae-6a4c-45b1-8337-2ae78f11f843"=>true, "f6983ac4-3f75-4584-8548-da8b2e3f17c3"=>true}
+{}


Failure:
MemCacheStoreTest#test_local_cache_of_fetch_multi [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:227]:
--- expected
+++ actual
@@ -1 +1 @@
-{"11d776eb-fc36-4cf2-adee-e4a82722c92a"=>true, "bad7978d-5c77-4e8e-8433-cacb54cceda0"=>true}
+{}


Failure:
ActiveSupport::Cache::RedisCacheStoreTests::RedisCacheStoreCommonBehaviorTest#test_local_cache_of_fetch_multi [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:227]:
--- expected
+++ actual
@@ -1 +1 @@
-{"06882cc0-a283-4b85-8ce8-346f5f2bb294"=>true, "8d724463-4995-4008-bef1-325e9c6f8c54"=>true}
+{}
```
</details>

<details>
<summary>Fixing the namespacing issue then causes many to fail</summary>
```
Failure:
ActiveSupport::Cache::RedisCacheStoreTests::RedisCacheStoreWithDistributedRedisTest#test_local_cache_of_read_multi [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:242]:
--- expected
+++ actual
@@ -1,3 +1 @@
-# encoding: US-ASCII
-#    valid: true
-"Ps4cp1UBjOtSj6vZ"
+nil


Failure:
ActiveSupport::Cache::RedisCacheStoreTests::RedisCacheStoreWithDistributedRedisTest#test_local_cache_of_increment [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:199]:
--- expected
+++ actual
@@ -1 +1 @@
-{"4c9cc82a-0948-4893-a59e-2a89428ccb5f"=>"3"}
+{"4c9cc82a-0948-4893-a59e-2a89428ccb5f"=>nil}


Failure:
ActiveSupport::Cache::RedisCacheStoreTests::RedisCacheStoreWithDistributedRedisTest#test_local_cache_of_decrement [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:214]:
--- expected
+++ actual
@@ -1 +1 @@
-{"79cbd99c-c775-47a7-b00f-87b52e1f15ed"=>"2"}
+{"79cbd99c-c775-47a7-b00f-87b52e1f15ed"=>nil}


Failure:
ActiveSupport::Cache::RedisCacheStoreTests::RedisCacheStoreWithDistributedRedisTest#test_local_cache_multi_read_write_and_increment_decrement_raw [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:331]:
--- expected
+++ actual
@@ -1 +1 @@
-{"446fed40-7302-4853-8ed4-600a9a51484b"=>"1", "f7e30018-8497-47e9-b150-efe4500159d2"=>"3"}
+{"446fed40-7302-4853-8ed4-600a9a51484b"=>nil, "f7e30018-8497-47e9-b150-efe4500159d2"=>nil}


Failure:
ActiveSupport::Cache::RedisCacheStoreTests::RedisCacheStoreCommonBehaviorTest#test_local_cache_of_read_multi [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:242]:
--- expected
+++ actual
@@ -1,3 +1 @@
-# encoding: US-ASCII
-#    valid: true
-"wyNVBTOXh7860zqY"
+nil


Failure:
ActiveSupport::Cache::RedisCacheStoreTests::RedisCacheStoreCommonBehaviorTest#test_local_cache_of_increment [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:199]:
--- expected
+++ actual
@@ -1 +1 @@
-{"9dd5d454-c0e8-47c3-871e-bd675a597d2b"=>"3"}
+{"9dd5d454-c0e8-47c3-871e-bd675a597d2b"=>nil}


Failure:
ActiveSupport::Cache::RedisCacheStoreTests::RedisCacheStoreCommonBehaviorTest#test_local_cache_of_decrement [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:214]:
--- expected
+++ actual
@@ -1 +1 @@
-{"60e50f1b-9442-46a0-9a3b-d1dd6bc51f87"=>"2"}
+{"60e50f1b-9442-46a0-9a3b-d1dd6bc51f87"=>nil}


Failure:
ActiveSupport::Cache::RedisCacheStoreTests::RedisCacheStoreCommonBehaviorTest#test_local_cache_multi_read_write_and_increment_decrement_raw [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:331]:
--- expected
+++ actual
@@ -1 +1 @@
-{"dec45ee5-1e91-4f14-890f-733578f09be6"=>"1", "3ca823b0-bfc8-4077-b91c-3da350bba634"=>"3"}
+{"dec45ee5-1e91-4f14-890f-733578f09be6"=>nil, "3ca823b0-bfc8-4077-b91c-3da350bba634"=>nil}


Failure:
MemCacheStoreTest#test_local_cache_of_decrement [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:214]:
--- expected
+++ actual
@@ -1 +1 @@
-{"83addc39-490b-4c85-ae28-58308aded731"=>"2"}
+{"83addc39-490b-4c85-ae28-58308aded731"=>nil}


Failure:
MemCacheStoreTest#test_local_cache_multi_read_write_and_increment_decrement_raw [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:331]:
--- expected
+++ actual
@@ -1 +1 @@
-{"d8761804-cc1f-47f2-afeb-aa75272ea070"=>"1", "aad24790-e3c9-4766-8ba5-1b894fbae557"=>"3"}
+{"d8761804-cc1f-47f2-afeb-aa75272ea070"=>nil, "aad24790-e3c9-4766-8ba5-1b894fbae557"=>nil}


Failure:
MemCacheStoreTest#test_local_cache_of_increment [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:199]:
--- expected
+++ actual
@@ -1 +1 @@
-{"809647ec-1184-410d-922b-29599f68b28a"=>"3"}
+{"809647ec-1184-410d-922b-29599f68b28a"=>nil}


Failure:
MemCacheStoreTest#test_local_cache_of_read_multi [/Users/fusion2004/dev/rails/activesupport/test/cache/behaviors/local_cache_behavior.rb:242]:
--- expected
+++ actual
@@ -1,3 +1 @@
-# encoding: US-ASCII
-#    valid: true
-"tA9p358pzdBEWuwP"
+nil
```
</details>

And with the deserialization fix, they should all be green.

2023-12-08 21:44 UTC, jonathanhefner reviewed
> Alrighty, now pushed up tests into `LocalCacheBehavior`!

Nice!

2023-12-08 22:31 UTC, fusion2004 commented on activesupport/lib/active_support/cache/strategy/local_cache.rb
> +              values[keys_to_names[key]] = deserialize_entry(payload, **options)&.value
Yep, that makes sense. Do we want to make a similar change to `transform_values!` in `MemCacheStore#read_multi_entries`? (If so should I do that in this PR or a separate one?)

2023-12-08 22:32 UTC, fusion2004 commented on activesupport/test/cache/behaviors/local_cache_behavior.rb
> +      assert_equal({ key => expected }, @cache.read_multi(key, raw: true))
Yep, I think I was being overzealous here, will remove.

2023-12-08 22:33 UTC, fusion2004 commented on activesupport/test/cache/behaviors/local_cache_behavior.rb
> +  end
Yep, I think I was just overzealous here again and was trying to cover the specific situation where this bug cropped up in our app. Will remove!

2023-12-08 23:03 UTC, jonathanhefner commented on activesupport/lib/active_support/cache/strategy/local_cache.rb
> +              values[keys_to_names[key]] = deserialize_entry(payload, **options)&.value
The code in [`MemCacheStore#read_multi_entries`](https://github.com/rails/rails/blob/5621c93bfc8e8aefab90223dcf0edf4b10e5dcf6/activesupport/lib/active_support/cache/mem_cache_store.rb#L274-L297) is a bit more complicated.  There are several cases where a key / value pair might be skipped.  I'm not sure whether it's worth changing `MemCacheStore#read_multi_entries`, but I would save that for another PR.

2023-12-11 16:15 UTC, fusion2004 commented
@jonathanhefner I believe I've addressed all the feedback!

2023-12-11 17:41 UTC, merged

2023-12-11 17:41 UTC, jonathanhefner commented
I pushed a commit to [squash the commits](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits).

Thank you, @fusion2004! :books:

2023-12-11 19:57 UTC, sbfaulkner commented
@fusion2004 looks like you fixed the main issue I was fixing ❤️  -- what prevented me from proceeding was that my scope crept a big bigger and I started to question what the actual behaviour should be in some of the cases. You've successfully worked around that by focusing on the "...prioritizes_local_entries" part of the behaviour so that it mattered less what the underlying cache store's behaviour was -- so, thank you!