Take AR affixes into account for Action Text database models
rails/rails pull request #50299
Opened 2023-12-08 08:13 UTC by chaadow

Follow up to https://github.com/rails/rails/pull/50247 and https://github.com/rails/rails/pull/50167 cc @jonathanhefner 

This removes the redundant hard coded table names to make the models compatible with `ActiveRecord::Base.{prefix|suffix}`

This also adds prefix/suffix in the dummy app to force the entire test suite to be agnostic to hard-coded table names.

2023-12-08 13:26 UTC, eileencodes requested changes
Same request here, can you add tests for the prefix/suffix? Thanks!

2023-12-08 17:50 UTC, chaadow reviewed
Thanks for the review @eileencodes I've added the missing tests.

As a side note, I've added tests in the previous PR for all isolated engines, that's why I thought I can skip them here. https://github.com/rails/rails/blob/900dc3280932df4a614cfa06b59959f249e65ce1/railties/test/railties/engine_test.rb#L1293-L1317

2023-12-08 19:38 UTC, eileencodes requested changes
Thanks for adding a test, I left some comments about simplifying it.

2023-12-08 21:45 UTC, jonathanhefner commented
> As a side note, I've added tests in the previous PR for all isolated engines, that's why I thought I can skip them here.

That was part of the reason why I didn't feel a test was necessary for #50167.  The other part is that we are removing configuration in favor of convention.  If we were going the other way (adding hard-coded table names to prevent them from incorporating `ActiveRecord::Base.table_name_{prefix,suffix}`), then I would have definitely included a test.  But since we're reverting to the default behavior, it didn't seem necessary, the same way we don't test that the derived table name is snake_cased and plural (outside of `activerecord/test` tests).

Of course, more test coverage doesn't hurt. :smiley:

2023-12-09 10:07 UTC, chaadow reviewed
Thanks for the review @eileencodes I've applied the changes.

2023-12-11 14:23 UTC, eileencodes approved these changes

2023-12-11 14:24 UTC, merged

2023-12-11 14:24 UTC, eileencodes commented
Thank you!