Fix inconsistent results of params.deep_transform_keys
rails/rails pull request #50361
Opened 2023-12-15 02:14 UTC by iagopiimenta

### Motivation / Background

Fix: #50326

### Detail

`params.deep_transform_keys` should transform the keys of the params, including nested hashes, arrays, and ActionController::Parameters objects.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

2024-02-20 15:56 UTC, iagopiimenta commented
Karma is failing to start browsers:

![image](https://github.com/rails/rails/assets/5642707/4bfa0557-ca1c-4197-9875-f10d2cf4291a)

Do I need some special permission?

2024-02-20 22:30 UTC, rafaelfranca requested changes

2024-02-20 22:30 UTC, rafaelfranca commented on activesupport/lib/active_support/core_ext/hash/keys.rb
> +      when defined?(ActionController::Parameters) && ActionController::Parameters
Active Support should not have any knowledge about `ActionController`. Can't this problem be solve by overriding those methods in `ActionController::Parameters`?

2024-02-21 17:55 UTC, merged

2024-08-29 20:06 UTC, cjavdev commented
I think this change may have broken us (maybe we were depending on the wrong behavior here, but it feels like a pattern lots of users might use to convert from camel case to snake case). We convert from camel to snake case with deep_transform_keys, and before this change, it would give us the expected top level snake case key with the data nested, but after this change we now get an empty hash as the value because it seems to be overwritten instead of merged.


```rb
module Api
  module V1
    class WaitlistUsersController < Api::BaseController
      def create
        user = WaitlistUser.find_by(email: waitlist_user_params[:email].downcase)

        if user.nil?
          @waitlist_user = WaitlistUser.new(waitlist_user_params)
        else
          @waitlist_user = user
          user.update(waitlist_user_params)
        end

        if @waitlist_user.save
          render json: @waitlist_user, status: :created
        else
          render json: { errors: @waitlist_user.errors }, status: :unprocessable_entity
        end
      end

      private

      def waitlist_user_params
        params
          .deep_transform_keys!(&:underscore)
          .require(:waitlist_user)
          .permit(
            :email,
            :name,
          )
      end
    end
  end
end
```

Request:

```sh
POST /api/v1/waitlist_users

{
    "waitlistUser": { "email": "test@example.com" }
}
```
worked fine. 

Now:

```sh
bin/rails s -p 3001
=> Booting Puma
=> Rails 7.2.1 application starting in development
=> Run `bin/rails server --help` for more startup options


Started POST "/api/v1/waitlist_users" for ::1 at 2024-08-29 16:05:03 -0400
Processing by Api::V1::WaitlistUsersController#create as JSON
  Parameters: {"waitlistUser"=>{"email"=>"[FILTERED]"}, "waitlist_user"=>{}}
Completed 400 Bad Request in 1218ms (ActiveRecord: 23.2ms (0 queries, 0 cached) | GC: 212.9ms)

ActionController::ParameterMissing (param is missing or the value is empty: waitlist_user):

app/controllers/api/v1/waitlist_users_controller.rb:34:in `waitlist_user_params'
app/controllers/api/v1/waitlist_users_controller.rb:7:in `create'
app/controllers/concerns/set_locale.rb:13:in `set_locale'
```

2024-08-29 21:01 UTC, iagopiimenta commented
I tested it, and it's working:
```ruby
irb(main):015> Rails.version
=> "7.2.1"
irb(main):016> params = ActionController::Parameters.new({ "waitlistUser": { "email": "TEST@example.com" } })
irb(main):017> waitlist_user_params = params.deep_transform_keys!(&:underscore).require(:waitlist_user).permit(:email, :name)
irb(main):018> waitlist_user_params[:email].downcase
=> "test@example.com"

```

@cjavdev make sure you don't have other things affecting your controller. You can try it with a fresh rails app.

2024-08-29 21:11 UTC, cjavdev commented
Thanks @iagopiimenta I figured it out. It was because I had this enabled for `wrap_parameters`:

```rb
ActiveSupport.on_load(:action_controller) do
  wrap_parameters format: [:json]
end
```

This meant that the test for my scenario would be:

```rb
params = ActionController::Parameters.new({ "waitlistUser": { "email": "TEST@example.com" }, "waitlist_user": {} })
params.deep_transform_keys!(&:underscore).require(:waitlist_user).permit(:email, :name)[:email]
```