Improve documentation for `action_text:install` task
rails/rails pull request #50557
Opened 2024-01-03 16:15 UTC by seanpdoyle

### Detail

First, mimic the documentation and guidance provided for the `active_storage:install` task, including nudges the execute the command when tables are missing.

Similarly, adjust the source code text in the generator itself. By removing the newlines, the generator won't inject the JS and CSS source more than once if it already exists.

### Additional information

This commit includes a diff scoped to `test/dummy` that was generated by executing the following:

```bash
cd test/dummy
bin/rails action_text:install
bin/rails db:migrate
```

2024-01-03 16:15 UTC, seanpdoyle commented
@zzak this might be related to the Railtie work you've been investigating for the various test harnesses.

2024-01-03 16:21 UTC, rafaelfranca requested changes

2024-01-03 16:21 UTC, rafaelfranca commented on guides/source/action_text_overview.md
> +```bash
```suggestion

```bash
```

2024-01-03 16:21 UTC, rafaelfranca commented on guides/source/action_text_overview.md
> +```
```suggestion
```

```

2024-01-05 16:48 UTC, brunoprietog reviewed
I think for CSS, maybe the installation should suggest importing the stylesheet from the application layout, before the `application.css`, since imports do not work well with Propshaft. See [rails/propshaft#90](https://github.com/rails/propshaft/issues/90)

2024-01-05 16:48 UTC, brunoprietog commented on guides/source/action_text_overview.md
> +This adds the Yarn package, and copies over the necessary migrations. Also, you need to set up Active Storage for embedded images and other attachments. Please refer to the [Active Storage Overview](
Or importmap / bun? Maybe change it to JavaScript package only?

2024-01-14 01:51 UTC, zzak commented
🙈 Yeah can we not update the dummy apps until that PR is merged?

2025-07-16 17:09 UTC, seanpdoyle commented
> 🙈 Yeah can we not update the dummy apps until that PR is merged?

@zzak has sufficient time passed to avoid conflicting with the Railties PR you'd worked on?

2025-07-18 09:43 UTC, zzak commented
Is it critical for this PR to update them?

2025-07-18 13:04 UTC, seanpdoyle commented
> Is it critical for this PR to update them?

@zzak baseed on my understanding, no. You had initially raised some concern about coordinating changes in January 2024, so I wanted to follow up. From what I can tell, the dependencies at-play here are strictly testing related.

2025-07-28 03:35 UTC, zzak commented
> strictly testing related

Does that mean "exercising those code paths for coverage" or "without them test behavior changes"?

Because if it's the former then we should just not bother.

2025-07-28 14:24 UTC, seanpdoyle commented
@zzak I'm still not quite sure what you had in mind when you sent https://github.com/rails/rails/pull/50557#issuecomment-1890820260.

Based on context clues, I _think_ what we're discussing is related to https://github.com/rails/rails/pull/54669, and that PR does not modify [railties/test/application/configuration_test.rb](https://github.com/rails/rails/pull/50557/files#diff-f0a37d99a7be9a0bfc46997768ccb3bfbe9a81c427311e2ba49a7ffe5eec26e4) at all.

With that in mind, I think this PR is ready.

2025-07-28 15:14 UTC, zzak commented on actiontext/test/dummy/app/assets/stylesheets/actiontext.css
I mean these changes, should be reverted unless they are required to e.g. fix a failing test introduced in this PR

2025-07-29 12:27 UTC, zzak commented on actiontext/test/dummy/db/schema.rb
> -    t.index ["blob_id"], name: "index_active_storage_attachments_on_blob_id"
These too, are they required?

2025-07-29 15:54 UTC, seanpdoyle commented on actiontext/test/dummy/db/schema.rb
> -    t.index ["blob_id"], name: "index_active_storage_attachments_on_blob_id"
I've reverted the schema changes.

2025-07-30 01:30 UTC, zzak commented on actiontext/lib/generators/action_text/install/install_generator.rb
> +          JS
Are these changes cosmetic? Can you revert them if so please :pray:

2025-07-30 01:33 UTC, zzak commented on railties/test/application/configuration_test.rb
> +    test "renders actionable exception page when Action Text is not installed" do
This file is already getting really huge, maybe we should move this test to `railties/test/application/action_text/whatever`, like we started to do for Active Storage:
https://github.com/rails/rails/blob/main/railties/test/application/active_storage/uploads_integration_test.rb

2025-07-31 02:28 UTC, seanpdoyle commented on railties/test/application/configuration_test.rb
> +    test "renders actionable exception page when Action Text is not installed" do
I've created a new `railties/test/application/action_text/installation_integration_test.rb` test file to move this test coverage out of `railties/test/application/configuration_test.rb`.

2025-07-31 02:28 UTC, seanpdoyle commented
@zzak evidently, a change just like this one has already landed in the Action Text Overview as part of https://github.com/rails/rails/pull/50977 (see https://github.com/rails/rails/commit/a4253311d8bec46770c402679374c223f3bfe7bc [lines 55-80](https://github.com/rails/rails/commit/a4253311d8bec46770c402679374c223f3bfe7bc#diff-627421de6945a9b1a34361cb69aacc680bcd3ce4d08408182c9923e2171dc9d7R55-R80)).

I've removed the documentation changes, and have instead re-purposed this commit to solely focus on improving the error page messaging when the exception is specific to Action Text.

2025-07-31 03:25 UTC, zzak commented on railties/test/application/action_text/installation_integration_test.rb
> +      assert_equal 500, last_response.status
Is it possible last_response could get corrupted between requests?
Should these be separate test cases with the setup appending config, routes, controllers, etc?

2025-07-31 14:07 UTC, seanpdoyle commented on railties/test/application/action_text/installation_integration_test.rb
> +      assert_equal 500, last_response.status
I've changed this coverage to focus solely on the single Action Text error. I think similar coverage should exist for the Active Storage error, but that feels best addressed in a separate PR.

2025-07-31 15:42 UTC, zzak approved these changes

2025-10-14 23:48 UTC, merged