Documentation: Expand documentation on has_one_attached method [ci-skip].
rails/rails pull request #50892
Opened 2024-01-26 20:02 UTC by Takahashi-Seiji

### Motivation / Background

Give further context about the requirements for using the has_one_attached method. 

I have an application that does not have an ActiveJob::Backend queue adapter. When I tried to destroy a record, it raised an error that I needed a queue adapter. There is a dependency between the has_one_attached method and a queue adapter. 

That is why adding more context about the functionality and requirements about using the has_one_attached method is important. 

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [N/A] Tests are added or updated if you fix a bug or add a feature.
* [X] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

2024-01-26 20:35 UTC, p8 commented on activestorage/lib/active_storage/attached/model.rb
> +      # If a queue adapter is not set in the application, it will raise an error.
I think we can remove some duplication in explaining the default option.
We can also recommend an alternative for when the queue adapter isn't set.
Maybe something like:
```suggestion
      # The +:dependent+ option defaults to +:purge_later+. This means the attachment will be
      # purged (i.e. destroyed) in the background whenever the record is destroyed. 
      # If an ActiveJob::Backend queue adapter is not set in the application set it to
      # +purge+ instead.
```

This also applies to `has_many_attached`.

2024-01-28 09:40 UTC, p8 commented
Having ActiveJob configured also applies to `has_many_attached`.

2024-01-29 20:20 UTC, Takahashi-Seiji commented
Added the suggestions, looking forward for review.

2024-01-29 20:22 UTC, p8 commented
Thanks @Takahashi-Seiji !
Can you squash your commits?

2024-01-29 21:26 UTC, Takahashi-Seiji commented
Squash done!

2024-01-30 09:16 UTC, p8 requested changes, later dismissed

2024-01-30 09:16 UTC, p8 commented on activestorage/lib/active_storage/attached/model.rb
> +
✂️ 
```suggestion
```

2024-02-06 18:14 UTC, salochara commented
Hi! @p8 
@Takahashi-Seiji resolved the last comment you kindly left in the PR. 
Let us know if there's something else missing! 

All the best!
Salomón.

2024-02-09 21:14 UTC, merged

2024-02-09 21:15 UTC, skipkayhil commented
Thanks for contributing to Rails! 🎉