`Rails::Generators::GeneratedAttribute#to_s`
rails/rails pull request #51112
Opened 2024-02-16 23:09 UTC by dorianmariecom

### Motivation / Background

I'm writing my own generator (concept) and would like to easily call the model generator

This Pull Request has been created because it wasn't easy to convert a generated attribute (options passed to the generator) to a string to be passed to another generator

### Detail

This Pull Request changes `Rails::Generators::GeneratedAttribute#to_s`

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

2024-02-17 05:47 UTC, dorianmariecom commented
both failed builds seems to come from a cancellation:

```
Received cancellation signal, interrupting
```

2024-02-20 17:41 UTC, rafaelfranca commented
Can you explain why you need this feature? Model generators already redirect all the attribute to the migrator generator and we didn't need a `to_s` method to do that.

2024-02-20 20:04 UTC, dorianmariecom commented
I was doing something like:

```ruby
rails_command("generate model #{attributes.join}")
```

Because I wanted custom options but the same attributes-like options

2024-02-20 20:15 UTC, rafaelfranca commented on railties/lib/rails/generators/generated_attribute.rb
> +      def attr_options_to_s
Does this method needs to be public?
```suggestion
      def print_attribute_options
```

2024-02-20 20:15 UTC, rafaelfranca reviewed
Got it. Idea makes sense. Made a comment about the implementation.

2024-02-20 20:19 UTC, dorianmariecom commented on railties/lib/rails/generators/generated_attribute.rb
> +      def attr_options_to_s
renamed the method and made it private

2024-02-20 20:32 UTC, dorianmariecom commented
I also added extra checks to know if there is only one option in case someone pass those options like "{size,limit}". Maybe too defensive

2024-02-20 20:43 UTC, rafaelfranca requested changes
Yeah, no need to check that. There is no way to generate this kind of options.

2024-02-20 20:43 UTC, rafaelfranca commented on railties/lib/rails/generators/generated_attribute.rb
> +          elsif attr_options[:size] && attr_options.one?
```suggestion
          elsif attr_options[:size]
```

2024-02-20 20:43 UTC, rafaelfranca commented on railties/lib/rails/generators/generated_attribute.rb
> +          elsif attr_options[:limit] && attr_options.one?
```suggestion
          elsif attr_options[:limit]
```

2024-02-20 20:53 UTC, dorianmariecom commented on railties/lib/rails/generators/generated_attribute.rb
> +          elsif attr_options[:size] && attr_options.one?
removed

2024-02-20 20:54 UTC, dorianmariecom commented on railties/lib/rails/generators/generated_attribute.rb
> +          elsif attr_options[:limit] && attr_options.one?
removed

2024-02-20 20:54 UTC, dorianmariecom commented
I removed the `one?` checks

2024-02-20 22:24 UTC, merged

2024-02-21 09:39 UTC, dorianmariecom commented
Thanks @rafaelfranca