[Fix #51164] query_constraints with single non-primary-key column rai…
rails/rails pull request #51165
Opened 2024-02-22 14:04 UTC by joshuay03

…ses incorrect error

### Motivation / Background

Fixes #51164.

### Detail

This Pull Request changes `ActiveRecord::Reflection::AssociationReflection#derive_fk_query_constraints` to raise an existing more appropriate error if `Model.query_constraints` is given a single non-primary-key column argument.

### Additional information

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

2024-02-22 14:09 UTC, joshuay03 commented on activerecord/test/cases/associations_test.rb
> +    assert_equal "The query constraints on the `Sharded::BlogPost` model does not include the primary key so Active Record is unable to derive the foreign key constraints for the association. You nee
Before patch:

<img width="1529" alt="Screenshot 2024-02-22 at 11 59 06 PM" src="https://github.com/rails/rails/assets/54629302/2beb5d11-e91a-43ba-85a9-df00cd16f4f0">

2024-02-27 17:47 UTC, eileencodes requested changes
Can you fix the tests? You need to use a different name for the `has_many`, the redefined ones need to be unique per test.

2024-02-28 04:40 UTC, joshuay03 commented
> Can you fix the tests? You need to use a different name for the `has_many`, the redefined ones need to be unique per test.

@eileencodes Done, thanks for taking a look! The current CI failure seems unrelated.

2024-02-28 13:12 UTC, eileencodes approved these changes

2024-02-28 13:12 UTC, merged

2024-02-28 13:52 UTC, eileencodes commented
Thanks!

Backported to 7-1-stable in 6f0c3a4721d2ff0190a17d687198c9b84decf2cf