Add :variant option to render-related documentation [ci skip]
rails/rails pull request #51382
Opened 2024-03-21 18:30 UTC by dylhack

### Motivation / Background

This Pull Request has been created because; when looking for the `:variant` option when rendering a partial I noticed there wasn't any API documentation on it. I saw it on the guidelines, but the guidelines didn't cover that the option could be singular.

### Detail

This Pull Request adds `:variant` documentation to `ActionView::PartialRenderer` and `ActionController::Rendering`.
 
### Additional information

It's not clear to me what areas should also include the as an available option, any insights would be helpful! 🙂 

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

2024-03-21 18:38 UTC, dylhack commented
I see in Rails 7 that `:variants` can't be singular in partial rendering, I'm going to update that now.

2024-03-21 18:40 UTC, dylhack commented
Corrected now.

2024-03-27 20:18 UTC, dylhack commented
cc @rafaelfranca

2025-02-18 23:54 UTC, dylhack commented
@zzak I thought it was outdated since the new rails docs updates, but I'd be happy to get this in!

2025-02-19 00:20 UTC, zzak commented
Looks like `variants` was added in #53601 but the singular form is missing, but tbh I'm not looking that closely at it. Maybe @p8 or @stevepolitodesign can take a look :bow:

2025-03-11 14:22 UTC, p8 requested changes

2025-03-11 19:05 UTC, dylhack commented
@p8 rebased and removed changes in 36e9f524ba3b16db5021153ed4abd3ca6a8320cf!

2025-03-25 15:56 UTC, p8 commented on actionview/lib/action_view/renderer/partial_renderer.rb
> +  # and with <tt>:desktop</tt> will render the original <tt>_account.html.erb</tt>.
This part is a bit unclear to me.
Maybe copy this from the guides?
https://edgeguides.rubyonrails.org/layouts_and_rendering.html#the-variants-option

```suggestion
  # This will look for the following templates and render the first one that exists:
  # * <tt>_account.html+desktop.erb</tt>
  # * <tt>_account.html+mobile.erb</tt>
  # * <tt>_account.html.erb</tt>
```

2025-03-26 04:44 UTC, dylhack commented on actionview/lib/action_view/renderer/partial_renderer.rb
> +  # and with <tt>:desktop</tt> will render the original <tt>_account.html.erb</tt>.
@p8 That sounds better

2025-03-26 09:34 UTC, p8 commented
Thanks @dylhack . Can you squash your commits?

2025-03-26 11:33 UTC, dylhack commented
@p8 squashed now

2025-03-26 14:30 UTC, merged

2025-03-26 14:30 UTC, p8 commented
Thanks @dylhack !