Raise specific exception when a pool is not configured
rails/rails pull request #52298
Opened 2024-07-09 21:19 UTC by hharen

### Motivation / Background

This Pull Request has been created to make it easier to provide programatic access to details about requested shard/role.

### Detail

- This Pull Request introduces a more specific exception `NoConnectionPool` as a subclass of the previously-raised ConnectionNotEstablished. The new exception is used to handle cases where a requested database connection pool has not been found.
- The `retrieve_connection_pool` method in `connection_handler.rb` has been modified to provide more specific error messages reflecting if we're missing a shard and/or a role.
- Test cases have been updated to reflect these changes.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

cc @matthewd

2024-07-10 18:58 UTC, eileencodes requested changes
Thanks for the PR @hharen!

I talked to @matthewd a bit about this today. I don't like the `NoConnectionPool` error name because a connection pool in this error is an internal detail  to Active Record. The real issue is there's no connection for the provided name with role and shared. So I'd rather a `NoConnectionError` or something like that. Open to other names as long as we don't mention the pool.

Also is there a way we can make this method a little cleaner? It's kind of hard to read at the moment.

2024-07-16 07:45 UTC, hharen commented
Thank you for the inputs, @eileencodes. 

We implemented following changes as per your suggestions:
#### Changed the exception name to `ConnectionNotDefined`
- `ConnectionNotDefined` is similar to existing `NotEstablished` exception
- it avoids any confusion with the _we know about that connection, but have failed to talk to the DB server_ interpretation of `no connection`

#### Message construction in `retrieve_connection_pool` method
- we construct the message first and have the raise call just once
- there's a bit more runtime work, but we only get here in an application-is-misconfigured error case

2024-07-16 12:10 UTC, eileencodes reviewed
This looks good! Thanks for making the changes. Can you add a CHANGELOG entry?

2024-07-16 18:01 UTC, eileencodes commented on activerecord/CHANGELOG.md
> +    *Hana Harencarova*, *Matthew Draper*
This needs to be at the top of the file, we add them backwards.

2024-07-16 20:57 UTC, merged

2024-07-16 20:57 UTC, eileencodes commented
Thank you!