Add setting for logging redirect source locations
rails/rails pull request #52297
Opened 2024-07-09 14:22 UTC by dennispaagman

### Motivation / Background

This introduces a new config setting: `action_dispatch.verbose_redirect_logs`. It logs the source location of redirects. It works similarly to `active_record.verbose_query_logs` and `active_job.verbose_enqueue_logs`.

Redirects are of course used a lot. They are often defined in different locations. For example in your authentication code, authorization code, fallbacks for resources that can't be found, and to redirect users to a different page after performing an action, possibly with multiple redirect options in one controller action.

I think it would be beneficial to know exactly which line of code triggered a redirect. 

### Detail

This adds a config setting that logs the source location of the redirect.

There are three main use cases, they would look like this:

1. Redirects in filters (these already have a "filter chain halted" log as well, which points you in the right direction a bit, but the exact code location can still be useful):

```
Redirected to http://localhost:3000/
↳ app/controllers/posts_controller.rb:76:in `check_something'
Filter chain halted as :redirect rendered or redirected
Completed 302 Found in 18ms (ActiveRecord: 0.1ms (1 query, 0 cached) | GC: 0.0ms)
```

2. Redirects in controller actions:

```
Redirected to http://localhost:3000/posts/7
↳ app/controllers/posts_controller.rb:32:in `block (2 levels) in create'
Completed 302 Found in 36ms (ActiveRecord: 1.3ms (1 query, 0 cached) | GC: 0.0ms)
```

3. Redirects in routes:

```
Started GET "/redirect" for ::1 at 2024-07-09 12:40:23 +0200
Redirected to http://localhost:3000/
↳ /Users/dennis/Code/rails-test-app/config/routes.rb:14
Completed 301 Moved Permanently in 9ms
```

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

---

There are a few points I'm not sure how to approach and like some guidance in:

1. ~~The test for for dispatch (`actionpack/test/dispatch/routing/log_subscriber_test.rb`) breaks currently. The code relies on [`request.routes`][2] to be set (which is true for actual applications), but it's `nil` in the tests. I'm not sure if going through `request.routes` is the best approach or what needs to change in the tests to make them pass or have the routes available.~~
2. The source location for redirects from the router looks slightly different. This is because it uses [the existing `source_location` implementation][1], which for example shows the absolute path. I'm not sure if that's fine, or we want to get that in line with how the backtrace cleaner is used in other places.
3. This is the 3rd very similar config setting (`verbose_query_logs`, `verbose_enqueue_logs` and now `verbose_redirect_logs`). I can imagine most people will either set all or none of them. Would it make sense to consolidate them into one setting, or maybe have a setting that sets all 3 at the same time? The code for them is also very similar. Happy to work in a direction that unifies them if that's desirable.

[1]: https://github.com/rails/rails/blob/16f1222753cac0a554a2acd8f4ffa3f23d51d945/actionpack/lib/action_dispatch/routing/mapper.rb#L378-L408
[2]: https://github.com/rails/rails/blob/16f1222753cac0a554a2acd8f4ffa3f23d51d945/actionpack/lib/action_dispatch/http/request.rb#L161-L163

2024-08-16 16:39 UTC, flavorjones commented
@djfpaagman :wave: Thank you for submitting this pull request! It generally looks pretty good. Currently there are some test failing, can you take a look? For example: https://buildkite.com/rails/rails/builds/109003#019097e0-a03c-45e3-a88d-92186fbababd

2024-08-16 19:16 UTC, flavorjones requested changes
Sorry, didn't see your questions above when I first responded.

1. Suggestion on getting the test to pass inline.
2. I think that's fine for now, personally, and can be cleaned up in a separate PR if someone wants to take the time.
3. I'll let someone from the core team weigh in.

2024-08-16 19:16 UTC, flavorjones commented on actionpack/test/dispatch/routing/log_subscriber_test.rb
> +    puts logs
Please remove this debugging statement!

2024-08-16 19:16 UTC, flavorjones commented on actionpack/test/dispatch/routing/log_subscriber_test.rb
> +    assert_equal 3, logs.size
One way to get this to pass is to add a method to this test class:

```patch
diff --git a/actionpack/test/dispatch/routing/log_subscriber_test.rb b/actionpack/test/dispatch/routing/log_subscriber_test.rb
index c28676ec..daf828ae 100644
--- a/actionpack/test/dispatch/routing/log_subscriber_test.rb
+++ b/actionpack/test/dispatch/routing/log_subscriber_test.rb
@@ -52,6 +52,10 @@ def draw(&block)
       end
     end
 
+    def get(path, **options)
+      super(path, **options.merge(headers: { "action_dispatch.routes" => @app.routes }))
+    end
+
     def logs
       @logs ||= @logger.logged(:info)
     end
```

2024-09-16 20:15 UTC, p8 commented on actionpack/lib/action_dispatch/log_subscriber.rb
> +
If the log level is higher than `:info`  we can skip some code execution by wrapping it all in the `info` block.
```suggestion
      info do
        if ActionDispatch.verbose_redirect_logs
          request = payload[:request]

          request.routes.router.recognize(request) do |route|
            "↳ #{route.source_location}"
            # Or maybe we need to assign it to a instance variable here:
            # message = "↳ #{route.source_location}"
          end
          # message # maybe?
        end
      end

```

2024-09-16 20:21 UTC, p8 commented on actionpack/lib/action_dispatch/routing/mapper.rb
> +              if Mapper.route_source_locations || ActionDispatch.verbose_redirect_logs
If we are going to return route source locations, we might as well change 
how `Mapper.route_source_locations` is set and avoid Mapper having to know about `verbose_redirect_logs`.
We could set it here:
https://github.com/rails/rails/blob/d0f830033b2ea27bc1e66683ce5b16bd9ca55df1/actionpack/lib/action_dispatch/railtie.rb#L71

```ruby
      ActionDispatch::Routing::Mapper.route_source_locations = Rails.env.development? || ActionDispatch.verbose_redirect_logs
```

Or could we just leave it out?
Not sure what the result would be.

2024-10-03 12:00 UTC, zzak commented
:thinking: Why not have this info for all requests? I know in large apps, finding where a request is defined can often be a multi-step and often consume more time than comfortable.

2024-10-04 01:34 UTC, zzak commented
Yes but I'd like to know how others feel about widening the scope of this, or if they are orthogonal.

2024-10-08 10:26 UTC, p8 commented
What line would we be showing in the logs for non-redirects?
The line where render is called won't work for non-explicit render calls:
```ruby
def show
  @post = Post.find(params[:id])
end
```
Maybe it would make sense to show where in the framework the render is called in this situation 🤔 ?

2024-11-22 13:10 UTC, flavorjones commented
@djfpaagman You may want to join the discord and ask for a review in the `#contributions` channel ([here's the relevant Guide section](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#get-some-feedback)). That's usually how I get PRs across the finish line.

2025-09-11 02:52 UTC, gmcgibbon requested changes

2025-09-11 02:52 UTC, gmcgibbon commented on actionpack/lib/action_dispatch/railtie.rb
> +      ActionDispatch::Routing::Mapper.route_source_locations = Rails.env.development? || ActionDispatch.verbose_redirect_logs
I dislike having to lean on this feature. I made a patch to use backtrace cleaners in both places. Let's use this instead:
```diff
diff --git a/actionpack/lib/action_controller/log_subscriber.rb b/actionpack/lib/action_controller/log_subscriber.rb
index d98ca3ef3d..3eb053df31 100644
--- a/actionpack/lib/action_controller/log_subscriber.rb
+++ b/actionpack/lib/action_controller/log_subscriber.rb
@@ -67,12 +67,8 @@ def redirect_to(event)
       info { "Redirected to #{event.payload[:location]}" }
 
       info do
-        if ActionDispatch.verbose_redirect_logs
-          source = redirect_source_location
-
-          if source
-            "↳ #{source}"
-          end
+        if ActionDispatch.verbose_redirect_logs && (source = redirect_source_location)
+          "↳ #{source}"
         end
       end
     end
diff --git a/actionpack/lib/action_controller/railtie.rb b/actionpack/lib/action_controller/railtie.rb
index 9e4b2d9909..756295c32f 100644
--- a/actionpack/lib/action_controller/railtie.rb
+++ b/actionpack/lib/action_controller/railtie.rb
@@ -137,9 +137,7 @@ class Railtie < Rails::Railtie # :nodoc:
     end
 
     initializer "action_controller.backtrace_cleaner" do
-      ActiveSupport.on_load(:action_controller) do
-        ActionController::LogSubscriber.backtrace_cleaner = ::Rails.backtrace_cleaner
-      end
+      ActionController::LogSubscriber.backtrace_cleaner = Rails.backtrace_cleaner
     end
   end
 end
diff --git a/actionpack/lib/action_dispatch/log_subscriber.rb b/actionpack/lib/action_dispatch/log_subscriber.rb
index aaa63d3b95..bcb040bfd9 100644
--- a/actionpack/lib/action_dispatch/log_subscriber.rb
+++ b/actionpack/lib/action_dispatch/log_subscriber.rb
@@ -4,23 +4,17 @@
 
 module ActionDispatch
   class LogSubscriber < ActiveSupport::LogSubscriber
+    class_attribute :backtrace_cleaner, default: ActiveSupport::BacktraceCleaner.new
+
     def redirect(event)
       payload = event.payload
 
       info { "Redirected to #{payload[:location]}" }
 
       info do
-        message = nil
-
-        if ActionDispatch.verbose_redirect_logs
-          request = payload[:request]
-
-          request.routes.router.recognize(request) do |route|
-            message = "↳ #{route.source_location}"
-          end
+        if ActionDispatch.verbose_redirect_logs && (source = redirect_source_location)
+          "↳ #{source}"
         end
-
-        message
       end
 
       info do
@@ -33,6 +27,12 @@ def redirect(event)
       end
     end
     subscribe_log_level :redirect, :info
+
+    private
+
+     def redirect_source_location
+      backtrace_cleaner.first_clean_frame
+    end
   end
 end
 
diff --git a/actionpack/lib/action_dispatch/railtie.rb b/actionpack/lib/action_dispatch/railtie.rb
index e3ecacc9d6..23e87566ed 100644
--- a/actionpack/lib/action_dispatch/railtie.rb
+++ b/actionpack/lib/action_dispatch/railtie.rb
@@ -81,10 +81,14 @@ class Railtie < Rails::Railtie # :nodoc:
       config.action_dispatch.always_write_cookie = Rails.env.development? if config.action_dispatch.always_write_cookie.nil?
       ActionDispatch::Cookies::CookieJar.always_write_cookie = config.action_dispatch.always_write_cookie
 
-      ActionDispatch::Routing::Mapper.route_source_locations = Rails.env.development? || ActionDispatch.verbose_redirect_logs
+      ActionDispatch::Routing::Mapper.route_source_locations = Rails.env.development?
 
       ActionDispatch::Http::Cache::Request.strict_freshness = app.config.action_dispatch.strict_freshness
       ActionDispatch.test_app = app
     end
+
+    initializer "action_dispatch.backtrace_cleaner" do
+      ActionDispatch::LogSubscriber.backtrace_cleaner = Rails.backtrace_cleaner
+    end
   end
 end
diff --git a/actionpack/test/controller/log_subscriber_test.rb b/actionpack/test/controller/log_subscriber_test.rb
index 6dd6ae6207..c208d5e5dc 100644
--- a/actionpack/test/controller/log_subscriber_test.rb
+++ b/actionpack/test/controller/log_subscriber_test.rb
@@ -318,15 +318,19 @@ def test_filter_redirect_bad_uri
   end
 
   def test_verbose_redirect_logs
+    old_cleaner = ActionController::LogSubscriber.backtrace_cleaner
+    ActionController::LogSubscriber.backtrace_cleaner = ActionController::LogSubscriber.backtrace_cleaner.dup
+    ActionController::LogSubscriber.backtrace_cleaner.add_silencer { |location| !location.include?(__FILE__) }
     ActionDispatch.verbose_redirect_logs = true
 
     get :redirector
     wait
 
     assert_equal 4, logs.size
-    assert_match(/↳/, logs[2])
+    assert_match(/↳ #{__FILE__}/, logs[2])
   ensure
     ActionDispatch.verbose_redirect_logs = false
+    ActionController::LogSubscriber.backtrace_cleaner = old_cleaner
   end
 
   def test_send_data
diff --git a/actionpack/test/dispatch/routing/log_subscriber_test.rb b/actionpack/test/dispatch/routing/log_subscriber_test.rb
index b44ecf66d9..2c8e0253f6 100644
--- a/actionpack/test/dispatch/routing/log_subscriber_test.rb
+++ b/actionpack/test/dispatch/routing/log_subscriber_test.rb
@@ -26,6 +26,9 @@ def setup
   end
 
   test "verbose redirect logs" do
+    old_cleaner = ActionDispatch::LogSubscriber.backtrace_cleaner
+    ActionDispatch::LogSubscriber.backtrace_cleaner = ActionDispatch::LogSubscriber.backtrace_cleaner.dup
+    ActionDispatch::LogSubscriber.backtrace_cleaner.add_silencer { |location| !location.include?(__FILE__) }
     ActionDispatch.verbose_redirect_logs = true
 
     draw do
@@ -36,9 +39,10 @@ def setup
     wait
 
     assert_equal 3, logs.size
-    assert_match(/↳/, logs[1])
+    assert_match(/↳ #{__FILE__}/, logs[1])
   ensure
     ActionDispatch.verbose_redirect_logs = false
+    ActionDispatch::LogSubscriber.backtrace_cleaner = old_cleaner
   end
 
   private

```

2025-09-11 02:52 UTC, gmcgibbon commented on guides/source/debugging_rails_applications.md
> +Similar to both 'verbose" log settings above, this logs the source location of a redirect.
```suggestion
Similar to other verbose log settings above, this logs the source location of a redirect.
```

2025-09-11 02:52 UTC, gmcgibbon commented on guides/source/debugging_rails_applications.md
> +It is enabled by default in development. To enable in other environments, add in `application.rb` or any environment initializer:
```suggestion
It is enabled by default in development. To enable in other environments, use this configuration:
```
I don't think we need to be so specific about where it goes.

2025-09-15 18:44 UTC, dennispaagman commented
@gmcgibbon thanks for your feedback and improvements, I've implemented them as is. Does this need anything else now?

I had to put back in the `on_load` block for the backtrace cleaner in the Action Controller railtie, as it was causing issues everywhere (uninitialized constant ActionController::LogSubscriber). Do you think there's a solution for that? In other places the backtrace cleaner is also initialized in a on_load block.

2025-09-24 05:15 UTC, gmcgibbon approved these changes
Looks great! Can you fix the merge conflict? I'll merge after that.

2025-09-24 05:15 UTC, gmcgibbon commented on actionpack/lib/action_controller/railtie.rb
> +      ActiveSupport.on_load(:action_controller) do
I don't think we need this load hook, do we? This shouldn't reference `ActionController::Base`.

2025-09-25 18:01 UTC, dennispaagman commented on actionpack/lib/action_controller/railtie.rb
> +      ActiveSupport.on_load(:action_controller) do
Without it the tests fail for railties:

> NameError: uninitialized constant ActionController::LogSubscriber

see this build for example: https://buildkite.com/rails/rails/builds/121608/steps/canvas

2025-09-25 18:04 UTC, dennispaagman commented
@gmcgibbon rebased it!

2025-09-26 08:27 UTC, gmcgibbon commented on actionpack/lib/action_controller/railtie.rb
> +      ActiveSupport.on_load(:action_controller) do
Oh that's right. The require lives in base so we do need it. 👍

2025-09-26 08:28 UTC, merged

2025-09-30 11:19 UTC, dennispaagman commented
@gmcgibbon do you know if this will be part of 8.1 or the next version?

2025-09-30 12:22 UTC, dennispaagman commented
hey @gmcgibbon I was checking it out on my app running on Rails main and noticed that the redirects from routes are not working as expected. 

I think this is because the change to use a backtrace cleaner there instead of going through the router to get the source_location of the route.

I didn't fully grasp it when I applied your patch I think.

I'm not sure if it's even possible to use a backtrace cleaner there, as the routes are compiled so we're never able to figure out the source for it.

This is the backtrace for at that point in the log subscriber for a redirected route (with some `binding.irb` stuff as well), as you can see there is no entry for config/routes.rb:

<details>
<summary>backtrace (collapsed for readability)</summary>
```
> Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/irb-1.15.2/lib/irb/workspace.rb:101:in `eval'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/irb-1.15.2/lib/irb/workspace.rb:101:in `evaluate'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/irb-1.15.2/lib/irb/context.rb:591:in `evaluate_expression'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/irb-1.15.2/lib/irb/context.rb:557:in `evaluate'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/irb-1.15.2/lib/irb.rb:201:in `block (2 levels) in eval_input'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/irb-1.15.2/lib/irb.rb:512:in `signal_status'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/irb-1.15.2/lib/irb.rb:193:in `block in eval_input'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/irb-1.15.2/lib/irb.rb:272:in `block in each_top_level_statement'
<internal:kernel>:187:in `loop'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/irb-1.15.2/lib/irb.rb:269:in `each_top_level_statement'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/irb-1.15.2/lib/irb.rb:192:in `eval_input'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/irb-1.15.2/lib/irb.rb:173:in `block in run'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/irb-1.15.2/lib/irb.rb:172:in `catch'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/irb-1.15.2/lib/irb.rb:172:in `run'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/irb-1.15.2/lib/irb.rb:732:in `irb'
<internal:prelude>:5:in `irb'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/log_subscriber.rb:13:in `block in redirect'
/Users/dennis/Code/rails/activesupport/lib/active_support/broadcast_logger.rb:212:in `block in dispatch'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/logger-1.7.0/lib/logger.rb:685:in `add'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/logger-1.7.0/lib/logger.rb:721:in `info'
/Users/dennis/Code/rails/activesupport/lib/active_support/broadcast_logger.rb:218:in `block in dispatch'
/Users/dennis/Code/rails/activesupport/lib/active_support/broadcast_logger.rb:217:in `map'
/Users/dennis/Code/rails/activesupport/lib/active_support/broadcast_logger.rb:217:in `dispatch'
/Users/dennis/Code/rails/activesupport/lib/active_support/broadcast_logger.rb:129:in `info'
/Users/dennis/Code/rails/activesupport/lib/active_support/log_subscriber.rb:158:in `info'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/log_subscriber.rb:12:in `redirect'
/Users/dennis/Code/rails/activesupport/lib/active_support/subscriber.rb:138:in `call'
/Users/dennis/Code/rails/activesupport/lib/active_support/log_subscriber.rb:147:in `call'
/Users/dennis/Code/rails/activesupport/lib/active_support/notifications/fanout.rb:180:in `block in finish'
/Users/dennis/Code/rails/activesupport/lib/active_support/notifications/fanout.rb:29:in `block in iterate_guarding_exceptions'
/Users/dennis/Code/rails/activesupport/lib/active_support/notifications/fanout.rb:28:in `each'
/Users/dennis/Code/rails/activesupport/lib/active_support/notifications/fanout.rb:28:in `iterate_guarding_exceptions'
/Users/dennis/Code/rails/activesupport/lib/active_support/notifications/fanout.rb:124:in `each'
/Users/dennis/Code/rails/activesupport/lib/active_support/notifications/fanout.rb:179:in `finish'
/Users/dennis/Code/rails/activesupport/lib/active_support/notifications/fanout.rb:259:in `block in finish_with_values'
/Users/dennis/Code/rails/activesupport/lib/active_support/notifications/fanout.rb:24:in `each'
/Users/dennis/Code/rails/activesupport/lib/active_support/notifications/fanout.rb:24:in `iterate_guarding_exceptions'
/Users/dennis/Code/rails/activesupport/lib/active_support/notifications/fanout.rb:258:in `finish_with_values'
/Users/dennis/Code/rails/activesupport/lib/active_support/notifications/fanout.rb:251:in `finish'
/Users/dennis/Code/rails/activesupport/lib/active_support/notifications/instrumenter.rb:64:in `instrument'
/Users/dennis/Code/rails/activesupport/lib/active_support/notifications.rb:210:in `instrument'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/routing/redirection.rb:23:in `call'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/routing/mapper.rb:33:in `block in <class:Constraints>'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/routing/mapper.rb:62:in `serve'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/journey/router.rb:35:in `block in serve'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/journey/router.rb:86:in `block in recognize'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/journey/router.rb:66:in `each'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/journey/router.rb:66:in `recognize'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/journey/router.rb:31:in `serve'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/routing/route_set.rb:906:in `call'
/Users/dennis/Code/rails/railties/lib/rails/engine/lazy_route_set.rb:60:in `call'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/rack-3.2.1/lib/rack/static.rb:162:in `call'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/rack-3.2.1/lib/rack/tempfile_reaper.rb:20:in `call'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/rack-3.2.1/lib/rack/etag.rb:29:in `call'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/rack-3.2.1/lib/rack/conditional_get.rb:31:in `call'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/rack-3.2.1/lib/rack/head.rb:15:in `call'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/http/content_security_policy.rb:38:in `call'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/rack-session-2.1.1/lib/rack/session/abstract/id.rb:274:in `context'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/rack-session-2.1.1/lib/rack/session/abstract/id.rb:268:in `call'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/middleware/cookies.rb:708:in `call'
/Users/dennis/Code/rails/activerecord/lib/active_record/migration.rb:671:in `call'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/middleware/callbacks.rb:31:in `block in call'
/Users/dennis/Code/rails/activesupport/lib/active_support/callbacks.rb:101:in `run_callbacks'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/middleware/callbacks.rb:30:in `call'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/middleware/executor.rb:20:in `call'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/Users/dennis/Code/rails/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:31:in `call'
/Users/dennis/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/web-console-4.2.1/lib/web_console/middleware.rb:132:in `call_app'
/Users/dennis/.local/share/mise/ [...]

2025-09-30 19:44 UTC, chaadow commented on guides/source/configuring.md
> +Specifies if source locations of redirects should be logged below relevant log lines. By default, the flag is `true` in development and `false` in all other environments.
Sorry, by reading this, and I already have an application,  I understand that in development I don't have to do anything or set anything in `development.rb`,
But by reading the PR, I need to enable it manually in `config/environments/development.rb` 

Maybe something like `By default in new applications, the flag is `true`` would make more sense.

2025-09-30 19:45 UTC, chaadow commented on guides/source/configuring.md
> +Specifies if source locations of redirects should be logged below relevant log lines. By default, the flag is `true` in development and `false` in all other environments.
<img width="628" height="102" alt="Image" src="https://github.com/user-attachments/assets/414aa9ca-0739-4007-8d24-4403424b9b10" />

2025-10-01 16:36 UTC, gmcgibbon commented
@dennispaagman I can't guarantee this will be included in the upcoming release of 8.1. I'll look into this problem next week. Thanks for following up.

2025-10-01 16:37 UTC, gmcgibbon commented on guides/source/configuring.md
> +Specifies if source locations of redirects should be logged below relevant log lines. By default, the flag is `true` in development and `false` in all other environments.
It should be turned on automatically in development. Sorry, I'll look into this too.

2025-10-12 13:31 UTC, gmcgibbon commented on guides/source/configuring.md
> +Specifies if source locations of redirects should be logged below relevant log lines. By default, the flag is `true` in development and `false` in all other environments.
This is expected because the option to turn it on is generated with new applications, and not enabled in new ones by default. All other verbose configs act this way too, so this is correct. I'll see if we can clarify the messaging here. Thanks for the feedback.

2025-10-12 14:52 UTC, gmcgibbon commented on guides/source/configuring.md
> +Specifies if source locations of redirects should be logged below relevant log lines. By default, the flag is `true` in development and `false` in all other environments.
Looks like other similar features are documented this way. I think we can clarify this in the upgrade notes instead of the docs added in this PR.