If a job fails due to an error, it is discarded, and don't re-raise.
rails/rails pull request #52557
Opened 2024-08-09 23:29 UTC by ioquatix

### Motivation / Background

There are three cases for error handling:

1/ Normal job submission, and the job executes successfully.

```
::ActiveJob::Base.execute(GoodJob.new.serialize)
```

2/ Normal job submission, but the job fails, and there is no appropriate error handler (`retry_on`). The job is discarded as expected, and the error is logged, but this method still raises an exception.

```ruby
::ActiveJob::Base.execute(BadJob.new.serialize)
```

3/ Bad job submission (or other internal error). The job is not processed, an error is raised, but there is no log.

```ruby
::ActiveJob::Base.execute({})
```

The problem is, the error raised by (2) is logged, but the error raised by (3) is not.

A job server may wrap `ActiveJob::Base.execute` like so:

```ruby
# Execute the given job.
while job = read_job
	begin
		::ActiveJob::Base.execute(job)
	rescue => error
		log_error(error)
	end
end
```

In case (2) above, this will lead to two log messages being emitted for the failure, one from ActiveJob and one from the Job runner. This is not ideal from a usability point of view, ideally only one log message should be emitted.

One way to solve the problem is this:

```ruby
# Execute the given job.
while job = read_job
	begin
		::ActiveJob::Base.execute(job)
	rescue => error
		# Ignore errors, logged by ActiveJob.
	end
end
```

Now ActiveJob is fully responsible for logging. However, there are some situations as shown in case (3) where `ActiveJob::Base.execute` can raise errors which are not logged. That is problematic as that would result in a silent failure which is a very bad user experience.

### Detail

This proposal changes case (2) to not re-raise the exception if the job is not retried. The error is still logged by ActiveJob, but the error is not propagated up, as it's normal and expected that the job is discarded in that case.

### Checklist

Before submitting the PR make sure the following are checked:

* [ ] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

2024-08-09 23:46 UTC, ioquatix commented
As a work-around, I extracted the method and ignored the errors from the job:

https://github.com/socketry/async-job-adapter-active_job/commit/4187de220ff57154577273b6b307aa7e34ccba7e

Probably not ideal, but it seemed to work.

See the test fixtures: https://github.com/socketry/async-job-adapter-active_job/blob/main/test/async/job/adapter/active_job/executor.rb

2024-08-10 00:31 UTC, rafaelfranca requested changes
I don't think it is good idea to just silently discard the job when the user didn't handle it. Need to raise in that case.

One of the tenants of Active Job is that the behavior is defined by the framework, not the job runner. This is inverting that tenant. The fact that the developer will know about the non-handled failures is not up the the job runner. That isn't something I want to delegate.

2024-08-10 00:37 UTC, rafaelfranca commented
I'm also seeing something inverted in the design of the code you shared from the runner. The runner should never call  `::ActiveJob::Base.execute(job)` directly outside of the [QueueAdapter](https://github.com/rails/rails/blob/main/activejob/lib/active_job/queue_adapters/async_adapter.rb#L70)

2024-08-10 00:41 UTC, rafaelfranca commented
Although, I'm more than happy to raise a different exception when `::ActiveJob::Base.execute({})` is raised so you can rescue that one and log if you want.

2024-08-10 01:58 UTC, bensheldon commented
I just want to flag that this likely will interact poorly with adapters/runners that aren't doing elaborate bookkeeping to ensure that retried jobs are not treated as newly enqueued jobs (most adapters). I imagine they would mark the initial job execution as successful if no error is raised to them.

As counterexample, GoodJob relies on the exception being raised to know that the current job execution errored, and that is the trigger to dig around in a pile of thread local variables (set in instrumentation subscribers, cause there is no other way) to see if there was a retry (or discard) during the current job execution. GoodJob is then able to piece together what happened and ensure the current (errored/discarded) job execution is appropriately updated and the retry appropriately scheduled. It's very adapter-specific. 

My ideal would be that `ActiveJob::Base.execute` returned to the adapter/runner a result object that contained all the details (whether the job errored, or was discarded, and the backend_job_id of any job that is reenqueued), and use exceptions only to indicate something went very wrong outside of the job itself.

2024-08-10 08:24 UTC, ioquatix commented
> I don't think it is good idea to just silently discard the job when the user didn't handle it. Need to raise in that case.

That's correct, and Rails currently logs when it's discarding the job.

> One of the tenants of Active Job is that the behavior is defined by the framework, not the job runner.

Yes, that seems very reasonable to me. I'm just trying to deliver the job data to `ActiveJob::Base.execute` and hope that it will handle all the policy decisions.

> The fact that the developer will know about the non-handled failures is not up the the job runner.

Yes, agreed, that's exactly my point by this PR.

> I'm also seeing something inverted in the design of the code you shared from the runner. 

I'm not sure I'm following you here, the `Executor` is effectively the queue adapter. Can you explain what you think should change in more detail?

> Although, I'm more than happy to raise a different exception when `::ActiveJob::Base.execute({})` is raised so you can rescue that one and log if you want.

If ActiveJob decides to drop the job, due to an error, or for any other reason, it's up to ActiveJob to log that however it wants. However, I don't think this error should propagate up to the job runner/adapter. Otherwise, it looks like an unhandled error. But as you've outlined, this error HAS been handled, explicitly, by opting to drop the job and log that fact.

> I just want to flag that this likely will interact poorly with adapters/runners that aren't doing elaborate bookkeeping to ensure that retried jobs are not treated as newly enqueued jobs (most adapters). I imagine they would mark the initial job execution as successful if no error is raised to them.

As discussed, I agree with the position that all job retry policy should be determined by ActiveJob. Therefore, I don't believe that "retried jobs are not treated as newly enqueued jobs" can be handled with the current return value / exception handling of `ActiveJob::Base.execute`. Maybe that's your point? In other words, I agree with that, and to Rafael's point, his position seems to be that you shouldn't need to know about it as the job will get requeued IFF ActiveJob's implementation decides it's appropriate.

2024-08-10 08:32 UTC, rosa commented
> This proposal changes case (2) to not re-raise the exception if the job is not retried. The error is still logged by ActiveJob, but the error is not propagated up, as it's normal and expected that the job is discarded in that case.

Wouldn't this case already be covered by `discard_on` if you know your job might fail with some exception that you know you don't need to handle because it's expected? I can't see how silently discarding jobs upon _any_ exceptions is desirable. In many cases you'd want to have the failed job so you can investigate, fix, retry manually... I feel I'm missing something here.

2024-08-10 08:36 UTC, rosa commented
> Therefore, I don't believe that "retried jobs are not treated as newly enqueued jobs" can be handled with the current return value / exception handling of `ActiveJob::Base.execute`. Maybe that's your point?

FWIW, Solid Queue treats retried jobs as newly enqueued jobs (except if they have been automatically retried, the serialized data includes the relevant values for `executions` and `exception_executions)`. This is just for simplicity, but it could be easily changed to do something else 🤔 Why do you think this can't be done?

2024-08-10 09:26 UTC, ioquatix commented
Not sure if you are addressing the question to me, but:

> FWIW, Solid Queue treats retried jobs as newly enqueued jobs

That's how it works (as documented) and how I've implemented it too.

2024-08-10 09:27 UTC, ioquatix commented
> I can't see how silently discarding jobs upon any exceptions is desirable.

I agree with that, right now the behaviour, as I understand it is to log the exception and discard the job. Is that not correct?

2024-08-10 09:46 UTC, ioquatix commented
Maybe this real code example helps:

```ruby
#!/usr/bin/env ruby

require 'active_job'

class GoodJob < ActiveJob::Base
	queue_as :default
	
	def perform
		puts 'Hello, world!'
	end
end

class BadJob < ActiveJob::Base
	queue_as :default
	
	def perform
		raise 'This is a bad job!'
	end
end

class RetryJob < ActiveJob::Base
	queue_as :default
	retry_on StandardError, wait: 5.seconds, attempts: 3
	
	def perform
		raise 'This is a bad job!'
	end
end

def job_server_execute(job_data)
	ActiveJob::Base.execute(job_data)
rescue => error
	$stderr.puts error.full_message
end

$stdout.puts "## Case 1: Successful Job\n\n```"
job_data = GoodJob.new.serialize
job_server_execute(job_data)
$stdout.puts "```\n\n"

$stdout.puts "## Case 2: Bad Job\n\n```"
job_data = BadJob.new.serialize
job_server_execute(job_data)
$stdout.puts "```\n\n"

$stderr.puts "## Case 3: Error in Job Server\n\n```"
job_data = {'job_class' => 'DoesNotExistJob'}
job_server_execute(job_data)
$stdout.puts "```\n\n"

$stdout.puts "## Case 4: Retry Job\n\n```"
job_data = RetryJob.new.serialize
job_server_execute(job_data)
$stdout.puts "```\n\n"
```

## Current Implementation of ActiveJob

### Case 1: Successful Job

```
[ActiveJob] [GoodJob] [61fbc6aa-d43d-48ba-8eeb-957e37698155] Performing GoodJob (Job ID: 61fbc6aa-d43d-48ba-8eeb-957e37698155) from Async(default) enqueued at 2024-08-10T09:42:24.645853933Z
Hello, world!
[ActiveJob] [GoodJob] [61fbc6aa-d43d-48ba-8eeb-957e37698155] Performed GoodJob (Job ID: 61fbc6aa-d43d-48ba-8eeb-957e37698155) from Async(default) in 7.81ms
```

### Case 2: Bad Job

```
[ActiveJob] [BadJob] [72cbbbf5-425e-4908-b184-d2f1792c064a] Performing BadJob (Job ID: 72cbbbf5-425e-4908-b184-d2f1792c064a) from Async(default) enqueued at 2024-08-10T09:42:24.655888835Z
[ActiveJob] [BadJob] [72cbbbf5-425e-4908-b184-d2f1792c064a] Error performing BadJob (Job ID: 72cbbbf5-425e-4908-b184-d2f1792c064a) from Async(default) in 0.07ms: RuntimeError (This is a bad job!):
/home/samuel/Developer/socketry/async-job-adapter-active_job/examples/logging/test.rb:17:in `perform'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/execution.rb:68:in `block in _perform_job'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/samuel/.gem/ruby/3.3.4/gems/i18n-1.14.5/lib/i18n.rb:351:in `with_locale'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:130:in `instance_exec'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:130:in `instance_exec'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:141:in `run_callbacks'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/execution.rb:67:in `_perform_job'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/instrumentation.rb:32:in `_perform_job'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/execution.rb:51:in `perform_now'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/instrumentation.rb:26:in `block in perform_now'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/instrumentation.rb:40:in `block in instrument'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/notifications.rb:210:in `block in instrument'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/notifications.rb:210:in `instrument'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/instrumentation.rb:39:in `instrument'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/instrumentation.rb:26:in `perform_now'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/logging.rb:32:in `block in perform_now'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/tagged_logging.rb:138:in `block in tagged'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/tagged_logging.rb:38:in `tagged'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/tagged_logging.rb:138:in `tagged'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/logging.rb:39:in `tag_logger'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/logging.rb:32:in `perform_now'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/execution.rb:29:in `block in execute'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:101:in `run_callbacks'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/execution.rb:27:in `execute'
/home/samuel/Developer/socketry/async-job-adapter-active_job/examples/logging/test.rb:31:in `job_server_execute'
/home/samuel/Developer/socketry/async-job-adapter-active_job/examples/logging/test.rb:43:in `<top (required)>'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/cli.rb:455:in `exec'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/cli.rb:35:in `dispatch'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/cli.rb:29:in `start'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/exe/bundle:28:in `block in <top (required)>'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/exe/bundle:20:in `<top (required)>'
/home/samuel/.rubies/ruby-3.3.4/bin/bundle:25:in `load'
/home/samuel/.rubies/ruby-3.3.4/bin/bundle:25:in `<main>'
/home/samuel/Developer/socketry/async-job-adapter-active_job/examples/logging/test.rb:17:in `perform': This is a bad job! (RuntimeError)
	from /home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/execution.rb:68:in `block in _perform_job'
	from /home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
	from /home/samuel/.gem/ruby/3.3.4/gems/i18n-1.14.5/lib/i18n.rb:351:in `with_locale'
	from /home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
	from /home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:130:in `instance_exec'
	from /home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
	from /home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
	from /home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
	from /home/samuel/.gem/ruby/3.3.4/gems/activesu [...]

2024-08-10 09:56 UTC, ioquatix commented
I will work on a example script which demonstrates the exact issue (and proposed fix) so we have something concrete to work from.

2024-08-10 10:43 UTC, ioquatix commented
Okay, here is my example:

```ruby
#!/usr/bin/env ruby

require 'active_job'

if ARGV.include? '--proposed'
  # This is not a perfect proposal. The complexities of the instrumentation are tied up with `#perform_now`.
  # Determing the best way to handle this is a larger discussion.
  require 'active_job/execution'
  module ActiveJob
    module Execution
      module ClassMethods
        def execute(job_data) # :nodoc:
          ActiveJob::Callbacks.run_callbacks(:execute) do
            job = deserialize(job_data)
            
            begin
              job.perform_now
            rescue => error
              # Ignore - it was already logged.
            end
          end
        end
      end
    end
  end
end

class GoodJob < ActiveJob::Base
  queue_as :default
  
  def perform
    puts 'Hello, world!'
  end
end

class BadJob < ActiveJob::Base
  queue_as :default
  
  def perform
    raise 'This is a bad job!'
  end
end

class RetryJob < ActiveJob::Base
  queue_as :default
  retry_on StandardError, wait: 5.seconds, attempts: 3
  
  def perform
    raise 'This is a bad job!'
  end
end

def job_server_execute(job_data)
  ActiveJob::Base.execute(job_data)
rescue => error
  # (Q) Should we log this here? Did Rails already log it?
  $stderr.puts error.full_message
end

$stdout.puts "### Case 1: Successful Job\n\n```"
job_data = GoodJob.new.serialize
job_server_execute(job_data)
$stdout.puts "```\n\n"

$stdout.puts "### Case 2: Bad Job\n\n```"
job_data = BadJob.new.serialize
job_server_execute(job_data)
$stdout.puts "```\n\n"

$stderr.puts "### Case 3: Error in Job Server\n\n```"
job_data = {'job_class' => 'DoesNotExistJob'}
job_server_execute(job_data)
$stdout.puts "```\n\n"

$stdout.puts "### Case 4: Retry Job\n\n```"
job_data = RetryJob.new.serialize
job_server_execute(job_data)
$stdout.puts "```\n\n"
```

## Current Output

### Case 1: Successful Job

```
[ActiveJob] [GoodJob] [a71c0694-1153-4688-a6ad-978921418516] Performing GoodJob (Job ID: a71c0694-1153-4688-a6ad-978921418516) from Async(default) enqueued at 2024-08-10T10:40:50.490666020Z
Hello, world!
[ActiveJob] [GoodJob] [a71c0694-1153-4688-a6ad-978921418516] Performed GoodJob (Job ID: a71c0694-1153-4688-a6ad-978921418516) from Async(default) in 8.27ms
```

### Case 2: Bad Job

```
[ActiveJob] [BadJob] [a5a6df71-b782-4893-a9a2-46b33490b357] Performing BadJob (Job ID: a5a6df71-b782-4893-a9a2-46b33490b357) from Async(default) enqueued at 2024-08-10T10:40:50.501977119Z
[ActiveJob] [BadJob] [a5a6df71-b782-4893-a9a2-46b33490b357] Error performing BadJob (Job ID: a5a6df71-b782-4893-a9a2-46b33490b357) from Async(default) in 0.07ms: RuntimeError (This is a bad job!):
/home/samuel/Developer/socketry/async-job-adapter-active_job/examples/logging/test.rb:40:in `perform'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/execution.rb:68:in `block in _perform_job'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/samuel/.gem/ruby/3.3.4/gems/i18n-1.14.5/lib/i18n.rb:351:in `with_locale'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:130:in `instance_exec'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:130:in `instance_exec'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:141:in `run_callbacks'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/execution.rb:67:in `_perform_job'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/instrumentation.rb:32:in `_perform_job'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/execution.rb:51:in `perform_now'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/instrumentation.rb:26:in `block in perform_now'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/instrumentation.rb:40:in `block in instrument'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/notifications.rb:210:in `block in instrument'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/notifications.rb:210:in `instrument'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/instrumentation.rb:39:in `instrument'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/instrumentation.rb:26:in `perform_now'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/logging.rb:32:in `block in perform_now'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/tagged_logging.rb:138:in `block in tagged'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/tagged_logging.rb:38:in `tagged'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/tagged_logging.rb:138:in `tagged'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/logging.rb:39:in `tag_logger'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/logging.rb:32:in `perform_now'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/execution.rb:29:in `block in execute'
/home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:101:in `run_callbacks'
/home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/execution.rb:27:in `execute'
/home/samuel/Developer/socketry/async-job-adapter-active_job/examples/logging/test.rb:54:in `job_server_execute'
/home/samuel/Developer/socketry/async-job-adapter-active_job/examples/logging/test.rb:67:in `<top (required)>'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/cli.rb:455:in `exec'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/cli.rb:35:in `dispatch'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/cli.rb:29:in `start'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/exe/bundle:28:in `block in <top (required)>'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/home/samuel/.rubies/ruby-3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/exe/bundle:20:in `<top (required)>'
/home/samuel/.rubies/ruby-3.3.4/bin/bundle:25:in `load'
/home/samuel/.rubies/ruby-3.3.4/bin/bundle:25:in `<main>'
/home/samuel/Developer/socketry/async-job-adapter-active_job/examples/logging/test.rb:40:in `perform': This is a bad job! (RuntimeError)
	from /home/samuel/.gem/ruby/3.3.4/gems/activejob-7.2.0/lib/active_job/execution.rb:68:in `block in _perform_job'
	from /home/samuel/.gem/ruby/3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
	from /home/samuel/.gem/ruby/3.3.4/gems/i18n-1.14.5/ [...]

2024-08-10 11:01 UTC, ioquatix commented
(Also IMHO, `rescue Exception` is almost always a bug - you probably shouldn't be trying to rescue `SystemExit`, `NoMemoryError` or `fatal` - use `ensure` instead if you need to always execute something on exit from a given block).

2024-08-10 16:17 UTC, bensheldon commented
Sorry for the wall of text. TLDR:

- I think I'm ok with not raising exceptions from Active Job
- I really need a result object though
- "Discard" is a hella overloaded term and it makes it easy to confuse stuff ❤️ 

> 1. Is it the responsibility of ActiveJob to log when a job fails to deserialize?

Yes. I consider a job-deserialization failure not-of-the-adapter, and thus of Active Job. Because the adapter did it's part of giving the serialized job data.

> 2. Is the default policy to drop and log a job on any kind of failure?
> 3. If a job is dropped due to an exception, should that exception be re-raised?

I think "drop" is undefined. And I assume you mean "Active Job's policy". There's some discussion in https://github.com/rails/rails/pull/48010#issuecomment-1520804313

I'm ok if I assume the intent of this statement is something like Active Job will never raise an exception to the adapter. With the implication that:

- Adapters only retry if there is an exceptional exception (or `Exception`)
- Adapters only allow retry jobs via Active Job interface (implicit)

Most adapters, currently, will re-run the job on an exception being raised (an exception being raised is the only communication channel... that isn't poking around in instrumentation subscribers)

> 4. Are there any alternatives to `retry_on` and `discard_on`?

Yes. `ActiveJob::Base#retry_job` will re-enqueue the current job (truly, it enqueues another job with the same job parameters and is up to the adapter to figure out whatever that means); it's possible to call multiple times during job execution and isn't necessary for the current job execution to error.

And I'll flag that `"discarded"` is a highly overloaded term. I think the conclusion of #48010 is that "discard" means:

- A job that has errored and not been retried
- A job that has errored and exhausted retries
- A job that has errored and been discarded via the `discard_on` handler

So I think when you write "drop" I think you mean "discard" based on the expansive definition.

Sidenote: In the practice of operating a queue, I think many folks try to differentiate between "We have intentionally decided to accept these known job exceptions and not retry them and farewell to them" and "We have never seen this exception before or rarely and we should isolate the job for later inspection and remediation". #48010 called both of those "discard", and I think it makes it harder to talk with precision about this stuff.

> 5. Should the job server wrap ActionJob::Base.execute(job_data) with exception handling and logging? With the current implementation, if so: in case 2, the error is logged twice, if not, in case 3 the error won't be logged at all.
> 6. As Rafael said, all policy should be implemented by ActiveJob. So I believe that ActiveJob::Base.execute(job_data) should not raise an exception in normal operation, including job failure which results in the job being discarded. Is this the direction we want to go in, or is there an alternative?

I'm ok with not raising an exception; I would be very happy if the adapter receives a result object so it can persist what happened (and display that in a dashboard, etc.)

As for what the job server should do... I think that's on the job server. 

> 7. As a specific example, how should {"job_class" => "bad"} be handled? Who is responsible for logging the error, handling the failure, etc and should this job be retried or discarded?

Active Job should raise a `ActiveJob::DeserializationError`. The application could define a `retry_on(ActiveJob::DeserializationError)` (with or without a block) or `discard_on ActiveJob::DeserializationError`. If they don't, Active Job should log the error, report it, and in my ideal world, return a result object back to the adapter that says "this job errored with this error".

Sidenote: this deserialization error would happen before the job began performing in an ExecutionWrapper so it won't go to the Rails `error_reporter`. If the job starts performing, any exception in there would also go to the `erorr_reporter` which is another wrinkle if you're trying to avoid duplicate error logging/reports.

> you probably shouldn't be trying to rescue `SystemExit`

This is a place where correctness conflicts with practicality. Not infrequently, people are adapting scripts into jobs, and being able to handle _anything_ can help. Example: https://github.com/bensheldon/good_job/issues/1384

2024-08-10 17:12 UTC, bensheldon commented
In case it's helpful, GoodJob currently identifies [6 different kinds](https://github.com/bensheldon/good_job/blob/a61fc09cdc06ba89a9615da90778459f13a837a8/app/models/concerns/good_job/error_events.rb#L9-L16) of "error events":

- `interrupted`: when a job is SIGKILLed or otherwise uncleanly exited. Identified after the fact when the job is (re-)executed and the job is found to be in an un-resolved state.
- `unhandled`: when an exception is bubbled up to the adapter and it can't be associated with a retry or discard event.
- `handled`: this is the weird one. I think `rescue_from` used on its own will cause the exception to be _returned_ from `ActiveJob::Base.execute`, rather than raised.
- `retried`: when there is a retry event
- `retry_stopped`: when the retry execution count is exhausted
- `discarded`: when `discard_on` is used

The logic for identifying these events lives [here](https://github.com/bensheldon/good_job/blob/a61fc09cdc06ba89a9615da90778459f13a837a8/app/models/good_job/job.rb#L599-L615) (except for `interrupted`).

2024-08-10 20:15 UTC, rosa commented
> Sidenote: In the practice of operating a queue, I think many folks try to differentiate between "We have intentionally decided to accept these known job exceptions and not retry them and farewell to them" and "We have never seen this exception before or rarely and we should isolate the job for later inspection and remediation". https://github.com/rails/rails/pull/48010 called both of those "discard", and I think it makes it harder to talk with precision about this stuff.

Aha! Thanks @bensheldon! This is the context I was missing here. I wasn't aware that _discard_ was so overloaded and confusing, sorry. All this time, I've been referred to _discard_ as: 

> A job that has errored and been discarded via the _discard_on_ handler

From your definitions above. 

> Sidenote: In the practice of operating a queue, I think many folks try to differentiate between "We have intentionally decided to accept these known job exceptions and not retry them and farewell to them" and "We have never seen this exception before or rarely and we should isolate the job for later inspection and remediation". https://github.com/rails/rails/pull/48010 called both of those "discard", and I think it makes it harder to talk with precision about this stuff.

Agree 100%. 

> I think I'm ok with not raising exceptions from Active Job
> I really need a result object though

Yes, same. If there's no exception raised, I need a result object too 😅 

I'm still not completely sold on this change, though 🤔  I'd emphasize what @bensheldon said: 

> I just want to flag that this likely will interact poorly with adapters/runners that aren't doing elaborate bookkeeping to ensure that retried jobs are not treated as newly enqueued jobs (most adapters). I imagine they would mark the initial job execution as successful if no error is raised to them.

This is true, and not sure if it's worth forcing all adapters to conform to this change just to avoid the double logging of an error 🤔

2024-08-10 23:25 UTC, ioquatix commented
Thanks both for all the discussion. It has been extremely helpful.

From my point of view, I'm just trying to feed data into ActiveJob, and I don't have a lot of historical context (in other words I'm pretty naive). When I saw the double logging, I felt it was a bad user experience (confusing at best, misleading at worst) and wanted to do something about it.

From my understanding, there are three ways I could choose to design this:

```ruby
# 1/ If an exception is raised, the system blows up.
def dequeue_job(job_data)
  ActiveJob::Base.execute(job_data)
end

# 2/ If an exception is raised, it gets logged.
def dequeue_job(job_data)
  ActiveJob::Base.execute(job_data)
rescue => error
  log(error)
end

# 3/ If an exception is raised, it gets ignored.
def dequeue_job(job_data)
  ActiveJob::Base.execute(job_data)
rescue => error
  # Ignore.
end
```

Option (2) is the only safe approach. As shown, today, there are plenty of things that can break due to bad input data, during deserialization or other unrelated processing, and **currently** ActiveJob is not handling or logging these errors (AFAIK). Please correct me if I'm wrong.

In other words, there are two groups of errors being raised: Those which have been handled by ActiveJob as part of normal job processing (and have been logged by ActiveJob) and those which come from unexpected behaviour in the program. We will never rule out the latter completely.

I believe the best way for us to solve this problem is to establish (and ideally document) clearly what the default behaviour should be when a job fails with an exception which does not match any `retry_on` or `discard_on` blocks.

The current implementation behaves very similarly to this default:

```
class MyJob
  discard_on(Exception) do
    raise
  end
end
```

Is this a desirable default?

2024-08-12 15:35 UTC, rafaelfranca commented
> Is this a desirable default?

Yes. That is definitely the desirable behavior. All the bult-in Active Job adapters, for Resque, Sidekiq, etc are build using this design in mind. That is why I said the design of your adapter isn't following the design of our adapters.

I don't think we will stop raising an exception and change to return a result object. At least not without a good reason to. And so far, I don't see any good reason.

Although, I do think `::ActiveJob::Base.execute({})` should raise an specific error that the adapter can chose to rescue if they want to.

2024-11-16 10:52 UTC, byroot commented
I think we can close?

2024-11-16 10:52 UTC, closed without merging