Add section for editor integrations to in getting started
rails/rails pull request #52979
Opened 2024-09-19 16:13 UTC by vinistock

### Motivation / Background

In #50453, it was proposed to include a language server with Rails by default. We were already working on the [Rails addon for the Ruby LSP](https://github.com/Shopify/ruby-lsp-rails) and at the time believed that Rails was the place for it to live.

After several experiments with different approaches, we found a way to extract runtime information from Rails without the need to implement anything inside of Rails itself. This was important to us since development tools can be released at a more aggressive cadence.

Despite not including the language server related code inside the Rails codebase, we should still provide documentation on setting up the development environment and getting editor integrations that help people building with Rails be as productive as they can be.

We have just finished a complete revamp of the [Ruby LSP documentation](https://shopify.github.io/ruby-lsp), which includes a section on the [Rails addon](https://shopify.github.io/ruby-lsp/rails-addon.html).

Additionally, we just shipped support for [request delegation in ERB](https://shopify.github.io/ruby-lsp/#erb-support). I'm quite excited about it as it makes all of the rich features language servers provide (like completion, definition, hover, etc) work in the embedded Ruby portion of the file, but also in the HTML parts of the file (including support for JavaScript and CSS inside relevant attributes).

### Detail

This PR simply includes a new section in getting started, with a few sentences about setting up editor integrations with the Ruby LSP.

Based on what the team told me, this part of the guides are due for a content review, so I didn't invest a lot of effort and just added a brief explanation with the relevant links.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

2024-09-19 16:28 UTC, andyw8 commented on guides/source/getting_started.md
> +----------------------------
```suggestion
---------------------------------------------
```

2024-09-19 19:12 UTC, MatheusRich commented on guides/source/getting_started.md
> +showing documentation on hover and many others.
```suggestion
To get the most out of your code editor when working with Rails, you can use a language
server to provide integrations and rich features such as go to definition, completion,
showing documentation on hover and many others.
```

2024-09-19 19:12 UTC, MatheusRich approved these changes
Small suggestion, but feel free to ignore.

2024-09-20 10:54 UTC, p8 requested changes

2024-09-20 10:54 UTC, p8 commented on guides/source/getting_started.md
> +Developer environment and editor integrations
For [headings,](https://guides.rubyonrails.org/ruby_on_rails_guides_guidelines.html#headings), we capitalize all words except prepositions, conjunctions, internal articles, and forms of the verb "to be":
```suggestion
Developer Environment and Editor Integrations
```

2024-09-20 10:54 UTC, p8 commented on guides/source/getting_started.md
> +showing documentation on hover and many others.
We try to use the Oxford Comma.
```suggestion
showing documentation on hover, and many others.
```

2024-09-20 10:54 UTC, p8 commented on guides/source/getting_started.md
> +server to provide integrations and rich features such as go to definition, completion,
Maybe also link to a LSP definition?
```suggestion
To get the most out of your code editor when working with Rails, you can use a [language
server](https://en.wikipedia.org/wiki/Language_Server_Protocol) to provide integrations and
rich features such as go to definition, completion,
```

2024-09-20 13:06 UTC, matthewd commented
This is so far from being a reasonable change that I can barely see that point from here.

The first three things we need to tell someone who's getting started are _not_: "What is Rails?", "Ruby LSP is useful", "How to install Rails & create an application".

It also reads far too much like an advertisement, even before considering the irony of this section immediately following a sentence that says "Rails has opinions [..] rather than [..] you specify minutiae".

We do want to recommend Ruby LSP as a tool, but that's going to need to take a very different from from this PR.

2024-09-20 13:25 UTC, vinistock commented
@matthewd my goal was to get this change going, but that doesn't mean the placement of the section or content are the most adequate. I was hoping to get feedback from maintainers and the community.

If you have strong feelings about it, can you be more specific with what you're looking for? What would be the appropriate section to put this in? I'm happy to move it anywhere. The only reason I put it there is because the next section immediately mentions dev containers, but we can move it anywhere else.

And do you have an example of the kind of content you are looking for?

I didn't think the Rails guides would want to fully replicate the Ruby LSP's own docs or have a very extensive section on editor tooling and language servers (especially considering the fact that this section of the guides are due for a content review), so it made sense to me to just recommend the tool and link to the more comprehensive content.

My approach was trying to communicate to the reader why they would care about a language server. How would you phrase it?

2024-09-24 18:11 UTC, vinistock commented
Chatted with @rafaelfranca about the approach. I changed this for a tip right below the dev containers one and made the text to be non-specific to the Ruby LSP, but instead mention only editor integrations.

2024-10-03 05:55 UTC, zzak commented
Still feels too early for me. How about around [say "Hello", Rails](https://75e5d8af.rails-docs-preview.pages.dev/guides/getting_started#say-hello-rails), where we reach the point it's time to open an editor and actually touch code. :thinking: 

It's also interesting there is no point here we talk about how to even edit these files, like we're assuming a lot more than I expected. For example, RailsGirls has a whole page for setting up the [tools](https://railsgirls.jp/tools) and environment, and I know they have a whole session dedicated to this before anyone writes any code.

2024-10-03 13:39 UTC, p8 commented
Having a single guide for setting up your environment is something the Documentation team has discussed as well.

2025-01-07 16:43 UTC, closed without merging