Add login_as(user) testing helper when generating authentication
rails/rails pull request #53708
Opened 2024-11-22 13:05 UTC by gobijan

### Motivation / Background

This Pull Request has been created because the generated authentication logic does not offer a way to test when a user is authenticated. There is a discussion going in here I initialized: #53207
So this PR adds a `SessionTestHelper` module with `sign_in_as(user)` and `sign_out` test helpers when
running `rails g authentication`. This simplifies authentication in integration tests.

### Detail

This Pull Request changes the generator for authentication to add described test helpers.

### Additional information

There were a few discussions how to do it best and for now I settle with the approach from the PR.

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [X] Tests are added or updated if you fix a bug or add a feature.
* [X] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

2024-12-04 21:52 UTC, stevepolitodesign commented
Would there be any value in adding a complimentary `logout_as` helper too?

2024-12-04 21:58 UTC, stevepolitodesign commented on railties/lib/rails/generators/rails/authentication/authentication_generator.rb
> +    end
I had success with `logout` locally.

```suggestion
    def login_as(user)
      session = user.sessions.create!
      Current.session = session
      request = ActionDispatch::Request.new(Rails.application.env_config)
      cookies = request.cookie_jar
      cookies.signed[:session_id] = { value: session.id, httponly: true, same_site: :lax }
    end
    
    def logout
      Current.session.destroy
      request = ActionDispatch::Request.new(Rails.application.env_config)
      cookies = request.cookie_jar
      cookies.delete(:session_id)
    end
```

2024-12-09 21:46 UTC, dhh commented
Yes, this is good. We have a helper like this in our projects as well, which is very similar. But let's name these "sign_in_as" and "sign_out". And then let's instantiate the cookie jar directly. Here's our method:

```ruby
def sign_in_as(user)
  Current.session = user.sessions.create!

  ActionDispatch::TestRequest.create.cookie_jar.tap do |cookie_jar|
    cookie_jar.signed[:session_id] = Current.session.id
    cookies[:session_id] = cookie_jar[:session_id]
  end
end
```

2024-12-09 21:50 UTC, dhh commented
Also, I would actually recommend that we add this in a dedicated file called SessionTestHelper and then include that via:

```ruby
class ActionDispatch::IntegrationTest
  include SessionTestHelper
end
```

Listed below the `ActiveSupport::TestCase` recommendation.

2025-01-17 15:23 UTC, MatheusRich commented
@gobijan do you still plan to work on this? I can take over this task and co-author you

2025-01-17 15:55 UTC, gobijan commented
I had serious problems getting the test suite to run tbh. Locally didn't work. The devcontainer environment was bugged and I had to rely on Github PR which was kind of unsatisfactory. 
Would you mind pointing me in the direction why my tests are failing? I'd love to collaborate on this and need help with the rails test suite.

2025-01-17 16:25 UTC, MatheusRich commented
@gobijan It should be pretty straightforward:

```sh
cd railties
bundle
bin/test
```

If that doesn't work, please ask for help in the Discord server.

2025-01-18 11:33 UTC, gobijan commented
I just refactored the PR according to @dhh 

The change:
- Extract test helpers from test_helper.rb into SessionTestHelper module
- Rename login_as to sign_in_as for consistent terminology
- Add sign_out helper method for testing user logout flows
- Update authentication generator and tests accordingly

2025-01-18 15:07 UTC, flavorjones requested changes
I made some comments that should get you to green in CI

2025-01-18 15:07 UTC, flavorjones commented on railties/test/generators/authentication_generator_test.rb
> +    assert_file "test/test_helper.rb" do |content|
In order for this to work in this test, you'll need something like this in the `setup` method:

```patch
diff --git a/railties/test/generators/authentication_generator_test.rb b/railties/test/generators/authentication_generator_test.rb
index 93653e8c..4fbabd58 100644
--- a/railties/test/generators/authentication_generator_test.rb
+++ b/railties/test/generators/authentication_generator_test.rb
@@ -13,6 +13,14 @@ def setup
       class ApplicationController < ActionController::Base
       end
     RUBY
+    FileUtils.mkdir_p("#{destination_root}/test")
+    File.write("#{destination_root}/test/test_helper.rb", <<~RUBY)
+      require "rails/test_help"
+      module ActiveSupport
+        class TestCase
+        end
+      end
+    RUBY

     copy_gemfile

```

2025-01-18 20:08 UTC, gobijan commented on railties/test/generators/authentication_generator_test.rb
> +      assert_match(/def login_as(user)/, content)
Argh. This was a remain if the old approach I overlooked.
This is the way I was checking already for the test_authentication_generator_with_api_flag variant.

```
    assert_file "test/test_helper.rb" do |content|
      assert_match(/session_test_helper/, content)
      assert_match(/SessionTestHelper/, content)
    end
```

2025-01-18 21:29 UTC, jeromedalbert commented
> Another note:
> I used `require_relative "helpers/session_test_helper"`. I was wondering if it would be better to add `config.autoload_paths += %w[ test/helpers ]` to test.rb
> Any opinion on that?

I think this would be nice as it would cut down on boilerplate requires whenever a test needs to sign in or sign out. In this [PR](https://github.com/rails/rails/pull/53726/files#diff-99ae1faf2fd35d5029eb4931969a64dd217e929d1103b903fbe022db621b43bcR21-R27) I also used `autoload_paths`, which I believe was inspired by code from 37signals' Writebook. Feel free to take anything from that PR if needed.

2025-01-19 03:25 UTC, flavorjones commented
> > I used `require_relative "helpers/session_test_helper"`. I was wondering if it would be better to add `config.autoload_paths += %w[ test/helpers ]` to test.rb
> > Any opinion on that?
> 
> I think this would be nice as it would cut down on boilerplate requires

I agree it would be nice, but I also don't think it needs to be part of this PR.

The failure in CI is unrelated, I'm tagging this for review by a core team member.

2025-01-19 03:25 UTC, flavorjones approved these changes

2025-01-19 08:39 UTC, zzak commented
Please add a [changelog](https://github.com/rails/rails/blob/main/railties/CHANGELOG.md) and [squash your commits](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits).

2025-01-19 15:24 UTC, MatheusRich commented on railties/lib/rails/generators/rails/authentication/templates/test/helpers/session_test_helper.rb.tt
> +      cookies[:session_id] = cookie_jar[:session_id]
Is this supposed to be added o system tests or request tests? I don't remember if system tests can access cookies

2025-01-20 08:56 UTC, gobijan commented on railties/lib/rails/generators/rails/authentication/templates/test/helpers/session_test_helper.rb.tt
> +      cookies[:session_id] = cookie_jar[:session_id]
This is for IntegrationTests (ActionDispatch::IntegrationTest).

2025-01-20 08:57 UTC, gobijan commented
> Please add a [changelog](https://github.com/rails/rails/blob/main/railties/CHANGELOG.md) and [squash your commits](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits).

Done :) Let me know if you need anything further.

2025-01-20 16:35 UTC, MatheusRich commented on railties/lib/rails/generators/rails/authentication/templates/test/helpers/session_test_helper.rb.tt
> +      cookies[:session_id] = cookie_jar[:session_id]
Should we have one for system tests too? I know @dhh is not a big fan of them, but for smoke tests, a set of system tests are useful. Should we let that for each app to implement? Maybe a initial implementation on the docs could be an alternative, if we don't want to ship it in the framework.

2025-01-20 18:08 UTC, gobijan commented on railties/lib/rails/generators/rails/authentication/templates/test/helpers/session_test_helper.rb.tt
> +      cookies[:session_id] = cookie_jar[:session_id]
Well good question. I think system tests are probably way simpler. These helpers here were not trivial because of the cookie jar problem mentioned in the referenced discussion.

For system tests it's pretty straightforward I guess. Something like:

```
visit new_session_url
fill_in "Email", with: "test@example.com"
fill_in "Password", with: "password123"
click_on "Sign in"
```

Where should logic for this go? Directly in the ApplicationSystemTestCase class?
Anyways I needed the IntegrationTest functionality as I was repeating it in all my projects. I let you guys decide how to move forward.

2025-01-20 19:25 UTC, MatheusRich commented on railties/lib/rails/generators/rails/authentication/templates/test/helpers/session_test_helper.rb.tt
> +      cookies[:session_id] = cookie_jar[:session_id]
I wonder if the system specs should actually login, or set cookies more "manually" too.

I'll defer to @dhh to say if this is necessary or not.

2025-02-20 18:06 UTC, csculley commented on railties/lib/rails/generators/rails/authentication/templates/test/helpers/session_test_helper.rb.tt
> +      cookies[:session_id] = cookie_jar[:session_id]
For system tests, I needed to add in the following to get that solution to work:
```
page.instance_variable_set(:@touched, false)
page.reset!
```
However, this is pretty hacky, and I'm pretty sure there's a better solution for system tests

2025-02-20 18:13 UTC, csculley commented on railties/lib/rails/generators/rails/authentication/templates/test/helpers/session_test_helper.rb.tt
> +      cookies[:session_id] = cookie_jar[:session_id]
Just an update, the solution in https://github.com/rails/rails/issues/53207#issuecomment-2628448719 works better for me than the page resetting! I think there was a significant amount of flake introduced by using stock capybara fill_in to initiate the session

2025-02-27 14:16 UTC, merged

2025-03-04 10:43 UTC, dwightwatson commented
Should the template go into the `test/test_helpers` directory, not the `test/helpers` directory (which is for testing application helpers).

`test_helpers` is referenced here: https://guides.rubyonrails.org/testing.html#using-separate-files

2025-03-04 10:58 UTC, dhh commented
Wups, good catch @dwightwatson. We do need to use test/test_helpers. If you or anyone wants to fix that, cc me on the PR ✌️

2025-03-04 23:15 UTC, gobijan commented
> Wups, good catch @dwightwatson. We do need to use test/test_helpers. If you or anyone wants to fix that, cc me on the PR ✌️

Of course I can step in and fix it. Will look into it tomorrow :)

2025-10-06 18:11 UTC, rafaelfranca commented on railties/lib/rails/generators/rails/authentication/templates/test/helpers/session_test_helper.rb.tt
> +      cookies[:session_id] = cookie_jar[:session_id]
If it is for `ActionDispatch::IntegrationTest` why is is being added to `ActiveSupport::TestCase`