`AR::Middleware::ShardSelector` support for granular database connection switching
rails/rails pull request #53783
Opened 2024-11-29 17:58 UTC by flavorjones

### Motivation / Background

Rails's horizontal sharding is supported on non-primary databases. However, the `ShardSelector` middleware only supports global shard switching using `ActiveRecord::Base.connected_to`.

This PR introduces a configuration option `class_name:` that allows `ShardSelector` to be used for granular switching on a specific abstract connection class.

Also this PR updates the "Multiple Databases" guide and generally improves the `ShardSelector` documentation.

### Detail

Adds a `class_name:` configuration option to `ShardSelector` to override the abstract connection class used for switching.

It takes a class _name_ instead of a class because the shard selector must be configured in the application configuration which is likely to be run before model classes have been loaded.

### Additional information

I could have added some logic to cache the class once constantized, but figured that could be a separate PR (since the `lock:` option could also be cached) and kept this change as slim as possible.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

2024-11-29 18:15 UTC, flavorjones commented
Docs preview:

- API: https://flavorjones-flavorjones-shar.rails-docs-preview.pages.dev/api/classes/ActiveRecord/Middleware/ShardSelector
- Guide: https://flavorjones-flavorjones-shar.rails-docs-preview.pages.dev/api/classes/ActiveRecord/Middleware/ShardSelector

The CI failure is an unrelated flake.

2024-12-02 12:30 UTC, byroot commented
Looks good to me. But I'd like @eileencodes's opinion.

2024-12-02 15:29 UTC, eileencodes requested changes
I'm good introducing this feature but the docs and changelog aren't using the correct terminology.

I hope this doesn't sound pedantic but `ActiveRecord::Base` isn't the "primary", `ApplicationRecord` is. `ActiveRecord::Base` is "global" so it will switch all connections (`ApplicationRecord` and `AnimalsRecord`) to whatever shard you ask for.

This change is introducing granular swapping to the shard selector which means if you set a class to `AnimalsRecord` then _only_ `AnimalsRecord` will ever be able to switch shards automatically.

I'd like the documentation and changelog to represent that and not use the word "non-primary" because it's not technically what this is implementing. Let me know if I can better explain this.

If it's helpful, docs for granular swapping are here https://guides.rubyonrails.org/active_record_multiple_databases.html#granular-database-connection-switching

2024-12-03 21:46 UTC, eileencodes approved these changes

2024-12-03 21:46 UTC, merged